### ISSUE TITLE
Support for Pantheon DE

### ISSUE THREAD

**Issue by megatux** [adapta-project/adapta-gtk-theme#245]
Any plans to support Pantheon desktop environment? What are the issues?

**Comment by tista500** [comment]
None and active development for Gtk+ 3.18.x is almost over. Then I don't think Adapta was needed in such elementaryOS. From the start of that OS, they had used to be inspired by macOS's benefits and results. On the other hand, Adapta strongly depends on both Google's Material Design and GNOME's HIG. Basically their Gala, Plank, Midori, Slingshot, Marlin, Granite, and almost things want to have their own design bases even if those core components violates the GNOME's HIG.,,

Isn't it enough to stack with their default Gtk+ theme?

Regards.

**Comment by WoodyWoodsta** [comment]
I was wondering the same, but the very idea of themes is that one wants to have something other than the default.

**Comment by tista500** [comment]
@WoodyWoodsta,

> but the very idea of themes is that one wants to have something other than the default.

Already some of themes should work on their DE.

> he elementary HIG has absolutely nothing to do with how a designer needs to design a theme

Disagreed. The results are shown their applications and granite widget engines. Left-most close buttons, right-most search-entries, path-bar in Marlin, specific stack-switchers, heavy gradient icon sets, etched and shadowed text materials, very low-contrast dimming, theme-untouchable Gala's  drop-shadows, and more and more...

> It's linux/unix - people can do what they want thereafter

It depends on those licenses.

Regards.

**Comment by NicoHood** [comment]
I've used EOs a long time before. EOs was made to be beautiful without that the user needs to customize anything. Pantheon is basically a gnome + wingpanel + plank and some software froks with tons of bugs (that just a fact, I still love their style though).

If you do not need their style their is basically no need in using EOs. Then you'd rather use an Ubuntu Flavour and customize it or just start with debian/arch on your own. You can get a similar result like EOs has with XFCE and the modifications I describe here (if the link one day is offline search at nicohood.de for xfce4):
https://github.com/NicoHood/NicoHood.github.io/wiki/Xfce4-Desktop-Environment-Customization

You can simply replace adapta with arc or whatever theme suits your needs. If you use something else than EOs you also have less portability problems, as they always do their own fork etc. And mostly their software is a fork of the original gnome tool with tons of missing bugfixes.

Another word about that general issue: EOs does not even care to merge user supplied XFCE etc patches to make their icon theme work with other DEs. Its not about requesting their help, its just about hitting "merge". And if they do not even care about that I also think its not worth to produce themes for their OS.

So after I figured that out I switched to arch, while EOs is still a beautiful distro though.

**Comment by tista500** [comment]
I've already answered to original reporter. Nothing to do for Pantheon.

Closed.

**Comment by xd1936** [comment]
This is a real bummer. Adapta is beautiful, and I would love to try it in Elementary. [Paper](https://itsfoss.com/install-paper-theme-linux/) works great as an alternative Material Design-inspired GTK theme.
