### ISSUE TITLE
Adapta for PHPStorm?

### ISSUE THREAD

**Issue by dimitrov-adrian** [adapta-project/adapta-gtk-theme#247]
Hi,

Any chance to make Adapta work well with PHPStorm? I know is Java but it could play GTK.

**Comment by xanscale** [comment]
using android-studio ubuntu and this theme just select "GTK+" on theme and works

i think that with PHPStorm will be same

**Comment by mehranrasulian** [comment]
very long and large menus are the first issue

**Comment by tista500** [comment]
> very long and large menus are the first issue

Was it the theme specific issue? If not, please file a report to PHPStorm...

**Comment by RhanCandia** [comment]
You can just select GTK+ default on the theme menu, right?

**Comment by dimitrov-adrian** [comment]
On Adapta, top menu current item is gray on gray background and it's hard to read. Also the space between the menu items is too small.

![adapta-mokko](https://cloud.githubusercontent.com/assets/1009639/19429488/a57a5b0a-9458-11e6-8cdd-6c88d7f5e262.png)

On Adapta Mokto the tab font color is light gray on white background

![adapta-phpstorm-current-menu-item](https://cloud.githubusercontent.com/assets/1009639/19429489/a57f9dea-9458-11e6-9459-e18e7b069649.png)

**Comment by tista500** [comment]
@dimitrov-adrian,

Please let me see how Numix and Ark-Darker draws on such bad Gtk+ backend.
Maybe I will not be able to help you though...

Regards

**Comment by mehranrasulian** [comment]
This is for Ambiance theme:
![dasturpokht - -code-dasturpokht - -resources-assets-js-app js - phpstorm 2016 2 1_006](https://cloud.githubusercontent.com/assets/7046255/19431148/1aa26e12-9464-11e6-9625-98663f90d878.png)

For Numix:
![dasturpokht - -code-dasturpokht - -resources-assets-js-app js - phpstorm 2016 2 1_010](https://cloud.githubusercontent.com/assets/7046255/19431176/38b51a76-9464-11e6-8a45-5967e342f7f6.png)

And for Adapta:
![dasturpokht - -code-dasturpokht - -resources-assets-js-app js - phpstorm 2016 2 1_007](https://cloud.githubusercontent.com/assets/7046255/19431192/446f45a8-9464-11e6-89f5-af69cf033f8f.png)

**Comment by tista500** [comment]
@mehranrasulian,

Display resolution and font-size please.

**Comment by mehranrasulian** [comment]
font-size by default is 13 and resolution is 1366 x 768 (16:9).

I have also scaled menu and title bars to `0.875` in display settings

**Comment by tista500** [comment]
13pt on WXGA!? Unbelievable...

As your shots, there's not huge differences the width of menuitems in that menubar. So if it was too tight, that's the problem of that apps itself.

And the height of menus, I don't want to shrink. Because in Material Design, 13px (9.75pt) and 14px (10.5pt) are the reference sizes of standard widget fonts.

**Comment by mehranrasulian** [comment]
13px.

It is while I have no problem with the menu of other apps like sublime text, chrome ,etc.
Anyway, I'm fine with the default theme of PHPStorm :) but not when I switch to GTK+ (Adapta)

**Comment by tista500** [comment]
> I'm fine with the default theme of PHPStorm :) but not when I switch to GTK+ (Adapta)

Low resolution display is the enemy of Adapta obviously.
Adapta is mainly developed on my Thinkpad X1 carbon's WQHD screen and VAIO Z21's FHD screen.

Finally if you've got Gtk+ 3.2x environments already, try new Eta variant for Gtk+ 2.x: https://github.com/adapta-project/adapta-gtk-theme/commit/bebfb22896470c37151108d0828abd78e4e7aaf1

Regards.

**Comment by xanscale** [comment]
io ho un Thinkpad X1 carbon's WQHD with
gsettings set org.gnome.desktop.interface scaling-factor 1

this is the result with android-studio using adapta base and GTK+ theme in android studio

![schermata del 2016-10-17 16-17-22](https://cloud.githubusercontent.com/assets/255819/19441255/5e12f7f4-9485-11e6-9177-a3dc2791f5d7.png)

**Comment by tista500** [comment]
Most of things seems wrong/incorrect in that apps, so I set this issue as "won't fix". 

Regards.
