### ISSUE TITLE
Window bar doesn't theme correctly

### ISSUE THREAD

**Issue by diazgilberto** [adapta-project/adapta-gtk-theme#248]
**Reporter info**

 ```
 * Distribution - Xubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment
 ```

**Adapta version (if you knew)**
Just download it today from github.

**Related Application and/or Shell theming (or name of widget)**
Window bar

**Actual issue**
the window bar doesn't theme as your post in [linuxslaves.com](http://www.linuxslaves.com/2016/10/adapta-gtk-material-design-theme-linux.html)

**Steps to reproduce (if you knew)**
I follow the github instructions step by step

**Expected behavior**

**Other Note (feature-request, question, etc...)**
I'm a OSX user and I'm trying Xubuntu in VMware to learn. I have been using Linux for 6 to 7 month straight now and I'm having a good experience. Now I want to learn how to customize my experience with the system.
Based on the bullets you are asking, I imagine that I need to download a package to theme a specific part of the window or system.

![screenshot_2016-10-14_22-19-57](https://cloud.githubusercontent.com/assets/9165819/19407080/603f10e2-925c-11e6-9ad7-18b1345ffcdb.png)

**Comment by tista500** [comment]
o_O ??

You mean `xfconf-query -c xfwm4 -p /general/theme -s "Adapta-Nokto"` did not work as we expected?

Regards.

**Comment by tista500** [comment]
> the window bar doesn't theme as your post in linuxslaves.com

That article is not my post.

**Comment by diazgilberto** [comment]
Nice, that command fixed it.
So many commands to learn.

**Comment by diazgilberto** [comment]
Can you explain the command for me?
What the `-c`, `-p`, and `-s` flags means?

**Comment by diazgilberto** [comment]
Some windows are themed but others not. For instance, the software window is not themed. If I try to do settings in the Panels and click the clock to change settings, that window is not themed.

![screenshot_2016-10-15_08-34-16](https://cloud.githubusercontent.com/assets/9165819/19410443/3ad396ba-92b2-11e6-81ec-8c1825ab6c61.png)

![screenshot_2016-10-15_08-32-13](https://cloud.githubusercontent.com/assets/9165819/19410435/e842cdee-92b1-11e6-9ab5-2aeda6122f4e.png)

**Comment by tista500** [comment]
> Window bar doesn't theme correctly

It's not the issue of Adapta and please ask in elsewhere "How to change the Gtk+ theme inXFce".

Regards.
