### ISSUE TITLE
Gnome Shell crash and restart only once at startup

### ISSUE THREAD

**Issue by eypsum** [adapta-project/adapta-gtk-theme#250]
**Reporter info**
gnome shell is crashed on first startup and restart if with Adapta-Nokto. (not tried with Adapta theme)
I had reported the issue  about a month ago.
In that time, I told that good works with default 'Adwaita'.
Today I tried to play with another 'Arc-Dark' gnome shell theme and it works good without being crashed.
I have reported bug about this issue to Ubuntu Gnome team like below link but their response is so slow.
 https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1619096

 ```
 * Distribution - Ubungu Gnome 16.04.1 
 * Gtk+ 3.0 version -  3.18.9
 * Desktop environment - 
 ```

**Adapta version (if you knew)**
3.22.1.77-0ubuntu1~xenial1

**Comment by tista500** [comment]
Stop duplicating old issue.

**Comment by tista500** [comment]
Re-opened: https://github.com/adapta-project/adapta-gtk-theme/issues/205
