### ISSUE TITLE
Color option for PPA?

### ISSUE THREAD

**Issue by ErnestThornhill** [adapta-project/adapta-gtk-theme#251]
Hello, I was just wondering if it would be possible for the color options that are now available in 3.22.1.108 when building would be possible when using the PPA? I would like to change the colors of a few items, for example the notification text color so I can see it better than the [black text on grey background](http://i.imgur.com/ALcQTHP.jpg), but would also like it to stay updated through my package manager. If this is not possible I understand but I thought I would ask.

**Comment by tista500** [comment]
I can't get the point but anyway feel free to rebuild the package at local machines in personal use.

Regards.
