### ISSUE TITLE
Buttons in Libreoffice 5.2.2.2 look the same after being pressed

### ISSUE THREAD

**Issue by Prukutu** [adapta-project/adapta-gtk-theme#253]
**Reporter info**

 ```
 * Distribution - Ubuntu (Yakkety Yak)
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome Shell
 ```

**Adapta version (if you knew)**

3.22.1.121-0ubuntu1~yakkety1

**Related Application and/or Shell theming (or name of widget)**

Libreoffice 5.2.2.2 (using GTK3 by default)

**Actual issue**

Buttons that have an on/off state (sorry if there's an actual word for them), such as bold and italics, don't show any difference between being on or off after being clicked. This makes it impossible to see whether bold/italics/etc is on or off. The problem does not seem to occur with other themes such as Adwaita or High Contrast.

**Steps to reproduce (if you knew)**

Highlight any word in a Libreoffice document (Writer, Impress, etc) and click on the "Bold" button. 

**Expected behaviour**

Under other GTK themes, these type of buttons look different after being clicked to show their on/off state. 

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
This is because LO completely ignores `box-shadow` property in that tool-bars. LO just draws `background-color` instead. In Adapta, GtkToolBar should be constructed with flat-buttons and underline-indicators for `:checked` pseudo-class.

This issue is related to LO's Gtk+ backend.

**Comment by Prukutu** [comment]
Ah, I suspected it was some weirdness on the LO side. Thanks for the remarkably quick (and insightful) response!

**Comment by tista500** [comment]
Workaround was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/1b1052c8a22706b8fc095dc4caf913c2794b330b

I'm not testing in Gtk+ 3.20.x yet, but hope that commit could solve this issue with crazy solution...

Regards.
