### ISSUE TITLE
Menus and icons spacing issue

### ISSUE THREAD

**Issue by mauriziopinotti** [adapta-project/adapta-gtk-theme#255]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10 (upgraded from 16.04)
 * Gtk+ 3.0 version - 3.20.9-1ubuntu2
 * Desktop environment - gnome-shell 3.20.4-0ubuntu1
 ```

**Adapta version (if you knew)**

3.22.1.138-0ubuntu1~yakkety1

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Icons and menus are missing room to separate each other, see for example Eclipse Neon (has both menu and icons issues):

![image](https://cloud.githubusercontent.com/assets/4000539/19601658/83f09828-97aa-11e6-9c07-cc133bff212a.png)

and Android Studio (only the menu issue):

![image](https://cloud.githubusercontent.com/assets/4000539/19601659/88e3ef10-97aa-11e6-9717-e4957c4db742.png)

**Steps to reproduce (if you knew)**

Set the GTK+ theme in Tweak Tool and open Eclipse Neon.

**Expected behaviour**

Here's how Eclipse looks like with Adwaita (default gnome-shell theme):

![image](https://cloud.githubusercontent.com/assets/4000539/19600886/3b69edfa-97a7-11e6-8201-ea74eb716b84.png)

**Comment by tista500** [comment]
partial workaround: https://github.com/adapta-project/adapta-gtk-theme/commit/cf7267016c68062f2ebfcce5f51bbcf9a5435dee
