### ISSUE TITLE
Font color white on white background on open file dialog Codeblock

### ISSUE THREAD

**Issue by truongnmt** [adapta-project/adapta-gtk-theme#257]
**Reporter info**
H/W: Intel Core i3 M350 
Distro: Ubuntu 16.04.1 LTS
Desktop: Unity 7.4.0

**Adapta version (if you knew)**

**Actual issue**
I'm using Codeblock, when I click File -> Open file, the font color on opening folder is white, I can't see it. I also attatched a picture.
![selection_024](https://cloud.githubusercontent.com/assets/11817656/19617979/21d807c4-9869-11e6-9710-0530ec175a85.png)

**Steps to reproduce (if you knew)**
Open Codeblock
Click File -> Open ...

**Expected behaviour**
The font color is black

**Comment by tista500** [comment]
Fix was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/ace7ac06c1c429b673445bb1dd7c152ed32973d8

Regards.
