### ISSUE TITLE
Doesnot Scroll Properly on Budgie Raven Sidebar

### ISSUE THREAD

**Issue by Bloodskate** [adapta-project/adapta-gtk-theme#258]
**Reporter info**
@bloodskate
 ```
 * Distribution - ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9-1ubun
 * Desktop environment - Budgie
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
 Raven Sidebar(Not Sure)

**Actual issue**
Doesnot scroll properly , cant see some ui buttons

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/249d1cac6d2704c04028584157a68e2e3df0c0f9
