### ISSUE TITLE
Dash to dock, theme faillure

### ISSUE THREAD

**Issue by mikafouenski** [adapta-project/adapta-gtk-theme#261]
**Reporter info**

 ```
 * Distribution - Arch linux 4.8.4-1
 * Gtk+ 3.0 version - 3.22.1
 * Desktop environment - Gnome 3
 ```

**Adapta version (if you knew)**
3.22.1.153-1

**Related Application and/or Shell theming (or name of widget)**
Dash to dock

**Actual issue**
Since the last update the theme, dash to dock theme do not work any more, it stay black.
![screenshot from 2016-10-24 10-54-51](https://cloud.githubusercontent.com/assets/11093325/19639594/606da9d2-99d9-11e6-8d5c-aa56365305b8.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
The dash will stay transparent except a 2px bar at the bottom (like it use to be).

**Other Note (feature-request, question, etc...)**
Thanks for reading this. Mickaël.

**Comment by tista500** [comment]
Dock design was changed, so tweak transparency via Dash to Dock settings window.

Regards.
