### ISSUE TITLE
Title bar hangs over/has an odd lip edge in Unity 

### ISSUE THREAD

**Issue by jwhipp** [adapta-project/adapta-gtk-theme#263]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10 
 * Gtk+ 3.0 version - 3.20.9
 * Desktop environment - Unity 7.5.9
 ```

**Adapta version (if you knew)**

3.22.2.9

**Actual issue**

Title bar hangs over, shows up in multiple apps (see screen shots).

**Steps to reproduce (if you knew)**

Set theme, open an affected app (e.g. Nautilus).

**Expected behaviour**

I'd expect the bar to be flush with the window or border.

**Other Note (feature-request, question, etc...)**

I've only noted this in Nautilus and Visual Studio Code since they are apps I use on a regular basis.  I opened shutter to grab a screen shot and noticed it's not happening for that window nor is it for the hangouts window in the screen shot.

![selection_001](https://cloud.githubusercontent.com/assets/556332/19733177/764e6c9a-9b60-11e6-8333-476775746483.png)

![selection_002](https://cloud.githubusercontent.com/assets/556332/19733239/9e93e78e-9b60-11e6-9bb6-eac1592e0bcc.png)

**Comment by tista500** [comment]
Hmm, I could not reproduce at least on my Unity7 7.5.0 with Gtk+ 3.22.2 & Nautilus 3.22.1:
![screenshot from 2016-10-27 17-46-23](https://cloud.githubusercontent.com/assets/6073622/19761211/ebe9b616-9c6f-11e6-9b73-eaa18d4ac7a6.png)

Regards.

**Comment by jwhipp** [comment]
I was just checking it on a development VM which is identical in versions to my laptop, same issue.  Looks like a 1 pixel "lip".   On my laptop and this VM, I used the ppa to install, is there a newer version perhaps?

**Comment by jwhipp** [comment]
I just built the theme from master, still seeing the lip.  I also notice from your shots compared to mine that the elements are tighter together in Nautilus.

**Comment by tista500** [comment]
> * Desktop environment - Unity **7.5.9**

Where did that Unity7 version come from? Proposed repo still keeps 7.5.0...

> is there a newer version perhaps?

It doesn't matter. Because I usually don't change Unity7 styling frequently.

> I also notice from your shots compared to mine that the elements are tighter together in Nautilus.

It isn't a big deal. Adapta is the scaling Gtk+ theme... Spacing depends on your font-sizes and scaling-factors.

So you mean logout & re-login (or reboot) did not solve the issue?

**Comment by jwhipp** [comment]
That should've said Unity 7.5.0, apologies.

I just tried logging out and back in per your recommendation and that fixed it.   Thanks for the quick responses.  So many of these good themes die out it seems, glad to see a great one like this is being actively maintained. :)
