### ISSUE TITLE
Font Change on cinnamon panel

### ISSUE THREAD

**Issue by aman4512** [adapta-project/adapta-gtk-theme#266]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Cinnamon
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Window list panel applet

**Actual issue**
There's no way to change the font of the panel as there's no adapta folder in ~./themes

**Steps to reproduce (if you knew)**

**Expected behaviour**
Usually, upon installing cinnamon themes, there's a theme specific folder in ~./themes in which there's a cinnamon.css file by editing which we can change panel fonts to our liking. The same isn't possible for adapta.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Usually, upon installing cinnamon themes, there's a theme specific folder in ~./themes in which there's a cinnamon.css file by editing which we can change panel fonts to our liking. 

o_O??
Doesn't it depend on `prefix` you defined?

> There's no way to change the font of the panel as there's no adapta folder in ~./themes

If you had set `prefix=/usr`, see `/usr/share/themes/Adapta`...
I don't have any ideas why we should duplicate them to `$HOME/.themes`.

**Comment by tista500** [comment]
Currently there's few things we can do with this report, closed.

Regards.
