### ISSUE TITLE
Adapta shell theme displays unreadable rectangular fonts

### ISSUE THREAD

**Issue by odifek** [adapta-project/adapta-gtk-theme#268]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```
Ubuntu Gnome 16.04.1 (xenial)
Gnome
**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Adapta Shell theme

**Actual issue**
I don't what happened but the theme has been running fine until after some time, precisely when I was reinstalling some of my software (I did a fresh install) - batch install. The theme write ups suddenly turned to rectangles. However if I select another shell theme, the fonts display fine but Adapta.

**Steps to reproduce (if you knew)**
I don't know

**Expected behaviour**

Should render shell fonts normal

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Please tell me how I could track down this issue without any informations about your locales and fonts you've installed...

**Comment by odifek** [comment]
I honestly don't know. However the theme was restored from backup using
aptik (not installed as Deb). It was working fine for days until I began
restoring other apps. Along the line the shell writeups became boxes like
shown in the screenshot.
I've also tried to install from ppa but no change occurred.
Maybe you can tell me where to look for errors relating to Adapta.
Thanks

On 4 Nov 2016 05:43, "Tista" <notifications@github.com> wrote:

Please tell me how I could track down this issue without any informations
about your locales and fonts you've installed...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adapta-project/adapta-gtk-theme/issues/268#issuecomment-258343848>,
or mute the thread

**Comment by tista500** [comment]
Please answer my previous questions:

* your locale:
* fonts you've installed:

> Along the line the shell writeups became boxes like shown in the screenshot.

Where was the shot?

Regards.

**Comment by tista500** [comment]
If your issue was related to font-caches, run `fc-cache -fv` and next logout and re-login (or reboot)...

**Comment by odifek** [comment]
OK, I didn't understand your first question. (a noob here). The fc-cache
did nothing. I'll print the fonts and locale and send

**Comment by odifek** [comment]
Attached are the font installed and locale. Thanks.

**Comment by odifek** [comment]
> Where  was the shot?

[Screenshot](https://jpst.it/P2d0)

**Comment by tista500** [comment]
Tofu....

Could you please check if `en_US.UTF-8` solved the issue.

**Comment by tista500** [comment]
Hmm, your truetype fonts are broken?

Because some `.ttf` has been renamed to `.ttf.dpkg-new`, especially NotoSans and Lato...
NotoSans family is very important for Adapta, so please purge all of packages named `fonts-noto*` and `fonts-lato`, then re-install them from main repository again...

**Comment by odifek** [comment]
OK, thank you very much. My system is broken now as I was trying to upgrade
to Gnome 3.20. I will try the solution after the reverting is done.
Many thanks.

**Comment by odifek** [comment]
Wow! After purging and reinstalling fonts-noto and fonts-lato the theme
came back to normal.
Many thanks!

On 4 Nov 2016 13:43, "Kennedy Odife" <kennedy998@gmail.com> wrote:

OK, thank you very much. My system is broken now as I was trying to upgrade
to Gnome 3.20. I will try the solution after the reverting is done.
Many thanks.

**Comment by pschichtel** [comment]
@tista500 As a suggestion: Maybe add a small "troubleshooting guide" to the README for more common problems like this. The README also doesn't seem to mention the importance of these fonts.

**Comment by pschichtel** [comment]
You could also reference this guide from your issue template, so people see it before creating issues

**Comment by tista500** [comment]
@pschichtel,

Most people read neither the README nor MaterialDesignGuidelines. Oh forgot to mention, some people ignore even the ISSUE_TEMPLATE. Please see some shots which users posted. They usually are NOT interested in Material Design fonts...

In this case, it was related to user's system health instead of the issue of Adapta itself. Yeah workaround may be quite easy. Just let Adapta check Cantarell only.

So your suggestion can be a blocker? I now think Material Design might NOT be needed in PCUnixOS. They just check out Adapta since it seems new,

**Comment by odifek** [comment]
I've been using Adapta for quite some time now and I love it. I love
material design on PC honestly. It gives my PC a new and trendy look!

**Comment by pschichtel** [comment]
@tista500 As the AUR package maintainer I do follow your work here as closely as time permits, so I'm aware of the issues. I remembered you posting a similar response earlier, that's why I suggested this in the first place. For people that **do** read your README / Issue template, it would probably be useful to have a few "sanity checks" that may already fix or show the problem.
For me as a package maintainer, the information about fonts would be helpful as well, so I can add package dependencies/suggestions to the Adapta package.

**Comment by pschichtel** [comment]
Something as simple as a simple checklist someone could go through to check for common things:

Troubleshooting Guide
===================

In case of broken font display
----------------------------------------

- Is font XY and/or ZW installed?
- Are your font files in a working condition?
- Is your locale in a working condition?

**Comment by tista500** [comment]
Added info for typography: https://github.com/adapta-project/adapta-gtk-theme/commit/e9c39721472f8cadd0bc3fad236b9a10b873f959
