### ISSUE TITLE
Notification UI issue

### ISSUE THREAD

**Issue by gav888** [adapta-project/adapta-gtk-theme#269]
**Reporter info**
gav888
 ```
 * Distribution - Linux Mint 18
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Cinnnamon 3.0.7
 ```

**Adapta version (if you knew)**
Adapta light

**Related Application and/or Shell theming (or name of widget)**
Firefox and Cinnamon desktop

**Actual issue**
Notification of Firefox Dowload

**Steps to reproduce (if you knew)**
Download file in Firefox and notification

**Expected behaviour**
Notification is not readable due to white font over gray background
![screenshot from 2016-11-04 10-01-15](https://cloud.githubusercontent.com/assets/23257401/20001820/bfe6ca5c-a275-11e6-9968-3b9c9c1d055f.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Ah, that issue happned in case notifications had multi-lines texts...
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/1a59ba937fd7937b9f177366b549f0e024f64171

Regards.
