### ISSUE TITLE
Move Plank and chrome themes to new repositories?

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#270]
In order to make it easier for people to install only plank/chrome theme, report bugs for only one of theme. Would you consider moving the plank and chrome theme to a new repository for each one ? Thanks

**Comment by tista500** [comment]
> In order to make it easier for people to install only plank/chrome theme

Were there anyone who wanted to do so?

**Comment by bil-elmoussaoui** [comment]
Maybe in the future, who knows :) it's just a suggestion, and plank/chrome theme are not Gtk theme..

**Comment by tista500** [comment]
> plank/chrome theme are not Gtk theme..

Gnome-Shell, Cinnamon, Mate, LXDE, Unity7 and Budgie-Desktop thems are not the Gtk+ theme, too...

**Comment by bil-elmoussaoui** [comment]
Sorry for the delay,
Well, what i meant is to keep this repository for only desktop env theming and move Plank, Chrome, Firefox and steam on the future to different repository; 
I don't really have an argument, but it's just to keep this repository cleaner :+1:

**Comment by tista500** [comment]
I really want to drop Plank support, because that app is a part of Pantheon I do not like...

>  Chrome, Firefox and steam on the future to different repository

Ah. And I hope SOMEONE could develop/maintain those 3rd-party-apps specific theming in future.
Adapta will be a year-old but currently I can not have much time to do anything for those apps yet...

Regards.

**Comment by bil-elmoussaoui** [comment]
Plank can be installed on other distros and does not use any Granite widget (for now) so it's okay to keep it for now...

**Comment by tista500** [comment]
I now don't have the ideas whether we should separate (split) a part of Plank/Chrome theming or not. So if someone has pushed PRs and/or feature-requests for this topic, I will re-open this report. ;)

Currently closed.

Regards.
