### ISSUE TITLE
Some icon got an imperfect circle if system lang not English.

### ISSUE THREAD

**Issue by caoli5288** [adapta-project/adapta-gtk-theme#271]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.0
 * Desktop environment - Gnome 3.22
 ```

**Adapta version (if you knew)**
Newest ppa version

**Related Application and/or Shell theming (or name of widget)**
Gedit

**Actual issue**
Icon got an imperfect circle if system lang not English. See gedit. More circle in English than chinese.
![2016-11-08 03-53-12](https://cloud.githubusercontent.com/assets/3120587/20073384/ab311314-a4f1-11e6-8937-48a84bf03644.png)
![2016-11-08 03-56-38](https://cloud.githubusercontent.com/assets/3120587/20073472/08b8470a-a4f2-11e6-95f2-df8867802b74.png)

But some always not imperfect like system-monitor.
![2016-11-08 03-59-36](https://cloud.githubusercontent.com/assets/3120587/20073591/7392e83c-a4f2-11e6-80f5-312cd7d796e1.png)

**Comment by tista500** [comment]
See the difference of height of GtkHeaderBar between Chinese and English. Your Chinese fonts have taller height compared with English fonts. You should optimize the font-size...

And Gnome-System-Monitor, developers did NOT implement `.image-button` style-class to that buttons which were exactly image based icon button. It means Adapta can not set icon button specific spacing to those buttons...

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/b244768365c70419489b489994653e0e844a286d

Closed.

**Comment by caoli5288** [comment]
THX
