### ISSUE TITLE
E: Unable to locate package adapta-gtk-theme on ubuntu for command sudo apt install adapta-gtk-theme

### ISSUE THREAD

**Issue by shauntrick** [adapta-project/adapta-gtk-theme#274]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by timothyvanderaerden** [comment]
Have you done the following steps:

- Added the repository: https://launchpad.net/~tista/+archive/ubuntu/adapta
    (sudo add-apt-repository ppa:tista/adapta)
- sudo apt update
- sudo apt install adapta-gtk-theme

**Comment by shauntrick** [comment]
yeah did the same got this error  "E: Unable to locate package adapta-gtk-theme"

**Comment by tista500** [comment]
I have no time to respond the **EMPTY** report.
PPA supports Xenial, Yakkety and Zesty, that's all.

Invalid.

**Comment by shauntrick** [comment]
So it doesn't support Willy warewolf , i guess that is the problem , Thanks for the Help !

**Comment by calidion** [comment]
@tista500 
I am on 16.04 xenial.
and encountered this problem too.

**Comment by ZhouYaoFeng** [comment]
i hava abandon ubuntu



发自我的小米手机
在 Eric <notifications@github.com>，2018年5月6日 下午3:10写道：

@tista500<https://github.com/tista500>
I am on 16.04 xenial.
and encountered this problem too.
