### ISSUE TITLE
[Gtk+ 3.x][xfce-notify-4.0] theme not found

### ISSUE THREAD

**Issue by HeikoAdams** [adapta-project/adapta-gtk-theme#275]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Xfce 4.12 
 ```

**Adapta version (if you knew)**
latest git master

**Actual issue**
When opening the xfce notification settings adapta's xfce4-notified-theme is not listed even it's installed.

**Comment by tista500** [comment]
Xfce4-notifyd 0.3.3 series seem to be broken even if I put `gtk.css` into `xfce-notify-4.0` directory. That ugly app shows just the same "default" theming anyway... :/

So I don't want to be in the same *broken* boat with that app.

Regards.

**Comment by tista500** [comment]
And now I found that app ignores multiple versioned theming like `xfce-notify-4.0/gtk-3.20/gtk.css`?

Makes no sense... damned.

**Comment by tista500** [comment]
Edited the title...

**Comment by tista500** [comment]
Hmm, "Default" seems to pull the selected Gtk+ theme styling for notify-window. I suppose "Default" is very bad idea to use Gtk+ theming which user selected, should be named "Gtk+" or something...
![screenshot from 2016-11-11 13-35-43](https://cloud.githubusercontent.com/assets/6073622/20204534/dbef32ae-a813-11e6-892d-621a1cce1616.png)

Anyway on multiple versioned themes like Adapta, we can't solve the version specific theming with that ugly app...

Regards.

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/1bf00ee593ff977fbf0d9b604837681ba8a57bc0

But this changes **Only for Gtk+ 3.2x users**, so Gtk+ 3.18.x users should select "Default" theme via that setting tool (I'm really disappointed with that app)...

Regards.
