### ISSUE TITLE
English Errors on the Github Page (Grammar & Wording)

### ISSUE THREAD

**Issue by ChristenColour** [adapta-project/adapta-gtk-theme#277]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 16.04 LTS
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**
N/A

**Related Application and/or Shell theming (or name of widget)**
N/A (Github page)

**Actual issue**
(grammar and wording of the github page)
There are some issues on the github page: where it says "Adapta strongly depends on results of the Material Design, especially fonts are very important stuffs." it should read "Adapta strongly depends on Material Design resources, especially its fonts." or some other variation thereof. There are a lot of ways it could be worded, I just wanted to let you know there were some issues with the english as it currently is.

**Steps to reproduce (if you knew)**
Go to Github Page: [https://github.com/adapta-project/adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme) and read contents

**Expected behaviour**
English should be correct (it's really not a huge deal but I figured I'd let you know)

**Other Note (feature-request, question, etc...)**
Stay awesome, I love what you guys have made~

**Comment by tista500** [comment]
Enough? https://github.com/adapta-project/adapta-gtk-theme/commit/ab0e719b3310650e906dca05b4c204d59e247ccc

English, English, English...

**Comment by tista500** [comment]
If you need some more changes, post PR please... (I'm not an English speaker)

Regards.
