### ISSUE TITLE
Top bar of shell theme looks broken.

### ISSUE THREAD

**Issue by USBA** [adapta-project/adapta-gtk-theme#278]
**Reporter info**

 ```
 * Distribution - Fedora 25 beta
 * Gtk+ 3.0 version - 3.22.1
 * Desktop environment - GNOME 3.22
 ```

**Adapta version (if you knew)** 

 latest from copr repo

**Related Application and/or Shell theming (or name of widget)**

Top bar

**Actual issue**

Top bar looks broken. And it is really small in size.

Look at the distance between top bar's menu and right side edge of the screen. 
It's too high.

My screen resolution : 1280 X 800 

Please check this screenshot
![screenshot from 2016-11-13 07-50-30](https://cloud.githubusercontent.com/assets/19838220/20243488/65aef562-a97f-11e6-8714-6d6806d24775.png)

**Comment by tista500** [comment]
> Top bar looks broken. 

What was the meaning "broken"?

> And it is really small in size.

It's intentional change for saving space.

Regards.

**Comment by tista500** [comment]
> Look at the distance between top bar's menu and right side edge of the screen.
It's too high.

Your LCD resolution seems too much lower than that Adapta concerns.

**Comment by tista500** [comment]
Panel height definition changed: https://github.com/adapta-project/adapta-gtk-theme/commit/cfb929b180e80102f01ad331bc60a45d6e8e9217

**Comment by tista500** [comment]
> > Look at the distance between top bar's menu and right side edge of the screen.
It's too high.
> 
> Your LCD resolution seems too much lower than that Adapta concerns.

This will NOT happen at least in WXGA (1366x768) or higher resolutions, so I don't want to fix this.
Adapta is designed with my standard WQHD (2560x1440) LCD screen on ThinkPad X1 Carbon 3rd-gen and FHD (1920x1080) on ThinkPad Helix 1st-gen (or VAIO Z).
