### ISSUE TITLE
 Unable to locate image file in pixmap_path

### ISSUE THREAD

**Issue by TheAifam5** [adapta-project/adapta-gtk-theme#279]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
git master (948a955d4dbe36eda1346fe9b597ab8f2cc7b140)

**Actual issue**
(gtk3, gtk2, xfce etc)
Spamming with messages like:
```
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:180: Background image options specified without filename
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:184: Unable to locate image file in pixmap_path: "../xfce-notify-4.0/flat-button-active.svg"
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:187: Background image options specified without filename
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:191: Unable to locate image file in pixmap_path: "../xfce-notify-4.0/flat-button-hover.svg"
/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0/3rd-party-dark-eta.rc:194: Background image options specified without filename
```

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/ff91fcbea50a99f8f157bea2a5690d9372518d7d

Regards.

**Comment by TheAifam5** [comment]
@tista500 The problem still exists.
Full log:
[log.txt](https://github.com/adapta-project/adapta-gtk-theme/files/590193/log.txt)

**Comment by zoutiyx** [comment]
I too can confirm that these messages are still present as of  `adapta-gtk-theme 3.22.3.67` on Arch Linux.

**Comment by tista500** [comment]
Download this: https://raw.githubusercontent.com/adapta-project/adapta-gtk-theme/master/gtk/gtk-2.0/3rd-party-dark-eta.rc

And check diff with your installed one like `/usr/share/themes/Adapta-Nokto-Eta/gtk-2.0//3rd-party-dark-eta.rc`. If diff returned non-null, your installation method is broken. Because my PPA and git tree already fixed.

**Comment by zoutiyx** [comment]
Mine returns nothing

**Comment by tista500** [comment]
I don't have any warnings when launching `xfce4-notify-config`:
![screenshot from 2016-11-18 02-29-17](https://cloud.githubusercontent.com/assets/6073622/20400199/1c89c806-ad37-11e6-9b51-9937f6e7d13e.png)

**Comment by tista500** [comment]
And `xfce4-appearance-settings`:
![screenshot from 2016-11-18 02-57-33](https://cloud.githubusercontent.com/assets/6073622/20401140/f4403ade-ad3a-11e6-995b-22d12ec1918c.png)
