### ISSUE TITLE
[Gtk+ 3.22][Evince] Scrolling big PDF in Evince extremely laggy

### ISSUE THREAD

**Issue by ichundu** [adapta-project/adapta-gtk-theme#280]
**Reporter info**
H/W: Dell XPS 13 9360 Laptop, core i5-7200u, 8gb RAM, Intel 620 integrated graphics.

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.3
 * Desktop environment - Gnome 3.22.2 Stable
 ```

**Adapta version (if you knew)**
3.22.3.40-1

**Related Application and/or Shell theming (or name of widget)**
Evince Document Viewer

**Actual issue**
Scrolling a big pdf document (1000+ pages) in Evince is extremely laggy and delayed.

**Steps to reproduce (if you knew)**
Open a big PDF document (~1000 pages or more) and scroll through the document. Here is a link of the actual document in my google drive:
[PDF document](https://drive.google.com/file/d/0BywMC3jzabwPNnFVd3k2SHZJQ1k/view?usp=sharing)

**Expected behaviour**
The scrolling is extremely laggy and delayed from page to page. This behaviour happens to me only when i apply adapta theme, with other themes (i have tried the default Adwaita theme and Arc) the scrolling inside the same document is silky smooth.

**Other Note (feature-request, question, etc...)**
I'd greatly appreciate if you could find a solution to my problem as i love your theme.

**Comment by tista500** [comment]
I confirmed this issue.
On my ThinkPad Helix (IveBridge i5-3337U, 4GB RAM,  HD graphics 4000), after scrolling via trackpoint to page 180 or so, it seemed to start lagging...

Regards.

**Comment by tista500** [comment]
Tracking down: `_3rd-party.scss` may cause this issue...

Regards.

**Comment by tista500** [comment]
Fix was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/fe984416e19f15b55811b458b364fe79fcef6a31

I can not determine the real problem in those codes yet, but anyway I've dropped related parts caused  the performance regression in Evince's `evview` node...

Regards.

**Comment by ichundu** [comment]
What a difference now :+1: 
Thanks for the quick fix, i can confirm this commit fixed my issue.

Best regards!
