### ISSUE TITLE
No Nokto on Unity

### ISSUE THREAD

**Issue by happydemic** [adapta-project/adapta-gtk-theme#288]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Unity
 ```
**Adapta version (if you knew)** - 3.89.1.18 (latest .deb package)

**Actual issue**
On Unity, Nokto can be selected (e.g. by Unity Tweak Tool) but appears identical to Adapta. That's been noted [elsewhere](http://www.omgubuntu.co.uk/2016/10/install-adapta-gtk-theme-on-ubuntu), but I couldn't find a discussion of this issue on github (sorry if I missed it). 

I realise the explanation is probably "Unity sucks", but I wondered if there's something I can do to enable Nokto, short of ditching Unity. Thanks for the beautiful theme.

**Comment by tista500** [comment]
Please read this section: https://github.com/adapta-project/adapta-gtk-theme#variant-matrix

It's not and issue of Adapta.
