### ISSUE TITLE
latest git master fails to buid

### ISSUE THREAD

**Issue by HeikoAdams** [adapta-project/adapta-gtk-theme#290]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Xfce 4.12
 ```

**Adapta version (if you knew)**
git master

**Actual issue**
git master fails to build with following error:

```
cp: cannot stat './gtk-3.18/gtk.gresource': No such file or directory
make[2]: *** [Makefile:1421: install-data-local] Error 1
'./asset/assets-gtk3/thumbnail@2.png' -> '/builddir/build/BUILDROOT/adapta-gtk-theme-3.22.4-1.201611231710gitefa1ffa.fc26.x86_64/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/builddir/build/BUILDROOT/adapta-gtk-theme-3.22.4-1.201611231710gitefa1ffa.fc26.x86_64/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
make[2]: Leaving directory '/builddir/build/BUILD/adapta-gtk-theme-efa1ffad0a77c4ff1261405378c87aa2b4b96687/gtk'
make[1]: Leaving directory '/builddir/build/BUILD/adapta-gtk-theme-efa1ffad0a77c4ff1261405378c87aa2b4b96687/gtk'
make[1]: *** [Makefile:1209: install-am] Error 2
make: *** [Makefile:359: install-recursive] Error 1

```

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by ronisbr** [comment]
When I was creating the openSUSE package, I was getting this exactly same error. In my case, it turns out that I was missing two build dependencies:

* gdk-pixbuf-loader-rsvg
* gdk-pixbuf-devel

Can you please post the entire build log, I may provide a more helpful comment after looking at the output messages.

**Comment by HeikoAdams** [comment]
Thanks for the hint. Addin gdk-pixbuf to the build-depencies solved the problem
