### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by bhajneet** [adapta-project/adapta-gtk-theme#296]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22?
 * Desktop environment -  XFCE
 ```

**Adapta version (if you knew)**
5677ff173d03dc32469c572b860d252926b3812d

**Related Application and/or Shell theming (or name of widget)**
Titlebar

**Actual issue**
Slightly wrong color #2A373E being used

**Steps to reproduce (if you knew)**
N/A

**Expected behaviour**
Blue Grey 900 #263238

**Other Note (feature-request, question, etc...)**
Not sure if this were a design choice, but the title bar is slightly off from the actual Blue Grey 900 shown in Material Design Guideline. Could be the color changed? Either way, I think it should be changed to #263238.

**Comment by tista500** [comment]
This is the design choice.
And Material Design can accept color-mix, too.

Won't fix.

**Comment by bhajneet** [comment]
Hello @tista500 ,

Thank you for getting back so quickly. Which colors are being mixed here? The difference between the two is quite small and I haven't seen where else this shade is being used. I did notice that in fullscreen it gets even darker. So is Blue Grey mixing with black? Thank you again.

**Comment by tista500** [comment]
There's no "shade" but "mix".

See https://github.com/adapta-project/adapta-gtk-theme/blob/master/gtk/sass/common/_colors.scss

**Comment by bhajneet** [comment]
Ah I see now! Thank you :+1: 

I will either modify this or my existing colors elsewhere. This was helpful.
