### ISSUE TITLE
No bug, just a thank you.

### ISSUE THREAD

**Issue by deepdivingspearo** [adapta-project/adapta-gtk-theme#297]
Thanks for the hard work to make a really great theme! 
And thanks for the PPA which makes installing it and upgrading a breeze for me.
All the best
Brendan

PS - apologies if this is not an appropriate place to post this, was not sure where else to do so.

**Comment by tista500** [comment]
You're welcome. ;)

**Comment by ronisbr** [comment]
I will also take the opportunity to thanks you @tista500 for this amazing theme.

People in openSUSE are using your themes, which is in my home devel repository, and  everyone are really liking it!

**Comment by talesbrenoan** [comment]
Também gostaria de agradecer, e também de destacar algo, os outros temas não se preocupam em fazer o realce do ícone de um app no momento de loading de abertura dele, como é padrão no unity, o que e era muito frustrante, as vezes eu preferia o tema padrão somente por conta desse detalhe, mas vocês implementaram esse recurso, muito bacana. Parabéns

**Comment by tista500** [comment]
I kept opening this post in 2 weeks, so let's close this...

Thanks guys.

Regards.
