### ISSUE TITLE
Each wifi signal quality color on dropdown list is so hard to see

### ISSUE THREAD

**Issue by truongnmt** [adapta-project/adapta-gtk-theme#298]
The wifi signal quality color on dropdown list is so hard to see, it should be bolder, only the icons in the dropdown list is hard to see, the icon on status bar is ok. 

![image](https://cloud.githubusercontent.com/assets/11817656/20867865/61c3b8cc-ba80-11e6-8ee5-fb63d0f44973.png)

**Comment by tista500** [comment]
Why did you ignore the issue-template?

I can't help this issue now, invalid.

**Comment by tista500** [comment]
No response, no reporter info. So I could not reproduce anyway.

Closed.

**Comment by txtsd** [comment]
Conversely, the wifi icons are too dark to see on my dark theme.

**Comment by truongnmt** [comment]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04 LTS
 * Gtk+ 3.0 version - libgtk-3-0:amd64 3.18.9-1ubuntu3.1
 * Desktop environment - Intel Core i3 M350, 64bit, 6GB RAM
 ```

**Adapta version (if you knew)**



**Related Application and/or Shell theming (or name of widget)**
The top left status bar


**Actual issue**
When you click on the wifi icon in the top left status bar, you will see a list of available wifi. Those icon are very hard to see the signal quality.


**Steps to reproduce (if you knew)**
1. Click the wifi icon in the top left status bar
2. See the list


**Expected behaviour**
I should clearly see the wifi signal quality 


**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> * Desktop environment - Intel Core i3 M350, 64bit, 6GB RAM

DE means what you're running as desktop session. Unity7, Gnome-Shell, Cinnamon, Budgie-desktop, LXDE, Mate, XFce4 or Gnome-Flashback?

Hmm, I imagine you're talking about `nm-applet` or `indicator-application` on `unity-panel`, if so, see my shot of Unity7 7.4.0 on Ubuntu 16.04.1 with `libnm-gtk0 1.2.0-0ubuntu0.16.04.4` and `network-manager-gnome 1.2.0-0ubuntu0.16.04.4`. I could not reproduce at all...

![screenshot from 2016-12-10 20-43-30](https://cloud.githubusercontent.com/assets/6073622/21073189/ba7dc3b4-bf1b-11e6-9f42-abe4350b6974.png)

**Comment by tista500** [comment]
See: `netwrok-manager-applet-1.2.4/src/ap-menu-item.c`
```
GtkWidget *
nm_network_menu_item_new (NMAccessPoint *ap,
                          guint32 dev_caps,
                          const char *hash,
                          gboolean has_connections,
                          NMApplet *applet)
{
	NMNetworkMenuItem *item;
	NMNetworkMenuItemPrivate *priv;
	guint32 ap_flags, ap_wpa, ap_rsn;
	GBytes *ssid;

	item = g_object_new (NM_TYPE_NETWORK_MENU_ITEM, NULL);
	g_assert (item);

	priv = NM_NETWORK_MENU_ITEM_GET_PRIVATE (item);

	nm_network_menu_item_add_dupe (item, ap);

	ssid = nm_access_point_get_ssid (ap);
	if (ssid) {
		priv->ssid_string = nm_utils_ssid_to_utf8 (g_bytes_get_data (ssid, NULL),
		                                           g_bytes_get_size (ssid));
	}
	if (!priv->ssid_string)
		priv->ssid_string = g_strdup ("<unknown>");

	priv->has_connections = has_connections;
	priv->hash = g_strdup (hash);
	priv->int_strength = nm_access_point_get_strength (ap);

	if (nm_access_point_get_mode (ap) == NM_802_11_MODE_ADHOC)
		priv->is_adhoc = TRUE;

	ap_flags = nm_access_point_get_flags (ap);
	ap_wpa = nm_access_point_get_wpa_flags (ap);
	ap_rsn = nm_access_point_get_rsn_flags (ap);
	if ((ap_flags & NM_802_11_AP_FLAGS_PRIVACY) || ap_wpa || ap_rsn)
		priv->is_encrypted = TRUE;

	/* Don't enable the menu item the device can't even connect to the AP */
	if (   !nm_utils_security_valid (NMU_SEC_NONE, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
        && !nm_utils_security_valid (NMU_SEC_STATIC_WEP, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_LEAP, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_DYNAMIC_WEP, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_WPA_PSK, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_WPA2_PSK, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_WPA_ENTERPRISE, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)
	    && !nm_utils_security_valid (NMU_SEC_WPA2_ENTERPRISE, dev_caps, TRUE, priv->is_adhoc, ap_flags, ap_wpa, ap_rsn)) {
		gtk_widget_set_sensitive (GTK_WIDGET (item), FALSE);
	}

	update_label (item, FALSE);
	update_icon (item, applet);
	update_atk_desc (item);

	return GTK_WIDGET (item);
}
```
Nm checked the 'security-types' of those AP lists and if those were invalid, menuitem node was turned into `insensitive`/`disabled` state. So I don't think this issue is not theme-specific.

**Comment by truongnmt** [comment]
Oh I think it's my icon pack that cause my trouble. I'm using Numix pack. What are you using in your screenshot?
