### ISSUE TITLE
App launching state for icons

### ISSUE THREAD

**Issue by YurySolovyov** [adapta-project/adapta-gtk-theme#299]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.1
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**

```sh
$ dpkg -l adapta-gtk-theme
3.89.1.95-0ubuntu1~xenial1
```

**Related Application and/or Shell theming (or name of widget)**
Launcher

**Actual issue**
No way to say if application is launching

**Steps to reproduce (if you knew)**
Launch any pinned application by clicking on launcher icon

**Expected behaviour**
Icon has some kind of anymation, highlight/pulsate/whatever

**Other Note (feature-request, question, etc...)**
This is working on native theme so it should be present on custom one too IMO.

**Comment by tista500** [comment]
I'm not sure which animation you're talking about, but anyway this commit improves "glow-animations", maybe: https://github.com/adapta-project/adapta-gtk-theme/commit/911e2680f0c62b84e2da3969287ab5a9eb9ad8b0

Regards.

**Comment by YurySolovyov** [comment]
For the future readers: you might need to use unity tweak tool to set something like this(see Icons section):

![image](https://cloud.githubusercontent.com/assets/2168518/21044148/762cb410-be0b-11e6-86c1-bc50ffa8c6e3.png)
