### ISSUE TITLE
Wrong-looking background behind icons

### ISSUE THREAD

**Issue by amachini** [adapta-project/adapta-gtk-theme#300]
**Distro and DE that I'm using:**
Ubuntu 16.04.1 with Unity 7.4.0

**Adapta version:**
I'm not really sure about WHICH version I'm using, but I'm sure it's the latest (checked the updates right now).

**Issue:**
The icons in the Unity launcher (also in the Alt+Tab app switcher, but I can't screenshot it) have a background (the rounded-edges square behind the icon) that before today's update for Adapta that I've installed wasn't there. I think it might be a bug because it doesn't look right:

![screenshot from 2016-12-09 22-14-20](https://cloud.githubusercontent.com/assets/21091621/21069885/1e9dfbee-be5d-11e6-8401-e52588a18da1.png)
_Screenshot also in http://imgur.com/a/INu0q_

**Expected behaviour:**
The rounded-edges square behind the icon shouldn't be showing.

Leaving this apart, I want to say thanks to tista500 for making this wonderful theme. I fell in love with it since I've saw it for first time in the OMG! Ubuntu website.

Greetings! :-)

**Comment by tista500** [comment]
See #299.
And you can disable those *chameleonic icon backgrounds* in unity-launcher via:
Unity-tweak-tool > Launcher > Icons > Icon Backgrounds  "Coloured edges".

It's not a bug but the enhancement that Ambiance improved...

Regards.
