### ISSUE TITLE
Larger window manager?

### ISSUE THREAD

**Issue by matteoalessiocarrara** [adapta-project/adapta-gtk-theme#301]
I'm using the wm of this theme in arch linux xfce (4.12), with gtk3 3.22.5. Until version 3.21.3.68 the xfwm theme was wider and had no edges. Currently it is not so, and imho looked better before. Could we have two versions of this theme? 

now
![screenshot_2016-12-10_17-27-58](https://cloud.githubusercontent.com/assets/7833001/21074628/08fccc60-befe-11e6-8933-cb49c8bba8f8.png)

before
![screenshot_2016-08-31_19-33-49](https://cloud.githubusercontent.com/assets/7833001/21074621/c2d30218-befd-11e6-872f-78e6f9361fc8.png)

**Comment by tista500** [comment]
That's for saving space, and a discussion about window-frames is here: #231.
Now both Metacity-2 and XFwm4 theming have such button spacing.

> Could we have two versions of this theme?

I'm afraid that I have to do so.

Regards.

**Comment by tista500** [comment]
Unfortunately I don't want to provide one another "alternate" xfwm4 theming currently. And if you don't need left/right/bottom frames to resize the GtkWindow, remove `bottom-*.png`, `left-*.png` and `right-*.png` from `Adapta/xfwm4` directory.

So I mark this request as "won't fix".

Regards.

**Comment by matteoalessiocarrara** [comment]
Thanks anyway, I will make a patch for my pc

**Comment by matteoalessiocarrara** [comment]
Thanks anyway, I will make a patch for my pc
