### ISSUE TITLE
Note on entry mixin usage.

### ISSUE THREAD

**Issue by euphonia** [adapta-project/adapta-gtk-theme#303]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Cinnamon
 ```

**Adapta version (if you knew)**

8db3e6389e9de2c8e1e5236520a2e3587f069683

**Related Application and/or Shell theming (or name of widget)**

entry mixin defined in shell/sass/common/_drawing.scss

**Actual issue**

The entry mixin defines normal, focus, hover, and insensitive. In the cinnamon _common.scss, it uses `entry(osd)` and `entry(osd-focus)` in a few places. 

This isn't a bug report per se because I haven't noticed it causing any problems, but I thought I'd point it out. Just skimming through your commit history, I get the impression you care about this sort of thing.

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/64c98c46081e29366e52aeb27d2823da52d8276b
