### ISSUE TITLE
Request for KDE Plasma Theme

### ISSUE THREAD

**Issue by gauravdighe1986** [adapta-project/adapta-gtk-theme#304]
Can you prepare a theme for KDE Plasma 5.8
There are not much themes that support both GTK and Plasma. So there's not much uniformity. I use some apps that are particulary GTK3 based and then I lose the uniformity.

If there are themes that support GTK as well Plasma then these issues could be sorted out.

Its just a request

**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - KDE Plasma 5.8
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Unfortunately K desktop is not my thing.

Regards.

**Comment by ceyhunnabiyev** [comment]
Yes, it would be nice for this theme to support qt5, because some of popular applications build on qt5 like Vlc, Qbittorrent..

**Comment by bil-elmoussaoui** [comment]
@varlesh might be able to help you fixing this!

**Comment by pschichtel** [comment]
I'm using qt5-styleplugins on Archlinux to enable GTK2 themes for Qt5 applications, which works ok.

**Comment by lilianmoraru** [comment]
I would also love this theme on KDE but I don't think that it applies cleanly to KDE(I am not aware of KDE supporting CSS theming).
GTK applications under KDE should not be a problem.

**Comment by jp7677** [comment]
@pschichtel thanks a lot for the tip with qt5-styleplugins. I'm using only 2 qt5 apps regularly, keepassxc and calibre, and both are looking now nearly native. Cool, that make my day!

For the record:
If you want to style your qt5 apps in Fedora with the adapta theme you should do as root:
`dnf install qt5ct qt5-qtstyleplugins`
and as your current user
```
export QT_QPA_PLATFORMTHEME=qt5ct
qt5ct
```
Within qt5ct you will need to select gtk2 as your style and adjust fonts and other options as wanted. Obviously you should have the adapta-gk2 theme installed.
You can persist the QT_QPA_PLATFORMTHEME setting by adding it to your `.profile` file. If you use the dark theme you will need to select adapta-nokto as your gnome theme since qt5ct knows nothing about global dark mode.

**Comment by mufeed20** [comment]
[This guy has made some progress i think.](https://www.reddit.com/r/Cockatrice/comments/5m3c2a/wip_adapta_theme_for_cockatrice_well_qt5_but_still/) Don't know much more.

**Comment by Paullux** [comment]
For Adapta-Nokto-Eta, I had install all plasma desktop, to edit plasma theme colors scheme, i created a file : AdaptaNoktoEta.colors
```
[ColorEffects:Disabled]
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=77,77,77
BackgroundNormal=47,61,68
DecorationFocus=0,147,163
DecorationHover=0,139,154
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=165,175,179
ForegroundPositive=0,188,212
ForegroundVisited=108,108,109

[Colors:Complementary]
ForegroundPositive=0,188,212

[Colors:Selection]
BackgroundAlternate=0,131,148
BackgroundNormal=0,188,212
DecorationFocus=0,113,126
DecorationHover=0,96,113
ForegroundActive=252,252,252
ForegroundInactive=239,240,241
ForegroundLink=253,188,75
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=0,93,104
ForegroundVisited=108,108,109

[Colors:Tooltip]
BackgroundAlternate=77,77,77
BackgroundNormal=49,54,59
DecorationFocus=0,188,212
DecorationHover=0,188,212
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=239,240,241
ForegroundPositive=0,188,212
ForegroundVisited=108,108,109

[Colors:View]
BackgroundAlternate=49,54,59
BackgroundNormal=34,45,50
DecorationFocus=22,160,133
DecorationHover=22,160,133
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=255,255,255
ForegroundPositive=39,174,96
ForegroundVisited=108,108,109

[Colors:Window]
BackgroundAlternate=77,77,77
BackgroundNormal=38,50,56
DecorationFocus=0,149,165
DecorationHover=0,149,165
ForegroundActive=61,174,233
ForegroundInactive=189,195,199
ForegroundLink=41,128,185
ForegroundNegative=218,68,83
ForegroundNeutral=246,116,0
ForegroundNormal=165,175,179
ForegroundPositive=0,188,212
ForegroundVisited=108,108,109

[General]
ColorScheme=Maia Dark
Name=Adapta Nokto Eta
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground=49,54,59
activeBlend=255,255,255
activeForeground=239,240,241
inactiveBackground=49,54,59
inactiveBlend=75,71,67
inactiveForeground=127,140,141
```
I added file in /usr/share/color-schemes/
And kdenlive and krita i choose theme Adapta-Nokto-Eta and now the two applications are more uniformed with the theme.

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/adapta-kde

**Comment by Ste74** [comment]
Hi there . Someone can explain how to fix this.. We adopt Adapta-theme for Gnome and Xfce-gtk3 edition but we have this problem with adapta..

https://github.com/manjaro/packages-community/issues/376
Thank you in advance

**Comment by tista500** [comment]
Close now, See: https://github.com/PapirusDevelopmentTeam/adapta-kde
