### ISSUE TITLE
Adapta causes emacsclient to render wrong background color

### ISSUE THREAD

**Issue by realcomplex** [adapta-project/adapta-gtk-theme#308]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - gtk3 3.22.5-1
 * Desktop environment - i3wm (i3-gaps)
 ```

**Adapta version (if you knew)**
adapta-gtk-theme 3.89.1.90-1

**Related Application and/or Shell theming (or name of widget)**
emacs, emacsclient

**Actual issue**
When opening an emacsclient instance in a new frame, the background color is not rendered correctly:
![emacs_bad](https://cloud.githubusercontent.com/assets/4990740/21151251/a8e76590-c116-11e6-8b45-266097562266.png)

Note that anything that causes the emascclient window to redraw fixes this (i.e. resizeing window, opening a buffer, switching workspaces, etc.). However, it is still annoying. 

**Steps to reproduce (if you knew)**
1. Enable adapta gtk theme
2. Start emacs in server mode: "emacs --daemon"
3. Start an emacsclient in a new frame: "emacsclient -c"
4. The emacsclient frame is now rendered as shown in the picture

**Expected behaviour**
The background color of the emacsclient window should be consistently white.

**Other Note (feature-request, question, etc...)**
Thanks in advance with any help, this gtk theme is amazing!

**Comment by tista500** [comment]
Committed workaround for damned Emacs24 window-mode: https://github.com/adapta-project/adapta-gtk-theme/commit/8fe9559965bac7326fde7ca92e39b11771f60226

Regards.

**Comment by realcomplex** [comment]
Hey @tista500, thanks for the quick reply! However, I installed adapta from the latest master branch, and it didn't change anything for me. Possibly because I'm using emacs version 25?

**Comment by tista500** [comment]
> Possibly because I'm using emacs version 25?

Hey hey, please let me know about it before tracking down... :/

**Comment by realcomplex** [comment]
Sorry for the confusion. Just tested latest master branch, still getting the same issue unfortunately...

Let me know if I can do anything to else to help.

**Comment by tista500** [comment]
FInal-shot: https://github.com/adapta-project/adapta-gtk-theme/commit/21fc7a69083d7af62a08f55b56a702c42fd20b9c

Closed.

**Comment by realcomplex** [comment]
I'm sorry, but it is not fixed for me yet... I appreciate the effort you have put into solving this, and recognize that this issue might not be worth your time. However, I would be happy to try and fix it, do you have any ideas for me on where to start? I can program, but don't have any experience with gtk themes.

**Comment by tista500** [comment]
o_O ?

That's weird. Those workarouds SHOULD work for both Emacs 24.5 and 25.1 with Gtk+ 3.x backend X11 mode...

Did you mean that this issue remained yet after restarting daemon (or systemd)?

**Comment by realcomplex** [comment]
No, appearently I'm an idot :P It's actually fixed. Thanks so much!

**Comment by tista500** [comment]
OK. Good... ;)
