### ISSUE TITLE
Request: More shadow for the right click window

### ISSUE THREAD

**Issue by Feichtmeier** [adapta-project/adapta-gtk-theme#309]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04.1
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

Nautilus? I am not sure

**Actual issue**

**Steps to reproduce (if you knew)**

Rightclick the desktop in Unity

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

When you rightclick in Unity you can hardly see the difference between the rightclick window and the background window because there is only a little shadow. Is it possible to add a bit more shadow? Thanks in advance and sorry if this is not adapta related. Just delete it then :D

![bildschirmfoto vom 2016-12-15 13-48-11](https://cloud.githubusercontent.com/assets/15329494/21224578/25f7bc4e-c2cd-11e6-9289-183e3187253f.png)
![bildschirmfoto vom 2016-12-15 13-47-59](https://cloud.githubusercontent.com/assets/15329494/21224579/25f7d5e4-c2cd-11e6-8ce3-dcfea5e864c8.png)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/28d8c9c42a275fde5a556a7c537e405ccbd9a383

The active development for Gtk+ 3.18.x theming is almost over. And there's some technical limitations in Unity7 theming as well.

So we can not improve the elevations/shadows which we've done in GNOME desktop environments (for me, Unity7 is too poor to add our shadow definitions, too poor).

Regards.

**Comment by Feichtmeier** [comment]
Thanks mate!
