### ISSUE TITLE
Possible issues with lightdm-gtk-greeter

### ISSUE THREAD

**Issue by PyGeek03** [adapta-project/adapta-gtk-theme#310]
**Reporter info**

 ```
 * Distribution - Xubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - XFCE 4, Gnome 3, KDE Plasma 5
 ```

**Adapta version (if you knew)** 
3.89.1.131-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)** 
lightdm-gtk-greeter 2.0.1-2ubuntu4

**Actual issue**
I'm not sure if this is an issue or not, but it seems that for the login window for lightdm-gtk-greeter, the colour scheme seem to be similar to Flat Plat instead of Adapta. 

**Steps to reproduce (if you knew)**
Lightdm-gtk-greeter's login window appears after booting into Xubuntu.

**Expected behaviour**
The login window color scheme should match that of Adapta's.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Adapta does not support lightdm-gtk-greeter in Gtk+ 3.18.x.

Closed

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/f190d5da462719a5085526edaeb7adf0aecc7474

Gtk+ 3.18.x theming development is almost over.

**Comment by PyGeek03** [comment]
I'm sorry for having bothered you. I'm really sad that my Xubuntu just
broke after updating to 16.10, so I have to stick with 16.04 and cannot get
GTK 3.20.

I just wanna say that I'm very grateful for your great work, and Adapta is
indeed my favorite GTK theme, and it works great with KDE too!
