### ISSUE TITLE
make fails 

### ISSUE THREAD

**Issue by millionpoundhat** [adapta-project/adapta-gtk-theme#311]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04 LTS
 * Gtk+ 3.0 version - 2.24.30-1ubuntu1
 * Desktop environment - ubuntu
 ```
Hello, I have an issue with building adapta from source, after installing dependencies manually I ran

./autogen.sh 

Which completed and gave me the option to make.Running make gives me :

Making all in gtk
make[1]: Entering directory '/home/uncle/adapta-gtk-theme/gtk'
/bin/mkdir -p ./gtk-3.18 && \
/bin/mkdir -p ./gtk-3.20 && \
/bin/mkdir -p ./gtk-3.20-eta && \
/bin/mkdir -p ./gtk-3.22 && \
/bin/mkdir -p ./gtk-3.22-eta && \
/bin/mkdir -p ./asset/assets-gtk2 && \
/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/bin/mkdir -p ./asset/assets-gtk2/Buttons && \
/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/bin/mkdir -p ./asset/assets-gtk2/Check-Radio && \
/bin/mkdir -p ./asset/assets-gtk2/Column && \
/bin/mkdir -p ./asset/assets-gtk2/Entry && \
/bin/mkdir -p ./asset/assets-gtk2/Handles && \
/bin/mkdir -p ./asset/assets-gtk2/Lines && \
/bin/mkdir -p ./asset/assets-gtk2/Others && \
/bin/mkdir -p ./asset/assets-gtk2/ProgressBar && \
/bin/mkdir -p ./asset/assets-gtk2/Range && \
/bin/mkdir -p ./asset/assets-gtk2/Scrollbars && \
/bin/mkdir -p ./asset/assets-gtk2/Shadows && \
/bin/mkdir -p ./asset/assets-gtk2/Spin && \
/bin/mkdir -p ./asset/assets-gtk2/Toolbar && \
/bin/mkdir -p ./asset/assets-gtk3
cd ./gtk-2.0 && ./recolor-gtk2.sh
cd ./sass && /usr/local/bin/sassc -t compact 3.18/gtk.scss ../gtk-3.18/gtk-contained.css
Error: unterminated argument to rgba(...)
        on line 77 of common/_colors-public.scss
>> 
   ---------------------------------------^
Makefile:1323: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/uncle/adapta-gtk-theme/gtk'
Makefile:360: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Any help is much appreciated, 

Thanks

**Comment by tista500** [comment]
o_O?

I could not reproduce. Xenial does not have any SassC packages, so where your SassC came from?

> after installing dependencies manually

Explain details. And show me the output of `sassc --version`.

**Comment by tista500** [comment]
> Gtk+ 3.0 version - 2.24.30-1ubuntu1

It is not the version of Gtk+ 3.x.

**Comment by tista500** [comment]
At lease we need to rebuild these packages to prepare for the SassC environments in Xenial: https://launchpad.net/~tista/+archive/ubuntu/build?field.series_filter=xenial

**Comment by millionpoundhat** [comment]
I installed dependencies through apt. Adapta was complaining that I did not have sassc when I ran Autogen, so I built it from the github source. 

sassc --version 

sassc: 3.2.1
libsass: 3.2.1
sass2scss: 1.0.3

libgtk-3-0:amd 3.18.9-1ubun amd64 
Libgtk2.0-0:am 2.24.30-1ubu amd64

**Comment by tista500** [comment]
> sassc: 3.2.1
> libsass: 3.2.1

Unmet dependencies on `libsass` and `sassc`: https://github.com/adapta-project/adapta-gtk-theme/issues#installation-from-git-source

It's not the issue of Adapta, so closed.
