### ISSUE TITLE
System Title bar

### ISSUE THREAD

**Issue by nmehta001** [adapta-project/adapta-gtk-theme#312]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.2
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Firefox, Chrome

**Actual issue**
The system title bar is white when the window is active, if you click away from the window the system title bar is black

**Steps to reproduce (if you knew)**
Open Google Chrome/ Firefox

**Expected behaviour**
System title bar should be black/dark with visible text

![screenshot from 2016-12-18 15-25-39](https://cloud.githubusercontent.com/assets/9056760/21294584/f3bf9a9a-c537-11e6-8f6e-3bbfb86d93cd.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O? I haven't experienced such issue now and then. So I could not reproduce anyway.

> Desktop environment - Gnome

Which is your display-server/window-protocol, Xorg or XWayland?

> Adapta version (if you knew)

How did you install Adapta? (empty is evil).

> The system title bar is white

What is the "system title bar"? DId you talk about Mutter's server-side-decorations?

Regards.

**Comment by nmehta001** [comment]
Display server is XWayland

Adapta was installed using the copr repo (3.22.4) I believe is the latest release

The system title bar is the bar that is above the application, so where you would see the close, minimise and maximise buttons it's not possible to see them using this theme when the window is active

**Comment by tista500** [comment]
> Adapta was installed using the copr repo (3.22.4) I believe is the latest release

Current release is 3.89.1.134.

> it's not possible to see them using this theme when the window is active

I said I could not reproduce:
Xwayland - 1.18.4
![screenshot from 2016-12-19 23-54-33](https://cloud.githubusercontent.com/assets/6073622/21317085/f9c77eca-c646-11e6-982c-0742011965e0.png)

**Comment by tista500** [comment]
Check if your extensions/add-ons are related to this report.

Regards.

**Comment by tista500** [comment]
Unable to track down this report...

Closed.
