### ISSUE TITLE
Fixing LibreOffice 5.2

### ISSUE THREAD

**Issue by fb87** [adapta-project/adapta-gtk-theme#313]
I have LibreOffice 5.2.3.3 running on Fedora 25. Since the new changes, the disign isn't as good as it was before, so it would be very nice if this could be resolved. :)

![unbenannt 1 - libreoffice writer_001](https://cloud.githubusercontent.com/assets/10520767/21370566/88c1e46a-c70c-11e6-8ad4-31ed929f3200.png)

![unbenannt 1 - libreoffice calc_001](https://cloud.githubusercontent.com/assets/10520767/21370585/9c0cf604-c70c-11e6-9e7e-2f3f365caad9.png)

**Comment by tista500** [comment]
Umm, there's no theme developers who want to polish the styling of those damned apps. Because most of our efforts are spoiled by upstream in every new releases.

So I won't do anything for those damned apps. Indeed, I'm really angry.

Regards.

**Comment by fb87** [comment]
The toolbars are getting a whole revamp in 5.3, but it looks very nice:
https://blog.documentfoundation.org/blog/2016/12/21/the-document-foundation-announces-the-muffin-a-new-tasty-user-interface-concept-for-libreoffice/

**Comment by tista500** [comment]
I don't trust their works even if the 'Ribbon' interface was unveiled in Release-Note. In past, they said "Gtk+ 3.20/22 support was implemented", but actually those implementations were too problematic...

Disaster again... And there's few things I can do for it, Closed.
