### ISSUE TITLE
I have Error In Kali 2.0

### ISSUE THREAD

**Issue by omicr0** [adapta-project/adapta-gtk-theme#314]
![selection_019](https://cloud.githubusercontent.com/assets/22940724/21468091/37eb93be-c9fb-11e6-8f55-02a18a7603d8.png)
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by omicr0** [comment]
Please ..Reply

**Comment by tista500** [comment]
Unmet build-dependencies: https://github.com/adapta-project/adapta-gtk-theme#installation-from-git-source

Invalid.
