### ISSUE TITLE
An error in pdf viewer

### ISSUE THREAD

**Issue by geekrainy** [adapta-project/adapta-gtk-theme#315]
When I selected a text in default pdf viewer, I can't see document content. I notice the font color is white.
Like this:
![2016122601](https://cloud.githubusercontent.com/assets/7333266/21475257/682e321a-cb64-11e6-94b9-6ad3c976c4a7.png)

The pdf viewer is [Xreader](https://github.com/linuxmint/xreader/)  My version is 1.2.2.

**Reporter info**

 ```
 * Distribution - LinuxMint 18.1
 * Gtk+ 3.0 version - 
 * Desktop environment - Cinnamon 3.2.7
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
You should report Gtk+ 3.x version as well. Because I don't know who you are, I don't know which Gtk+ version is included in LinuxMint 18.1.

Invalid.

**Comment by tista500** [comment]
This does not happen in Evince at least ver.3.2x. So I suspect devs  had rebased those apps from Gtk+ 2.x to 3.x without checking widget compatibility especially transition properties... ;/

Committed and closed.

**Comment by geekrainy** [comment]
Thank you, I will give feedback to Xreader author.
