### ISSUE TITLE
Call me stupid but I don't get which font?

### ISSUE THREAD

**Issue by systematicat** [adapta-project/adapta-gtk-theme#316]
* Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome
 *Adapta version - Git

Hi! Thank you for such a gorgeous theme! 
By default font in Fedora is Cantarell size 11 and after installing Adapta-Nokto-Eta it looks a bit alien.
I just don't get which font and which size I need to set in my Fedora 25 Gnome for best expirience with Nokto-Eta? Can you help me?

**Comment by tista500** [comment]
Read this first: https://github.com/adapta-project/adapta-gtk-theme#before-using-adapta

If your locale was `en_` family, try Roboto-hinted first. Roboto is the best truetype-font well-matched with Adapta. But Roboto does not cover/support various locales unfortunately, so you can choose the Noto-sans family instead. Adapta tries to pull Noto-sans as the default font-family in Gnome-Shell theming. Check those fonts via gnome-font-viewer or some other viewers. I usually install both of them.

Focusing to font-size, it depends on your LCD's specification and your work-flow. For example, my ThinkPad X1 Carbon (3rd-gen) has the 14" WQHD screen, so I use 10.5pt Roboto for Gtk+ widgets and Noto-mono 11pt for terminals. On the other hand, my ThinkPad Helix (1st-gen) has 11.6" FHD. then I set 9.75pt Roboto and 10.5pt Noto-mono. Finally I bought ThinkPad 13 Chromebook a couple of days ago, it has 13.3" FHD multi-touch, I'm now using 10pt Noto-sans and 10.5pt Noto-mono....

Hope this helps.

Regards.

**Comment by systematicat** [comment]
Thanx! Everything is absolutely clear!
