### ISSUE TITLE
[Kali-rolling][Gtk-3.22] Theme not showing in Gnome Tweak Tool

### ISSUE THREAD

**Issue by HazmirulZ** [adapta-project/adapta-gtk-theme#317]
**Reporter info**
 ```
 * Distribution - Kali GNU/Linux Rolling 64-bit
 * Gtk+ 3.0 version - 3.22.5-1 
 * Desktop environment - Gnome 3
 ```

**Adapta version (if you knew)**
3.89.2.12

**Related Application and/or Shell theming (or name of widget)**
gnome-tweak-tool

**Actual issue**
Adapta theme not showing in `gnome-tweak-tool`.

**Steps to reproduce (if you knew)**
I install using Git Source step. All build requirements already install. Run `./autogen.sh` `make` and `sudo make install` without any problem. I check the tweak tool > appearance > theme > gtk , Adapta theme not showing.

**Expected behaviour**
Adapta theme shown in the tweak tool and select to change the theme.

**Other Note (feature-request, question, etc...)**
I also already try to reboot after the installation and also tried to reinstall the theme, but still doesn't shown up in tweak tool.

**Comment by tista500** [comment]
o_O?
Let me see the output of `ll /usr/share/themes/Adapta/gtk-3.22`.

Regards.

**Comment by HazmirulZ** [comment]
Sorry for late reply, I got error 'cannot access '/usr/share/themes/Adapta/gtk-3.22': No such file or directory' .

**Comment by HazmirulZ** [comment]
I try to reinstall, and notice these after it is done. I'm not sure why. also I've checked the directory `ls -l /usr/share/themes/Adapta/gtk-3.22` and looks like Adapta folder in /usr/share/themes seems not created.
```
Cloning ../../openbox-3/desk.xbm
Cloning ../../openbox-3/iconify.xbm
Cloning ../../openbox-3/max_toggled.xbm
Cloning ../../openbox-3/max.xbm
Cloning ../../openbox-3/shade_toggled.xbm
Cloning ../../openbox-3/shade.xbm
make[1]: Leaving directory '/root/Downloads/adapta-gtk-theme-3.89.2.12/wm'
Making all in extra
make[1]: Entering directory '/root/Downloads/adapta-gtk-theme-3.89.2.12/extra'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/Downloads/adapta-gtk-theme-3.89.2.12/extra'
make[1]: Entering directory '/root/Downloads/adapta-gtk-theme-3.89.2.12'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/Downloads/adapta-gtk-theme-3.89.2.12'
root@IceM4nn:~/Downloads/adapta-gtk-theme-3.89.2.12# 
```

**Comment by tista500** [comment]
Logined as root!?
What a hell security policy of Kali is...

Anyway `./autogen.sh` and `make` never require root privileges, just `sudo make install` needs root privileges via `sudo` to install files into `/usr/share/themes` directory (nobody suggests to run `make` as root). Then if you'd logined as root, simply run `make install` after finishing `make`, no need to permit via `sudo`.

I'm really afraid Kali...

**Comment by HazmirulZ** [comment]
yeah, everything is good now. I run the installer once again in user. not root. and everything is fine now. Thanks you.
