### ISSUE TITLE
background/Wallpaper crash

### ISSUE THREAD

**Issue by benjamingb** [adapta-project/adapta-gtk-theme#319]
**Reporter info**

This morning was updated automatically adapta-gtk-theme via ppa and the wallpaper is not displayed, in other themes if it is displayed correctly, already reinstall but nothing

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version -  3.20.9-1ubuntu2
 * Desktop environment - adapta
 ```

**Comment by AnachronyX** [comment]
I have the same issue.

> - Ubuntu 16.10
> - Gtk+ 3.20.9
> - Gnome with Adapta theme

**Comment by happydemic** [comment]
And me - same specs.
