### ISSUE TITLE
Wallpaper vanished

### ISSUE THREAD

**Issue by meetdilip** [adapta-project/adapta-gtk-theme#320]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - default Unity 7 with 16.04 updated
 * Desktop environment - Unity 7
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
I had Adapta installed long back. Today I re-enabled it only to find wallpaper replaced by a white screen on desktop. When I switch back to Numix, all is well

**Steps to reproduce (if you knew)**

I used Unity Tweak Tool to enable Adapta, which gives this issue.

**Expected behaviour**

Wallpaper stays

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Report exact version of these packages:
```
libgtk-3-0
nautilus
unity-teak-tool
libunity-core
```

I could not reproduce.

**Comment by meetdilip** [comment]
It got fixed once I went ahead with an update available for Adapta just after reporting this issue.

**Comment by tista500** [comment]
> 3.20.8-1ubuntu0~ppa1

Hey hey, Gtk+ 3.20.x is NOT "default Unity 7 with 16.04 updated"... :(

> It got fixed once I went ahead with an update available for Adapta just after reporting this issue.

You seem to employ some PPAs to upgrade stock Gtk+ 3.18.x, In Adapta, I've recently tweaked some codes for Nautilus 3.2x: https://github.com/adapta-project/adapta-gtk-theme/commit/f0b566b994503fea3d475d2c360e3165d98c10b6

That commit fixed your nautilus's behaviour as well.

Please report CORRECT package versions you've installed... :(
Closed.

**Comment by meetdilip** [comment]
> You seem to employ some PPAs to upgrade stock Gtk+ 3.18.x, In Adapta, I've recently tweaked some codes for Nautilus 3.2x: f0b566b

I honestly had no idea about that. Is it bad ? Do I have to fix anything ? Like, removing that particular PPA.

**Comment by tista500** [comment]
This issue was related to Adapta's code itself instead of your PPAs.

But I have to say once more.
Report correct package versions you've installed, otherwise I can not track the issue down. Please take my time to develop...
