### ISSUE TITLE
Popover in Lollypop doesn't display category text

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#321]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.2
 * Desktop environment - Gnome Shell
 ```

**Adapta version (if you knew)**
latest

**Related Application and/or Shell theming (or name of widget)**
Lollypop

**Actual issue**
Popover doesn't display the category text, so that it looks like a superfluous separator:

![](https://cloud.githubusercontent.com/assets/10520767/21667892/feb2c90e-d2fc-11e6-94de-55e0011901b4.png)

![auswahl_001](https://cloud.githubusercontent.com/assets/10520767/21687875/312dfe8a-d36b-11e6-9506-03353553d9d5.png)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/8618ef26c3015caecdd083dae8eeda99c93de179
