### ISSUE TITLE
[Inkscape 0.92.x] No cc:license metadata found

### ISSUE THREAD

**Issue by pschichtel** [adapta-project/adapta-gtk-theme#322]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.5
 * Desktop environment - GNOME 3.22.2
 ```

**Adapta version (if you knew)**
3.89.2.53

**Related Application and/or Shell theming (or name of widget)**
During build

**Actual issue**
During the build pretty much every line of rendering prints this:
```
** (inkscape:6398): WARNING **: No cc:license metadata found, derived license URI from cc:License: http://creativecommons.org/licenses/by-sa/4.0/
Rendering ../assets-gtk2/Scrollbars/h-trough.png
```

This is probably related to Inkscape's 0.92 release.

**Steps to reproduce (if you knew)**
Build the theme using Inkscape 0.92+

**Expected behaviour**
No warnings during build.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.89.2.65
