### ISSUE TITLE
Lightdm gtk greeter dialog is transparent

### ISSUE THREAD

**Issue by realcomplex** [adapta-project/adapta-gtk-theme#324]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - gtk3 3.22.6-1
 * Desktop environment - i3-gaps/xfce
 ```

**Adapta version (if you knew)**
3.89.2.53-1

**Related Application and/or Shell theming (or name of widget)**
lightdm 1:1.18.3-1
lightdm-gtk-greeter 1:2.0.2-1

**Actual issue**
The login dialog of the lightdm gtk greeter is completely transparent when the Adapta theme is applied.

**Steps to reproduce (if you knew)**
Install lightdm, lightdm-gtk-greeter. Change the gtk greeter theme to Adapta. Switch to the greeter.

**Expected behaviour**
The login dialog should not be transparent; a background image makes the text hard to read.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
It depends on your brightness of wallpapers, and we can not concern/support all of wallpapers in the world... :(

Regads.

**Comment by realcomplex** [comment]
I think Adapta has very non-standard behaviour for the login dialog. Here is a comparison between the login dialog.

Actual behaviour (under Adapta):
![adapta](https://cloud.githubusercontent.com/assets/4990740/21755260/f8dacc22-d5c5-11e6-85c5-a0d095c399e0.jpg)

Expected behaviour (here under Adwaita):
![adwaita](https://cloud.githubusercontent.com/assets/4990740/21755261/fd20f5e0-d5c5-11e6-8602-657acd9c5ecc.jpg)

(username and host hidden)

Sorry for the poor image quality.

**Comment by tista500** [comment]
Adwaita is NOT modern for us...

**Comment by realcomplex** [comment]
Okay I see what you mean. I'll make some modifications to my wallpaper then. Thank you for your time!

**Comment by tista500** [comment]
Back to classical interfaces: https://github.com/adapta-project/adapta-gtk-theme/commit/6cd8af26fbbbba721a87eda97c3278c2c5b56e36

Ugly though... :(

**Comment by realcomplex** [comment]
Personally I like it. However, it's up to you; if you think that this goes against the spirit of the theme / is ugly, then I'll be fine if you revert it. I managed to draw some stuff on my wallpaper that made the old situation look better too. Thanks anyway for the help!
