### ISSUE TITLE
Line at top of screen

### ISSUE THREAD

**Issue by shaansheikh** [adapta-project/adapta-gtk-theme#325]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - 3.20.9-1ubun
 * Desktop environment - Unity
 ```

**Actual issue**

At the top edge of the screen there is a line under the menu bar. I find this very annoying. I'm not sure if it's intentional or not, but I find it to be very annoying. I thought it may be intentional because I noticed the color of the line changes depending on my wallpaper. However, I don't see it in screenshots others have posted of their Adapta installs.

![image](https://cloud.githubusercontent.com/assets/4933608/21755797/f7ff2728-d5e6-11e6-869b-03dc6abe75d7.png)

It's not that noticible in the screenshot when viewed in the browser because the white bar is at the top edge of the image next to the white colored background. However, it's more noticable on my actual desktop because it's on a dark wallpaper next to a dark screen bezel. Open it in a new tab and fullscreen it to see what I mean.

Is this intentional or not? Is there any way to get rid of it?

**Comment by tista500** [comment]
Report Gtk+ 3.x version first, please.

**Comment by shaansheikh** [comment]
Sorry, it's 3.20.9-1ubun

**Comment by tista500** [comment]
Ah, it happens in case:
* If "show desktop icons" key was enabled via gsettings
* If Ubuntu (Unity7) specific patch was applied to Nautilus
* Logined into Unity7

Confirmed and committed: https://github.com/adapta-project/adapta-gtk-theme/commit/5da9e971650bf37066c5ba4a93a14bb73a30e6d0

Regards.
