### ISSUE TITLE
Linux Mint 18 Adapta Nokto GTK3 theme parsing error

### ISSUE THREAD

**Issue by ryu0** [adapta-project/adapta-gtk-theme#328]
**Reporter info**

 ```
 * Distribution - Linux Mint 18
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - XFCE
 ```

**Adapta version (if you knew)**
3.89.2.88

**Related Application and/or Shell theming (or name of widget)**
xed, or any other GTK3 applications

**Actual issue**
GTK3 applications using Adapta Nokto theme from the adapta-gtk-theme package provided by the Ubuntu 16.04 PPA display the following error message about the GTK3 theme when booted:
(xed:15970): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:2750:55: Not a valid image

**Steps to reproduce (if you knew)**
Just launch any GTK3 application and it will print this theme parsing error.

**Expected behaviour**
No GTK3 errors related to the theme being used.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/3376d318be9452ab2cea61dc64d5ba8b5683d2a8

Regards.
