### ISSUE TITLE
Telegram theme

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#329]
**Reporter info**

 ```
 * Distribution -Archlinux
 * Gtk+ 3.0 version - 3.22.2
 * Desktop environment -  Gnome latest stable version
 ```

**Adapta version (if you knew)** latest git version

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Since the latest version of telegram 1.0, you can now apply a theme to the application! it should be cool to have an adapta theme for telegram. 
Here's an example of the default telegram theme https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/default.tdesktop-theme

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/2284fb1e981ae3ff9da5897839bb99fd4b6f294b

But I'm not a telegram user, so some part of styling might be incorrect though...

Regards.

**Comment by bil-elmoussaoui** [comment]
Perfect! Thanks :100:
