### ISSUE TITLE
Unreadable text on GtkMessageDialog

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#331]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.2
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)** Latest git version

**Related Application and/or Shell theming (or name of widget)** GtkMessageDialog > GtkExpander

**Actual issue**
![screenshot from 2017-01-15 16-08-49](https://cloud.githubusercontent.com/assets/7660997/21963532/eb1c594e-db3c-11e6-80f8-c8512a5933a7.png)

![screenshot from 2017-01-15 16-05-50](https://cloud.githubusercontent.com/assets/7660997/21963521/c55459fa-db3c-11e6-9227-1f2bab89b2e7.png)

Here's the hierarchy of the widget
![screenshot from 2017-01-15 16-08-16](https://cloud.githubusercontent.com/assets/7660997/21963525/dbec6d74-db3c-11e6-9d77-9b523b5239a3.png)

**Steps to reproduce (if you knew)**
Just try to remove a file that was created using root permissions 

**Expected behaviour**
The font color should be more visible 
The same widget with Adwaita 
![screenshot from 2017-01-15 16-10-29](https://cloud.githubusercontent.com/assets/7660997/21963547/26c469a0-db3d-11e6-87c7-5309dae0b5d5.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/7695636dacaa2724c040fcbbb2a6e364d5f347de

Regards.
