### ISSUE TITLE
Adapta theme for Telegram Desktop?

### ISSUE THREAD

**Issue by pschichtel** [adapta-project/adapta-gtk-theme#332]
It would be nice to have an Adapta themed Telegram client.
They added theming support in their 1.0 release:
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/default.tdesktop-theme

**Comment by bil-elmoussaoui** [comment]
Duplicate of #329

**Comment by pschichtel** [comment]
oh, completely missed that one, thanks
