### ISSUE TITLE
Gtk.Button on a selected Gtk.ListBoxRow

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#334]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.7
 * Desktop environment -  Gnome 3.22.2
 ```

**Adapta version (if you knew)** Latest git version

**Related Application and/or Shell theming (or name of widget)** Gtk.Button on a selected Gtk.ListBoxRow (maybe the same for Gtk.FlowBoxChild) anyway related to `.selected` class 

**Actual issue**
![screenshot from 2017-01-18 08-05-10](https://cloud.githubusercontent.com/assets/7660997/22054306/2f7dbd84-dd55-11e6-9184-3dcb6f64b680.png)
![screenshot from 2017-01-18 08-04-57](https://cloud.githubusercontent.com/assets/7660997/22054307/2f8b5cd2-dd55-11e6-9c4c-9641ce9dc741.png)

Also this is slightly different issue, but i've remarked  that when i use
```python
button = Gtk.Button()
label = Gtk.Label()
label.set_text("hello world")
button.add(label)
```
The font styling is slightly different than it's when i use (font weight)
```python
button = Gtk.Button()
button.set_label("hello wrold")
```
Edit:  Here's a simple python code to reporduce this
```python
from gi import require_version
require_version("Gtk", "3.0")
from gi.repository import Gtk

class Main(Gtk.Window):

	def __init__(self):
		Gtk.Window.__init__(self)
		self.connect("destroy", self.on_quit)
		mainbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
		self.set_border_width(18)
		# Button with issue
		button = Gtk.Button()
		label = Gtk.Label()
		label.set_text("look i'm different!")
		button.add(label)
		# Normal Button
		button2 = Gtk.Button()
		button2.set_label("hey!")

		mainbox.pack_start(button, False, False, 6)
		mainbox.pack_start(button2, False, False, 6)

		self.add(mainbox)
		self.show_all()

	def on_quit(self, *args):
		Gtk.main_quit()

app = Main()
Gtk.main()
```
And here's a screenshot that shows the difference
![screenshot from 2017-01-18 08-24-01](https://cloud.githubusercontent.com/assets/7660997/22054770/9f2271a0-dd57-11e6-8af4-ff70dfc2c1ec.png)

**Steps to reproduce (if you knew)**
There's no application that uses Gtk.Button inside a Gtk.ListBoxRow but anyway, i'm bad designer and i used buttons instead of symbolic icons.

**Expected behaviour**
A different buttons styling. I have the same issue with Adwaita, but who cares! it's not the best out there!

**Other Note (feature-request, question, etc...)**

Thank you for the great work!

**Comment by bil-elmoussaoui** [comment]
Sorry, I've completely forgot about the possibility to set the selection mode to None. So the first issue is invalid! 
What about the second part of the issue ?

**Comment by bil-elmoussaoui** [comment]
Yeah, i did that because i replace the label with a Gtk.Spinner to avoid users spamming the Gtk.Button. In doing so, i can reuse the Gtk.Label later and add it back to the Gtk.Button

**Comment by tista500** [comment]
Who set the "preffered_width" of GtkButton?
I suspect your code seems to do scaling 1st button labels to contain all of chars. Could you please set proper width of GtkButton enough wider.

**Comment by bil-elmoussaoui** [comment]
I don't rescale anything, the buttons are created with code example i gave you. Just create a simple python file copy/paste and execute it and i will be able to see by yourself

**Comment by bil-elmoussaoui** [comment]
Ah okey! By taking a look with Gtk.Inspector it seems that Gtk adds a `text-button` class. I will add that manually.
So both issues are invalid!
Closing, thanks for your time!
