### ISSUE TITLE
[Question] Matching Gedit theme.

### ISSUE THREAD

**Issue by systematicat** [adapta-project/adapta-gtk-theme#335]
Hi @tista500 

I've create a theme for Gedit with Material colors for syntax and Adapta colors for interface. Not sure about PR maybe /extra? Here it is - https://github.com/systematicat/gedit-material-theme

**Comment by tista500** [comment]
Looks cool! :)

I will prepare for PR by creating base directories and editing makefile, so wait a moment...
Be right back soon...

Regards.

**Comment by tista500** [comment]
Forgot to mention.
Is it OK to publish your code under GPLv2?

**Comment by tista500** [comment]
@systematicat,

OK to PR.
Please create `extra/gedit` directory.
Then put your `adapta.xml` and `readme.md` into that directory.

Regards.

**Comment by bil-elmoussaoui** [comment]
@tista500 can you please install this under gtksourceview instead of gedit? this way it can be detected by Builder and Gedit :+1:

**Comment by tista500** [comment]
I'm not willing to bundle the "installer"... that xml should be copied by hand of users at their own risk, isn't it? I won't install any files outside of our `themes/Adapta*` directories...

**Comment by tista500** [comment]
Or push the request fo upstream?

**Comment by bil-elmoussaoui** [comment]
Ah okey! I thought it will be installed installed automatically :)

**Comment by tista500** [comment]
As https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes said, `~/.local/share/...` will be safe for regular users...

**Comment by systematicat** [comment]
@tista500 PR sended. GPLv2 is OK since I'm usng WTFPL. You can do WHAT THE F**K YOU WANT with it :-)

**Comment by tista500** [comment]
@systematicat,

OK, now merged...

Regards.

**Comment by systematicat** [comment]
Shit! I forgot to change paths in readme. Sorry.
