### ISSUE TITLE
Activity bars compatibility with the Shelltile extension

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#338]
In Gnome Shell you introduced activity bars for tiled windows, which I like pretty much. But I use the shell extension [Shelltile](https://github.com/emasab/shelltile) for improved tiling options. When I now tile a window by pushing it against one edge, I no more get those activity bars. Is there a way for making this extension compatible with the Adapta theme?

**Comment by tista500** [comment]
Hmm, Mutter does NOT support horizontally aligned `.tiled` style-class. Gnome-Shell is not the window-manager but shell. So I don't think extensions had those features are good idea...

If you need such vertically aligned and/or multi-column tiled states, you should ask/push some ideas to the development team of Mutter.

Regards.

**Comment by fbruetting** [comment]
So you're saying, this extension should affect Mutter directly instead of Gnome Shell? Sorry, I don't have any idea about window management…

**Comment by tista500** [comment]
I meant extensions should not implement such things. Those features should be handled by Mutter at least in X11-mode Gnome-Shell (in XWayland, wayland-compositor instead).

**Comment by tista500** [comment]
Or develop their(your) own window-manager based on libmutter to implement those tiled window handler as the extension of Mutter...

So I could not solve your issue currently.
