### ISSUE TITLE
Inconsistent fonts

### ISSUE THREAD

**Issue by 392781** [adapta-project/adapta-gtk-theme#339]
**Reporter info**

 ```
 * Distribution - Xubuntu
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - XFCE
 ```

**Actual issue**
Panel font is the medium weight of the theme while window fonts are the same light weight.
I'm new to this but I was trying to look for the css file that manages weights and just fix it for myself.

**Comment by tista500** [comment]
Let me see your basis of interface design. Are there any evidences we should use the exact same weight between panel widget and GtkWindow?

I don't have any ideas why you said "Inconsistent fonts".

**Comment by 392781** [comment]
[http://i.imgur.com/Gem0T38.png](Here is what I mean)

Shell window ends up with Ubuntu Light while panel uses Ubuntu light with weight 400.  Is this as intended or is something broken on my end?  This propagates through all windows btw.

**Comment by tista500** [comment]
Ubuntu fonts are not our things. See README. Light weight fonts are NOT for the Material Design at least.

**Comment by 392781** [comment]
Gotcha.  Thanks for the response.
