### ISSUE TITLE
nautilus file preview looks weird

### ISSUE THREAD

**Issue by philiparvidsson** [adapta-project/adapta-gtk-theme#341]
**Reporter info**

 ```
 * Distribution Ubuntu GNOME 16.10
 * Gtk+ 3.0 version - 3.20.9-1ubun
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**

Current (as of creating the issue).

**Related Application and/or Shell theming (or name of widget)**

Nautilus ('Files')

**Actual issue**

The background color in text file preview in Nautilus makes it hard to read syntax highlighted text. It would be better to switch to a light background with dark text.

**Steps to reproduce (if you knew)**

Press space in Nautilus to preview a text file.

**Expected behaviour**

The text background color should be white. The current color, dark slate or something similar, looks weird and broken. See screenshot.

![image](https://cloud.githubusercontent.com/assets/1163299/22348659/ded694e6-e40c-11e6-907c-eb134cfbacb2.png)

**Comment by tista500** [comment]
> The text background color should be white

Disagreed.
https://git.gnome.org/browse/sushi/tree/src/js/viewers/text.js
GtkSourceView should be drawn with its colour-scheme defined by users. Sushi just only pulls your colour-scheme theme.

Or use our color-scheme: https://github.com/adapta-project/adapta-gtk-theme#gtksourceviewgedit-color-scheme-support

Closed.
