### ISSUE TITLE
Installation of v 3.89.3.58-1 from AUR fails due to missing file gtk.gresource

### ISSUE THREAD

**Issue by jdalrymple** [adapta-project/adapta-gtk-theme#343]
**Reporter info**

 ```
 * Distribution - Linux hyde 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux

 * Gtk+ 3.0 version - gtk3 3.22.7-2
 * Desktop environment - Gnome3 ( gnome-shell v3.22.2+18+gdf7727a-1)
 ```

**Adapta version (if you knew)** - v3.89.3.58-1

**Actual issue**
Seems to crash when it cant find a resource :
cp: cannot stat './gtk-3.18/gtk.gresource': No such file or directory

See full error below:

==> Starting package()...
Making install in gtk
make[1]: Entering directory '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/src/adapta-gtk-theme-3.89.3.29/gtk'
make[2]: Entering directory '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/src/adapta-gtk-theme-3.89.3.29/gtk'
make[2]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta
/usr/bin/mkdir -p /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto
/usr/bin/mkdir -p /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta
/usr/bin/mkdir -p /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta
'./index.theme' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/usr/bin/mkdir -p /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css ./gtk-3.18/gtk.gresource ./asset/assets-gtk3/thumbnail@2.png ./asset/assets-gtk3/thumbnail.png /tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0
'./gtk-3.18/gtk.css' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/gtk.css'
'./gtk-3.18/gtk-dark.css' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/gtk-dark.css'
cp: cannot stat './gtk-3.18/gtk.gresource': No such file or directory
'./asset/assets-gtk3/thumbnail@2.png' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
make[2]: *** [Makefile:1419: install-data-local] Error 1
make[2]: Leaving directory '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/src/adapta-gtk-theme-3.89.3.29/gtk'
make[1]: *** [Makefile:1210: install-am] Error 2
make[1]: Leaving directory '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/src/adapta-gtk-theme-3.89.3.29/gtk'
make: *** [Makefile:360: install-recursive] Error 1
==> ERROR: A failure occurred in package().
Aborting...
The build failed.

**Steps to reproduce (if you knew)**
packer -S adapta-gtk-theme

**Comment by tista500** [comment]
Hey, I'm not a contributor of AUR packages, file a report to https://aur.archlinux.org/packages/adapta-gtk-theme/ before posting here... :(

Regards.

**Comment by tista500** [comment]
And  you mean you had verified that your issue had happened with 'building from source' as well?

**Comment by jdalrymple** [comment]
@tista500 Will do sorry! Just saw a comment mentioning the same problem and it was suggested it be reported upstream. I haven't verified building from source. Will try this afternoon.

**Comment by jdalrymple** [comment]
Installing from source seemed to have solved the problem. All went smoothly!

**Comment by tista500** [comment]
Your package version seems:

> v3.89.3.58-1

But your temp directory for build has:

> `make[1]: Entering directory '/tmp/packerbuild-1000/adapta-gtk-theme/adapta-gtk-theme/src/adapta-gtk-theme-3.89.3.29/gtk'`

Isn't it better purging the package `adapta-gtk-theme` (or clean up build directory) and re-install it?

**Comment by pschichtel** [comment]
Some AUR helpers seem to do dirty builds, which is problematic. There is not much I can do from the package definition side.
