### ISSUE TITLE
VMware Player does not get properly skinned

### ISSUE THREAD

**Issue by hogar1977** [adapta-project/adapta-gtk-theme#344]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - 3.22.7
 * Gtk+ 2.0 version - 2.24.30
 * Desktop environment - Gnome 3.22
 ```

**Adapta version - 3.89.3.74**
Adapta Nokto Eto theme

**Related Application and/or Shell theming (or name of widget)**
VMware Player 12.5.2

**Actual issue**

Don't know if this is the theme issue or not, but I figure if anyone will know how to fix this properly you guys here will...

**Steps to reproduce (if you knew)**

When I use for example Synaptic (app package manager) only app title bar gets dark but everything else remains light themed. I suppose that is due to the app being gtk2? But at least its usable.
On the other hand VMware Player 12.5.2 build-4638234  (also gtk2 app afaik) when I apply Adapta theme, some windows change to dark and look perfectly in line with the theme, but menus and some windows stay light themed with light text making it not very nice to use. If I switch to default Adwaita theme, all the menus and windows in the app revert to light theme with dark text even though I selected the global dark theme, but at least it looks ok from the usability standpoint.

See screenshots below
![wmvare about - looks good in adapta](https://cloud.githubusercontent.com/assets/25427104/22415230/7e60dbf4-e6d6-11e6-96a0-84d75a6919c9.png)
![wmvare - any selected option looks like this in adapta](https://cloud.githubusercontent.com/assets/25427104/22415228/7e608b68-e6d6-11e6-9b74-236d4478174e.png)
![wmvare - any selected option looks like this in adwaita - default global dark](https://cloud.githubusercontent.com/assets/25427104/22415229/7e60a4cc-e6d6-11e6-9148-71dfa6ffae80.png)
![wmvare - dropdown menus in adapta](https://cloud.githubusercontent.com/assets/25427104/22415231/7e611088-e6d6-11e6-94d7-5b1c5e05072a.png)

...

**Expected behaviour**

Either properly dark themed, or let it be light themed but with dark text but not what I have now :-)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Synaptic (app package manager) only app title bar gets dark but everything else remains light themed. I suppose that is due to the app being gtk2?

No.
Synaptic is Gtk+ 3.x app now. But it's already outdated as default graphical package manager, so I won't do anything for that app...

> VMware Player 12.5.2 build-4638234 (also gtk2 app afaik)

For me, it ls not the Gtk+ app, it just has Gtk+ backend to render widgets on GNOME eco-system. And indeed, that app uses Gtk+ 2.x (core components are written in Java?).

>  but menus and some windows stay light themed with light text making it not very nice to use. 

Please check whether some other Gtk+ themes like Arc can render properly with complete dark-variant (because Arc also has dark-variant Gtk+ 2.x theming) or not...

> f I switch to default Adwaita theme, all the menus and windows in the app revert to light theme with dark text even though I selected the global dark theme,

Because Adiwaita does not have any dark-variant Gtk+ 2.x theming.

Regards.

**Comment by hogar1977** [comment]
Hi, thank you for such a quick reply.
And by the way, the theme is beautiful. Really makes my desktop pop...

Went and installed arc theme. With this theme it is only slightly better, now the dropdown menus are themed properly (dark background, light text) but the VM settings window remained exactly the same as on my screenshot... do I need to restart the app for these themes to take full effect or not?

**Comment by tista500** [comment]
> do I need to restart the app for these themes to take full effect or not?

Yes please...

**Comment by hogar1977** [comment]
No, same as I reported before...

Arc theme is only marginally better in a sense that dropdown menues get themed, but once I pick any option, like VM settings, when that window opens it does not get themed...

I don't have Unity installed to see how it would behave there but I think I have seen screenshots on internet of exactly this app (although I don't know what version) with dark theme in Ubuntu Unity... without issues that I now see...

**Comment by tista500** [comment]
> No, same as I reported before...

Sounds that issue (shown with Fig.2) seems to be "theme-unrelated" issue for me. If that was related to VMWare codes ifself, we can not solve the issue from theme-side...

> Arc theme is only marginally better in a sense that dropdown menues get themed,

Strange...
I haven't seen such issues in any other native Gtk+ 2.x apps.

**Comment by hogar1977** [comment]
I'm not a developer myself,
especially not a gtk one, but I would say it might be that app developer forgot to make that background property themeable and went with a fixed background color? Or it doesn't work that way?
I agree that this looks more as a application issue and not theme issue. In any case thx for your help. Will try to ping WMware about it, although I have 0% hope of any success on that front :-)

**Comment by tista500** [comment]
> but I would say it might be that app developer forgot to make that background property themeable and went with a fixed background color?

In some cross-platform apps, those apps bring such incorrect theming...
See #246. As of some comments, they have own Gtk+ bindings (via gtkmm?) to override the Gtk+ theming.

Just closed now, if we could get some ideas for this issue, I will re-open this.

Regards.
