### ISSUE TITLE
Maximising Chromium does not keep colour consistency in title bar

### ISSUE THREAD

**Issue by Bulmanator** [adapta-project/adapta-gtk-theme#346]
**Reporter info**
Chromium version: 56.0.2924.76 (Developer Build 64-bit)
 ```
 * Distribution - Antergos Arch Linux
 * Gtk+ 3.0 version - 3.22.7-2
 * Desktop environment - Gnome 3.22.2
 ```

**Adapta version**
git commit f01e5a5 (Latest as of writing this)

**Related Application and/or Shell theming (or name of widget)**
Chromium

**Actual issue**
When maximising the Chromium window whilst using 'Use system title bar and boarders' will change the colour of the title bar to keep consistent with the Gnome Shell theme however the background to the tabs will stay the same as if it was not maximised

This is what the title bar looks like when not maximised
![screenshot from 2017-01-30 20-06-46](https://cloud.githubusercontent.com/assets/8584482/22439593/2a62d5e6-e728-11e6-9242-387b93b05f0b.png)
And this is how it looks while maximised, as you can see the title bar changes correctly but the tabs do not
![screenshot from 2017-01-30 20-08-15](https://cloud.githubusercontent.com/assets/8584482/22439596/2c63b996-e728-11e6-8290-b893c9188168.png)

**Steps to reproduce**
1. Open Chrome/ Chromium
2. Maximise the window

If it is an issue with Chromium itself, would it be possible to change it so maximising doesn't change the title bar colour for Chromium
If you require any more information please let me know

**Comment by timvisee** [comment]
I've seen this with quite a few other applications too. Such as Firefox, Telegram, FileZilla and some other applications that have, for example, a menu bar inside the window. I know Firefox and Telegram themes are a work in progress or not yet supported, but still.

I don't think the developer has in mind to fix this, although I'd think that would be awesome!

**Comment by bil-elmoussaoui** [comment]
It's just impossible. Those applications uses Gtk 2 which does not provide a specific styling class when the window widget is maximised

**Comment by Bulmanator** [comment]
Ah right, I didn't know this but that is unfortunate
From the Chromium standpoint according to this: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_gtk_theme_integration.md
GTK3 will become default sometime soon after Chromium 57 is released and GTK2 will be deprecated, but then again we have no way of knowing when this will come out
Thanks for pointing this out

**Comment by tista500** [comment]
Wait until fully Gtk+ 3.x support has landed in Chrome(ium) stable-channel...
But that "tab-bar" is the internal (specific) widget rendered by its own, so we will need specific (extra) style-class or node to do theming though (surely those apps should support `.maximized` and `.tiled` style-classes in their GtkWindows as well).

Anyway currently I had no plan to change the styling of Chrome(ium).

Closed...
