### ISSUE TITLE
Firefox URL history highlight - Location bar

### ISSUE THREAD

**Issue by zeten30** [adapta-project/adapta-gtk-theme#347]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
201702011200git

**Related Application and/or Shell theming (or name of widget)**
Firefox 51

**Actual issue**
Item in location bar (URL) history is not highlighted with alternate background color (like in other themes or with older Firefox / Adapta). Highlited item is not different from other items, only font color differs. 

![firefox-url-history-highlight](https://cloud.githubusercontent.com/assets/1825873/22525362/29530504-e8c7-11e6-9f8c-48708a990aa8.png)

**Steps to reproduce (if you knew)**
Open location bar history in firefox

**Expected behaviour**
Highlighted item should differ on first sight

**Comment by tista500** [comment]
Firefox 51 did not landed in our Ubuntu 17.04 yet and I also did not see it...

**Comment by zeten30** [comment]
Ok, not a big issue. It looks more like Firefox problem. I tested downgrade to Firefox 49 and it works normally.

![firefox-49](https://cloud.githubusercontent.com/assets/1825873/22526661/64dd0908-e8cc-11e6-8497-5a660c7ce874.png)

However, it works with Adwaita or NumixSX themes and Firefox 51. There might be some missing piece..

**Comment by tista500** [comment]
Sounds strange...

My Firefox 52,0b2 seems to work as I expected:
![screenshot from 2017-02-02 06-25-35](https://cloud.githubusercontent.com/assets/6073622/22526969/ba15706a-e910-11e6-93b3-7d4a3023b8a4.png)

**Comment by zeten30** [comment]
Really strange. Anyway. Beta 52 works as expected on my system. So this is really Firefox problem (or maybe just the Fedora packaged version). I'm closing this because it's not theme issue.

**Comment by zeten30** [comment]
Hi, I've found the culprit. Fedora maintainers added a specific patch recently  and it's breaking Firefox appearance with Adapta themes:( So this is a Fedora specific thing.

You can review it if interested. I've build a custom RPM without this patch and I experienced no issues.

[patch.zip](https://github.com/adapta-project/adapta-gtk-theme/files/747314/patch.zip)

BTW: Thx for great job with Adapta!

Cheers
Milan

**Comment by tista500** [comment]
A workaround was committed: bd8c6fa

Regards.

**Comment by tista500** [comment]
The 2nd shot was committed: bfb2516

Regards.

**Comment by zeten30** [comment]
Perfect. Thank you very much.
