### ISSUE TITLE
Wrong rendering with threeview while expanding a node NOT selected

### ISSUE THREAD

**Issue by luca-viggiani** [adapta-project/adapta-gtk-theme#348]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.7-2
 * Desktop environment - GNOME Shell 3.22.2
 ```

**Adapta version (if you knew)**
Latest fron GIT 2017-02-03 9.14 CET - dd75ce929ea425d4a267a38b54ab5b773e9f91af

**Related Application and/or Shell theming (or name of widget)**

Gnome Builder

**Actual issue**

When you expand a node (not selected) in the three view, the node disappears (rendered same color as background?). The node is actually there because if you click on the empty space, it will appear again.
See attached video in zip file

**Steps to reproduce (if you knew)**
1) Open gnome-builder nd open any projects
2) Expand a node on the treeview (do not select that node, just click on the triangle icon)

The node will expand but the node itself will "disappear"

3) Click on the empty space were the node is supposed to be

The node will appear again.

[treeview issue.zip](https://github.com/adapta-project/adapta-gtk-theme/files/749857/treeview.issue.zip)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/5bd7e1a762b7f6a2e17223808f9db3159e96a078

Regards.
