### ISSUE TITLE
Active unity launcher icons get a square as background

### ISSUE THREAD

**Issue by johannesjo** [adapta-project/adapta-gtk-theme#349]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - ?
 * Desktop environment - Unity 7
 ```

**Adapta version (if you knew)**

Latest from the ppa

**Actual issue**
Active unity launcher icons get a square as background. 
![http://www.directupload.net/file/d/4622/wh86isez_png.htm](http://fs5.directupload.net/images/170204/wh86isez.png)

**Expected behaviour**

There should be no square!

**Comment by tista500** [comment]
Set Unity-tweak-tool > Launcher > Icons > Icon backgrounds: **Coloured edges**.
But that disables any "launching" animations as well.

Closed.

**Comment by johannesjo** [comment]
Thanks! That did it!
