### ISSUE TITLE
make: *** [install-recursive] Error 1

### ISSUE THREAD

**Issue by ConraD22** [adapta-project/adapta-gtk-theme#350]
**Reporter info**

 ```
 * Distribution - ubuntu gnome16.10
 * Gtk+ 3.0 version - 3.22.7-1ubun amd64
 * Desktop environment -  Gnome 3.22
 ```

**Actual issue**

when i run the "sudo make install" command line it gives me the next error:

**Other Note (feature-request, question, etc...)**

Makefile:981: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/home/conrad/adapta-gtk-theme/gtk'
Makefile:781: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/conrad/adapta-gtk-theme/gtk'
Makefile:361: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by tista500** [comment]
I could not reproduce, please read: https://github.com/adapta-project/adapta-gtk-theme#installation-from-git-source

And my PPA does not have any failures while `make` and `make install` as well...

Closed.
