### ISSUE TITLE
Fail sudo make install

### ISSUE THREAD

**Issue by Kawumek** [adapta-project/adapta-gtk-theme#351]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome3
 ```
**Actual issue**
Errors after `sudo make install`
**Log**
[kawumek@localhost adapta-gtk-theme-3.89.3.89]$ sudo make install
Making install in gtk
make[1]: Entering directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
make[2]: Entering directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
make[2]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/share/themes/Adapta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto
/usr/bin/mkdir -p /usr/share/themes/Adapta-Eta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /usr/share/themes/Adapta
'./index.theme' -> '/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/usr/bin/mkdir -p /usr/share/themes/Adapta/gtk-3.0
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css ./gtk-3.18/gtk.gresource ./asset/assets-gtk3/thumbnail@2.png ./asset/assets-gtk3/thumbnail.png /usr/share/themes/Adapta/gtk-3.0
'./gtk-3.18/gtk.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk.css'
'./gtk-3.18/gtk-dark.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk-dark.css'
cp: cannot stat './gtk-3.18/gtk.gresource': No such file or directory
'./asset/assets-gtk3/thumbnail@2.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
Makefile:992: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
Makefile:792: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
Makefile:360: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
[kawumek@localhost adapta-gtk-theme-3.89.3.89]$ ^C
[kawumek@localhost adapta-gtk-theme-3.89.3.89]$ sudo make install
Making install in gtk
make[1]: Entering directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
make[2]: Entering directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
make[2]: Nothing to be done for 'install-exec-am'.
/usr/bin/mkdir -p /usr/share/themes/Adapta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto
/usr/bin/mkdir -p /usr/share/themes/Adapta-Eta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /usr/share/themes/Adapta
'./index.theme' -> '/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/usr/bin/mkdir -p /usr/share/themes/Adapta/gtk-3.0
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css ./gtk-3.18/gtk.gresource ./asset/assets-gtk3/thumbnail@2.png ./asset/assets-gtk3/thumbnail.png /usr/share/themes/Adapta/gtk-3.0
'./gtk-3.18/gtk.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk.css'
'./gtk-3.18/gtk-dark.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk-dark.css'
cp: cannot stat './gtk-3.18/gtk.gresource': No such file or directory
'./asset/assets-gtk3/thumbnail@2.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
Makefile:992: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
Makefile:792: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/kawumek/Documents/adapta-gtk-theme-3.89.3.89/gtk'
Makefile:360: recipe for target 'install-recursive' failed

**Comment by tista500** [comment]
Dup of #290?

Anyway check the build requirements again...

**Comment by tista500** [comment]
The latest copr uses this spec file: http://copr-dist-git.fedorainfracloud.org/cgit/heikoada/gtk-themes/adapta-gtk-theme.git/tree/adapta-gtk-theme.spec?id=df7647b4b64d189bee6df2dd0919d1de75da6417

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/26dd953d0b7e2a145eb2a4d3a9a84a2de74108b6 and https://github.com/adapta-project/adapta-gtk-theme/commit/951a702dd1b1b733199799606becdf66b87f6b5c

Regards.
