### ISSUE TITLE
Cannot select Adapta as GTK+ theme in Fedora 25 with gnome-tweak-tool

### ISSUE THREAD

**Issue by ghaabor** [adapta-project/adapta-gtk-theme#352]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.22.7
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**

adapta-gtk-theme-common.noarch
adapta-gtk-theme-gtk3.noarch 
3.89.3-1.201702071905gitbac67c6.fc2 from here: https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/

**Related Application and/or Shell theming (or name of widget)**

gnome-tweak-tool 3.22.0-1.fc25
gnome-shell-theme-adapta.noarch (same source as above)

**Actual issue**

I cannot select Adapta as the GTK+ theme, only Adwaita. After installing gnome-shell-theme-adapta.noarch from the repo above I can set the shell theme which changes the status bar and the dash/dock but I still cannot select Adapta as the GTK+ theme. 

**Steps to reproduce (if you knew)**

**Expected behaviour**

Being able to select Adapta with gnome-tweak-tool.

**Other Note (feature-request, question, etc...)**

I've ran around the issues for a time now and nothing worked for this situation.

**Comment by tista500** [comment]
`adapta-gtk-theme-gtk2.noarch` was installed as well?
See: https://git.gnome.org/browse/gnome-tweak-tool/tree/gtweak/tweaks/tweak_group_interface.py#n47

**Comment by ghaabor** [comment]
@tista500 Nice, thanks, that did the trick!
