### ISSUE TITLE
LibreOffice Fresh Red lines

### ISSUE THREAD

**Issue by TheAifam5** [adapta-project/adapta-gtk-theme#355]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.22.8
 * Desktop environment - Budgie Desktop
 ```

**Adapta version (if you knew)**
344b7200b7cf87b2c557e68e39ea2acb8197218b

**Related Application and/or Shell theming (or name of widget)**
LibreOffice 5.3.0.3

**Actual issue**
Red lines on GTK3, but on GTK2 is perfect :)

**Steps to reproduce (if you knew)**
Start LibreOffice and open a document

**Expected behaviour**
Obviously should be not red :)

**Other Note (feature-request, question, etc...)**

Adapta Theme (icons: Breeze Dark) - `SAL_USE_VCLPLUGIN=gtk3`:
![red-adapta](https://cloud.githubusercontent.com/assets/2192274/23139601/7c1f41b8-f7ad-11e6-889d-47666aafabc8.png)

Adapta Theme GTK2 (icons: Breeze Dark) - `SAL_USE_VCLPLUGIN=gtk`:
![adapta-gtk](https://cloud.githubusercontent.com/assets/2192274/23139782/6ed3f750-f7ae-11e6-98e9-f090a524f783.png)

Adwaita (icons: Oxygen):
![adwaita](https://cloud.githubusercontent.com/assets/2192274/23139671/e2eaeeec-f7ad-11e6-8a53-a1138d0e6e8a.png)

**Comment by tista500** [comment]
See https://github.com/horst3180/arc-theme/issues/738, upstream issue I think.
Unable to fix from here.

Regards.

**Comment by TheAifam5** [comment]
Ok.. Actualy you can use: `GTK_THEME=Adapta-Nokto-Eta libreoffice` to enable white theme which works perfectly or `GTK_THEME=Adapta-Nokto-Eta:dark libreoffice` which shows red lines :)

**Comment by tista500** [comment]
I won't do anything for this issue, so I close.
