### ISSUE TITLE
[Gedit] Background over shadow on mouse hover

### ISSUE THREAD

**Issue by mckbsky** [adapta-project/adapta-gtk-theme#356]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.8
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.89.4.32 from adapta-gtk-theme AUR

**Related Application and/or Shell theming (or name of widget)**
Gedit side panel

**Actual issue**
There is a background under buttons and combobox of gedit's side panel in 'file browser' section that overlaps headerbar shadow. Same thing happen in in 'documents' section on 'X' button.

![gedit_side_panel](https://cloud.githubusercontent.com/assets/17955603/23141572/b2ff1028-f7b7-11e6-815d-13c1bd81e0e1.png)

**Steps to reproduce (if you knew)**
Hover mouse over said widgets.

**Comment by tista500** [comment]
I could not reproduce at least on my gedit 3.22.0...
