### ISSUE TITLE
White scroll bar background in Telegram Desktop contact list

### ISSUE THREAD

**Issue by Nik-mmzd** [adapta-project/adapta-gtk-theme#359]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.8
 * Desktop environment - Gnome 3.22.2
 ```

**Adapta version**
3.89.4.41.r1.fa512e34 from adapta-gtk-theme-git AUR

**Related Application and/or Shell theming (or name of widget)**
Telegram Desktop 1.0.14

**Actual issue**
White scroll bar background in Adapta Nokto Telegram theme
![screenshot](https://cloud.githubusercontent.com/assets/19509291/23257810/76b887f4-f9d6-11e6-97df-745334732fa7.png)

**Steps to reproduce**
Hover cursor over any contact when contact list scroll bar is visible

**Other Note (feature-request, question, etc...)**
I used these options when I built Adapta:
```
    --prefix='/usr'
    --enable-parallel
    --enable-chrome
    --disable-plank
    --disable-unity
    --enable-telegram
    --disable-cinnamon
    --disable-flashback
    --disable-xfce
    --disable-mate
    --disable-openbox
```

**Comment by tista500** [comment]
Ugghh, I suspect this issue may be related to the upstream... :(
Seems telegram might unable to draw them by mixing multiple alpha-blended elements.

I'm not testing yet, but this commit will fix the issue: https://github.com/adapta-project/adapta-gtk-theme/commit/37fa70c32b1acfc7e88140c22397468460eca751

Regards.
