### ISSUE TITLE
Multiple "missing name of pseudo-class"

### ISSUE THREAD

**Issue by AravK** [adapta-project/adapta-gtk-theme#360]
**Reporter info**

 ```
 * `uname -a` - Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
 * Gtk+ 3.0 version (libgtk-3-0) - 3.14.5-1+deb8u1
 * Desktop environment - GNOME 3.14.2-3 
 ```

**Adapta version**
commit 75c9c97fe168f53c613777e925176eb1605fea03
Author: tista500 <tista.gma500@gmail.com>
Date:   Sat Feb 25 08:31:20 2017 +0900
    "Gtk-3.20&3.22&4.0: [Epiphany] Update selectors for .flating-bar style-class"

**Related Application and/or Shell theming (or name of widget)**
All GUI applications when using Adapta-Nokto

**Actual issue**
Whenever I run a GUI command from the terminal, eg. `gnome-control-center`, I get  a bunch of errors: [adapta-nokto-errors.txt](https://github.com/adapta-project/adapta-gtk-theme/files/801767/adapta-nokto-errors.txt)

**Steps to reproduce**
Compile Adapta w/ Chrome
Apply Adapta-Nokto all over GNOME (but not shell theme)
Open terminal
Run `gnome-...`

**Expected behavior**
No errors

**Other Note (feature-request, question, etc...)**
Please don't make Adapta depend on package versions which are still not in the Debian `stable` repos yet. All required packages had to be manually installed from `testing` repos.

**Comment by tista500** [comment]
o_O ??

Adapta does NOT support GNOME 3.14 but 3.18 or higher. Read the README.md.
Invalid.
