### ISSUE TITLE
Problem on notification center 

### ISSUE THREAD

**Issue by anonimo1w** [adapta-project/adapta-gtk-theme#361]
**Reporter info**

 ```
 * Distribution -Fedora 24
 * Gtk+ 3.0 version - 3.20.9
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)** Version 3.89.4.52

**Related Application and/or Shell theming (or name of widget)**
Gnome-Shell (gnome-shell notification center)

**Actual issue**
For some reason Adapta is the only Shell theme that looks like this on notification center. It happens here in all Adapta themes ("normal", "normal-eta", "nokto" and "nokto-eta")

![scr1](https://cloud.githubusercontent.com/assets/2099867/23526088/8cb6f63c-ff6f-11e6-8fd3-372334803e0c.png)

As pictured, all notifications have a strange background format (being smaller than the text)

**Expected behaviour**
And, from Adwaita, it should looks like this

![scr2](https://cloud.githubusercontent.com/assets/2099867/23526089/8cbb493a-ff6f-11e6-99be-5a0fd9837dd8.png)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/234cca3e3a419cb7c3669393206bf74039fa250a

Regards.
