### ISSUE TITLE
Text in titlebars on Qt applications is dark and hard to read. (dark/nokto theme, cinnamon)

### ISSUE THREAD

**Issue by euphonia** [adapta-project/adapta-gtk-theme#362]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Cinnamon
 ```

**Adapta version (if you knew)**
baaf1d948beb353c17ba59170872fda1eed5c1a4

**Related Application and/or Shell theming (or name of widget)**
Dunno. Titlebars? 

**Actual issue**
I built from master recently and noticed that, on the dark theme, text on titlebars was dark (and unreadable) on Qt applications (VLC, VirtualBox, and Clementine). Before, text was light on untiled windows, dark on tiled unfocused windows, and light on tiled focused windows. 

I looked through the git history, and I think the issue is commit 8e612ecc0b7ef1e6804df56a0ef490c75a529fd7. I reverted it and rebuilt adapta, and text the titlebars looked like they did before.

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/c4b31f2a1aeabc8c55ae7129408e4e76610f2de0

Regards.

**Comment by tista500** [comment]
Simply reverted: https://github.com/adapta-project/adapta-gtk-theme/commit/a4fb1c5bb62edc8a824766018379d9b3c0676ae1
