### ISSUE TITLE
cant select dark theme

### ISSUE THREAD

**Issue by rafilkmp3** [adapta-project/adapta-gtk-theme#364]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```Unity

**Adapta version (if you knew)**
last from PPA


**Related Application and/or Shell theming (or name of widget)**



**Actual issue**
Cant get dark theme


**Steps to reproduce (if you knew)**
installed from ppa and select from Unity Tweak Tool adpta-notok and still clear one


**Expected behaviour**

Dark theme from screenshot 

**Other Note (feature-request, question, etc...)**
dark theme

**Comment by tista500** [comment]
Please read the README.md before posting the issues... :(

If you talked about 'global dark theme', see:
https://github.com/adapta-project/adapta-gtk-theme#variant-matrix

Invalid.

**Comment by rafilkmp3** [comment]
but i guess "  Nokto is a dark variant. " and if a select nothing is changed 

nokto
![image](https://cloud.githubusercontent.com/assets/12433667/23671510/4a4e6bde-034a-11e7-88ee-84f75dfa737a.png)

default one
![image](https://cloud.githubusercontent.com/assets/12433667/23671555/719511de-034a-11e7-8dd3-dc0d58889d0d.png)

**Comment by squall77it** [comment]
I have the same problem, global dark is activated and i have restarted gnome-shell
![adapta-nokto](https://cloud.githubusercontent.com/assets/5853097/23680295/fdd797bc-038a-11e7-8a37-12a352fcddc2.png)

**Comment by tista500** [comment]
@squall77it,

Not the same.
Synaptic needs polkit authentication via pkexec as "another user" (root). So your report is not the theme-specific issue ( means this happens with other Gtk+ themes as well).

**Comment by squall77it** [comment]
With vertex-dark theme work  
![vertex-dark](https://cloud.githubusercontent.com/assets/5853097/23682567/c42e613a-0394-11e7-95e5-806825a5ea28.png)

**Comment by tista500** [comment]
No. Arc/Vertex are non-standard Gtk+ theme.
Because those themes just contains only a colour variant in every single theme. On the other hand, Adapta, Numix, and Adwaita contains both light/dark variant in a single theme.

There's no meaning to be compared to Arc/Vertex with Adapta about 'global dark theme'.

**Comment by squall77it** [comment]
OK, thanks..
I have activated the global dark theme for root, now work fine.
The theme is very beautiful...
