### ISSUE TITLE
Gnome Shell Classic top and bottom bar color

### ISSUE THREAD

**Issue by dieserkai** [adapta-project/adapta-gtk-theme#365]
**Reporter info**

 ```
 * Distribution Ubuntu 16.04.2
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.2 
 * Desktop environment - Gnome Shell Classic v3.18.5
 ```

**Adapta version (if you knew)**
3.89.4.119-0ubuntu1~xenial1

**Actual issue**
The Color of the top and bottom bar does not change to the colors of the theme. There is only a color gradient from black to white with a white font color.

Screenshots:
https://picload.org/image/rllrwcpa/bildschirmfotovom2017-03-0823-.png
https://picload.org/image/rllrwcpl/bildschirmfotovom2017-03-0823-.png

**Expected behaviour**
I would expect that the top and bottom bar color fit to the theme (like it does in the standard / not classic view) and is easier to read. 

best regards,
Kai

**Comment by tista500** [comment]
It's not the theme-specific issue but the upstream. It also happens in any other user-themes.

I've already explained: https://github.com/adapta-project/adapta-gtk-theme/tree/master/shell/gnome-shell/extensions/window-list

Unable to fix.
Regards.
