### ISSUE TITLE
Gpg pubkey for ppa?

### ISSUE THREAD

**Issue by cpg1111** [adapta-project/adapta-gtk-theme#366]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - unity
 ```

**Adapta version (if you knew)**

Not installed yet

**Related Application and/or Shell theming (or name of widget)**

gpg

**Actual issue**

No gpg pubkey was added when adding the ppa.

**Steps to reproduce (if you knew)**

`sudo add-apt-repository ppa:tista/adapta && sudo apt-get update`

**Expected behaviour**

Either have a gpg pubkey to manually add to my keyring, or had it added when adding the ppa.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O !?
Unable to reproduce at all...

**Comment by cpg1111** [comment]
I'm getting a "no public key found" on apt-get update

**Comment by tista500** [comment]
Run:
```
sudo rm -f /etc/apt/sources.list.d/tista-ubuntu-adapta-xenial.list
sudo rm -f /etc/apt/trusted.gpg.d/tista_ubuntu_adapta.gpg
sudo apt update
sudo add-apt-repository ppa:tista/adapta -y
```

Then let me see the output of `sudo add-apt-repository ppa:tista/adapta -y`.

**Comment by tista500** [comment]
No response, closed.
