### ISSUE TITLE
Text box appears blank on Remmina Remote Desktop

### ISSUE THREAD

**Issue by snydox** [adapta-project/adapta-gtk-theme#367]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 1.2.10
 * Desktop environment - Gnome 3.22.3
 ```

**Adapta version (if you knew)**

The version last modified on: 29-Nov-2016

**Related Application and/or Shell theming (or name of widget)**

Remmina Remote Desktop Version: 1.2.0-rcgit-15

**Actual issue**

Unable to see what I'm typing.

Screenshot: http://i.imgur.com/c5os1au.png

**Steps to reproduce (if you knew)**

Just open it and type on the text bar.

**Expected behaviour**

I should  be able to see what I'm typing. But the text is as dark as the background. It should be white instead.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Please let me see how Arc-Darker and/or Numix worked if you've installed them.

Regards.

**Comment by ceyhunnabiyev** [comment]
Strange!!! I also used Remmina  with latest adapta    AUR package, I have no any problem on theme..
![screenshot from 2017-03-11 03 09 47](https://cloud.githubusercontent.com/assets/5506156/23816853/7e41904a-0608-11e7-8d6a-25da7ef3626d.png)

**Comment by ceyhunnabiyev** [comment]
Maybe package version problem. My Remmina version: 1.2.0-rcgit-18

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/6d0b963674a68b8bd8ff02c3028aa1a2699dd8df

Regards.

**Comment by tista500** [comment]
@ceyhunnabiyev,

This happened on light variant only, and `.default` weird style-class was getting in our way of styling of entry node...

Regards.

**Comment by snydox** [comment]
Indeed the problem only happens with the light version. I just change it to
the dark version and works fine.




​


*Eric Nicholls*
