### ISSUE TITLE
Less-frequent updates

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#368]
I'm running Fedora and everyday, I get displayed a notification about new updates because of a new Adapta version. Can this be reduced to a normal amount of about once per week, please? The differences aren't as urgent as a daily update is necessary. Overall, I recognize almost no changes over weeks.
Please don't understand that wrongly – I appreciate it a lot that you're working on Adapta on a daily basis. But these update are more annoying than useful/necessary.

**Comment by PeterFeicht** [comment]
I think you should configure your update notifications appropriately.

**Comment by tista500** [comment]
> The differences aren't as urgent as a daily update is necessary.

Isn't it better using other themes?

> I think you should configure your update notifications appropriately.

Agreed.
