### ISSUE TITLE
White scroll bar and "typing" icon background in Telegram Desktop contact list

### ISSUE THREAD

**Issue by Nik-mmzd** [adapta-project/adapta-gtk-theme#369]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.9
 * Desktop environment - Gnome 3.22.3
 ```

**Adapta version (if you knew)**
3.89.4.142 (just built from source)

**Related Application and/or Shell theming (or name of widget)**
Telegram Desktop 1.0.14

**Actual issue**
1. White scroll bar background in Adapta Nokto Telegram theme
(also it sometimes "transparent white" and it "stacks" to usual white when I'm scrolling contacts list)
(seems like #359 still not fixed)
![tg-bug-1](https://cloud.githubusercontent.com/assets/19509291/23833963/2bc0e2d2-075f-11e7-9abd-e07b9f4c5cf0.png)
![tg-bug-2](https://cloud.githubusercontent.com/assets/19509291/23833965/343ca6c6-075f-11e7-8914-482030d1a018.png)
![tg-bug-3](https://cloud.githubusercontent.com/assets/19509291/23833967/36eb36ee-075f-11e7-9111-eb2af5187037.png)

2. White "typing" icon background
![tg-bug-1](https://cloud.githubusercontent.com/assets/19509291/23833963/2bc0e2d2-075f-11e7-9abd-e07b9f4c5cf0.png)

**Steps to reproduce (if you knew)**
1. Hover cursor over any contact when contact list scroll bar is visible. Also hover and scroll contact list to see "stacking" background
2. Hover cursor over user typing smth

**Other Note (feature-request, question, etc...)**
I used these options when I built Adapta:
```
    --prefix='/usr'
    --enable-parallel
    --enable-chrome
    --disable-plank
    --disable-unity
    --enable-telegram
    --disable-cinnamon
    --disable-flashback
    --disable-xfce
    --disable-mate
    --disable-openbox
```

Also, I have no such bugs with default Telegram theme or "Nightmode" theme, so I think it's Adapta theme bug

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/ac38a6132de8372cbd1e2b58925627a098f0a51e

> Also, I have no such bugs with default Telegram theme or "Nightmode" theme, so I think it's Adapta theme bug

I don't think so, becuase of ton of Telegram's limitations of colour blending (poor theming features).
Telegram theming always makes me mad.

Regards.

**Comment by tista500** [comment]
One of the reasons is the fact that devs seem to mix "Contact" elements with "lightButton" elements when rendered. This is completely upstream issue in case we tried to do theming. Personally those two different elements should not be confused/mixed at least... :/

**Comment by tista500** [comment]
Currently I have few things to polish that app styling, so unfortunately closed.
