### ISSUE TITLE
Synapse highlighted item issue

### ISSUE THREAD

**Issue by ivandotv** [adapta-project/adapta-gtk-theme#370]
**Reporter info**

 ```
 * Distribution - Ubuntu gnome 16.04
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.2 
 * Desktop environment - GNOME Shell 3.18.5  
 ```

**Adapta version (if you knew)**
Latest

**Related Application and/or Shell theming (or name of widget)**
Synapse

**Actual issue**
Color of the text when item is highlighted inside synapse.
In the screenshot, dropbox item ( first item is highlighted)
![img_20170313_194136](https://cloud.githubusercontent.com/assets/390700/23870367/7d97a15a-0826-11e7-949f-a38ce55ef98e.jpg)

**Steps to reproduce (if you knew)**
Open synapse and do a search

**Expected behaviour**
Better colors

**Comment by tista500** [comment]
@ivandotv,

Gtk+ theme specific issue? (I don't think so)

**Comment by ivandotv** [comment]
Arc theme - both light and dark versions correctly skin synapse. So i think it's a theme issue.

**Comment by tista500** [comment]
See: https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.18/sass/_applications.scss#L512

This is the apps specific workaround what standard Gtk+ themes do not have. Upstream issue for me.

Regards.

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/3c2b8ede554d176a0890aa250c3790d89e1df906
