### ISSUE TITLE
Some elements in gnome-builder header bar are almost invisible

### ISSUE THREAD

**Issue by luca-viggiani** [adapta-project/adapta-gtk-theme#371]
**Reporter info**

 ```
 * Distribution - Arch Linux 64bit
 * Gtk+ 3.0 version - 3.22.9+2+gaebe3a74ec-1 
 * Desktop environment - Gnome Shell 3.22.2
 ```

**Adapta version (if you knew)**
Latest from git (2014-03-14 11:10 CET)

**Related Application and/or Shell theming (or name of widget)**
gnome-builder header bar

**Actual issue**
some elements are almost invisible (see attached image)
![image](https://cloud.githubusercontent.com/assets/25035914/23895713/fccf10d6-08a6-11e7-9dbd-ee4686313b86.png)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/c734d9de3d4e918ac9ccdfe5500f1a08b160de05
