### ISSUE TITLE
Latest git version does not build

### ISSUE THREAD

**Issue by luca-viggiani** [adapta-project/adapta-gtk-theme#373]
Error: Invalid CSS after "}": expected "}", was ""
        on line 6350 of 3.20/_common.scss
>> }
   -^
make[1]: *** [Makefile:918: all] Error 1

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/commit/ec399370c06bf5f86ea706395918af33a494d467
