### ISSUE TITLE
Selected items in MySQL Workbench are not visible

### ISSUE THREAD

**Issue by luca-viggiani** [adapta-project/adapta-gtk-theme#375]
* Distribution - Arch 64bit
* Gtk+ 3.0 version - 3.22.10-1
* Desktop environment - 
GNOME Shell 3.22.3-1
MySQL Workbench 6.3.9

**Adapta version (if you knew)**
Git c734d9de3d4e918ac9ccdfe5500f1a08b160de05

**Related Application and/or Shell theming (or name of widget)**
MySQL Workbench Treeview on the left

**Actual issue**
Selected item text is invilible (probably same color as treeview background)

![schermata da 2017-03-16 08-54-27](https://cloud.githubusercontent.com/assets/25035914/23986865/a39e2980-0a26-11e7-90ff-dcffcbeeef6f.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/ba7ae6aae7d85fb788ca777889e333bc2012e486

**Comment by luca-viggiani** [comment]
Unfortunately the issue is still there... text and arrow are rendered in white
