### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by jaume5900** [adapta-project/adapta-gtk-theme#376]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Actual issue**
`root@jaume5900:/home/jaume5900/Downloads/Adapta# make
Making all in gtk
make[1]: Entering directory '/home/jaume5900/Downloads/Adapta/gtk'
/bin/mkdir -p ./gtk-3.18 && \
/bin/mkdir -p ./gtk-3.20 && \
/bin/mkdir -p ./gtk-3.20-eta && \
/bin/mkdir -p ./gtk-3.22 && \
/bin/mkdir -p ./gtk-3.22-eta && \
/bin/mkdir -p ./asset/assets-gtk2 && \
/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/bin/mkdir -p ./asset/assets-gtk2/Buttons && \
/bin/mkdir -p ./asset/assets-gtk2/Arrows && \
/bin/mkdir -p ./asset/assets-gtk2/Check-Radio && \
/bin/mkdir -p ./asset/assets-gtk2/Column && \
/bin/mkdir -p ./asset/assets-gtk2/Entry && \
/bin/mkdir -p ./asset/assets-gtk2/Handles && \
/bin/mkdir -p ./asset/assets-gtk2/Lines && \
/bin/mkdir -p ./asset/assets-gtk2/Others && \
/bin/mkdir -p ./asset/assets-gtk2/ProgressBar && \
/bin/mkdir -p ./asset/assets-gtk2/Range && \
/bin/mkdir -p ./asset/assets-gtk2/Scrollbars && \
/bin/mkdir -p ./asset/assets-gtk2/Shadows && \
/bin/mkdir -p ./asset/assets-gtk2/Spin && \
/bin/mkdir -p ./asset/assets-gtk2/Toolbar && \
/bin/mkdir -p ./asset/assets-gtk3
cd ./gtk-2.0 && ./recolor-gtk2.sh
cd ./sass && /usr/local/bin/sassc -t compact 3.18/gtk.scss ../gtk-3.18/gtk-contained.css
Error: unterminated argument to rgba(...)
        on line 115 of common/_colors-public.scss
>> Makefile:915: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/jaume5900/Downloads/Adapta/gtk'
Makefile:370: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Steps to reproduce (if you knew)**

make command

**Expected behaviour**
Work 

I guess its related to the colors but i dont know anything about sass

**Comment by tista500** [comment]
Unable to reproduce.
Read: https://github.com/adapta-project/adapta-gtk-theme#installation-from-git-source

Your sassc/libsass0 seems too old.

Closed.
