### ISSUE TITLE
[Gnome-Shell 3.24] Items hard to read

### ISSUE THREAD

**Issue by HeikoAdams** [adapta-project/adapta-gtk-theme#377]
**Reporter info**

 ```
 * Distribution - Fedora 26 (pre-alpha)
 * Gtk+ 3.0 version - 3.22.10
 * Desktop environment - Gnome 3.23.92
 ```

**Adapta version (if you knew)**
git master

**Actual issue**
Items like the player navigation or missed notifications are very hard to read on Gnome-Shell 3.24

![bildschirmfoto von 2017-03-18 20-12-14](https://cloud.githubusercontent.com/assets/1418818/24075238/bcbb26dc-0c17-11e7-9f75-549b6a9e6786.png)

**Comment by bil-elmoussaoui** [comment]
I can confirm that too

**Comment by tista500** [comment]
o_O ??

Unable to reproduce:
![screenshot from 2017-03-19 07-00-14](https://cloud.githubusercontent.com/assets/6073622/24076379/13e62074-0c72-11e7-94a1-94405a03e3ff.png)

**Comment by tista500** [comment]
Still un-reproducible, but this should fix: https://github.com/adapta-project/adapta-gtk-theme/commit/4d02d35a4bd2af65441810a2fcce53ae98eca5cc

**Comment by HeikoAdams** [comment]
For the records: It's fixed in latest git master
