### ISSUE TITLE
Can't see the URL Bar in Gnome web browser 3.24

### ISSUE THREAD

**Issue by siucdude** [adapta-project/adapta-gtk-theme#380]
with the new update, I can't see what im typing in the Gnome Web Browser 3.24
![screenshot from 2017-03-23 00-20-20](https://cloud.githubusercontent.com/assets/6015094/24233189/8b87814c-0f5e-11e7-8885-f8f52d2c0575.png)

**Comment by tista500** [comment]
Please follow the issue_template if you'd like to file the report to Adapta or stop filing to us!! :/

Invalid.
