### ISSUE TITLE
Inappropriate mate-panel height, icon size and font-weight

### ISSUE THREAD

**Issue by Serede** [adapta-project/adapta-gtk-theme#381]
**Reporter info**

 ```
 * Distribution - Arch Linux x86_64 4.10.5-1-ARCH
 * Gtk+ 3.0 version - 3.22.10-1
 * Desktop environment - MATE 1.18.0-1 (gtk3)
 ```

**Adapta version**
adapta-gtk-theme 3.89.5.51-1 (from [AUR](https://aur.archlinux.org/packages/adapta-gtk-theme/))

**Related Application and/or Shell theming (or name of widget)**
mate-panel (Panel-Widget)

**Actual issue**
With 1366x768@96dpi resolution and Noto Sans 10 as system font, applying any Adapta theme results in a 31 pixels high, 32x32-icons, bold font mate-panel, which looks too big and pretty unaesthetic.

**Steps to reproduce**
Setup the aforementioned environment, install adapta-gtk-theme and apply any Adapta theme.

**Expected behaviour**
For comparison, when the Arc theme is applied the bar is 26 pixels high, uses 16x16 icons and the font is regular instead of bold, fitting quite better.

**Screenshots**
*Adapta*
![adapta](https://cloud.githubusercontent.com/assets/8126306/24335432/b143f466-127d-11e7-8712-9515685f2dcc.png)
*Arc*
![arc](https://cloud.githubusercontent.com/assets/8126306/24335433/b145ba44-127d-11e7-80ca-83354f4f680a.png)

**Comment by tista500** [comment]
> For comparison, when the Arc theme is applied the bar is 26 pixels high, uses 16x16 icons and the font is regular instead of bold, fitting quite better.

Feel free to go back to Arc. ;)

**Comment by tista500** [comment]
Partial fix was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/a8fc6b4408cc872ec5d479d245efc5bc47ed5d91

Adapta uses 700 weight fonts in top-bar as default in Gnome-Shell, Cinnamon, XFCE, LXDE and Budgie-desktop, so I don't want to use 400 weight fonts in gnome-panel/mate-panel. The only special case is wnck-tasklist, it would be rendered with 400 weight fonts.

Regards.

**Comment by Serede** [comment]
Looks neat now. Thanks a lot, I appreciate your effort.
