### ISSUE TITLE
Synaptic has white background on Nokto(-eta) variant

### ISSUE THREAD

**Issue by Zulgrib** [adapta-project/adapta-gtk-theme#385]
**Reporter info**

 ```
 * Distribution - Mint 18.1
 * Gtk+ 3.0 version - 3.20.8
 * Desktop environment - 1.16.1
 ```

**Adapta version (if you knew)**
3.89.5.83

**Related Application and/or Shell theming (or name of widget)**

- synaptic
- synaptic-pkexec

**Actual issue**
Synaptic has light background instead of dark, text is dark instead of light

**Steps to reproduce (if you knew)**

1. Apply theme
2. Open synaptic

**Expected behaviour**
Dark background, white text

**Other Note (feature-request, question, etc...)**

**Comment by Zulgrib** [comment]
Did not apply correctly the global dark theme (was [settings] instead of [Settings] in my config file)

**Comment by tista500** [comment]
Ah, fixed typo: https://github.com/adapta-project/adapta-gtk-theme/commit/0135650aef0c269f8798e584545c820cdb8ffccb
