### ISSUE TITLE
Ubuntu MATE 17.04 : no visible icon for Brisk Menu

### ISSUE THREAD

**Issue by 1Claude** [adapta-project/adapta-gtk-theme#387]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version -
 * Desktop environment - MATE
 ```

**Adapta version (if you knew)** Latest from PPA

**Related Application and/or Shell theming (or name of widget)** Brisk Menu

**Actual issue** The icon for the Brisk Menu is not visible.

**Steps to reproduce (if you knew)** in MATE Tweak, set the panel to Pantheon

**Expected behaviour** A visible icon for the Brisk Menu, like in other Ubuntu MATE theme.

See screenshot, the upper left corner, where the Brisk Menu icon should be visible. 

![brisk menu](https://cloud.githubusercontent.com/assets/19640810/24641193/9ec24cf8-18cb-11e7-94ac-4316f4261667.png)

**Comment by tista500** [comment]
Adapta does NOT support Pantheon.

**Comment by 1Claude** [comment]
It's not Pantheon, the Desktop...

Just a name for the panel selection in MATE Tweak : Plank at the bottom and the Brisk Menu on top.

**Comment by 1Claude** [comment]
Here's an example with the regular Ambiante MATE theme. 

![expected](https://cloud.githubusercontent.com/assets/19640810/24641581/fc10ca08-18ce-11e7-981f-dfc56ecd82f3.png)

**Comment by tista500** [comment]
> set the panel to Pantheon

Please clarify the meaning. Pantheon is the default shell of elementaryOS. And their default panel application is wing-panel.

Anyway enhancement was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/9b03b700aae6c1c554fedf99da4a45457002bb94

**Comment by metaphorex** [comment]
There are plenty of themes in MATE and Pantheon is one of them.

**Comment by chuutatsu** [comment]
Pantheon the OP talked about is the new panel layout style for Mate panel. It's recently be integrated in Brisk Menu. http://ubuntu-mate.org/blog/ubuntu-mate-zesty-beta2/

Not that Pantheon's elementary OS.

**Comment by tista500** [comment]
o_O ??

I'm very confused, because OP's shot did not have any Pantheon-ish panel widget layouts at all... :(
