### ISSUE TITLE
Darker border lines under the window manager.

### ISSUE THREAD

**Issue by chuutatsu** [adapta-project/adapta-gtk-theme#388]
**Reporter info**

 ```
 * Distribution - Xubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Xfce
 ```

**Adapta version (if you knew)** Latest from PPA

**Related Application and/or Shell theming (or name of widget)** Thunar, File-Roller, Transmission (and probably other (GTK+ 2?) apps, I haven't check all but I assume that they suffer too)

**Actual issue**
![screenshot_2017-04-04_13-57-22](https://cloud.githubusercontent.com/assets/24815847/24644837/c2807eac-193f-11e7-9df6-529581b5fabd.png)
![screenshot_2017-04-04_13-57-47](https://cloud.githubusercontent.com/assets/24815847/24644838/c2847368-193f-11e7-9f65-0fe26088a097.png)

**Steps to reproduce (if you knew)** Open certain apps that I mentioned above (Thunar etc.) after applying the full suite of Adapta theme (gtk and window manager themes).

**Expected behaviour** The darker border lines of window manager shall be removed. The colors of the window manager shall blend nicely with the applications' menubars.

**Other Note (feature-request, question, etc...)** Will you fix this noticeable thing? Thanks.

**Comment by tista500** [comment]
> The darker border lines of window manager shall be removed.

This is the design decision, please use other themes.

Closed.

**Comment by chuutatsu** [comment]
I think there is a misunderstanding here. I meant that it would be nice to see a well-looking and blend on the top portion of xfwm4 window of GTK2 apps. It looks good in GTK3 apps already, though.

 I was about to paraphrase my words again, but because you decided to not fix that very small thing...

Okay, fine. I'll go figure how to remove them by myself.

**Comment by chuutatsu** [comment]
So, is that possible to remove that dark line? Which line I should delete?

**Comment by chuutatsu** [comment]
![screenshot_2017-04-08_01-10-16](https://cloud.githubusercontent.com/assets/24815847/24813565/a86d5a74-1bf8-11e7-9e71-bfce7cad3523.png)

Though I have no enough time to have a look at the whole code... 
For those who uses Xfce like me and experiences the same problem (border line below the titlebar/window manager), you an use an alternate fix. Open~/.config/gtk-3.0/gtk.css using text editor and add the following:

> /* No line below the title bar */
.titlebar {
    border: 0px;
    box-shadow: none;
}
> .csd .header-bar {
  border-width: 0 0 1px;
  border-style: solid;
  border-color: #2a373e;
}
> .menubar {
    box-shadow: none;
    background-color: #2a373e;
}

The result is can be seen on the screenshot above. I do not know whether this also works in other DEs but you can try.

Source: A certain Arch Linux forum https://bbs.archlinux.org/viewtopic.php?id=195906
