### ISSUE TITLE
[Feature request] Title bar color in gnome window swapping (edge tiling)

### ISSUE THREAD

**Issue by ichundu** [adapta-project/adapta-gtk-theme#390]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.10-1
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.90.0.44-1

**Other Note (feature-request, question, etc...)**
Since you dropped the maximization effects on the window titlebar (color becoming darker when maximizing window) on one of your recent releases [Release 3.90.0.29](https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.90.0.29), it would also be nice if you modify the window swapping (edge tiling in gnome) effect on the title bar color. 
Right now the title bar color becomes darker/blackish when swapping windows to the edge of the screen. I think it would be more visually appealing if the title bar color doesn't change in this case, since I usually match the gnome panel color with that of the window title bar.
![screenshot from 2017-04-16 19-49-52](https://cloud.githubusercontent.com/assets/16067816/25073150/6a8f26ee-22e0-11e7-834f-3b36a93d3e46.png)

Regards

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/dfb455da1169aff81ec508a12d862d3d7ae325f8 and https://github.com/adapta-project/adapta-gtk-theme/commit/44b9c08356bc760e66ece6c523b890b5cfdc15e3
