### ISSUE TITLE
White bar on top of wallpaper

### ISSUE THREAD

**Issue by SandPox** [adapta-project/adapta-gtk-theme#391]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - Budgie
 ```

**Adapta version (if you knew)**

3.90.0.69-0ubuntu1~zesty1

**Actual issue**

There is a 1px white bar on top of the background.

**Other Note (feature-request, question, etc...)**

The problem seems to be gone if I disable "Show desktop icons".

![image](https://cloud.githubusercontent.com/assets/14113155/25087134/53aa422a-235c-11e7-9209-fe78ee1e6a6b.png)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/79f2af6dd2860a161f585fb1ac066565fa301230

This does not happen on my 3.24.0 Nautilus... :/

**Comment by SandPox** [comment]
This seems to be fixed by latest ppa update, thank you for this great theme!
