### ISSUE TITLE
LibreOffice (Gtk+ v3) main menu text almost invisible.

### ISSUE THREAD

**Issue by viewizard** [adapta-project/adapta-gtk-theme#393]
**Reporter info**

 ```
 * Distribution - Gentoo
 * Gtk+ 3.0 version - 3.22.11
 * Desktop environment - XFCE4
 ```

**Adapta version (if you knew)**
3.90.0.81

**Related Application and/or Shell theming (or name of widget)**
LibreOffice v 3.2.3.3 (Gtk+ v3) with default configuration (first launch).
All is fine with LibreOffice (Gtk+ v2).

**Actual issue**
I am testing LibreOffice build with Gtk+ v3, and found that the main menu text almost invisible with Adapta theme.

![libreoffice](https://cloud.githubusercontent.com/assets/15098562/25194168/342dc718-2542-11e7-9b4d-d913c12be4fd.png)

**Comment by tista500** [comment]
> LibreOffice v 3.2.3.3 (Gtk+ v3) with default configuration (first launch).

3.2.3!?

Hey, 3.2 series was released in 2011 or 2012. That's totally out of my sight of developments. Currently I'm working on 5.3.2 rc releases with Gtk+ 3.22.12 and 3.90.0.

Fedora, OpenSUSE: https://www.rpmfind.net/linux/rpm2html/search.php?query=libreoffice
Arch: https://www.archlinux.org/packages/?sort=&repo=Extra&q=libreoffice&maintainer=&flagged=
Debian: https://packages.debian.org/search?lang=ja&searchon=names&keywords=libreoffice
Ubuntu: https://launchpad.net/ubuntu/+source/libreoffice

Most of Gtk+ 3.18 or higher versioned distributions will have 5.1 or newer version LibreOffice. So why do I have to support such ancient LibreOffice? :(

Won't fix.

**Comment by viewizard** [comment]
Should be "LibreOffice v 5.2.3.3". I mistaped in first post.
