### ISSUE TITLE
Unneeded margins in Gnome-shell favorites bar/dock

### ISSUE THREAD

**Issue by Austint30** [adapta-project/adapta-gtk-theme#395]
```
 * Distribution - Ubuntu Gnome
 * Gtk+ 3.0 version - GTK 3.22
 * Desktop environment - Gnome Shell 3.22
 ```
**Related Application and/or Shell theming (or name of widget)**
Gnome Shell favorites Dash and Dash to Dock extension

**Actual issue**
There is a 2px margin around the buttons of the gnome shell favorites bar/dock. That means you cannot click an application icon simply by clicking on the edge of the screen. You have to move the mouse right a little bit after moving your mouse to the edge of the screen to launch the application which is annoying. The exact same issue exists with the Dash to Dock extension, however the Dash to Dock extension uses the current theming of the regular favorites bar.

I solved the issue myself by editing the gnome-shell.css and changing the .dash-item-container margin from 2px to 0px.

**Comment by tista500** [comment]
Unneeded? Why you decide it?

And circular buttons does not have to touch to edge, and "edge to select" is not our feature.

Won't fix, closed.

**Comment by Austint30** [comment]
I have noticed that you guys seem to be really harsh when it comes to feature requests. Can you please try to be more friendly?

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/b44d85ae02dbced574a58864c3b6e96c34d3f570

Not tested, not reviewed, but it will be enough.
