### ISSUE TITLE
Cannot build anymore on Arch

### ISSUE THREAD

**Issue by lviggiani** [adapta-project/adapta-gtk-theme#396]
By running `./configure`, I get this
```
checking for sassc... /usr/bin/sassc
configure: error: 'sassc >= 3.3' not met.
```

```
$ pacman -Ss sassc
community/sassc 3.4.2-1 [installed]

$ pcman -Ss libsass
community/libsass 3.4.3-1 [installed]
    C implementation of Sass CSS preprocessor (library).

$ sassc --version
sassc: na
libsass: na
sass2scss: 1.1.0
sass: 3.4

$ which sassc
/usr/bin/sassc
```

**Comment by tista500** [comment]
> sassc: na
> libsass: na

Those `na` causes autoconf error.

**Comment by lviggiani** [comment]
That was my guess too... Do you think it's a problem in latest `sassc` / `libsass` packages in Arch?
Are you using Arch and experiencing the same?
I see that both they have been updated on 2017-02-07 and I'm sure I successfully compiled the them after that date. Did you include `sassc` check recently in `configure`?

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/b9e217e2eebcb068df0e9b556e6e3ca10830e0cb

I'm not an Arch user, and here's my Ubuntu's output of `sassc --version`:
```
sassc: 3.4.2
libsass: 3.4.3
sass2scss: 1.1.0
sass: 3.4
```

Revert commit should fix this issue.

**Comment by lviggiani** [comment]
Thanks, I'm reporting the issue to Arch
