### ISSUE TITLE
Darker "dark" version?

### ISSUE THREAD

**Issue by HoratiuMl** [adapta-project/adapta-gtk-theme#397]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.10
 * Desktop environment - GNOME 3.22.3
 ```

**Adapta version (if you knew)**

3.90.0.72

**Related Application and/or Shell theming (or name of widget)**

Dark variant

**Actual issue**

It is too light and blue

**Steps to reproduce (if you knew)**

Switch to global dark theme through GNOME Tweak Tool

**Expected behaviour**

Actual dark theme, kinda like this:

![expected_dark](https://cloud.githubusercontent.com/assets/10261133/25290690/b51e5018-26d7-11e7-9487-7e6dc7f9e5bc.png)

(The above image is that of a modified Adapta css from an old version)

**Other Note (feature-request, question, etc...)**

Can you please make the dark variant more dark? I don't want it to be completely black, that would be bad. And not necessarily dark grey either.
But the current blue colour is just too light... A dark blue (almost grey) like in the picture above, would be really good. The colour that I used is the same one used for the top panel in the unmodified version.

**Comment by tista500** [comment]
New Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.90.0.104

Unfortunately your approach seems to break light-variant theming if we shared the same GtkHeaderBar styling. So I will not apply your request...
