### ISSUE TITLE
Calendar Issue

### ISSUE THREAD

**Issue by snake629** [adapta-project/adapta-gtk-theme#399]
**Reporter info**
![captura de pantalla de 2017-04-23 17-26-09](https://cloud.githubusercontent.com/assets/27930552/25317988/83844bce-284a-11e7-8f3b-3e70dd40ab07.png)

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
A shot without any info... :/

I don't know what are you talking about, but if you'd like to show the truncation of GtkPopover, it's not the theme issue but Application design itself. See how Adwaita works:
![screenshot from 2017-04-24 22-13-50](https://cloud.githubusercontent.com/assets/6073622/25338889/bbe5e9cc-293b-11e7-8905-1b3613713a3f.png)

GtkPopover CAN NOT overhang the parent GtkWidget, in this case, GtkDialog. So remained area was truncated by the parent GtkWidget's allocation-size with decoration node. And GtkToggleButton ("Add Reminder...") is placed at the vertically centre of the GtkDialog, it means GtkPopover only can use a half of height/width of the parent GtkDialog as its own allocation (or clip-area).

Won't fix, sorry.

**Comment by snake629** [comment]
I have ubuntu 17.04 with theme adwaita (predetermined) and theme shell predetermined too. I change theme to Adapta any version and present this issue with the others theme, I dont have any problem
