### ISSUE TITLE
GNOME Web Incognito Mode Looking Broken

### ISSUE THREAD

**Issue by weltenweber** [adapta-project/adapta-gtk-theme#400]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME Shell
 ```

**Adapta version (if you knew)**
3.90.0.97-0ubuntu1~zesty1 (Adapta Nokto + Global Dark theme enabled)

**Related Application and/or Shell theming (or name of widget)**
GNOME Web (epiphany-browser)

**Actual issue**
Incognito Mode looks unthemed / broken, see picture.

![issue-screenshot](https://cloud.githubusercontent.com/assets/15271679/25403170/c73b5ec2-29fb-11e7-93ef-49ea72364955.png)

**Steps to reproduce (if you knew)**

- Open GNOME Web
- Hit Ctrl+Shift+N to open a new incognito window

**Expected behaviour**
The Window should look the same as the normal mode window, or slightly different for better visual distinction, but in line with the overall look-and-feel of the theme.

**Other Note (feature-request, question, etc...)**
Great theme overall, thanks a lot!

**Comment by tista500** [comment]
See : https://git.gnome.org/browse/epiphany/tree/src/resources/epiphany.scss

There's no theme can override their hard-coded stylesheet. I've only tweaked foreground colours as possible as I could.

Unfortunately there's few things to do from user-themes.

Regards.

**Comment by weltenweber** [comment]
Oh, I wasn’t aware of that. Thank you for the heads-up anyway!
