### ISSUE TITLE
Incorrect menu color in gtk2 and qt apps

### ISSUE THREAD

**Issue by sbsbs15** [adapta-project/adapta-gtk-theme#401]
Hi, I recently update your theme from AUR (Archlinux) and some apps, like chrome, virtualbox or lxappearance have a different color from the window in the menu.

Chrome:
![adapta](https://cloud.githubusercontent.com/assets/15521217/25456782/37cb5bdc-2ad4-11e7-9487-e059fb481b51.png)

Thanks!

**Comment by tista500** [comment]
If you ignored Issue-template, I will ignore your report, too. There's few info I have to track down.

This commit may or may not affect: https://github.com/adapta-project/adapta-gtk-theme/commit/8fd77d5d43e064daccb3330ffa2f0c770b0f6a86

Invalid, closed.
