### ISSUE TITLE
Broken TextBox on hexchat

### ISSUE THREAD

**Issue by thypon** [adapta-project/adapta-gtk-theme#402]
**Reporter info**

 ```
 * Distribution - VoidLinux
 * Gtk+ 3.0 version - 3.22.12
 * Desktop environment - Nothing (i3), theme changed with lxappearance
 ```

**Adapta version 3.90.0.108**

The textbox of hexchat is black text on dark.

**Comment by tista500** [comment]
o_O?

You meant that configuration of "Colors" did not work properly?:
![screenshot from 2017-04-27 20-34-25](https://cloud.githubusercontent.com/assets/6073622/25481778/ac720912-2b89-11e7-98c7-78a62e0abfbd.png)

**Comment by thypon** [comment]
Yep that settings work globally. The problem is that the input textbox has a dark background, while the messages textbox has a bright background. Meanwhile, I can only change the foreground settings globally where you point me out.

A hack could be making also the messages background darker, but I think a cleaner solution for the input textbox could be a good idea.

**Comment by tista500** [comment]
Disagreed.

The stem of the issue is (He)CChat ignores Gtk+ 2.x theming. We're not using light background in standard Gtk+ widgets if you had changed to dark-variants.

**Comment by thypon** [comment]
![2017-04-27-135336_1920x1080_scrot](https://cloud.githubusercontent.com/assets/581115/25482225/1327df94-2b51-11e7-99cb-2f596416cf70.png)

For documentation.

**Comment by tista500** [comment]
This bad commit may or may not fix: https://github.com/adapta-project/adapta-gtk-theme/commit/a2785bc28d113665a0ec421e27c2436e0aca679e
