### ISSUE TITLE
Lollypop hover issue

### ISSUE THREAD

**Issue by m110s** [adapta-project/adapta-gtk-theme#403]
Arch linux
gtk3 3.22.12+6+g42aa4c138c-1
Adapta 3.90.0.111

Songs list moving right on hover.
1. Only first song.
![1](https://cloud.githubusercontent.com/assets/5939323/25496890/f2162c34-2b82-11e7-8c0f-30929d470f14.png)

2. hover on first 5 songs
![1-5](https://cloud.githubusercontent.com/assets/5939323/25496935/308b796a-2b83-11e7-8cad-9eccdf3e679c.png)

3. hover on all songs:
![all](https://cloud.githubusercontent.com/assets/5939323/25496976/50cda04a-2b83-11e7-948b-51c8c2d283d4.png)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/9f95eaf31b16c3d883ac1e270844191200d4adf5
