### ISSUE TITLE
Extension icons are not themed in Chrome.

### ISSUE THREAD

**Issue by metaphx** [adapta-project/adapta-gtk-theme#404]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version -GTK 3.22.12
 * Desktop environment - GNOME 3.24
 ```

**Adapta version (if you knew)**
 3.90.117

**Related Application and/or Shell theming (or name of widget)**
Chromium / Chrome

**Actual issue**
Extension icons in the pop-up settings menu are not themed.

**Steps to reproduce (if you knew)**
Firstly, you need to move an addon to this menu, right click on the icon and select 'Hide in Chrome menu'

**Expected behaviour**
Extension icons should be correctly themed as it was some time ago.

**Other Note (feature-request, question, etc...)**
This issue is only present on Chrome/Chromium 60.0.3080.5
![screenshot from 2017-04-28 10-54-24](https://cloud.githubusercontent.com/assets/28017553/25521887/8bebdbbe-2c01-11e7-954e-02d44355e66b.png)

**Comment by tista500** [comment]
> This issue is only present on Chrome/Chromium 60.0.3080.5

No. more precisely, 59.0.3079 or higher.

**Comment by tista500** [comment]
This still happens even if we've switched to Adwaita. So upstream issue maybe.

Won't fix, sorry.

**Comment by bil-elmoussaoui** [comment]
Just to let you know that this was fixed recently (in the latest update)
