### ISSUE TITLE
Pixeled app indicator icons in cinnamon

### ISSUE THREAD

**Issue by szekeres2016** [adapta-project/adapta-gtk-theme#405]
Good day, I noticed that the Adapta and Adapta-Nokto Cinnamon themes make the app indicator icons  pixeled and over sized if cinnamon notification support is enabled. I'm not sure if this is by design or a bug, but I thought it's worth mentioning. Fortunately there is a fix I could apply but it might be the best to make this change upstream. Pictures to demonstrate:

22px app indicator (original):
![buggy](https://cloud.githubusercontent.com/assets/20751590/25563046/8f0c54ac-2d93-11e7-8455-2d2738f35bcc.png)

16px app indicator (modified):
![fixed](https://cloud.githubusercontent.com/assets/20751590/25563049/93f70cdc-2d93-11e7-9ee8-d013f322118a.png)

I of course set the panel size to be set by theme and the workaround I used was to change the ".applet-icon { icon-size: 22px;" part of the cinnamon.css file to ".applet-icon { icon-size: 16px;".

**Comment by tista500** [comment]
Cinammon stock theme: https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css#L1560

Could you verify this was truly related to user theme specific?

Regards.

**Comment by szekeres2016** [comment]
Now that you mention it most cinnamon themes suffer from this 'bug' if it really is. Numix-Cinnamon has this 16px set solution, but almost every other one looks pixely (default ones and Arc included) with icon size set to 22. So I'm not sure what to make of this to be honest.

**Comment by tista500** [comment]
Isn't it better filing to Cinnamon project instead? I'm OK to shrink them to 16px though.

**Comment by szekeres2016** [comment]
Good idea I'll open a ticket there about this, this might just be a simple overlook and all themes are supposed to have 16px icons so who knows. Thank you for your time!

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/104abb6c5e989a48462564e42027a2c73b34b657

Regards.
