### ISSUE TITLE
Polari channel list text becomes unreadable

### ISSUE THREAD

**Issue by villekivela** [adapta-project/adapta-gtk-theme#406]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - Budgie
 ```

**Adapta version (if you knew)**
3.90.0.117

**Related Application and/or Shell theming (or name of widget)**
Polari 3.24.1

**Actual issue**
Channel text becomes unreadable on an active channel when the focus is on another window and message is received.
![screenshot from 2017-04-30 14 02 00](https://cloud.githubusercontent.com/assets/5814559/25563866/2d963e2a-2dae-11e7-9e8e-c116469620bb.png)

**Steps to reproduce (if you knew)**
Leave the application open, have the focus on another window. When new message is received on the active channel, the channel highlight color goes to transparent and text becomes unreadable.

**Expected behaviour**
The highlight color should be retained.

**Comment by tista500** [comment]
Damned Polari... :/
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/8a20800179345d9418e77acb2a6dbf42e55d01fc

Regards.
