### ISSUE TITLE
Pressure effect bug in Cinnamon settings

### ISSUE THREAD

**Issue by szekeres2016** [adapta-project/adapta-gtk-theme#407]
Good day, I just noticed a tiny bug in this otherwise flawless theme. In Linux Mint 18.1 Cinnamon edition I've noticed the mouse rolling pressure effect is buggy. I've attach screenshots to demonstrate:

Other areas like Nemo (normal):
![kepernyokep 2017-04-30 15-51-33](https://cloud.githubusercontent.com/assets/20751590/25564897/69e100a4-2dbd-11e7-860e-748774b4d7ff.png)

Cinnamon settings (buggy):
![kepernyokep 2017-04-30 15-51-50](https://cloud.githubusercontent.com/assets/20751590/25564899/7534c5f8-2dbd-11e7-9a66-47325b48c9a6.png)

As it's visible the effect is just a big square block. GTK+ version is '3.18.9-1ubuntu3.3' and cinnamon version is 3.2.7. Adapta GTK theme version is '3.90.0.125-0ubuntu1~xenial1'.

**Comment by tista500** [comment]
> the mouse rolling pressure effect

We call them 'Overshoots'.
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/e5de5285633f2c90036e01f8dc7f23492b666a32

But I'm neither LinuxMint user nor Cinnamon user, so it may or may not fix.

Regards.

**Comment by szekeres2016** [comment]
It fixed it thank you! :D
