### ISSUE TITLE
White 1px height line below toolbar in Chromium (58.0.x)

### ISSUE THREAD

**Issue by FistMeNaruto** [adapta-project/adapta-gtk-theme#408]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22.12
 * Desktop environment - GNOME 3.24
 ```

**Adapta version (if you knew)**

3.90.0.44-1

**Related Application and/or Shell theming (or name of widget)**

Chromium 58.0

**Actual issue**

1px height white line below the toolbar

![screenshot from 2017-05-03 09-07-50](https://cloud.githubusercontent.com/assets/13431677/25649959/332a6b00-2fe2-11e7-8756-ecd77c4d7bd1.png)

**Steps to reproduce (if you knew)**

-

**Expected behaviour**

-

**Other Note (feature-request, question, etc...)**

Something else might be causing it and it might also be a limitation of chrome theming, but I'd like to know if I'm the only one affected. I'll look into the chromium theme and see if I can fix this myself.

**Comment by tista500** [comment]
This is the known issue in case Chrome(ium) compiled with Gtk+ 2.x backend, that bottom border was drawn by its internal codes. Chrome(ium) Gtk+ 2.x backend generate bottom border colour from "foreground-color" without using theme's GtkFrame border colour.

It means once you've switched to dark-variant, that bottom border turned to light foreground like GtkLabel and GtkTextView had. It also means there's few things to do from theme side.

Check 59.0.30xx compiled with Gtk+ 3 x backend. The 'download-bar' (revealed at the bottom of Chormeium window while downloading) had still light top border though, but at least main toolbar widget are drawn with dark bottom borders if bookmark toolbar was activated ( if bookmark toolbar was disabled, bottom border was not drawn by default).

Regards.

**Comment by FistMeNaruto** [comment]
Thank you for an elaborate response. You've got a great project running here.
