### ISSUE TITLE
 Comboboxes animate when first rendered but not after that

### ISSUE THREAD

**Issue by isantop** [adapta-project/adapta-gtk-theme#409]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME Shell 3.24
 ```

**Adapta version (if you knew)** 

3.90.0

**Related Application and/or Shell theming (or name of widget)**
GtkComboBox

**Actual issue**

When a combobox is clicked, the menu that opens as a result animates the first time the box is opened, however it doesn't animate after that. 

**Steps to reproduce (if you knew)**

1. Open a new window with a GtkComboBox widget (like `gtk3-widget-factory`).
2. Click a ComboBox
3. The menu nicely animates open
4. Click elsewhere to close the menu
5. Click the same ComboBox
6. The menu simply appears, and is not aligned the same way as it was before.

**Expected behaviour**

Either the menu animates every time it's opened, or doesn't animate at all.

**Other Note (feature-request, question, etc...)**

The menu seems to be aligned to the right and slightly down from the button. This can lead to changing things by accident if one clicks on a button then clicks again immediately on accident. It would be better if the current item in the list were aligned to its same position as the button (like it is when the menu doesn't animate.

https://github.com/system76/pop-gtk-theme/issues/6 is a duplicate of this issue, with a GIF of the problem as demonstration.

**Comment by cassidyjames** [comment]
I suspect this is due to GTK miscalculating where the menu is actually drawing the first time it renders (due to an animation in the GTK theme), and then correcting itself the next time the menu renders.

**Comment by tista500** [comment]
This is not the theme specific issue. This was unveiled in Gtk+ 3.22.x release cycle, so what did you guys want me to do? :(

And I don't understand why original reporter said this was an our bug. Please be very careful to use the word of "Bug". I'm neither a member of your fork nor your project.

**Comment by tista500** [comment]
Ah, you meant Adwaita did not have this issue?

**Comment by isantop** [comment]
Thanks, that does fix the problem. Sorry about using the term "bug" there; I'm still getting used to Github after only ever using Launchpad, where all issues are called "bugs".
