### ISSUE TITLE
Parallel issue

### ISSUE THREAD

**Issue by thepasto** [adapta-project/adapta-gtk-theme#412]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - Gtk 3.22
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.90.0.166

**Actual issue**
I'm try to install adapta-gtk-theme from aur, but the build process is stopping whith a parallel error

`/usr/bin/parallel --no-notice --line-buffer -j0 bash ::: \
	render-assets-gtk2-arrow.sh \
	render-assets-gtk2-button.sh \
	render-assets-gtk2-checkradio.sh \
	render-assets-gtk2-column.sh \
	render-assets-gtk2-entry.sh \
	render-assets-gtk2-handle.sh \
	render-assets-gtk2-misc.sh \
	render-assets-gtk2-range.sh \
	render-assets-gtk2-scrollbar.sh \
	render-assets-gtk2-spin.sh \
	clone-assets-gtk2.sh

parallel: Error: Command line too long (32 >= 0) at input 0: render-assets-gtk2-arrow.sh`

It builds fine if i remove --enable-parallel parameter.

Thanks

**Comment by tista500** [comment]
I could not reproduce this though, check this commit: https://github.com/adapta-project/adapta-gtk-theme/commit/bf93dc0c2d89b2e3f86e22043428fb7205a7c421

**Comment by thepasto** [comment]
Thanks for your reply, but no luck with your last commit. 
Anyway i found the parallel problem i can build the package as well with: 
` /usr/bin/parallel -0 --no-notice --line-buffer --jobs 100% --noswap bash ::: \ `
-0 is the arguments [delimiter ](https://www.gnu.org/software/parallel/parallel_tutorial.html#Changing-the-argument-delimiter).

Maybe it can help.
Thanks again

**Comment by tista500** [comment]
This works?: https://github.com/adapta-project/adapta-gtk-theme/commit/b83d2ee1db067e1f6d833882958535dbcb2bf2e1

**Comment by thepasto** [comment]
Yes, it's the same i tried before.
Fixed for me!
Thanks

**Comment by tista500** [comment]
OK, closed...
