### ISSUE TITLE
Request: Add Adapta theme as an Flatpak extension

### ISSUE THREAD

**Issue by haevalencia** [adapta-project/adapta-gtk-theme#413]
Flatpak now supports themes and it would be great to have Adapta, see: https://tingping.github.io/2017/05/11/flatpak-theming.html

**Comment by tista500** [comment]
That will be hopefully nice to have in someday...

**Comment by tista500** [comment]
As I read this commit: https://git.gnome.org/browse/gnome-sdk-images/commit/?h=gnome-3-24&id=6702c2bd1b652f3a183fc52fa3f92cfc41812efe , FlatPak seem to ignore 'multiple versioned themes' at least, right (Adapta depends on that feature already)?
Hard-coded suffix: `--extension=org.gtk.Gtk3theme=subdirectory-suffix=gtk-3.0`

> https://tingping.github.io/2017/05/11/flatpak-theming.html

Listed themes are the 'single versioned theme'.... damned. :/

**Comment by pschichtel** [comment]
couldn't you build a single versioned variant of Adapta for Flatpak ?

**Comment by isantop** [comment]
Pop (derived from Adapta) is currently packaged for Flatpak without any issues, so adapting from that shouldn't be hard. https://github.com/flathub/org.gtk.Gtk3theme.Pop

**Comment by jp7677** [comment]
I would love to have this too. Is having Adapta as Flatpak extension feasible?

**Comment by jp7677** [comment]
Eventually @TingPing could give some advice here..

**Comment by TingPing** [comment]
Hey, so the only Gtk version you need to target for Flatpak is 3.22, Duplicating the linked Pop theme with Adapta details should just work fine. You can then open a PR against flathub/flathub and a repo for it will be created.

**Comment by jp7677** [comment]
Hi @tista500, is there a way to convince you to work on this one? Cookies? Beer? Please name your price? ;)

**Comment by isantop** [comment]
I happen to know of an internet cookie delivery service.

**Comment by jp7677** [comment]
Oh, its nearly done. https://github.com/adapta-project/adapta-gtk-theme-flatpak
Thanks a lot!

**Comment by tista500** [comment]
https://github.com/flathub/org.gtk.Gtk3theme.Adapta
https://github.com/flathub/org.gtk.Gtk3theme.Adapta-Eta
https://github.com/flathub/org.gtk.Gtk3theme.Adapta-Nokto
https://github.com/flathub/org.gtk.Gtk3theme.Adapta-Nokto-Eta

I've also got invitations from those new repos.

Closed.
