### ISSUE TITLE
improve usability in Tilix headerbar buttons

### ISSUE THREAD

**Issue by alex285** [adapta-project/adapta-gtk-theme#417]
i'm attaching two images to demo the issue

![tilix-adwaita](https://cloud.githubusercontent.com/assets/11244308/26282725/76041b6a-3e1f-11e7-9944-148c1ce8f9a1.png)

with Adwaita we can clearly see that caret arrow belongs to 1/1 button

![tilix-issue](https://cloud.githubusercontent.com/assets/11244308/26282720/67ba8710-3e1f-11e7-9966-d5ecf214bfd0.png)

with Adapta seems like a different button

in general when the aesthetics are very good, the usability is a loosing a bit, and the buttons should have more distances, they icons perhaps should be bigger etc. also this affects more things and not just Tilix

in any case i open this in response to 
https://github.com/gnunn1/tilix/issues/934

in some buttons you use shadow/depth, is there any suggestion here?

**Comment by tista500** [comment]
@alex285,

> with Adwaita we can clearly see that caret arrow belongs to 1/1 button

Hmm, In Material Design, "text label(s) + down/up arrow" meas ComboBox in general. See our generic combo node design:
![screenshot from 2017-05-21 23-21-28](https://cloud.githubusercontent.com/assets/6073622/26284689/581c9cfa-3e7c-11e7-84a5-5be28471e4c5.png)

That "arrow" informs to users that "This widgets will pop-up/down new context-menus". But in Tilix, that button opens GtkOverlay with revealer at the left-side of its GtkWindow and It looks like the "
Navigation drawer" in Material Design though.

On the other hand, Budgie-desktop has the specific icons for similar revealer "Raven": 
![screenshot from 2017-05-21 23-30-17](https://cloud.githubusercontent.com/assets/6073622/26284757/7e09b9d8-3e7d-11e7-80fd-20e69ff4d1cd.png)
(You can see the "slide-in" icons at right-most of budgie-panel.)

I mean Up/Down-Arrow icons in that GtkToggleButton might not be the best way to open new overlay widgets sliding-in/out *horizontally*, just my thoughts... I know Tilix needs to show the current session ID and total number of sessions inside that button, but arrows are really needed?

Regards.

**Comment by alex285** [comment]
@tista500 
>but arrows are really needed?

it was also my suggestion to @gnunn1 to remove the arrow, but i moved that here first to get some ideas from you side, and second to ask if you need some extra classes that can make this case better

**Comment by alex285** [comment]
@tista500 also im not saying that you should make special cases for every app, but it may is a worth regarding the popularity both of Adapta and Tilix!

**Comment by tista500** [comment]
1st enhancement was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/83b60a5372db9f3dc988ca2aa083839668bb1ca9

Regards.

**Comment by tista500** [comment]
2nd shot was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/28e43c9d90a8f90798147f319d50d7ea3d8520bd

But that commit depends on upstream (Tilix) changes, so you will see the changes after you've updated Tilix with latest commits as well...

Regards.

**Comment by alex285** [comment]
@tista500 @gnunn1 thank you both!
