### ISSUE TITLE
Debian jessie support

### ISSUE THREAD

**Issue by holms** [adapta-project/adapta-gtk-theme#418]
In Debian Jessie latest libgdk-pixbuf2.0-dev package is 

 ```
 * Debian Jessie latest 
 ```

**Adapta version (if you knew)**

Latest

**Actual issue**

```
checking for GDK_PIXBUF... no
configure: error: Package requirements (gdk-pixbuf-2.0 >= 2.32.2) were not met:

Requested 'gdk-pixbuf-2.0 >= 2.32.2' but version of GdkPixbuf is 2.31.1

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GDK_PIXBUF_CFLAGS
and GDK_PIXBUF_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more detail
```

**Steps to reproduce (if you knew)**

Went through all your steps installing dependencies, as you can see Debian Jessie doesn't have unstable packages in apt tree.

**Expected behaviour**

Should use stable GDKPiXBUF version.

**Other Note (feature-request, question, etc...)**

Debian Jessie support. Why not to have CI for building adapta package for various OS?

**Comment by tista500** [comment]
Adapta does not support Gtk+ 3.14.x: https://packages.debian.org/jessie/libgtk-3-dev
We only support Gtk+ 3.18.x or higher platforms.
So Jessie is unsupported release for us, sorry.

Closed.
