### ISSUE TITLE
Toggles/Switches do not follow Material Design guidelines

### ISSUE THREAD

**Issue by georgelemental** [adapta-project/adapta-gtk-theme#419]
**Reporter info**

 ```
 * Distribution - Ubuntu GNOME 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME Shell 3.24
 ```

**Adapta version (if you know)**
Latest from Git

**Related Application and/or Shell theming (or name of widget)**
Toggle/Switch (Screenshots from Widget Factory)

**Actual issue**
The toggle/switch color does not follow Material Design guidelines. The toggles look like this: 
![light-toggles](https://cloud.githubusercontent.com/assets/11415479/26558950/64be7ad8-447a-11e7-92a4-f3c5034a0414.png)
![dark-togges](https://cloud.githubusercontent.com/assets/11415479/26558948/638c2f20-447a-11e7-9093-a8d7d06b5989.png)
This makes the toggles hard to see and differentiate, because they blend in with the background. 

**Steps to reproduce (if you know)**
Open an application with a toggle or switch

**Expected behaviour**
The toggle switches should look like those in the Material Design guidelines: https://material.io/guidelines/components/selection-controls.html#selection-controls-switch

>**Light**
> Thumb On: Swatch 500, Opacity 100%
> Track On: Swatch 500, Opacity 50%
> 
> Thumb Off: Grey 50, #FAFAFA, Opacity 100%
> Track Off: #000000, Opacity 38%
> 
> Thumb Disabled: Grey 400, #BDBDBD, Opacity 100%
> Track Disabled: #000000, Opacity 12%
>
>![image](https://cloud.githubusercontent.com/assets/11415479/26558701/c7a6eac4-4478-11e7-8b7d-6c5e9ce538ac.png)

>**Dark**
>Thumb On: Swatch 200, Opacity 100%
> Track On: Swatch 200, Opacity 50%
> 
> Thumb Off: Grey 400, #BDBDBD, Opacity 100%
> Track Off: #FFFFFF, Opacity 30%
> 
> Thumb Disabled: Grey 800, #424242, Opacity 100%
> Track Disabled: #FFFFFF, Opacity 10%
> 
> ![image](https://cloud.githubusercontent.com/assets/11415479/26558709/d87b8742-4478-11e7-8923-766a4ccca0f8.png)

The toggles are easy to see and stand out against the background. 

**Other Note (feature-request, question, etc...)**
Is there a specific reason for this? Is it intentional? Or is it just an oversight?

**Comment by tista500** [comment]
Yeah this is intentional, our specific design decisions.

* Basically we use the same colour blending with raised buttons.
  * Our `:disabled` pseudo-class GtkButtons have elevation '0' (rest).
  * Original MD brings too bright sliders even if sliders are disabled and elevation +1 sometimes misleads "clickable or non-clickable, which?".
  * Troughs are rendered with our Tracking-colors like GtkButtons.
  * `:hover` pseudo-class has our specific slider highlight colours.

> This makes the toggles hard to see and differentiate

I don't think so...

Regards.

**Comment by tista500** [comment]
Currently I'm not going to refactor GtkSwitch design. To be honest, I don't like the Original MD switch design especially in N release cycle, so maybe someday I will retry those designs again...

Regards.

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.91.2.177
