### ISSUE TITLE
Shelltile extension support

### ISSUE THREAD

**Issue by bil-elmoussaoui** [adapta-project/adapta-gtk-theme#422]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - Gtk3.22
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** : latest git commit (built using AUR)

**Related Application and/or Shell theming (or name of widget)** Shelltile extension

**Actual issue**
The extension uses a CSS class with an orange background color which looks so alien with Adapta theme and material design guidelines 

**Steps to reproduce (if you knew)**
1 - Download the extension: https://extensions.gnome.org/extension/657/shelltile/
2 - activate it and try to move a window around 

**Expected behavior**
Better extension styling :)

**Other Note (feature-request, question, etc...)**
Here you can find the current CSS file for the extension: https://github.com/emasab/shelltile/blob/master/stylesheet.css
Nothing too huge to do, it's just one class to override:+1: 

Thanks for the great theme!

**Comment by tista500** [comment]
@bil-elmoussaoui,

Hmm, that extension does not have any look-ups from user-themes? I could not find any functions to do so from their codes... If not, there's few things to override that style-class from user-themes.

On my rough test, that extension ignores any changes via our `gnome-shell.css`.

Regards.

**Comment by tista500** [comment]
Upstream feature request is here: https://github.com/emasab/shelltile/issues/21

**Comment by bil-elmoussaoui** [comment]
I saw that PR, and I've also tried to override the theme from gnome-shell.css but I didn't succeed either. I thought maybe I'm missing something! 
Well, we can close this, and i will reopen it if this will ever be implemented someday =)  For now i will patch the extension myself 
Thanks!
