### ISSUE TITLE
Question regarding the look of this theme

### ISSUE THREAD

**Issue by Xiaoming94** [adapta-project/adapta-gtk-theme#424]
**Question**

Applied the theme right now, Is it supposed to look like this?
![lxappearance](https://user-images.githubusercontent.com/6448975/26932357-8c032350-4c63-11e7-81b9-7f877950a9d4.png)
 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.15
 * Desktop environment - i3WM
 ```
Maybe I am missing some compilation dependencies?

**Comment by tristan957** [comment]
What specifically are you referring to

**Comment by Xiaoming94** [comment]
The lack of Material design elements. For instance, the buttons "doesn't look like" material design buttons. Compare the look of the button, to the screenshots in the repo

**Comment by tista500** [comment]
On Gtk+ 2.x and some GtK+ 3.x with `libgtkmm` integration as backends, we use our fallback-mode widget design, sorry.

Closed.

**Comment by Xiaoming94** [comment]
Sorry for asking, even though the issues is closed.

But, IIRC, This wasn't the case a little while ago. Is this a recent design decision?
I'm just curious :) 
love the theme otherwise! Keep up the good work!
