### ISSUE TITLE
How can I reduce height of Entry widget for Eclipse Neon 3 running on GTK3?

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#425]
I am running Eclipse Neon 3(latest version of Eclipse) on Fedora 24 with GTK3. As shown in picture because of Entry widget the size of toolbar is large also if I open Preferences option from Window menu there also I can see height of Entry widget bigger.

Is there any way I can do changes to reduce height of Entry widget? So that the space taken by toolbar will be reduce.

![gtk3_eclipse_neon](https://user-images.githubusercontent.com/12842912/27000860-ea4b8684-4dd8-11e7-8e33-075fa3d5863b.png)

Also, I found that description area of preferences window is black as shown below:

![screenshot from 2017-06-10 12-43-06](https://user-images.githubusercontent.com/12842912/27000941-b634668e-4dda-11e7-81aa-4e154fe180da.png)

Where as when I run Eclipse on GTK2 it seems nice as expected:

![gtk2_eclipse_neon_preferences](https://user-images.githubusercontent.com/12842912/27000953-270e737c-4ddb-11e7-82ce-e0bf02b387d1.png)

**Comment by tista500** [comment]
> Is there any way I can do changes to reduce height of Entry widget?

Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/011d8c945f3176f76b92c4cba4b4278d85f1f35d

> description area of preferences window is black as shown below

That is not the theme-specific issue but upstream issue (because devs put `rgb(0, 0, 0) into that `textview > text` node.

Regards.

**Comment by tista500** [comment]
Forgot to mention.
We have ISSUE_TEMPLATE : https://github.com/adapta-project/adapta-gtk-theme/blob/master/.github/ISSUE_TEMPLATE.md already, so please follow that template to report with useful info. If not, we'll ignore your report next time.

**Comment by prasadpatil25** [comment]
Thanks alot for effort, it worked well as expected. However just want 1 more suggestion if I want to reduce entry size for all entry in eclipse then how can be this achieve?

**Comment by tista500** [comment]
Please stop posting multiple issues in a single report as "one more...". That's really annoying for me.

Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/5fe5527fb3955ec17c2b444ab2d0cff627b9bbdb
