### ISSUE TITLE
Tiny text in calendar Applet [Cinnamon]

### ISSUE THREAD

**Issue by viggy96** [adapta-project/adapta-gtk-theme#426]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04.2 LTS
 * Desktop environment - Cinnamon 3.4.1
 ```

**Actual issue**
Text too small in calendar applet

**Comment by tista500** [comment]
o_O?

Default theme:
https://github.com/linuxmint/Cinnamon/blob/master/data/theme/cinnamon.css#L587

Arc:
https://github.com/horst3180/arc-theme/blob/master/common/cinnamon/sass/_common.scss#L695

Adapta:
https://github.com/adapta-project/adapta-gtk-theme/blob/master/shell/sass/cinnamon/_common.scss#L770

I don't think Adapta renders StLabel too tiny as theme-specific.
Won't fix, sorry.

Regards.
