### ISSUE TITLE
Problems when installing it in debian9...

### ISSUE THREAD

**Issue by minundb** [adapta-project/adapta-gtk-theme#428]
**Reporter info**

 ```
 * Distribution - Debian 9
 * Gtk+ 3.0 version - 3.22.15
 * Desktop environment - gnome 3.24.2
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
these information appears after execute "make"
...
cd ./sass && ./compile-gresource.sh 3.20
failed to load "../gtk-3.20/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.20/assets/bar-blue.svg'
../gtk-3.20/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.20-eta/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.20-eta/assets/bar-blue.svg'
../gtk-3.20-eta/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.20-nokto/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.20-nokto/assets/bar-blue.svg'
../gtk-3.20-nokto/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.20-nokto-eta/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.20-nokto-eta/assets/bar-blue.svg'
../gtk-3.20-nokto-eta/gtk.gresource.xml: 子进程退出，代码 1.
cd ./sass && ./compile-gresource.sh 3.22
failed to load "../gtk-3.22/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.22/assets/bar-blue.svg'
../gtk-3.22/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.22-eta/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.22-eta/assets/bar-blue.svg'
../gtk-3.22-eta/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.22-nokto/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.22-nokto/assets/bar-blue.svg'
../gtk-3.22-nokto/gtk.gresource.xml: 子进程退出，代码 1.
failed to load "../gtk-3.22-nokto-eta/assets/bar-blue.svg": Couldn't recognize the image file format for file '../gtk-3.22-nokto-eta/assets/bar-blue.svg'
../gtk-3.22-nokto-eta/gtk.gresource.xml: 子进程退出，代码 1.
make[1]: Leaving directory '/home/ksmarisa/adapta-gtk-theme-master/gtk'
Making all in shell
...

and these appears after execute"sudo make install"
cp: 无法获取'./gtk-3.20/gtk.gresource' 的文件状态(stat): 没有那个文件或目录
Makefile:1076: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/home/ksmarisa/adapta-gtk-theme-master/gtk'
Makefile:861: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/ksmarisa/adapta-gtk-theme-master/gtk'
Makefile:375: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Steps to reproduce (if you knew)**
just execute"./autogen.sh make sudo make install"
and before i execute "make"
i had installed the packages it needs..

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O?

> `Couldn't recognize the image file format for file '../gtk-3.22-nokto-eta/assets/bar-blue.svg'`

Have you really installed `ibrsvg2-common` (`ibrsvg2-dev` should pull that package as dependency)?
We need `libpixbufloader-svg.so` library to embed SVG images into gresource.

**Comment by minundb** [comment]
@tista500 yeah.. they had already been installed..

**Comment by tista500** [comment]
Unfortunately it may or may not distribution specific. Other distros could run glib-compile-resource with such rsvg2 (or rsvg) as we expected. So I won't do anything special for Debian...

Won't fix, sorry.

Closed.
