### ISSUE TITLE
Font scaling and top panel in gnome-shell

### ISSUE THREAD

**Issue by ichundu** [adapta-project/adapta-gtk-theme#429]
**Reporter info**
 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - gtk3 3.22.15-1
 * Desktop environment - Gnome 3.24
 ```

**Adapta version (if you knew)**
3.90.1.21-1 (latest in arch community repo, same issue with the latest aur package)

**Related Application and/or Shell theming (or name of widget)**
Top panel

**Actual issue**
Top panel is not scaling well with "font-scaling"

**Steps to reproduce (if you knew)**
Use any font scaling greater than 1.

**Expected behaviour**
Handle scaling like the default adwaita theme.

**Other Note (feature-request, question, etc...)**
I have a 1080p resolution on a 13 inch laptop, and i need font-scaling (with a factor of 1.25) otherwise everything looks tiny and not comfortable. HIDPI scaling is not an option since it only allows full factor scaling (like 2, 3 etc). I notice with font-scaling the top panel in gnome is not scaled properly (check screenshots):

1. Panel font is scaled but panel height is not (and font exceeds panel border if scaling is bigger than 2)
2. Right applet icons are not scaled at all.

Adapta:
![adapta](https://user-images.githubusercontent.com/16067816/27049002-2ce534f0-4fae-11e7-9830-be5554c3a390.jpg)

Adwaita:
![adwaita](https://user-images.githubusercontent.com/16067816/27049006-3288b2ce-4fae-11e7-930a-db6360fa0657.jpg)

**Comment by tista500** [comment]
> I have a 1080p resolution on a 13 inch laptop, and i need font-scaling (with a factor of 1.25) otherwise everything looks tiny and not comfortable. 

13" 1080p with 1.25 scaling!?
My ThinkPads also had 1080p (Yoga 260, 13 Chromebook and Helix), but I don't need any up-scaling via font-scaling...

> Right applet icons are not scaled at all.

Intentional. Since sometimes user scaling-factor makes icons blurred.

**Comment by tista500** [comment]
> Panel font is scaled but panel height is not (and font exceeds panel border if scaling is bigger than 2)

Hey, font-scaling does NOT up/down-scale GtkImage in GtkWidgets. If you need 2x up-scaling, should use `sacling-factor` instead of `font-scaling-factor`...

**Comment by tista500** [comment]
Partially enhancement for responsive height of TopBar: https://github.com/adapta-project/adapta-gtk-theme/commit/0fc918f84f70748bd467e04743c4c42923527882

But I won't use sub-upscaling in StIcons, sorry.

Regards.

**Comment by ichundu** [comment]
> 13" 1080p with 1.25 scaling!?
My ThinkPads also had 1080p (Yoga 260, 13 Chromebook and Helix), but I don't need any up-scaling via font-scaling..

Well it's personal taste, for me default text is tiny in a 13" screen and beyond my comfort zone.

> But I won't use sub-upscaling in StIcons, sorry.

That's a pity, I hope you change your mind on this. It seems logical to me that whenever you scale the ui fonts, all other related items (like icons) should be scaled as well. This is how Adwaita and several other themes i tried for this purpose are handling this.
