### ISSUE TITLE
A little bit fat border inside default selected buttons for click in GTK2 applications

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#431]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.15
 * Desktop environment - Gnome 3.24.2
 ```

**Adapta version (if you knew)**
Latest git version, using Adapta-Eta

**Related Application and/or Shell theming (or name of widget)**
Examples: Gsopcast - Save button (when clicked);  Dbeaver  Dialog Buttons- Cancel OK(default selected)

**Actual issue**
A little bit fat border inside default selected buttons for click doesn't look cool, especially with background color(Adapta Selection Color) of the buttons during Click Event.

**Suggestion**
Use  very thin border for this like Arc-theme and if it is possible make this border invisible during Click Event.

Greak Work,
Regards..

**Comment by tista500** [comment]
Those outlines are for `focused` pseudo-class instead of `selected`. Commonly those outline borders are used in both Gtk+ 2 and 3 apps for keyboard navigation. And I don't think those apps you listed were native Gtk+ 2 apps but Qt backend. Adapta is just for Gtk+ theme.

Won't fix, sorry.

**Comment by ceyhunnabiyev** [comment]
> And I don't think those apps you listed were native Gtk+ 2 apps but Qt backend. Adapta is just for Gtk+ theme.

Disagreed.  Arc-theme is also Gtk+ theme, but its outlines are so thin.  I just gave examples. This problem related to  all gtk2 applications.  Why do   you notice  it, think about it? You only say wontfix)))).  I like your theme so much.

**Comment by ceyhunnabiyev** [comment]
I fixed this with using arc-theme focus-line.png instead of your focus.png))).
