### ISSUE TITLE
Chrome theme

### ISSUE THREAD

**Issue by jingw222** [adapta-project/adapta-gtk-theme#432]
I'm pretty satisfied with your great theme and using it everyday. But when it comes to the chrome theme `adapta-nokto-theme`, wouldn't it be better if you could make the omnibox dark also? Any thoughts on that?

**Comment by tista500** [comment]
> wouldn't it be better if you could make the omnibox dark also?

No, we can't. : https://developer.chrome.com/extensions/themes

In 59.0.30xx or newer, we suggest use `GTK+` themes: https://github.com/adapta-project/adapta-gtk-theme/commit/b8e2fe6ad86a90cef0ac2ddb5a4319eafaa9dc12

Regards.
