### ISSUE TITLE
#autogen.sh not working

### ISSUE THREAD

**Issue by Armanmd** [adapta-project/adapta-gtk-theme#433]
**Reporter info**

 ```
 * Distribution - Kali rolling
 * Gtk+ 3.0 version -   
 * Kernel: x86_64 Linux 4.9.0-kali4-amd64
 * Desktop environment - Gnome and Gnome shell
 ```

**Adapta version (if you knew)**
The latest version on github

i cant install :-1: Because autogen.sh not working befor install . i install librsvg2-bin but not it working
The problem is not just my problem is everyone's problem (I saw in other froum)
./autogen.sh 
+ ./configure --prefix=/usr --disable-gtk_legacy --disable-gtk_next --disable-parallel --disable-chrome --disable-plank --disable-telegram
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GDK_PIXBUF... yes
checking for GLIB... yes
checking for RSVG... no
configure: error: Package requirements (librsvg-2.0 >= 2.40.13) were not met:

No package 'librsvg-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables RSVG_CFLAGS
and RSVG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

#autogen.sh not working

**Comment by tista500** [comment]
o_O?

> i install librsvg2-bin but not it working

We never require `librsvg2-bin` but `librsvg2-dev` (and `librsvg2-common`).
Please see https://github.com/adapta-project/adapta-gtk-theme#installation-from-git-source

**Comment by Armanmd** [comment]
I read the readme but I could not install  autogen.sh not working

what to do ?

**Comment by tista500** [comment]
run `pkg-config --modversion librsvg-2.0` and let us see the output.

**Comment by tista500** [comment]
> `* Gtk+ 3.0 version -   `

Run `dpkg-query --status libgtk-3-0` and let us see as well.

**Comment by Armanmd** [comment]
pkg-config --modversion librsvg-2.0 output : 

#:pkg-config --modversion librsvg-2.0
Package librsvg-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `librsvg-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librsvg-2.0' found

dpkg-query --status libgtk-3-0 and let us see the output: 

#:dpkg-query --status libgtk-3-0
Package: libgtk-3-0
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 9005
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: same
Source: gtk+3.0
Version: 3.22.11-1
Provides: gtk3-binver-3.0.0
Depends: libgtk-3-common (>= 3.22.11-1), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.15.1), libc6 (>= 2.14), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.14.0), libcolord2 (>= 0.1.29), libcups2 (>= 1.6.0), libepoxy0 (>= 1.0), libfontconfig1 (>= 2.11), libfreetype6 (>= 2.2.1), libgdk-pixbuf2.0-0 (>= 2.30.1), libglib2.0-0 (>= 2.49.5), libjson-glib-1.0-0 (>= 0.12.0), libpango-1.0-0 (>= 1.37.5), libpangocairo-1.0-0 (>= 1.37.3), libpangoft2-1.0-0 (>= 1.37.3), librest-0.7-0 (>= 0.7), libsoup2.4-1 (>= 2.4.0), libwayland-client0 (>= 1.9.91), libwayland-cursor0 (>= 1.9.91), libwayland-egl1-mesa (>= 10.0.2) | libwayland-egl1, libx11-6 (>= 2:1.4.99.1), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6 (>= 2:1.2.99.4), libxinerama1, libxkbcommon0 (>= 0.5.0), libxml2 (>= 2.6.27), libxrandr2 (>= 2:1.5.0), hicolor-icon-theme, adwaita-icon-theme, shared-mime-info
Recommends: libgtk-3-bin
Suggests: librsvg2-common, gvfs
Breaks: gnome-themes-standard (<< 3.6), gtk3-engines-oxygen (<< 1.4.1-3)
Description: GTK+ graphical user interface library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the shared libraries.
Homepage: http://www.gtk.org/

**Comment by tista500** [comment]
> `Package librsvg-2.0 was not found in the pkg-config search path.`

Have you installed `librsvg2-dev`?

**Comment by Armanmd** [comment]
I did not install . let me to install

now i runing again autogen.sh

and this is new output

#: ./autogen.sh 
+ ./configure --prefix=/usr --disable-gtk_legacy --disable-gtk_next --disable-parallel --disable-chrome --disable-plank --disable-telegram
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GDK_PIXBUF... yes
checking for GLIB... yes
checking for RSVG... yes
checking for sassc... no
configure: error: 'sassc' not found.

**Comment by Armanmd** [comment]
oh shit! i must install sassc ?

**Comment by tista500** [comment]
Hey, why did NOT read the README.md? :(
And if you logined as root, switch to user account at first: https://github.com/adapta-project/adapta-gtk-theme/issues/317

Invalid.
