### ISSUE TITLE
There is a black line in chrome under bookmark bar

### ISSUE THREAD

**Issue by pratikborsadiya** [adapta-project/adapta-gtk-theme#436]
**Reporter info**
Pratik Borsadiya

It works fine with default theme adwaita. But when using adapta a black line appears under bookmark bar in chrome, at first i thought it was a chrome issue. Now as i know it's only happening with adapta theme. This issue started from chrome version 59. 
[Chrome bug link for more resources related to bug](https://bugs.chromium.org/p/chromium/issues/detail?id=729935)

 ```
 * Distribution - Ubuntu 17.04 Gnome
 * Gtk+ 3.0 version - 
 * Desktop environment - Gnome 3.24
 ```

**Adapta version (if you knew)**
3.91.0.94-0ubuntu1~zesty1

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Now as i know it's only happening with adapta theme.

Numix and Flat-Plat, too.

**Comment by pratikborsadiya** [comment]
Well I have never used any other theme than Adapta. It's really an awesome theme and hat's off to you for keeping up development of such a great theme.

**Comment by tista500** [comment]
@pratikborsadiya,

Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/fdc397c96fb5414da8de2dfeb2c80d994bbdb854

I'm not tested well yet, but at least missing separators/borders should be fixed (Still dark-variants could not get rid of the weird top-edge of NTP though).

Regards.

**Comment by pratikborsadiya** [comment]
@tista500 The issue is fixed after updating. Again thank you so much for such a good theme. I am loving it.
