### ISSUE TITLE
Cinnamon menu search cuts off descending letters

### ISSUE THREAD

**Issue by ipwnmice** [adapta-project/adapta-gtk-theme#437]
**Reporter info**

 ```
 * Distribution - Arch 
 * Gtk+ 3.0 version - 3.22.16-1
 * Desktop environment - Cinnamon 3.2.8
 ```

**Adapta version (if you knew)**
3.91.0.88-1

Search in Cinnamon cuts off all letters that have descenders (extend below the line) such as q,y,p,g,j.

![adaptabug](https://user-images.githubusercontent.com/14303970/27394250-82dde59c-5679-11e7-8093-55569aa724bc.png)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/1b7b85e7123d663390c48845e0f7f82b12a6a4fe

Regards.
