### ISSUE TITLE
Xfce indicator background white for eta variants

### ISSUE THREAD

**Issue by ryzokuken** [adapta-project/adapta-gtk-theme#439]
**Reporter info**

 ```
 * Distribution - Linux Mint
* Gtk+ 3 version - 3.18.9-1ubuntu3.3 (source: dpkg -s libgtk-3-0|grep '^Version')
 * Desktop environment - Xfce
 ```

**Related Application and/or Shell theming (or name of widget)** Xfce Panel Indicator Plugin

**Actual issue** The background of the indicator plugin is white for the eta variants. However, it is correctly set for the normal variants. For the time-being, I switched to the normal theme but the eta variants work better on smaller resolutions, so I really prefer them.

**Steps to reproduce (if you knew)** Just install Xfce ;-)

Also, as far as I can remember, I did not have this issue with Debian, so I guess it could be something related to dissimilar versions? (FYI I used the testing branch (stretch) of Debian)

**Expected behaviour** The background should be dark, matching the rest of the panel. It works perfectly for the normal variants.

**Comment by tista500** [comment]
Why did you hide the Gtk+ version?

**Comment by ryzokuken** [comment]
@tista500 I didn't thought it would matter, and I didn't have `xfce4-about` installed. I am installing it now and will add it in a jiffy.

**Comment by tista500** [comment]
Run `dpkg -l | grep libgtk-3-0`. No need to install graphical apps.

And if you're in Gtk+ 32.18.x, Eta is unspported: https://github.com/adapta-project/adapta-gtk-theme#variant-matrix (Read the notes).

**Comment by ryzokuken** [comment]
I think you meant `3.18.x`, in which case, yes I am. I guess a later update for Xfce will upgrade my Gtk version?

**Comment by tista500** [comment]
Linux Mint 18.1?
Basically Ubuntu based distros do NOT upgrade Gtk+ minor version within a release. And I don't have any ideas why your theme-selector could select -Eta variants on Gtk+ 3.18.x (At least Gnome-Tweak-Tool blocks unsupported Gtk+ versioned themes properly). :(

**Comment by ryzokuken** [comment]
> Linux Mint 18.1?

Yes.

> Basically Ubuntu based distros do NOT upgrade Gtk+ minor version within a release. And I don't have any ideas why your theme-selector could select -Eta variants on Gtk+ 3.18.x (At least Gnome-Tweak-Tool blocks unsupported Gtk+ versioned themes properly).

Apparently, Xfce4 Appearance tool does not. I will keep using the normal theme then. Thanks. 

Great theme, BTW. We never really get the opportunity to express gratitude, but I really love it.

**Comment by tista500** [comment]
Our active development focus is moved to Gtk+ 3.22 and 3.91 already. So I don't have much time to support 3.18.x even if 3.18.x has been staying in LTS release... 

Sorry.
