### ISSUE TITLE
Lollypop hover issue 2

### ISSUE THREAD

**Issue by m110s** [adapta-project/adapta-gtk-theme#441]
Arch linux
gtk3 3.22.16
Adapta 3.91.0.113

Same issue as #403 
but now appears in pop-up about performer, album tab. (click on header)
![1](https://user-images.githubusercontent.com/5939323/27514102-abcb5872-5980-11e7-8df8-49f91b7418ca.png)

I know, it's Lollypop. :)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/4d833b1fac4dca73c006b0314ef51d1817ff3c45

I never use that app now and then. So I did not test that commit yet and I will not track down the issue anymore even if it may not be fixed...

Sorry.

**Comment by m110s** [comment]
Fix doesn't work, it's even worse because issue #403 is back.
If you can please reverse patch leave this issue open, fix issue #403 and I'll stop sending issues regarding Lollypop.
Thanks for your work.

**Comment by m110s** [comment]
Thanks for fix, now everything is ok.
