### ISSUE TITLE
Missing titlebars on non CSD apps (GNU Parallel usage corrupts theme build)

### ISSUE THREAD

**Issue by ikeydoherty** [adapta-project/adapta-gtk-theme#442]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.15,
 * Desktop environment -  Budgie
 ```

**Adapta version (if you knew)**

3.91.0.122,

**Related Application and/or Shell theming (or name of widget)**

Titlebars in GTK2 apps

**Actual issue**

All non CSD apps lack titlebar theming (Chrome, hexchat, etc)

**Steps to reproduce (if you knew)**

Use any non CSD app

**Expected behaviour**

Would like titlebars. :P

**Other Note (feature-request, question, etc...)**

Could be a local thing I genuinely have no idea but bringing it up to you first. It does seem to be limited to the GTK2 stuff only.

**Comment by ikeydoherty** [comment]
Also note that hitting `dark` mode in Budgie completely bricks it - if a dark theme isn't going to be shipped would it not make sense to symlink the `gtk.css` to `gtk-dark.css` to solve application issues?

**Comment by ikeydoherty** [comment]
OK further, `budgie-wm` is spitting out:

(budgie-wm:12486): Gtk-WARNING **: Theme parsing error: gtk.css:1:84: Failed to import: The resource at “/org/adapta-project/gtk-3.22-nokto/gtk-contained-dark.css” does not exist

**Comment by tista500** [comment]
I can't find any issues on dark variants with ServerSideDecorations:

![screenshot from 2017-06-26 06-13-26](https://user-images.githubusercontent.com/6073622/27519810-f36f6d38-5a36-11e7-9460-a7db101ec03b.png)

Even if I ran PCmanFM from terminal (I could not see such Gtk-WARNING).

So could you please remove installed `/usr/share/themes/Adapta*` and then re-run `sudo make install`?

**Comment by ikeydoherty** [comment]
This theme takes longer to build than Budgie -_-

**Comment by ikeydoherty** [comment]
I suspect this is a packaging issue because `%make` macro uses `-j$JOBCOUNT` and the build system is failing under parallel builds (`-j40`). I'll build a package with -j1 forced and see what happens.

**Comment by ikeydoherty** [comment]
Ok this packaging change fixes it in Solus: https://dev.solus-project.com/R338:4d92eb2c3f1c5e9647bc2d2f05a8df0eeea3334d

We've got reports of this happening to our Arch Linux friends too, so this is a bug with Adapta's use of GNU Parallel (it creates corrupt builds)

**Comment by tista500** [comment]
@ikeydoherty,

Trial: https://github.com/adapta-project/adapta-gtk-theme/commit/721e15b0f65154da277431d5733d4310f2175fa2

I'm not sure what I should do, but could that commit avoid unwanted ton of job processes while --enable-parallel?

Regards.

**Comment by ikeydoherty** [comment]
The latest build in Solus using that patch now works properly @tista500 - thanks!

**Comment by tista500** [comment]
OK. Nice. ;)

Closed.
