### ISSUE TITLE
[Dynamic-panel-transparency-extension] Gnome top bar shows unwanted arrow when application opened.

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#444]
**Reporter info**
I am Prasad Patil using adapta theme on Fedora 24. 
 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - gtk2-2.24.31-1.fc24.x86_64
 * Desktop environment - Gnome Version 3.20.2
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Gnome top bar (the bar in which activities, date and controls are displayed)

**Actual issue**
The issue is the top bar shows unwanted arrows whenever any application is opened and also arrow is visible in controls options as shown in figure.

**Steps to reproduce (if you knew)**
Open any application and check arrow in top bar after the name of the application.

**Expected behaviour**
It would look great if that unwanted arrow will be removed and this will save the space.

**Other Note (feature-request, question, etc...)**
Please check the picture attached. The application which is opened in the picture is google chrome and it shows the arrows beside its name.

![drop down arrow](https://user-images.githubusercontent.com/12842912/27722216-ca2514c8-5d83-11e7-96b4-efe39948c4af.png)

**Comment by tista500** [comment]
We never use the translucent TopBar node in gnome-shell 3.24 or lower theming. Invalid.

**Comment by tista500** [comment]
Who did draw the text-shadow and icon-shadow?

**Comment by prasadpatil25** [comment]
I have used following Gnome extension to make it like shown in picture.

https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/

**Comment by tista500** [comment]
This is not our issue.
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/7c4ac205770bf656a981bfa54cddcdf64702a83a
