### ISSUE TITLE
Semidark variant

### ISSUE THREAD

**Issue by tenten8401** [adapta-project/adapta-gtk-theme#446]
Can we have a semidark variant of this theme like Arc does? I really like the white theme but I wish it had a darker sidebar on things like nautilus. I made a mockup of what I'm talking about below:
![semidark-mockup](https://user-images.githubusercontent.com/6174343/27762696-e1a63d68-5e44-11e7-807e-d85219e4f191.png)

**Comment by tista500** [comment]
Currently there's no plan to add any more variants. Sorry.

Closed.
