### ISSUE TITLE
Consistency of Context menu all over the places

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#447]
**Reporter info**
   I am Prasad Patil using adapta theme on Fedora 24.
 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - gtk2-2.24.31-1.fc24.x86_64
 * Desktop environment - Gnome Version 3.20.2 
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Nautilus context menu and Dash to Dock context menu.

**Actual issue**
Context menu on Dash to Dock takes more spaces between menu items compared to context menu on any folder/file click operation on Nautilus.

**Steps to reproduce (if you knew)**
Click on Dash to Dock icon and check the context menu and open nautilus and click on any folder or file or just click on blank space. You will see the difference as shown in figure.

**Expected behaviour**
Should have consistent spacing between menu items so that it will look pretty and same all over the places.  Nautilus context menu looks good in space management. Dash to Dock should implement same. Please find attachment for Nautilus context menu and Dash To Dock context menu.

**Other Note (feature-request, question, etc...)**
Please note that this is a suggestion not a bug.

![nautiluscontextmenu](https://user-images.githubusercontent.com/12842912/27850155-1d997e38-6170-11e7-90b0-ee5a3ae21464.jpg)

![dashtodockcontextmenu](https://user-images.githubusercontent.com/12842912/27850161-24204ae8-6170-11e7-82eb-c365bd7be30e.jpg)

**Comment by tista500** [comment]
If you would like to talk about the height of separator StWidget in Gnome-Shell, no we can't: https://git.gnome.org/browse/gnome-shell/tree/js/ui/popupMenu.js#n271

**Comment by tista500** [comment]
In technically, it's too hard to draw the exact same separator widgets in Gnome-Shell.

I set this "can't fix", sorry.
