### ISSUE TITLE
Adapta-theme on Deepin Linux

### ISSUE THREAD

**Issue by bbruno5** [adapta-project/adapta-gtk-theme#448]
Just for documentation, adapta theme is completely compatible with Deepin Linux. I've tested today, and it is pretty.

**Comment by jacobcantele** [comment]
bbruno, I was just about to ask about this. Could you post screenshots? Really, no issues at all? I am thinking of moving to Manjaro Deepin and would really like to see official Deepin support.

**Comment by tista500** [comment]
Here is the issue tracker.
