### ISSUE TITLE
Can't get SassC

### ISSUE THREAD

**Issue by JesselSteele** [adapta-project/adapta-gtk-theme#449]
I cannot get SassC installed on my system. It's no longer in the apt repos, so it seems. I can run a git clone and make to install libsass, but not sassc.

Arc and Vertex don't need it. Would you consider using a different dependency?

With SassC as a dependency, Adapta just isn't an option, and that makes me really sad because it's so awesome.

FYI. Lots of love.

**Comment by tista500** [comment]
Xenial?

> Would you consider using a different dependency?

Oh please, you means we should revive damned Ruby Sass dependencies? :(
We and upstream Adwaita have already switched to SassC processing. Ruby actually has huge processing performance regression, and too heavy dependency. It's quite far from modern CSS processing, though Ruby-Sass had 'watch' feature...

You can build SassC from source instead.

Unfortunately I won't go back to Ruby-Sass in any reasons, sorry.

Regards.

**Comment by tristan957** [comment]
@JesselSteele if you're on ubuntu, just use the ppa.
