### ISSUE TITLE
Adapta overrides Budgie Menu's icon

### ISSUE THREAD

**Issue by ikeydoherty** [adapta-project/adapta-gtk-theme#453]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.16
 * Desktop environment -  Budgie v10.3.1-367-g8782f5b
 ```

**Adapta version (if you knew)**

All

**Related Application and/or Shell theming (or name of widget)**

Budgie Menu

**Actual issue**

Budgie Menu's icon is controlled by GSettings and is overridden by Adapta. This causes scaling issues in vertical panels and is always inconsistent with icon themes. Perhaps we can bundle the image assets into Budgie Desktop itself and have it set by schema to use the icon? I want to allow users to be able to choose the icon in Budgie Menu Settings but if its always overriden with Adapta we can't do that :)

**Steps to reproduce (if you knew)**

Use Budgie.

**Expected behaviour**

Not override ;P

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@ikeydoherty,

> I want to allow users to be able to choose the icon in Budgie Menu Settings

Was that mechanism landed already? Mine is `v10.3.1-369-gd3f7271` but unfortunately I can not find such appearance settings in BudgieSettingsWindow...

Regards.

**Comment by ikeydoherty** [comment]
Not yet but thats the plan today/tomorrow. I don't know if I should pop up an icon chooser dialog or just a simple text entry to allow changing the icon. Thoughts?

Also while I have you here I know I need to fix the default Solus Budgie ISO fonts to match Adapta, so is it Roboto default in the UI and Noto Sans for document font?

**Comment by ikeydoherty** [comment]
OK I got them the wrong way around wrt fonts..

**Comment by tista500** [comment]
> Not yet but thats the plan today/tomorrow. 

Ah, OK I'll drop the overrides.

**Comment by ikeydoherty** [comment]
Cheers :)

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/924dd7e438bfbb296d649340ae71d57d727ce89d (Gtk+ 3.22 or higher)

**Comment by tista500** [comment]
>  don't know if I should pop up an icon chooser dialog or just a simple text entry to allow changing the icon. Thoughts?

Personally I'm enough with plain entry 'file-path' though, here is Arc-menu extension settings window:
![screenshot from 2017-07-13 22-43-50](https://user-images.githubusercontent.com/6073622/28169418-3b4ab114-681d-11e7-8f94-95b833c5a057.png)

Seems it has GtkButton to open GtkFileChooserDialog and GtkComboBox to open popup with 3 menu-items. This looks very classical but at least it would work fine...

Regards.

**Comment by ikeydoherty** [comment]
I took the path of least resistance in the end because it proved impossible to have a nice graphical icon picker without eating the CPU

**Comment by tista500** [comment]
@ikeydoherty,

I saw the tweet with screenshot, yeah simple and clean... :)

Commit for Gtk+ 3.20 & 3.18 : https://github.com/adapta-project/adapta-gtk-theme/commit/23833c20f74643ca55f901c38740db1adb67a0b3

Finally all of our overrides are dropped completely.

Regards.

**Comment by ikeydoherty** [comment]
Cheers! :)
