### ISSUE TITLE
Adapta theme is no longer applied to login and lock screens

### ISSUE THREAD

**Issue by marrabld** [adapta-project/adapta-gtk-theme#454]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04 x86_64
 * Gtk+ 3.0 version - 3.22.11
 * Desktop environment - GNOME Shell 3.24.2
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
My Gnome login and lock screen seems to have defaulted back to the default gnome login theme rather than the cool Adapta one after upgrading from 16.10 -> 17.04.  Once logged in, the Adapta theme is applied as expected.  I have tried setting and un-setting the theme in the tweak tool and rebooting a few times with no joy.  Is there a way I can assert this theme to the login screen?

**Steps to reproduce (if you knew)**

**Expected behaviour**
Adapta themed login and lock screen

**Other Note (feature-request, question, etc...)**
Love this theme, thanks for your work!

**Comment by marrabld** [comment]
This is what I see now.

![screenshot from 2017-07-16 12-13-55](https://user-images.githubusercontent.com/2086569/28244543-4a33e57e-6a20-11e7-82a3-13e3cb1b43e1.png)

**Comment by tista500** [comment]
Read this: https://github.com/nana-4/Flat-Plat#gdm-locklogin-screen
