### ISSUE TITLE
Fedora 25 Wayland Eclipse Neon 3 Toolbar bar Issue

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#455]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - gtk2-2.24.31-2.fc25.x86_64 
 * Desktop environment - Gnome 3.22.16 
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Eclipse Neon 3 Toolbar running on Wayland 

**Actual issue**
Eclipse menu looks inconsistent while running it on Wayland where as it looks expected on x11.

**Steps to reproduce (if you knew)**
Run gnome session on Wayland and then open Eclipse Neon 3 then you can see Toolbar.

**Expected behaviour**
Should look exactly same on Wayland just like in x11 session.

**Other Note (feature-request, question, etc...)**
Please look at the attachment with highlighted area.

![eclipse-toolbar-wayland](https://user-images.githubusercontent.com/12842912/28248908-63f784e4-6a6a-11e7-9070-ed8e0b7e13eb.jpg)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/20a68bae70a8c9f84c5d3560c021d445ddc7e766

Regards.
