### ISSUE TITLE
adapta and kali linux

### ISSUE THREAD

**Issue by karencho777** [adapta-project/adapta-gtk-theme#456]
hello can someone help to install theme on kali linux..... 
it based on  debian have Gnome 3.2 version

**Comment by tristan957** [comment]
Not going to happen. This theme only supports GTK+ 3.2x & 4.0. Also not sure why you would need a theme for Kali when you're not even supposed to install it from what I've heard. Meant to be used in a live session.

**Comment by tista500** [comment]
Adapta does not support Gnome 3.2, sorry.

Closed.
