### ISSUE TITLE
Xfce errors with option  --disable-xfce

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#457]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.16
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Actual issue**
I installed Adapta manually with options: --disable-cinnamon --disable-unity --disable-xfce --disable-mate  --disable-openbox  --enable-telegram. But  I see xfce errors in logs.

![screenshot-20170718023805-1230x231](https://user-images.githubusercontent.com/5506156/28292877-4811a8c4-6b62-11e7-998c-b47249e76d38.png)

**Expected behaviour**
It have to  disable options completely.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/0b61773e319061a9e30c16aa6f82940cab8e6142 and https://github.com/adapta-project/adapta-gtk-theme/commit/1049afb1421ffa5e8f78953c63ddc779baa22e39

Regards.

**Comment by ceyhunnabiyev** [comment]
Wow, very fast!!  Thanks a lot...

**Comment by ceyhunnabiyev** [comment]
Hi @tista500 , 
I see  again  error message  with option `--disable-unity` like `Failed to load module "unity-gtk-module"` in applications (chromium, uget, gnome-shell and etc.)
