### ISSUE TITLE
No contrast for fonts and text-box background color - turns them unreadable

### ISSUE THREAD

**Issue by juanmatias** [adapta-project/adapta-gtk-theme#458]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04.2 LTS
 * Gtk+ 3.0 version - libgtk-3-0:amd64             3.18.9-1ubuntu3.3
 * Desktop environment - Cinnamon
 * Display server protocol - X11 or Wayland? I think it's X11 since Xorg is running in my system
 ```

**Adapta version (if you knew)**
Installed from package on Ubuntu:
Package: adapta-gtk-theme
Version: 3.91.0.234-0ubuntu1~xenial1

Also happens in Solus (installing from packages, I don't remember version right now).

**Related Application and/or Shell theming (or name of widget)**
Firefox, Libreoffice...

**Actual issue**
Using Adpata-Nokto.
In some apps (i.e. Firefox, LibreOffice) some fields are shown without contrast between font color and background color. This way they are unreadables.

**Steps to reproduce (if you knew)**
Open for example Google Calendar site in FF and look for text-box named "Other Calendars". Characters in text-box become unreadable. You still can use the text-box, can write to it, but low contrast turns characters almost invisible.

**Expected behaviour**
The contrast between characters and box-background should allow them to be readable.

**Other Note (feature-request, question, etc...)**
I was digging in styles sheets for Adpata-Nokto, but I can't figure out what style matchs with these text-boxes. May you give some advice to fix my issue?

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme#variant-matrix
Development for Gtk+ 3.18.x theming is over.

**Comment by tista500** [comment]
FIrefox extension: https://addons.mozilla.org/en-US/firefox/addon/text-contrast-for-dark-themes/?src=api
It's firefox specific issue.

**Comment by tista500** [comment]
LibreOffice in Xenial, use Gtk+ 2.x backend instead, please. I won't go back to ancient Gtk+ 3.18 theme developments anymore. After releasing 18.04, we will drop Xenial support.

So I set it "won't fix", sorry.

**Comment by juanmatias** [comment]
Extension solved issue on FF. Thanks.
