### ISSUE TITLE
[Gtk+ 3.18.x] Better support for LibreOffice 5.1.x?

### ISSUE THREAD

**Issue by Sadi58** [adapta-project/adapta-gtk-theme#465]
**Reporter info**

 ```
 * Distribution - Linux Mint 18.2
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Cinnamon
 * Display server protocol - X11
 ```

**Adapta version**
3.91.1.7-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
LibreOffice 5.1.6\~rc2-0ubuntu1\~xenial2

**The issue**
The screenshots below show how my LibreOffice Writer looks with the themes **Mint-Y**, **Arc** and **Adapta** (from top to bottom).

I think Mint-Y offers the best solution regarding spacing in the toolbar and background color (for the toolbar and ruler, etc.) 

I would expect the same (if not better) from Adapta as usual ;-)

![lo mint-y](https://user-images.githubusercontent.com/6375934/28497894-a2a0b73a-6f9a-11e7-8e57-2ccdc3711bfc.png)

![lo arc](https://user-images.githubusercontent.com/6375934/28497895-aed37b6e-6f9a-11e7-9149-d331c32f184b.png)

![lo adapta](https://user-images.githubusercontent.com/6375934/28497897-b412082a-6f9a-11e7-80a8-28d1fa932ba3.png)

**Comment by tista500** [comment]
Developments for Gtk+ 3.18 theming is over, and by default, we no longer bundle Gtk+ 3.18 theming anymore.

> LibreOffice 5.1.6~rc2-0ubuntu1~xenial2

Our target is 5.3.x series and Gtk+ 3.2x or higher. In Apr 2018, we will drop Gtk+ 3.18 theming.

Regards.

**Comment by Sadi58** [comment]
OK. I understand. I look forward to seeing the upgrade to the said higher versions then. Thanks!
