### ISSUE TITLE
Button not displaying in GNOME notes (Bijiben)

### ISSUE THREAD

**Issue by voidmage413** [adapta-project/adapta-gtk-theme#466]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04 and Fedora 26
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - GNOME Shell
 * Display server protocol - X11 or Wayland?  X11
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Bijiben (also known as GNOME Notes)

**Actual issue**
The "Move To Trash" button does not display when using an Adapta-Gtk theme

**Steps to reproduce (if you knew)**
1)  Install Bijiben
2) Create a new note.
3) Back out to the main screen showing all notes.
4) Click the checkmark button on the top bar, then select the note by clicking on the small checkbox that will appear on it in the lower right corner of the note. 
5)  When you click on the note to select it, a small bar will appear at the bottom of the application window.  This bar will have several buttons on it, such as "Notebooks" and "Open in another window".  There is a red button at the far right of this bar that says "Move to Trash".

**Expected behaviour**
The "Move to Trash" button should be visible at all times, and it is visible in the default (Adwaita) theme.  In an Adapta-GTK theme, this button does not appear unless the mouse is over it, at which it emerges as a red button from the solid white of the bar.  

Adwaita theme:
![adwaita](https://user-images.githubusercontent.com/30393486/28503018-6fffc24e-6fcc-11e7-93b5-a7dc83750002.png)

Adapta theme:
![adapta](https://user-images.githubusercontent.com/30393486/28503021-76e3ac2e-6fcc-11e7-91c2-e358bd3b3965.png)

Adapta theme on mouseover:
![adapta_mouseover](https://user-images.githubusercontent.com/30393486/28503023-7cdb32f0-6fcc-11e7-88f4-bcaecb8bcb40.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> `* Gtk+ 3.0 version - 3.24`

Gtk+ 3.24 is never released.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/326752e7de51e444c1bd2b86ffb449d9917b3545

**Comment by voidmage413** [comment]
Thank you.  That commit fixed the button.

(Also, my GTK+ version is 3.22.  Sorry about the typo).
