### ISSUE TITLE
Material Design's color is still used in some parts of the GTK widgets WHILE other parts of the theme has changed to blue accents already.

### ISSUE THREAD

**Issue by chuutatsu** [adapta-project/adapta-gtk-theme#467]
**Reporter info**

 ```
 * Distribution - Manjaro 17.0.2
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Xfce 4.12
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.91.0.150-1

**Related Application and/or Shell theming (or name of widget) and Actual Issue**
Any applications that contains these "drag from left or right" thingie (sorry I don't know the proper name of it). It has original material design color compared to the blue checkbox:
![screenshot_2017-07-25_12-29-36](https://user-images.githubusercontent.com/24815847/28557229-64c3e3b4-7135-11e7-9ebc-52b37e0090ba.png)
(Xfce panel settings is used in this example)

**Steps to reproduce (if you knew)**
Just open any applications that contains the thingie above.

**Expected behaviour**
All blue accents of Adapta are applied not only to checkboxes and menus. I would like to see them being applied on that thingie above.

**Other Note (feature-request, question, etc...)**
Is this color difference intentional/design decision? Or just unfinished?

**Comment by tista500** [comment]
> All blue accents of Adapta are applied not only to checkboxes and menus. 

o_O?

**Comment by tista500** [comment]
> Is this color difference intentional/design decision? 

Intentional. Because primary colour is different from accent colour.

**Comment by chuutatsu** [comment]
Sorry, it is the expected behavior part, but now what actually happened. l'll rephrase my words.

1. See the blue checkbox in the screenshot above? Apparently the only thing that hasn't changed in the latest Adapta theme is the greenish thing on the right of the "row size".
2. My question is..... is this really intentional to leave them untouched? 
3. Or are you planning to change them later?

(While almost accents in Adapta is now light blue instead of green.)

**Comment by chuutatsu** [comment]
Oh alright, thanks for answering. I apparently replied a bit late above.

**Comment by tista500** [comment]
> See the blue checkbox in the screenshot above? 

That's not blue but Cyan500.

> greenish thing on the right of the "row size".

GtkScale with Teal300.

> My question is..... is this really intentional to leave them untouched?

Intelntional.

> Or are you planning to change them later?

No.
