### ISSUE TITLE
Fedora 25 Eclipse Neon 3 GTK3 Tooltip issue. 

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#470]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - gtk2-2.24.31-2.fc25.x86_64 
 * Desktop environment - Gnome 3.22.16 
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Tooltip widget of Eclipse Neon 3 running on GTK3.

**Actual issue**
Showing black tooptip widget with white font.

**Steps to reproduce (if you knew)**
Write any Java program and run in debug mode and hover on the variable.

**Expected behaviour**
Should contain white background with black font. Or preferably nice looking tooltip.

**Other Note (feature-request, question, etc...)**
Please check picture for more details

![screenshot from 2017-07-22 18-32-42](https://user-images.githubusercontent.com/12842912/28743055-d8ee8d7c-745d-11e7-8700-7797c15bd974.png)

**Comment by tista500** [comment]
> https://github.com/adapta-project/adapta-gtk-theme/commit/e6642defaebac93bb51824ab3a1bde3e397dad93

Totally upstream design issue. And I gave up tracking this down, it may or may not work.

Closed.
