### ISSUE TITLE
XFCE4 Mail Watcher icon cropped

### ISSUE THREAD

**Issue by pegasusearl** [adapta-project/adapta-gtk-theme#471]
## **Reporter info**

 ```
 * Distribution - Antergos (Arch)
 * Gtk+ 3.0 version - 3.22.17-1
 .. GTK2 version - 2.24.31-1
 * Desktop environment - XFCE4 with compton
 * Display server protocol - X11
 ```

## **Adapta version (if you knew)**
**Version:** `3.91.0.150-1`
`adapta-gtk-theme` from _community_ repo or `gtk-theme-adapta` from _antergos_ repo. 

## **Related Application and/or Shell theming (or name of widget)**
`xfce4-panel` `xfce4-mailwatch-plugin`
using [arc-icon-theme](https://github.com/horst3180/arc-icon-theme)

.. **EDIT:** `inkscape`

## **Actual issue**
When using this theme, `xfce4-mailwatch-plugin`'s icon was cropped.
### Preview
- Adapta and Adapta-Nokto https://pasteboard.co/GDuftQo.png (noticeable)
- Adapta-Eta and Adapta-Nokto-Eta https://pasteboard.co/GDugYHn.png (almost unnoticed)
- Normal (another theme) https://pasteboard.co/GDuhyIs.png

- **edit:** also happened in `inkscape` toolbar https://pasteboard.co/GDvhWa8.png

## **Expected behaviour**
Usually looked like this https://pasteboard.co/GDuhyIs.png

## **Other Note (feature-request, question, etc...)**
EDIT: When I'm going to upload mailwatcher and clipman xfce4 panel plugin, I just realized, this cropping also happened to something else. 
This is the toolbar in inkscape: https://pasteboard.co/GDvhWa8.png

**Comment by tista500** [comment]
Stop reporting multiple issues into a single report, please...

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/35438bd77a9d597efecfc70019a28ff721ac2d29
