### ISSUE TITLE
[Gnome-Software] Review bars are miss leading

### ISSUE THREAD

**Issue by gocarlos** [adapta-project/adapta-gtk-theme#473]
**Reporter info**

 ```
 * Distribution - ubuntu gnome 17.04
 * Gtk+ 3.0 version - ii  libgtk-3-0:amd 3.22.11-0ubu amd64  
 * Desktop environment - gnome 3.24
 * Display server protocol - X11 or Wayland? - x11
 ```

**Adapta version (if you knew)**

latest 

**Related Application and/or Shell theming (or name of widget)**

Gnome software

**Actual issue**

the colors are miss leading in the review bars

**Steps to reproduce (if you knew)**

always like that

**Expected behaviour**

the colors should be inverted, as brighter should be the number of reviews with that number of stars

**Other Note (feature-request, question, etc...)**
I don't know how much of this issue is only my own opinion and how much others also think this should be different. 

![image](https://user-images.githubusercontent.com/1331762/28978748-7bd9aaa6-7947-11e7-8532-be62e91ceab0.png)

**Comment by tista500** [comment]
Hard-coded: 
  `widget.reviewbar`: https://git.gnome.org/browse/gnome-software/tree/src/gtk-style.css#n300

**Comment by tista500** [comment]
This happens with Adwaita-Dark as well, so I don't think that was theme specific.

Won't (Can't ) fix, sorry.

Closed.
