### ISSUE TITLE
Editable combo boxes takes more height on screen compared to non-editable.

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#474]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - gtk2-2.24.31-2.fc25.x86_64 
 * Desktop environment - Gnome 3.22.16 
 * Display server protocol - X11 or Wayland? Doesnt matter
 ```

**Adapta version (if you knew)**
Latest build from sources.

**Related Application and/or Shell theming (or name of widget)**
Editable combo boxes. Applications Gnome Tweak Tool and Eclipse workspace selection window.

**Actual issue**
Compared to non-editable combo boxes, editable combo boxes takes more height on screen.

**Steps to reproduce (if you knew)**
Open Gnome Tweak Tool and click on fonts option and check combo boxes.
Open Eclipse and check workspace selection screen.

**Expected behaviour**
Should take exact (or even less) amount of height like non-editable combo boxes. All combo boxes (editable and non-editable) and entry boxes should have consistent height.
Distance between text and line should be reduced.

**Other Note (feature-request, question, etc...)**
Please check images.

Gnome Tweak Tool:
![screenshot from 2017-08-06 11-04-01](https://user-images.githubusercontent.com/12842912/29000933-e8593546-7a98-11e7-894f-ce20403446f8.png)

Eclipse workspace selection window:
![screenshot from 2017-08-06 11-02-43](https://user-images.githubusercontent.com/12842912/29000938-fc22e3e2-7a98-11e7-9ea8-d88ca131ccb4.png)

**Comment by tista500** [comment]
Spinbutton is not the part of combobox. And can't fix in Eclipse at least, sorry.

**Comment by tista500** [comment]
Report correct version:

> * Gtk+ 3.0 version - gtk2-2.24.31-2.fc25.x86_64

**Comment by prasadpatil25** [comment]
I guess correct version is: gtk3-3.22.17-2.fc25.x86_64

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/commit/9d8299e324487fccd733c8e6126d9b1bf5db19cf
https://github.com/adapta-project/adapta-gtk-theme/commit/0aa4d010307c3d1e7fc8631f246180f147bdec27

Eclipse, eclipse, eclipse, the curse...
