### ISSUE TITLE
Gnome-shell theme spamming journal with assertion 'width > 0' failed

### ISSUE THREAD

**Issue by pmargeti34** [adapta-project/adapta-gtk-theme#475]
```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.17-1
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? - X11
```

**Adapta version (if you knew)** 
3.91.0.150-1

**Related Application and/or Shell theming (or name of widget)**
Gnome shell 3.24.3-1 using any variant of adapta shell theme (-eta -nokto)

**Actual issue**
System journal is flooded with many lines containing text:
`gnome-shell[621] setup_framebuffers: assertion 'width > 0' failed`

**Steps to reproduce (if you knew)**
run` journalctl --follow in terminal`
activate gnome shell overview
observe log being filled with `setup_framebuffers: assertion 'width > 0' failed` messages

**Expected behaviour**
no errors in system log when using gnome-shell with adapta shell theme

**Other Note (feature-request, question, etc...)**
This error message doesn't seem to do anything other than flood the systemd log.

**Comment by tista500** [comment]
o_O?

I could not reproduce...

**Comment by tista500** [comment]
Ah, Dash: `st_widget_get_theme_node called on the widget [0x36b28fdb0 StIcon.show-apps-icon:last-child first-child] which is not in the stage.`

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/bcbe7a3f04c9e15b8a2378c114275a39bd8963e1

Regards.
