### ISSUE TITLE
Tabs in Tilix are too big

### ISSUE THREAD

**Issue by alex285** [adapta-project/adapta-gtk-theme#476]
please see https://github.com/gnunn1/tilix/issues/1057
i test with Adapta from master

**Comment by tista500** [comment]
I'm neither a Tilix user nor tracking their design changes...

**Comment by tista500** [comment]
Maybe later.

**Comment by tista500** [comment]
`.tilix-small-button` style-class is not the standard class, use `.small-button` instead.
And that class hoard-codes 2px non-scalable padding.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/8b20a60a57a7d05e412131801889d45b2d392499

Regards.
