### ISSUE TITLE
Parallel building does not go ahead on NixOS

### ISSUE THREAD

**Issue by romildo** [adapta-project/adapta-gtk-theme#477]
**Reporter info**

 ```
 * Distribution - NixOS
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - awesome window manager
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.90.1.1 or greater

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

After `parallel` options were changed to
```
--no-notice --line-buffer -j0 
```
the package cannot be built anymore with parallel enabled. It just hangs on the command:
```
nix/store/hsj40c64nky7r6pc27nfzlvzjjhwlfmx-parallel-20170722/bin/parallel -0 --no-notice --line-buffer --jobs 100% --noswap bash ::: \
	render-assets-gtk2-arrow.sh \
	render-assets-gtk2-button.sh \
	render-assets-gtk2-checkradio.sh \
	render-assets-gtk2-column.sh \
	render-assets-gtk2-entry.sh \
	render-assets-gtk2-handle.sh \
	render-assets-gtk2-misc.sh \
	render-assets-gtk2-range.sh \
	render-assets-gtk2-scrollbar.sh \
	render-assets-gtk2-spin.sh \
	clone-assets-gtk2.sh
```
and nohting more appears on the terminal.

**Steps to reproduce (if you knew)**

Build the package in NixOS.

**Expected behaviour**

Building should terminate.

**Other Note (feature-request, question, etc...)**

If the option `--noswap` is removed from the `parallel` command line, it works.

**Comment by tista500** [comment]
Nobody reads the README.md.

We do NOT suggest `parallel` option when packaging... :(

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/2b992450e2db2b1daee77e990d3c551103d458e5

**Comment by romildo** [comment]
Thanks for the fix.

This issue was happening on my notebook, which is not a remote/shared build-server.
