### ISSUE TITLE
Adapta Theme as a CSS Web Framework

### ISSUE THREAD

**Issue by Kuchiriel** [adapta-project/adapta-gtk-theme#478]
This would be so great!

**Comment by Madis0** [comment]
There are several frameworks that implement Material Design, for example:
* https://getmdl.io/
* https://materializecss.com/
* https://www.muicss.com/
* https://material-ui.com/

**Comment by Kuchiriel** [comment]
@Madis0 But they are not like adapta, just similar :/

**Comment by tista500** [comment]
I have not much time to do with this, So close, sorry...
