### ISSUE TITLE
Poor readability in meld due to the used colors

### ISSUE THREAD

**Issue by romildo** [adapta-project/adapta-gtk-theme#479]
**Reporter info**

 ```
 * Distribution - NixOS
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Openbox
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
 3.91.1.47

**Related Application and/or Shell theming (or name of widget)**
 meld

**Actual issue** 
Meld shows the differences between versions of files. The used colors make them very difficult to read, both with and without syntax highlighting.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
![screenshot_2017-08-12_06-38-27](https://user-images.githubusercontent.com/1217934/29239679-26e4d1c2-7f2a-11e7-8bd9-090a7468a54c.png)
![screenshot_2017-08-12_06-39-26](https://user-images.githubusercontent.com/1217934/29239680-26e6d9ea-7f2a-11e7-957c-5077faed6377.png)

**Comment by tista500** [comment]
What was the reason you did not use 'Meld dark scheme'? I don't think this is theme-specific and this WILL happen with Adwaita-dark as well.

**Comment by tista500** [comment]
Our colour scheme: https://github.com/adapta-project/adapta-gtk-theme#gtksourceviewgedit-color-scheme-support

**Comment by tista500** [comment]
Official Wiki: https://wiki.gnome.org/Apps/Meld/DarkThemes

**Comment by romildo** [comment]
The theme file `adapta.xml` has already been installed into the `~/.local/share/gtksourceview-3.0/styles` directory, but I haven't noticed the _Syntax highlighting color scheme_ setting in preferences. Sorry for the noise.

Nonetheless, when I select the _Adapta Gedit_ color scheme, it is still difficult to read:
![screenshot_2017-08-12_08-49-52](https://user-images.githubusercontent.com/1217934/29240418-40a4b940-7f3b-11e7-8514-b782a16ca3ca.png)

**Comment by tista500** [comment]
> Nonetheless, when I select the Adapta Gedit color scheme, it is still difficult to read:

It's completely upstream issue, not our fault, please... :(
This happens with other dark-variant themes & most of their colour schemes, too.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/7e84a515edd8a87f628304eaa2c949644f3cc259

**Comment by skebanga** [comment]
Please forgive me commenting on a closed issue - I'm looking for some guidance.

I have the same problem as this issue. I am using Adapta-Dark theme, and when using [meld](http://meldmerge.org/) and selecting `solarized-dark` theme for syntax highlighting, the colours used for highlighting diffs make it hard to read.

I copy-pasted the changes in commit [7e84a51](https://github.com/adapta-project/adapta-gtk-theme/commit/7e84a515edd8a87f628304eaa2c949644f3cc259) into `/usr/share/gtksourceview-3.0/styles/solarized-dark.xml`, and this has the desired effect of changing the colours used for diff highlighting.

I can't help but think this is not the right way to fix this issue though!

Is there a more idiomatic way to change the diff colours?
