### ISSUE TITLE
disabled view when windows is not focused

### ISSUE THREAD

**Issue by ItamarShDev** [adapta-project/adapta-gtk-theme#480]
One of gnome best UI feature IMHO is the disabled view when the window is not focused
is it possible to add it?

**Comment by tista500** [comment]
> One of gnome best UI feature IMHO is the disabled view when the window is not focused

o_O? Backdrop pseudo-class?
That's one of Adwaita Gtk+ 3.x theme feature and Gtk+ 2.x apps are not supported.

Adwaita is NOT our design source, so we've set backdrop state styling in GtkHeaderBar only as usual.

**Comment by tista500** [comment]
#10

**Comment by tista500** [comment]
And I've never seen such feature in ChromeOS and/or Android unfortunately.

**Comment by tista500** [comment]
Later I may or may not re-open this though, but currently there's no plan to revive backdrop state styling outside the GtkHeaderBar, sorry...

Set this as 'Re-track in future'.

Regards.
