### ISSUE TITLE
Button text color difficult to read on VMware Horzion Client application

### ISSUE THREAD

**Issue by voidmage413** [adapta-project/adapta-gtk-theme#481]
**Reporter info**

 ```
 * Distribution - Fedora 26 and Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME 3
 * Display server protocol - X11 or Wayland?  X11 (same on Wayland)
 ```

**Adapta version (if you knew)**
Recent version built from github on August 15, 2017

**Related Application and/or Shell theming (or name of widget)**
VMware Horizon Client

**Actual issue**
The text of the "New Server" button on the VMware Horizon Client is so light as to be difficult to read.  Other parts of the Horizon Client interface within a virtual desktop instance also share this problem.  Several other themes, at least within the GNOME 3 environment, do not display this issue.  Example themes where the button text color is clearly legible include Adwaita, Arc, Numix, and United GNOME.  (Pictures of the client in these themes attached)

**Steps to reproduce (if you knew)**
1.  Install VMware Horizon Client for Linux
https://my.vmware.com/web/vmware/details?downloadGroup=CART17Q2_LIN64_450&productId=578&rPId=17207

2. Make Adapta-GTK the active GTK+ theme in GNOME 3.

3.  Open VMware Horizon Client

**Expected behaviour**
All of the interface, particularly the "New Server" button in the top toolbar, is a color that is clearly readable, rather than a color that nearly disappears into the toolbar background. 

**Other Note (feature-request, question, etc...)**
VMware Horizon Client with the Adapta-GTK theme (red rectangle edited in to mark problem text):
![adapta_horizon_mark](https://user-images.githubusercontent.com/30393486/29342088-b6091a7e-81f6-11e7-9223-743d870e16a0.png)

VMware Horizon Client with the Adwaita theme:
![adwaita_horizon](https://user-images.githubusercontent.com/30393486/29342068-8956268e-81f6-11e7-887e-02bb437f6d11.png)

VMware Horizon Client with Arc theme:
![arc_horizon](https://user-images.githubusercontent.com/30393486/29342113-f007b1cc-81f6-11e7-88d5-9c1b8af10559.png)

VMware Horizon Client with Numix theme:
![numix_horizon](https://user-images.githubusercontent.com/30393486/29342118-fb3a44e2-81f6-11e7-88bd-552cf410df02.png)

VMware Horizon Client with United GNOME theme:
![united_horizon](https://user-images.githubusercontent.com/30393486/29342132-03bdd886-81f7-11e7-9e40-059b0d453dcd.png)

**Comment by tista500** [comment]
This does not happen in any native Gtk+ 2.x apps AFAIK. :/
