### ISSUE TITLE
Theme compatibility with Arc-Menu's icon option

### ISSUE THREAD

**Issue by lexruee** [adapta-project/adapta-gtk-theme#482]
Hi @tista500 . First of all, thank you for your awesome theme. It's my default theme on my GNOME Desktop. 

**Reporter info**

 ```
 * Distribution - Debian Sid
 * Gtk+ 3.0 version - Gtk+ 3.22.x
 * Desktop environment - GNOME 3.22
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
All (or master branch 2e69c3af331b4a5f1ac3759c8283a9675cdddee5)

**Related Application and/or Shell theming (or name of widget)**
[Arc Menu GNOME Shell Extension](https://github.com/LinxGem33/Arc-Menu) (version 14)

**Actual issue**
![screenshot from 2017-08-16 13-12-07](https://user-images.githubusercontent.com/649340/29360725-8f1a4f9e-8284-11e7-97de-f1b4330614f0.png)

Since the release of Arc Menu version 14 (with some code cleanups), the icon is overridden by Adapta. The theme causes that the user defined icon is displayed on top of the Adapta menu icon, as shown by the figure above. 

Here are more technical details which are related to the Adapta theme: https://github.com/LinxGem33/Arc-Menu/issues/124#issuecomment-321552032

**Steps to reproduce (if you knew)**
1. Install Adapta theme
2. Install Arc Menu (v14) on GNOME 3

**Expected behaviour**
Not override :-)

**Other Note (feature-request, question, etc...)**
My question is how can Arc Menu or the Adapta theme be adjusted so that a user defined icon is not overridden by Adapta, without any Arc Menu coding hacks :P.

**Comment by tista500** [comment]
I dislike any "Logo" images as application menus... Those were not pared with its function. But I will drop our workaround...

**Comment by tista500** [comment]
I stopped using that extension now.

Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/cc803e74b0040b6f2ff708c4fef15626ce41cbc3

**Comment by lexruee** [comment]
Hey, thanks for the quick fix and the commit :+1:. Regarding logo images as menu icons, I understand your point and you're right, but lot of Arc Menu users requested that feature.

By the way, keep up the good work :smiley:.

Cheers!
