### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ikeydoherty** [adapta-project/adapta-gtk-theme#483]
We're noticing a significantly higher memory usage in the base OS with Adapta (150MB or so), so...

 - Any way we can debug this? SVG -> PNG -> Optipng?
 - Anything we can do to help reduce this footprint?

**Comment by tista500** [comment]
Adwaita:
  * asset files: 142
  * asset usage: 874 KB

Adapta:
  * asset files: 404
  * asset usage: 388 KB

Adapta-Nokto:
  * asset files: 267
  * asset usage: 244 KB

So I don't think we *significantly* eat RAMs by asset image files, but out CSSs may eat them...

**Comment by tista500** [comment]
Anyway number of asset files is 2 or 3 times larger than Adwaita, so yeah dropping images can reduce our footprint though...

**Comment by ikeydoherty** [comment]
The CSS is being minified though right?

**Comment by tista500** [comment]
Yes. But currently Gtk+ 3.22 theming needs to cover Gnome 3.22 to 3.26, then our Gtk+ 3.22 theming is getting larger and larger... for example, `_3rd-party.scss` eats 80 MB or so unfortunately...

It's around time to clean up and drop some application support....

Regards.

**Comment by ikeydoherty** [comment]
Wow! Sorry to hear that. I wonder if it would be feasible to split out Budgie support (if its super heavy) and make Budgie load it directly?

**Comment by tista500** [comment]
> I wonder if it would be feasible to split out Budgie support (if its super heavy) and make Budgie load it directly?

No. Budgie styling will be kept in our CSSs. ;)
Basically my codes contain a bit longer selectors to prevent unwanted conflicts, so if I could shorten them, those may be 20% or 30% lighter as tolal number of CSS lines. And `@extend` links sometimes eat resources than `@include`, so yes, I need to refactor them, too.

**Comment by ikeydoherty** [comment]
Oh I see, well, sorry for causing more work for you :3

**Comment by tista500** [comment]
Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.91.2.35

That release will reduce the actual RAM usage 20 MB to 50 MB per a single variant, and improve a bit faster apps response especially when launching... Currently that's the best effort for me because we need to keep some backward compat in various apps/desktop support for *non-rolling release* distros unfortunately.

This time I close this issue, and later I will re-open and re-track this.

Regards.

**Comment by ikeydoherty** [comment]
Thanks bud - really appreciate it!

**Comment by tista500** [comment]
Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.91.2.41

We've reduced generated CSS size per a single variant to 60%, so that will bring more memory saving around 30 MB or so...

Regards.

**Comment by ikeydoherty** [comment]
I kinda feel guilty now. xD

**Comment by tista500** [comment]
Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.91.2.109

I've killed some *RAM eaters*, so rev.109 will reduce RAM usage more than 30 MB compared with rev.41...
