### ISSUE TITLE
Adapta scrollbar is not user-friendly

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#484]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.17
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version - 3.91.1.26**

**Actual issue**
When I  hover cursor on Adapta scrollbar, it confuses with resizing window, sometimes it causes to stick, not to extend the scrollbar..

**Comment by tristan957** [comment]
This could just be a GTK scrollbar issue. There are various scrollbar looks a developer can choose from

**Comment by ceyhunnabiyev** [comment]
Hi @tista500 , I know, that is upstream issue, but  I think, Adapta Scrollbar within container solves a little bit when  cursor is hovered on the scrollbar.  Arc-theme is OK, because it uses container  when the scrollbar is extended.

**Comment by tristan957** [comment]
Include some picturres to help people understand what you  are talking about

**Comment by ceyhunnabiyev** [comment]
Screenshots from Arc theme and United-Gnome (Archlinux version):
![screenshot from 2017-08-24 01-01-05](https://user-images.githubusercontent.com/5506156/29638479-6e478ad6-8868-11e7-9926-495c4576608a.png)
![screenshot from 2017-08-24 01-02-48](https://user-images.githubusercontent.com/5506156/29638488-74c1c7f0-8868-11e7-8c22-757babb1d7d7.png)
