### ISSUE TITLE
Bad window decorations after start

### ISSUE THREAD

**Issue by AnachronyX** [adapta-project/adapta-gtk-theme#485]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - GNOME 
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
Latest from PPA.

**Actual issue**
Fullscreen apps like Firefox have bad window decorations after GNOME start. When I restart GNOME (Alt+F2 r) everything is O.K.

Here is a screenshot https://ibb.co/dEcrhQ

Maybe it's GNOME issue. When I reset all of GNOME's settings, it remains the same.

**Comment by tista500** [comment]
o_O?

> Fullscreen apps like Firefox have bad window decorations 

What are you talking about? In general, once apps was expanded by pressing F11 key, all of Mutter's window-frames and GtkHeaderBars are hidden by default.

**Comment by tista500** [comment]
And you should clarify what extension you enabled before explaining the issue...

**Comment by AnachronyX** [comment]
Sorry, my fault, I meant maximized window.

![obrazek](https://user-images.githubusercontent.com/16992240/29477229-d6dfdce2-8467-11e7-8779-5c1a6bafbdfb.png)

I have 20 extensions installed:
- AlternateTab
- Appfolders Management extension
- Applications Menu
- Auto Move Windows
- Caffeine
- Coverflow Alt-Tab
- Dash to Dock
- Dynamic Top Bar
- Extensions
- Launch new instance
- Mailnag
- Media Player Indicator
- Native Window Placement
- OpenWeather
- Pixel Saver
- Places Status Indicator
- Removable Drive Menu
- TopIcons Plus
- User Themes
- Workspace Grid

**Comment by tista500** [comment]
It's neither default Gnome-Shell feature, nor user-themes. 
We do not support this extension: https://github.com/deadalnix/pixel-saver
As far as I know, we've never seen such feature in our upstream: https://git.gnome.org/browse/gnome-shell

Won't fix, sorry.

**Comment by chuutatsu** [comment]
@AnachronyX Do you use Window Header plugin on that panel?

(In Xfce it's Window Header. Idk its name in Gnome.)

**Comment by AnachronyX** [comment]
No, I don't. I found a solution to this problem on the pixel-saver
extension pages thanks to Tista.

<https://github.com/deadalnix/pixel-saver/issues/132>
https://github.com/deadalnix/pixel-saver/issues/132


2017-08-19 15:05 GMT+02:00 Shiba Chuutatsu <notifications@github.com>:
