### ISSUE TITLE
oomox compatibility request for Adapta 

### ISSUE THREAD

**Issue by Warmuser** [adapta-project/adapta-gtk-theme#486]
Hello, can you replace the bitmap image assets with SVG format to your Adapta theme? Read these request that I posted to oomox owner: https://github.com/actionless/oomox/issues/94#issuecomment-323549164 :)

**Comment by tista500** [comment]
No, I won't. Because we've already have our own color-changer. We do not support that application.

Won't fix, sorry.

**Comment by tista500** [comment]
We do not use any bmp images but png images.

**Comment by Warmuser** [comment]
Oops..  Ok, no problem. The color-changer is a WIP or is already available? Thanks

**Comment by actionless** [comment]
are you planning to implement changing background and foreground colors?
