### ISSUE TITLE
Unity dash and app switcher (Alt + Tab) showing purple background color (Default Unity color)

### ISSUE THREAD

**Issue by sanjaypra555** [adapta-project/adapta-gtk-theme#487]
![screenshot from 2017-08-23 13-02-47](https://user-images.githubusercontent.com/18235954/29603957-9b1b2776-8803-11e7-8790-9127abdbce94.png)
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9-1ubuntu
 * Desktop environment - Unity
 * Display server protocol - X11 or Wayland? - X11
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Unity dash and app switcher (Alt + Tab) showing purple background color (Default Unity color)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Capture screenshot please...

**Comment by sanjaypra555** [comment]
@tista500  Screenshot added..

**Comment by tista500** [comment]
So where is the element with purple background color? o_O?

**Comment by sanjaypra555** [comment]
Before some days the background of the dash was gray and now it has the background of unity default.

**Comment by tista500** [comment]
I'm really afraid you're talking about "average-bg-color": https://askubuntu.com/questions/138839/where-does-unity-store-the-chameleonic-launcher-dash-color

If so, it's not theme-side issue. Unity7 generates that colour via its code as "chameleonic effect".
