### ISSUE TITLE
[Telegram] Certain parts of the interface are untextured

### ISSUE THREAD

**Issue by Noammac** [adapta-project/adapta-gtk-theme#489]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.18-2
 * Desktop environment - GNOME
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.91.0.150-1

**Related Application and/or Shell theming (or name of widget)**
Telegram

**Actual issue**
Certain parts of the Telegram theme are untextured:

![peek 2017-08-23 15-37](https://user-images.githubusercontent.com/19552683/29616624-d13797f6-881a-11e7-89d2-e324f2eefd7a.gif)
A small area around the scroll bar.
![peek 2017-08-23 15-38](https://user-images.githubusercontent.com/19552683/29616626-d14e0054-881a-11e7-96e3-06d828ded2b8.gif)
The small area around the "typing" symbol.
![peek 2017-08-23 15-49](https://user-images.githubusercontent.com/19552683/29616623-d1376448-881a-11e7-8c15-5653d6480d28.gif)
The area before the "circle" when holding your mouse on a contact.

**Steps to reproduce (if you knew)**
Install Adapta through the AUR, change Telegram's colour scheme through the texture file at /usr/share/themes/Adapta-Nokto/telegram, try the actions displayed in the GIFs

**Expected behaviour**
The parts of the interface that are coloured white will be coloured according to the Adapta-Nokto colour scheme.

**Other Note (feature-request, question, etc...)**
I only tested it with Nokto, might test it with regular Adapta later.
Also, there are some parts that are coloured in shades of blue that seem odd.

**Comment by tista500** [comment]
Confirmed. I'll look into it in this weekend. Maybe I need to rewrite styling.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/8737f22f19adb6f847b7b36e4d0da60b764fff59
