### ISSUE TITLE
The README.md says Pantheon isn't supported, but it works.

### ISSUE THREAD

**Issue by superchampionoftheworld** [adapta-project/adapta-gtk-theme#493]
**Reporter info**

 ```
 * Distribution - Elementary OS
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Pantheon
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

According to the README.md, Pantheon isn't supported, but here I am, happily using it on Elementary OS 0.4.1 Loki.

**Steps to reproduce (if you knew)**
Install Adapta on Elementary OS.

**Expected behaviour**
I expected it to not work at all. 

**Other Note (feature-request, question, etc...)**
I'm not really sure if this should be posted as an issue.

**Comment by tista500** [comment]
For me, Adapta does not work with Pantheon shell, and I do not suggest now and then. If their results of libgranite could be merged into vanilla Gtk+, I may support.

Sorry, closed...
