### ISSUE TITLE
Disabled buttons without background

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#497]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version -  3.22.18
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.92.2.109 (with breath color - 1abc9c)

**Actual issue**
![screenshot-20170901102857-288x48](https://user-images.githubusercontent.com/5506156/29958176-626b6e76-8f02-11e7-8f74-fcd2c2ad1671.png)

**Expected behaviour**
I think, disabled buttons without background (only disabled button text ) would be nice like active buttons that showed above..

**Comment by tista500** [comment]
Let me see how those buttons looked when turning to normal state.

**Comment by tista500** [comment]
GtkButtonBox?

**Comment by ceyhunnabiyev** [comment]
I don't know. Screenshot from [pamac](https://github.com/manjaro/pamac) (GTK3 app)

**Comment by ceyhunnabiyev** [comment]
I think, that is dialog buttons.
