### ISSUE TITLE
Invisible Progressed bar on selected item

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#498]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.18
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.92.2.109 (with custom color - 1abc9c)

**Actual issue**
![screenshot-20170901105354-540x85](https://user-images.githubusercontent.com/5506156/29958702-15160cbe-8f05-11e7-93ed-b81fedb8c21c.png)

**Comment by tista500** [comment]
Steps to reproduce please.

**Comment by ceyhunnabiyev** [comment]
Maybe tiny white borders around  progressbar would fix this issue.

**Comment by ceyhunnabiyev** [comment]
Screenshot from Deluge..

**Comment by tista500** [comment]
I asked "steps to reproduce".

**Comment by ceyhunnabiyev** [comment]
Choose another color for  progressed part of the bar. I have no any nice idea for this right now.

**Comment by tista500** [comment]
I ASKED "HOW TO REPRODUCE" THIS ISSUE. But anyway I've checked gtk-demo. I'm going to block you unfortunately.

Closed.

**Comment by ceyhunnabiyev** [comment]
Thanks @tista500 , Sorry for my English. I don't understand it. I mean  you asked me to give ideas  how resolve this issue. Why are you going to block me?

**Comment by georgelemental** [comment]
@ceyhunnabiyev "Steps to reproduce" means "steps to make the issue happen," not "steps to fix the issue." 

@tista500 Here is how to reproduce ceyhunnabiyev's issue: 

1. Install the [Deluge Bittorrent client](http://dev.deluge-torrent.org/wiki/Installing/Linux)

2. Open the client

3. Download [The torrent file for Ubuntu 17.04](http://releases.ubuntu.com/17.04/ubuntu-17.04-desktop-amd64.iso.torrent) as a test

4. Press on the + button at the top-left of the Deluge window
![screenshot from 2017-09-01 12-37-28](https://user-images.githubusercontent.com/11415479/29979193-81b3b8a0-8f12-11e7-939c-e0cbdb63b108.png)

5. Press "File"
![screenshot from 2017-09-01 12-43-09](https://user-images.githubusercontent.com/11415479/29979366-268c3186-8f13-11e7-93e5-0688f6959a60.png)

6. Navigate to the ubuntu torrent file you downloaded and press "Open" 

7. Press "Add"

8. Wait a few seconds

9. Look at the progress bar: its end is invisible. ![image](https://user-images.githubusercontent.com/11415479/29979503-b42b68cc-8f13-11e7-9407-8880c88e46e5.png)

10. Now click on the torrent: the beginning of the progress bar becomes invisible 
![image](https://user-images.githubusercontent.com/11415479/29979626-42152060-8f14-11e7-87a1-9ee8ce41e411.png)

11. Compare to Adwaita: There is a grey background, making the progress bar fully visible. 
![image](https://user-images.githubusercontent.com/11415479/29979680-7225b24c-8f14-11e7-9917-b1c247d0c8b7.png)
![image](https://user-images.githubusercontent.com/11415479/29979689-7f035eb0-8f14-11e7-8c52-c11f930436a5.png)

**Comment by ArchangeGabriel** [comment]
“How to reproduce” means what should I do in order to observe this behaviour on my side.
