### ISSUE TITLE
Window managers without compositor (Openbox and xfwm4, marco without compositor enabled): gtk3 gnome-style applications cannot be resized with mouse on left and right edges 

### ISSUE THREAD

**Issue by ThanosApostolou** [adapta-project/adapta-gtk-theme#500]
**Reporter info**
Thanos Apostolou (maintainer of the manjaro lxde edition)
 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.19
 * Desktop environment - lxde/openbox
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.91.2.129

**Related Application and/or Shell theming (or name of widget)**
Gtk3 applications with gnome style like **gnome-disk-utility** and manjaro applications like **pamac**, **manjaro-hello**

**Actual issue**
When using lxde/openbox, the gtk3 gnome-style applications cannot be resized with mouse from left and right edges, but they can only be resized from bottom and top edges as well as the corners.

**Steps to reproduce (if you knew)**
Use lxde or openbox with adapta gtk theme and try to resize gnome-disk-utility from the left/right edges with the mouse.

**Expected behaviour**
Being able to resize these windows from left and right edges with mouse.

**Other Note (feature-request, question, etc...)**
When using **arc-gtk-theme** then the applications can be resized from all edges but it's kinda hard to click on them.
**Adwaita** gtk theme has the best behaviour. Somehow it seems to add borders with enough width, in order to be easily resizable, to these gtk3 gnome-style apps but only when using openbox or lxde. When using xfwm4, marco or mutter the borders don't exist (as far as I know adwaita has the same approach as adapta regarding window borders, meaning that they don't want them to be visible). Is it possible to make adapta theme behave similarly (I can do a small video if you want in order to show you the problem better)?

**Comment by ThanosApostolou** [comment]
Correction about what I said about adwaita. It seems that it adds those borders when compositor is not available (it seems that it has something to do with the fact that shadow width is not available without compositor). I can reproduce this with **xfwm4** by enabling and disabling compositor. When compositor is disabled, gnome-style apps cannot be resized with adapta theme, while they can get resized with adwaita theme.

So, I believe that this issue affects all window managers without compositor

**Comment by ThanosApostolou** [comment]
Reproduced with **marco** without the compositor too.

**Comment by tista500** [comment]
Bordered, bordered, bordered... I have no idea why ancient window-manager users want to break Material Design effort... :(

**Comment by ThanosApostolou** [comment]
Works perfectly thx!!!
