### ISSUE TITLE
Support For QGnomePlatform

### ISSUE THREAD

**Issue by Syntist** [adapta-project/adapta-gtk-theme#501]
It would be nice if you can create adapta-qt-theme package, So qt and gtk Apps look more consistent.

As adwaita-qt works fine but i don't like it. Adapta is cool but than my qt apps look alien. i know i can use gtk2 theme on qt apps but that isn't that much appealing!! 

I would suggest you think about it.

https://github.com/MartinBriza/QGnomePlatform

Adwaita-gtk with adwaita-qt

![screenshot from 2017-09-05 14-14-04](https://user-images.githubusercontent.com/24858150/30054138-837c5a40-9244-11e7-8b98-3fd12fb2771e.png)

**Comment by CDrummond** [comment]
Kvantum contains KvAdapta (and the author is working in KvAdaptaDark). Whilst this is not a 100% clone, it is very similar to Adapta.

I have create a pull request #26 against QGnomePlatform to add support for Kvantum themes. If merged, then if a user select Adapta as his Gtk theme, Kvantum will be used with KvAdapta

If a Gtk theme itself provides a Kvantum variant (e.g. /usr/share/themes/Adapta/Kvantum/...) then QGnomePlatform would use this in preference to KvAdapta. So, if Adapta wanted to provided a better Qt experience, you could copy KvAdapta and modify the SVG and config files to provider a more consistent match.

**Comment by tista500** [comment]
Unfortunately I won't do anything with K desktop, so I close this, sorry.
