### ISSUE TITLE
Unable to resize window of noCSD apps on MATE desktop

### ISSUE THREAD

**Issue by atauzki** [adapta-project/adapta-gtk-theme#503]
**Reporter info**

 ```
 * Distribution - Debian 9.1
 * Gtk+ 3.0 version - 3.22.11
 * Desktop environment - MATE 1.16
 * Display server protocol - X11 or Wayland?  X11
 ```

**Adapta version (if you knew)**
3.91.2.136

**Related Application and/or Shell theming (or name of widget)**
the apps that dont use gnome3 style(CSD) like Caja,Pluma,Firefox,mate-terminal

**Actual issue**
apps cannot be resized with mouse from left and right edges,  but they can be resized from bottom and top edges as well as the corners.

**Expected behaviour**
Being able to resize these windows from left and right edges with mouse.

**Other Note (feature-request, question, etc...)**
the bottom border is too big.

**Comment by tista500** [comment]
Marco...

**Comment by tista500** [comment]
Or switch to Metacity please... I hate the 'border-dependent' damned window-managers...

**Comment by atauzki** [comment]
But Metacity can't resize at all

**Comment by atauzki** [comment]
Marco works well for me now.
But MATE with Metacity is even worse,  I cant resize window on non-csd app at all

**Comment by tista500** [comment]
o_O?

Sounds quite strange. Metacity 3.2x X11-based compositor should work on various X11 sessions in both 'gtk-mode' and 'metacity' mode theming. without any visible (ugly) borders like Mutter.

**Comment by atauzki** [comment]
Um.... I'm sorry. I tried Metacity and It's works just now.

**Comment by atauzki** [comment]
I tried Metacity and it works, and It doesn't work on metacity with compton.

**Comment by tista500** [comment]
Compton is the extra compositor for less-featured window-managers like Openbox, Fluxbox and so.

Metacity and Marco (a fork of ancient metacity) have their own compositor without any extra one. And those compositors should work without OpenGL accelerated GPU user-space drivers (Mutter and Compiz are the OpenGL-based compositors instead).

So I have no ideas why compton was needed in such X11 sessions running with Metacity and/or Marco... In Adapta, z-axis (the 'depth' direction) is the part of our design, means we design 'shadows' for Material Design. It means we strongly suggest using proper compositor if bundled with their window-managers officially ( in both X11-based and OpenGL-based).
