### ISSUE TITLE
Dash-to-dock "Unity7 like glossy backlit items" doesn't look right

### ISSUE THREAD

**Issue by PHLAK** [adapta-project/adapta-gtk-theme#506]
The new "Unity7 like glossy backlit items" feature just released in dash-to-dock does not look good. Namely there appears to be a "double" outline (one circular, one rounded box) when an item is active.

![screenshot 2017-09-14 13 57 48](https://user-images.githubusercontent.com/53531/30455625-65c9e55e-9955-11e7-9dce-d5f58d6519d0.png)

**Reporter info**

 ```
 * Distribution - Ubuntu Gnome 17.04
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - Gnome
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

  - 3.91.2.144-0ubuntu1~zesty1

**Related Application and/or Shell theming (or name of widget)**

  - dash-to-dock

**Steps to reproduce (if you knew)**

  1. Install dash-to-dock
  2. Install and enable adapta-eta theme
  3. Enable "Unity7 like glossy backlit items" in dash-to-dock

**Comment by tista500** [comment]
Hard-coded: https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L693

So I never start supporting that feature. And that feature is not suitable for Material Design.

I set this "won't fix", sorry.

**Comment by SavageTiger** [comment]
@PHLAK There is a rectangular svg inside the dash-to-dock extension. how did you manage to get the glossyness rounded?

**Comment by PHLAK** [comment]
@SavageTiger I didn't do anything special, ust enabled the adapta-eta theme and enabled "Unity7 like glossy backlit items" in dash-to-dock
