### ISSUE TITLE
Cinnamon Applet Slingshot is not lined out properly

### ISSUE THREAD

**Issue by MPE2016** [adapta-project/adapta-gtk-theme#508]
* Distribution - Linux Mint 18.3
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Cinnamon 3.4.3.
 * Display server protocol: X11
 * Adapta version: 3.91.2.146

I have Linux Mint and Cinnamon desktop 3.4.3. When I installed the applet called slingshot (an app-launching menu) I noticed that it is not lined out properly. I first filed a bug report with the developers of the app, but we have determined that the issue is probably with the theme I am using which, unsurprisingly, is Adapta. I have installed the theme using the PPA and I receive regular updates. I'll include a picture to demonstrate the problem in more detail. 

![slingshot problem](https://user-images.githubusercontent.com/15818884/30489987-0cd507dc-9a39-11e7-96ea-6dd7337e23c5.png)

Steps you might be able to reproduce:
1) Install Linux Mint
2) add the Adapta PPA.
3) install the theme
4) select Adapta as GTK and desktop.
5) add the slingshot-app to the cinnamon panel.
6) when the app is opened, the right side is not lined out properly.

The expected behavior would be for the app to be lined out properly i.e., the search field should be within the boundaries of the app. See [this link](https://cinnamon-spices.linuxmint.com/applets/view/197) for the desired outcome.

I you have any more questions, feel free to ask, and thanks a million in advance, I really enjoy your work!

MPE

**Comment by tista500** [comment]
o_O?

This happens with Arc/Arc-Dark as well. And we never support *Pantheon-featured* apps except for Plank...
