### ISSUE TITLE
[proposal] change main window text color to black to enhance readability

### ISSUE THREAD

**Issue by Eneen** [adapta-project/adapta-gtk-theme#511]
Similar to Adwaita theme: when windows is not focused text color is slightly blue/grey. When window is focused text is black. This greatly enhances readability especially on small laptop displays.

**Comment by Eneen** [comment]
![adapta_black_font_proposal](https://user-images.githubusercontent.com/25537418/30567870-b296bd3c-9cd2-11e7-9bdc-bed3670ad1a8.png)

**Comment by varlesh** [comment]
@Eneen Please show gnomeshell adapta panel screenshot (with indicators). 
PS: it's need for adapta-kde port, i'm not use Gnome ))

**Comment by varlesh** [comment]
With combination `#7f898e`  and `#00bcd4`   not good looking on  GTK2 apps too:
![image](https://user-images.githubusercontent.com/8083855/30578340-599842a8-9d24-11e7-9d4f-625037ff856e.png)
I know, this color `#7f898e` used on icon theme... But this color from nautilus left sidebar

**Comment by varlesh** [comment]
@tista500 Will be cool use single color for symbolic icons on light background

![image](https://user-images.githubusercontent.com/8083855/30581314-be3ad08e-9d30-11e7-90bb-616b83e566d4.png)
![image](https://user-images.githubusercontent.com/8083855/30581350-dab64d42-9d30-11e7-932d-be4bd6ff0e38.png)

![image](https://user-images.githubusercontent.com/8083855/30581370-ecbbdf66-9d30-11e7-9aea-dd6c2dd5cd08.png)


See all GTK-apps use different color:
- popup menu on gnomeshell panel `#5c6569`
- Settings sidebar (Ubuntu 17.10) `#5a6368`
- Nautilus sidebar `#81898c`

**Comment by Eneen** [comment]
![adapta_colors_for_kde](https://user-images.githubusercontent.com/25537418/30592162-08658d38-9d46-11e7-8df7-f6e57ee48b28.png)
Is it ok? I made shots with subsampling off to be able to easly pick colors.
Will your theme work with Qt5 apps inside GNOME?

**Comment by varlesh** [comment]
> Will your theme work with Qt5 apps inside GNOME?

I don't know... 
@tsujan it's possible use Kvantum on gnome DE for Qt-apps?

**Comment by tsujan** [comment]
> it's possible use Kvantum on gnome DE for Qt-apps?

Oh, yes! Craig (the creator of QtCurve, who doesn't develop QtCurve anymore) has added great codes to Kvantum for that. Not only Kvantum works OK on gnome-shell but also the gnome titlebar can be dark for dark variants (themes with a "Dark" suffix in their names).

However, I can't help you with gnome because I don't have it on the laptop I use. I'd installed it on another computer just for testing the new codes. I even don't remember how I made all Qt apps use Kvantum under gnome-shell (I'm sure it had something to do with GDM). Please tell me if you find an easy way to do so!

**Comment by ceyhunnabiyev** [comment]
It works great on GNOME with setting Kvantum on qt5ct. Thanks to @tsujan .

**Comment by tsujan** [comment]
> It works great on GNOME with setting Kvantum on qt5ct.

There should be a direct way too because I didn't have qt5ct under gnome-shell. I vaguely remember that I edited a root file belonging to GDM, logged out and in, and then, all Qt apps were drawn by Kvantum.

**Comment by Eneen** [comment]
@tsujan: thx, I have to look for this, as qt5ct is not available for artful yet.

**Comment by Eneen** [comment]
@tsujan:
I was thinking about *simple* solution, to just mimic adapta colors using fusion theme to avoid plugin-on-plugin-on-plugin installation (memory and speed wise). I'm lost googling here. Do you know if it's possible to change default color palette for fusion style? Here seems to be tool for this:
https://github.com/spillerrec/QtPalettor
...but when "make" comes I'm done.

**Comment by tsujan** [comment]
> I have to look for this, as qt5ct is not available for artful yet.

@Eneen As soon as I have access to my second computer, I'll see how that could be done. It's about exporting the environment variable `QT_STYLE_OVERRIDE`. Gnome doesn't accept places like `~/.profile`, `~/.bashrc` or `~/.xsessionrc` but I'm sure I found a way.

As for changing fusion's palette, it can't be done without a separate Qt plugin. Qt4 had a utility for that but, for whatever reason, they removed it with Qt5.

**Comment by tista500** [comment]
Stop spreading off-topics. I really dislike Original reporter ignores issue_templete.

Commit: 
https://github.com/adapta-project/adapta-gtk-theme/commit/7464c5ecae71ed317dc197fcd9527c80ce0ef599
