### ISSUE TITLE
Different pressed color on scrollbar GTK2 & GTK3

### ISSUE THREAD

**Issue by varlesh** [adapta-project/adapta-gtk-theme#512]
Ubuntu 16.04 KDE adapra-gtk-theme from official PPA.
Nautilus (GTK3) use  `#263238`:
![image](https://user-images.githubusercontent.com/8083855/30578176-a35449e2-9d23-11e7-99f5-cd1c27327ee3.png)
Inkscape (GTK2) use `#5c656a`:
![image](https://user-images.githubusercontent.com/8083855/30578200-be5ca626-9d23-11e7-9709-8d80546012b2.png)

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/commit/7464c5ecae71ed317dc197fcd9527c80ce0ef599
