### ISSUE TITLE
[proposal] Use Hack font instead of Noto Mono as monospace font

### ISSUE THREAD

**Issue by Eneen** [adapta-project/adapta-gtk-theme#513]
http://sourcefoundry.org/hack/
This font is IMO really nice, take a look. It's available as package for Ubuntu: fonts-hack

**Comment by tista500** [comment]
No I won't, sorry.

**Comment by ArchangeGabriel** [comment]
Note that Hack was made popular by KDE because they needed a good monospace font to go along with Noto, because this last one lacked a (widely packaged) monospace variant. So if Noto Mono is available, there is not necessarily a reason to use Hack.

That being said, you can change the font, right?
