### ISSUE TITLE
PGP public key for PPA missing?

### ISSUE THREAD

**Issue by Kspaeth93** [adapta-project/adapta-gtk-theme#514]
**Reporter info**

 ```
 * Distribution - Debian 9.1
 * Gtk+ 3.0 Version - Version 3.22.11-1
 * Desktop Environment - GNOME 3
 ```

**Adapta version (if you knew)**

Not Installed Yet

**Related Application and/or Shell theming (or name of widget)**

PGP

**Actual issue**

No gpg pubkey was added when adding the ppa.

**Steps to reproduce (if you knew)**

sudo apt-add-repository ppa:tista/adapta -y

**Expected behaviour**

Either have a gpg pubkey to manually add to my keyring, or had it added when adding the ppa.

**Other Note (feature-request, question, etc...)**

Essentially the same as https://github.com/adapta-project/adapta-gtk-theme/issues/366.

I did, however, run the following code.

`sudo rm -f /etc/apt/sources.list.d/tista-ubuntu-adapta-xenial.list`
`sudo rm -f /etc/apt/trusted.gpg.d/tista_ubuntu_adapta.gpg`
`sudo apt update`
`sudo add-apt-repository ppa:tista/adapta -y`

The output of reinstalling the PPA that you were looking for is shown below.

`gpg: keybox '/tmp/tmpgmgrfc4w/pubring.gpg' created`
`gpg: /tmp/tmpgmgrfc4w/trustdb.gpg: trustdb created`
`gpg: key B76E53652D87398A: public key "Launchpad PPA for tista" imported`
`gpg: Total number processed: 1`
`gpg:               imported: 1`
`gpg: no valid OpenPGP data found.`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python3.5/threading.py", line 862, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in` `addkey_func`
`    func(**kwargs)`
`  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key`
`    return apsk.add_ppa_signing_key()`
`  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key`
`    cleanup(tmp_keyring_dir)`
`  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup`
`    shutil.rmtree(tmp_keyring_dir)`
`  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree`
`    _rmtree_safe_fd(fd, path, onerror)`
`  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd`
`    onerror(os.unlink, fullname, sys.exc_info())`
`  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd`
`    os.unlink(name, dir_fd=topfd)`
`FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'`

**Comment by tista500** [comment]
Are really search the ubuntu keyserver?

run: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EAC0D406E5D79A82ADEEDFDFB76E53652D87398A`

**Comment by Kspaeth93** [comment]
Hey, thanks for the quick response. After seeing your comment I did some research and learned that PPA are designed for Ubuntu and can be used on Debian but it seems.. hacky. I didn't realize that, so I apologize for reporting this issue. I'm going to go ahead and follow the instructions to install from the repository. I'll reach out to you if I have any more questions.
