### ISSUE TITLE
[proposal] GDM theme?

### ISSUE THREAD

**Issue by Eneen** [adapta-project/adapta-gtk-theme#515]
Ok, under Ubuntu there is way to revert back to vanilla theme:
https://didrocks.fr/2017/09/11/ubuntu-gnome-shell-in-artful-day-11/
Maybe this way it's possible to add Adapta too?

**Comment by Eneen** [comment]
Further reading:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1715722

**Comment by tista500** [comment]
We've already bundled GDM specific CSSs, then register them by yourself manually via `update-alternatives`.

I dislike the canonical changes though.

**Comment by Eneen** [comment]
Thanx!
In case anyone was looking for how to install manually Adapta for GDM3:
`sudo update-alternatives --install /usr/share/gnome-shell/theme/gdm3.css gdm3.css /usr/share/themes/Adapta-Eta/gnome-shell/gdm3-Adapta-Eta.css 1`
