### ISSUE TITLE
Top bar too translucent for bright backgrounds

### ISSUE THREAD

**Issue by Eneen** [adapta-project/adapta-gtk-theme#516]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10 Artful Ardvark
 * Gtk+ 3.0 version - 3.22.21
 * Desktop environment - GNOME Shell
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
Current screenshot from Adapta 3.91.2.169

**Related Application and/or Shell theming (or name of widget)**
Adapta-Eta

**Actual issue**
Top-bar too translucent for bright backgrounds

**Steps to reproduce (if you knew)**
Set bright background.

**Expected behaviour**
Top bar should be little less translucent to enhance readability

**Other Note (feature-request, question, etc...)**

On screenshot: left - Adwaita, right - Adapta
![adapta_bar_too_translucent](https://user-images.githubusercontent.com/25537418/30664413-eaf419be-9e4d-11e7-88ee-d2f5219958f8.png)

**Comment by tista500** [comment]
Currently we neither support bright wallpapers nor employ translucent TopBar...

Won't fix, sorry.

**Comment by Eneen** [comment]
Oh... that's bad. Hasn't translucent top bar been introduced with GNOME Shell 3.26?
Anyway, extreme config screenshot:
![adapta_bar_too_translucent2](https://user-images.githubusercontent.com/25537418/30665717-41b3a388-9e52-11e7-84bf-90de2ff6546e.png)

**Comment by Eneen** [comment]
Ok, I've got it.
New dynamic transparency seems to use lock/unlock/login screen background so changing:
`#panel.unlock-screen, #panel.login-screen, #panel.lock-screen { background-color: rgba(19, 25, 28, 0.01);`
to
`#panel.unlock-screen, #panel.login-screen, #panel.lock-screen { background-color: rgba(19, 25, 28, **0.51**);`
made this:
![adapta_panel_transparency_051](https://user-images.githubusercontent.com/25537418/30671604-27ea4cfc-9e68-11e7-8c8d-0bdf7841eae1.png)
Hope it's useful.
