### ISSUE TITLE
white shadow on top of windows in Xfce

### ISSUE THREAD

**Issue by Allen-B1** [adapta-project/adapta-gtk-theme#517]
**Reporter info**

 ```
 * Distribution - Xubuntu (on virtualbox)
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Xfce
 * Display server protocol - X11 or Wayland? X11 I think
 ```
**Related Application and/or Shell theming (or name of widget)**  
Title Bar? I don't know. In `Gtk.HeaderBar`, there's no problem

**Actual issue**  
In Xfce, the top of the windows have a white shadow

**Steps to reproduce (if you knew)**
1. Install Adapta Theme 
2. Apply it
3. Restart computer

**Expected behaviour**  
The top of the windows will have weird white shadows

**Comment by tista500** [comment]
Screenshot, please.

**Comment by tista500** [comment]
No response. Close this.
