### ISSUE TITLE
How to install locally?

### ISSUE THREAD

**Issue by captainraccoon2** [adapta-project/adapta-gtk-theme#518]
Hi, 

I really like this theme. However I do not wish to use it by the following steps on the home page. I would like to use it without root access by placing it in my home folder in ~/.themes. How can I do this after downloading the master file from the git page?

**Comment by ceyhunnabiyev** [comment]
Hi @captainraccoon2 , use autogen.sh with  ` --prefix ` option. Default is `/usr`.

**Comment by tista500** [comment]
Already answered.
