### ISSUE TITLE
Did Adapta-nokto just get darker? Or did I mess something up?

### ISSUE THREAD

**Issue by cj-sv** [adapta-project/adapta-gtk-theme#519]
* Ubuntu GNOME
 * Gtk+ 3.22
 * GNOME Shell
 * X11
 * Adapta-gtk-theme 3.91.2.189-0ubuntu1~zesty1

![image](https://user-images.githubusercontent.com/11567756/30794978-dea47c40-a1fd-11e7-9eef-d7533230333b.png)

Didn't notice when I updated but It happened after I installed the [Ant GTK Theme](https://github.com/EliverLara/Ant) and switched back.

**Comment by tista500** [comment]
No, we didn't.

**Comment by cj-sv** [comment]
Bummer, I also noticed my other installed themes have gotten darker as well. I have no idea what may have caused this. Can't find any info elsewhere.

**Comment by cj-sv** [comment]
I found the culprit. It was a buggy Mesa update. I noticed when I found Wayland session missing.
