### ISSUE TITLE
New folder button

### ISSUE THREAD

**Issue by meetdilip** [adapta-project/adapta-gtk-theme#520]
**Reporter info**

 ```
 * Distribution - 16.04 Ubuntu
 * Gtk+ 3.0 version - 3.20.8-1ubuntu0~ppa1 / 2.24.30-4ubuntu1~ubuntu16.04.1 
 * Desktop environment - Unity in 16.04
 * Display server protocol - X11 or Wayland? No idea
 ```

**Adapta version (if you knew)** How to find out ?

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Is it possible to add a " New Folder " button as in Windows ? Thanks.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

Feature request

**Comment by tista500** [comment]
I can't get the point of this report. What is the 'New Folder Button"? o_O?

**Comment by meetdilip** [comment]
@tista500 , a button like this which can create a new folder in the current directory

![new folder](https://user-images.githubusercontent.com/6965443/30849799-208488b2-a2c1-11e7-8f52-70e2043d7b24.png)

**Comment by tista500** [comment]
o_O?

Why were you asking me to "enhance the UI of FileManagers"? I'm not a developer of that FileManager... Or was there a theme specific issue that Adapta made that button invisible? At least I've never seen such GtkHeaderBar button in Nautilus.

I don't have any ideas why this report was sent to us.

**Comment by meetdilip** [comment]
I thought it was something you can fix. Since there was a ctrl + L alternative available with the theme.

**Comment by tista500** [comment]
> Since there was a ctrl + L alternative available with the theme.

o_O? The shortcut *Ctrl+L* is usually used as "a trigger to switch (toggle) path-bar entry on/off" in Nautilus. So I don't have any clue why that shortcut was related to user themes because shortcuts are defined by those applications (and by Gtk+ as globally).

Could you please clarify your report?

**Comment by meetdilip** [comment]
I thought it was part of the theme. I use Adapta all the time. And, when I noticed the option " Enter Location ", I thought it came through the theme. Looks like " Ambiance " has it as well. My mistake. Sorry.

**Comment by tista500** [comment]
OK. Closed.
