### ISSUE TITLE
[Question] Close titlebar button does not showing in a few dialog boxes.

### ISSUE THREAD

**Issue by chuutatsu** [adapta-project/adapta-gtk-theme#522]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Mate 1.19
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.91.2

**Actual issue**
![screenshot at 2017-09-29 14-32-45](https://user-images.githubusercontent.com/24815847/31005533-4fdea534-a523-11e7-9539-27fe6ddc54e3.png)

When using other themes (such as Arc and Vimix), the close (x) titlebar buttons display properly. In Adapta it does not shown.

![screenshot at 2017-09-28 20-47-32](https://user-images.githubusercontent.com/24815847/31005406-c0b2c1f6-a522-11e7-98aa-ff3234a7c2f4.png)
_(as seen in Adapta theme)_

**Question**
Is this the feature of Adapta's window manager theme? 

Just asking.

**Steps to reproduce**
Open any sub-dialog boxes of applications.

**Comment by tista500** [comment]
> Is this the feature of Adapta's window manager theme?

Hmm, maybe not. This might be the metacity-2 theming issue... :(

**Comment by chuutatsu** [comment]
Will you able to repair it? Or it was really Metacity/Marco problem?

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/a93b658a02ae2264f9453561804fe863d68a1813

**Comment by chuutatsu** [comment]
Alright, thank you for fixing it. I'll try to update Adapta now.

**Comment by tista500** [comment]
Commit for older Metacity: https://github.com/adapta-project/adapta-gtk-theme/commit/0ca8241140372f55079146a73ecf7777d326ffd9

**Comment by 0xicl33n** [comment]
@chuutatsu what is that program youre using to customize the theme? does it come with adapta? Sorry for necro
