### ISSUE TITLE
Difficult find active Windows caused by same title bar color

### ISSUE THREAD

**Issue by NothingCtrl** [adapta-project/adapta-gtk-theme#523]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment -
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Adapta theme with option dark color.
When I have multiple windows open, is very hard to discern them, to find which one is active windows, they have similar color, tiny shadow effect.
![screenshot from 2017-09-29 15-07-01](https://user-images.githubusercontent.com/5380820/31006969-14a6f362-a529-11e7-81ed-1e0c6ee8d45a.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
Should easy to discern them, like brighten title bar color?

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> like brighten title bar color?

No, I won't. I may or may not re-open this if I changed my mind... But currently I won't tweak anything.

Closed.
