### ISSUE TITLE
How to add border for menuitem

### ISSUE THREAD

**Issue by SeptemberHX** [adapta-project/adapta-gtk-theme#525]
There is no shadow for menuitem with gtk theme in KDE, so I need border.

![image](https://user-images.githubusercontent.com/18042424/31062982-897eb5be-a761-11e7-8092-dffa775985aa.png)

Just like the screenshot above. I can't recognize the border. And it will be worse if the main window's color is white:

![image](https://user-images.githubusercontent.com/18042424/31063015-f94b4e3e-a761-11e7-802e-28fdd76ab1d9.png)

It's right-click menu in above picture.

So is there a way to add border for it ?

**Comment by tista500** [comment]
Oh please... It's not our issue but your window-manager(s) and/or Gtk+ backends... :(

**Comment by tista500** [comment]
No sense commit for Gtk+ 2.0: https://github.com/adapta-project/adapta-gtk-theme/commit/e71a7c8b763eea623ff9f10542a5ed72b0506a5b

And we don't support Gtk+ 3.x theming in such damned K desktop.
