### ISSUE TITLE
Firefox window title offset after using Activities overview

### ISSUE THREAD

**Issue by pmargeti34** [adapta-project/adapta-gtk-theme#527]
```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.24-1
 * Desktop environment - Gnome-shell 3.26.1-1
 * Display server protocol - X11 or Wayland? Wayland (same issue present in X11)
 ```

**Adapta version (if you knew)**
3.91.2.220.r2.e1dfbc5c-1

**Related Application and/or Shell theming (or name of widget)**
Firefox

**Actual issue**
Window title is offset down and to the right

**Steps to reproduce (if you knew)**
Maximize Firefox.
Launch another application.
Use Activities overview few times in a row selecting other running application (so that Firefox is not in foreground)
Observe firefox window title glitch

**Expected behaviour**
Window title doesn't offset

**Other Note (feature-request, question, etc...)**
Including screenshot. Issue started appearing with 3.26.1 mutter / gnome-shell update. Affects Firefox, Firefox-nightly and possibly others in the same family.

![screenshot from 2017-10-06 13-02-17](https://user-images.githubusercontent.com/13254332/31275554-01adcdf2-aa98-11e7-9b74-22c1a879abe0.png)

**Comment by ikeydoherty** [comment]
Confirmed on Solus unstable - happening with all non-CSD windows (Firefox, Telegram, etc). Only appears to happen when the window no longer has active focus.

**Comment by ikeydoherty** [comment]
Further, this appears to be causing random segfaults in Mutter 3.24:

```
Oct 06 14:29:36 ironhide gnome-session[805]: gnome-session-binary[805]: WARNING: Application 'budgie-wm.desktop' killed by signal 6
```

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/35f4fd54f4d93c9194583ab9678fe16c679b7978

That commit may fix this issue...

**Comment by ikeydoherty** [comment]
Doing local build here now cheers :]

**Comment by ikeydoherty** [comment]
That seems to have done the trick!

**Comment by ikeydoherty** [comment]
Thanks for the fast workaround @tista500 - I'll stick 220 + patch into Solus repos (I would've happily rolled back to older version, just so yknow, no pressure, etc. :D)

**Comment by pmargeti34** [comment]
@tista500 best theme made by the best dev. Thanks @ikeydoherty for confirmation and further diagnosis of the problem.

**Comment by ikeydoherty** [comment]
> Yeah I frequently encounter "1 step forward, 2 steps backward"... ;)

Story of my life :D I'll bump us to the properly released tag
