### ISSUE TITLE
Is it possible to create "child" theme?

### ISSUE THREAD

**Issue by sangdth** [adapta-project/adapta-gtk-theme#528]
I love this theme, it works great on my ubuntu machine. Btw, I have some modifications on it, and it's gone everytime the theme updated. Do we have anyway to keep my modifications and still get update?

**Comment by tista500** [comment]
Unfortunately we clean up our theme directories while installing/updating, so no, sorry.

I set this 'Won't fix".

**Comment by georgelemental** [comment]
@sangdth You can always fork the theme repository, commit your modifications, and keep your fork up to date by running `git pull https://github.com/adapta-project/adapta-gtk-theme.git -s recursive -Xtheirs` regularly.

**Comment by sangdth** [comment]
@georgelemental  Thank you for suggestion.
