### ISSUE TITLE
Window manager not being themed

### ISSUE THREAD

**Issue by fredefox** [adapta-project/adapta-gtk-theme#529]
**Reporter info**

 * Distribution
Ubuntu 17.10 Artful

 * Gtk+ 3.0 version
3.22.21-0ubu

 * Desktop environment
Gnome

 * Display server protocol
Wayland

**Adapta version (if you knew)**
3.91.2.228-0ubuntu1~artful1 from the Ubuntu ppa

**Actual issue**
The window manager (mutter) is not being themed. It's still using the Adwaita default theme. This issue is the same for some other themes I've tried. What could be the issue of this? I've googled around to no avail.

The rest of the UI elements are changed though like dialog boxes, the dock...

I thought it might've been an issue with other shell extensions that I've installed but disabling them doesn't fix it. I'm currently running: Pixel saver, Ubutnu appinidactors, Ubuntu dock and the user themes requires extension.

**Comment by tista500** [comment]
I don't have such issue while switching user-themes on my proposed-Artful.

> It's still using the Adwaita default theme. This issue is the same for some other themes I've tried. 

I don't think this report is an Adapta specific issue.

>  What could be the issue of this? 

I don't know and then I could not help you at all, sorry. Closed.
