### ISSUE TITLE
The GTK3 Theme doesn't work on KDE5

### ISSUE THREAD

**Issue by Warmuser** [adapta-project/adapta-gtk-theme#533]
I tried to install manually these theme into the default folder on KDE5 but nothing happen. The GTK window setting doesn't recognize the Adapta GTK Theme on Fedora 26. But on Antergos 17 it works perfectly.

Fedora 26 (with the latest updates)

![adapta gtk compatibility](https://user-images.githubusercontent.com/19243318/31434751-89cd8806-ae7d-11e7-97ea-ec20393aaddc.png)

Antergos 17 (with the latest updates)

![adapta gtk compatibility2](https://user-images.githubusercontent.com/19243318/31435851-469ef9e4-ae81-11e7-9f3b-a35c4f50caef.png)

**Comment by tista500** [comment]
We don't support K desktop officially, And please stop ignoring issue-templete, or I will block you next time...

Won't fix, closed.

**Comment by Warmuser** [comment]
KDE5 support also GTK2 and GTK3 themes in its settings. And I tried to install the theme for the GTK2/GTK3 applications. So, I don't know why you become angry with me. My porpouse was to report the problem. Ok, don't worry I will never disturb you again. Bye!

**Comment by Lonsfor** [comment]
@Warmuser try https://git.io/adapta-kde

**Comment by Warmuser** [comment]
@Lonsfor thanks! :)
