### ISSUE TITLE
[Help] Standard Fonts

### ISSUE THREAD

**Issue by btd1337** [adapta-project/adapta-gtk-theme#534]
Devs,

What is the recommended fonts for Gnome 3.26?

![screenshot from 2017-10-12 22-55-59](https://user-images.githubusercontent.com/11943860/31526994-d917d49c-afa0-11e7-8862-b19a4fc165f9.png)

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme#typography

Roboto.

**Comment by btd1337** [comment]
This I read,

Should only Roboto be used for all options? No variation?

**Comment by tista500** [comment]
Window Title: Roboto Bold
Interface: Roboto Regular
Documents: we don't care
Monospace: we don't care
