### ISSUE TITLE
Top bar style

### ISSUE THREAD

**Issue by ThibaudJeannin** [adapta-project/adapta-gtk-theme#536]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version -  3.26
 * Desktop environment - Gnome shell 3.26.1
 * Display server protocol - X11
 ```

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
![screenshot from 2017-10-15 23-19-51](https://user-images.githubusercontent.com/19266468/31589427-7accb0c0-b201-11e7-8099-50b81ad21438.png)

**Expected behaviour**
The top bar should be solid, not gradient, and black, instead of the default ubuntu color.

**Other Note (feature-request, question, etc...)**
Thank you for making my Gnome Desktop look nice everyday

**Comment by tista500** [comment]
o_O?

**Comment by tista500** [comment]
Ah, use 'Gnome' or 'Gnome on Xorg' session instead.
Canonical heavily patched to 'Ubuntu/Ubuntu on Xorg' sessions, then those changes will override user-themes.

We won't support damned downstream (Canonical) changes.

**Comment by SolarLiner** [comment]
FYI the vanilla Gnome session isn't available by default on 17.10. Install `gnome-session` and restart.

**Comment by hAtul89** [comment]
How did you resolve this?

**Comment by SolarLiner** [comment]
@hAtul89 install `gnome-session` package with apt and reboot. Now, after clicking on your username, click on the gear to select "GNOME" or "GNOME on Xorg" depending on the graphical technology you want to use (Xorg is the currently widely used technology, and the other one is Wayland). This will get you to the unaffected GNOME shell, that you can theme.
