### ISSUE TITLE
Modified web widgets destroy the site layout

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#537]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.21
 * Desktop environment - Gnome 3.26.1
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.91.2-2.201710xxxxxxxx

**Related Application and/or Shell theming (or name of widget)**
 * Firefox 57.0b7

**Actual issue**
As you see in the screenshot below, Adapta enlarges the buttons of the website – which leads to a corrupted layout. Normally, the − and + signs are on either side of the counter.

**Expected behaviour**
No modification, at least not with respect to the size of the widgets.

**Other Note (feature-request, question, etc...)**
I don’t think that it is actual reasonable to modify web widgets at all…

![bildschirmfoto von 2017-10-16 00-19-02](https://user-images.githubusercontent.com/10520767/31590109-40c177c6-b20b-11e7-89e8-5e8479c596a3.png)

**Comment by tista500** [comment]
Shot with Adwaita please.

**Comment by tista500** [comment]
And a link to reproduce as well, please...

**Comment by tista500** [comment]
No need to report any extra info now. Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/0b5c06c2a3fad0c5dce74b5ee598638805db1f44

This would bring the similar button/entry spacing with Adwaita maybe...
