### ISSUE TITLE
[Firefox Quantum] Widget space

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#538]
```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.21
 * Desktop environment - Gnome 3.26.1
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.91.2-2.201710xxxx

**Related Application and/or Shell theming (or name of widget)**
Firefox Quantum 57.0

Sorry to bother you again. With #537 you trimmed the space of the widgets to the minimum, ok. But now the widgets look a bit squeezed… like KDE. I know it is hard to find _the_ correct size, but what do you think about a bit more padding for making it looking less squeezed (at least for the non-Eta versions of Adapta)? Maybe half in between the state of now and pre-#537 could be a good compromise?

![bildschirmfoto von 2017-10-19 19-20-25](https://user-images.githubusercontent.com/10520767/31796524-3a491788-b52a-11e7-9a50-b4301c7b31d2.png)

**Comment by tista500** [comment]
I may or may not do later.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/c79fc7e351e80f753fac8dfde0230349a0f69463
