### ISSUE TITLE
gnome-shell become transpartent with customer autogen

### ISSUE THREAD

**Issue by terroreek** [adapta-project/adapta-gtk-theme#539]
```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.24-0ubuntu1
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
latest from git as of October 22nd 21:46 EST

**Related Application and/or Shell theming (or name of widget)**
Any GTK them with any of the Adapta Gnome Shell themes

**Actual issue**
If the no windows touch the 'shell bar', like full screen or just touching the edge of the shell, the shell bar becomes transparent.  Using ./autogen.sh with the default colors I have no issue.  If I copy the theme to Debian Sid no issues with gnome shell.  My guess is its because of wayland.

**Steps to reproduce (if you knew)**
When building the latest theme after with this custom autogen

./autogen.sh --with-selection_color=#AA0000 --with-second_selection_color=#801414 --with-accent_color=#8E1515 --with-suggestion_color=#C40000

**Expected behaviour**

Shell should remain black, but is transparent.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O?

Since Gnome-Shell-3.26, we've switched to Dynamic-mode TopBar design.

> Shell should remain black, but is transparent.

Disagreed. Rest-mode should be complete transparent currently of our design... Or use some extensions to handle TopBar appearances.

**Comment by tista500** [comment]
> https://github.com/rockon999/dynamic-panel-transparency

**Comment by terroreek** [comment]
Ah ok so I didn't know that, thank you for clarification, I am not sure if I just wasn't patient, but I rebuilt the theme without my colour customization and sure enough it works just as you said sorry.  Great theme and thank you.
