### ISSUE TITLE
[Question] How do I customize font for gnome-panel?  

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#541]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Gnome 3.26
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.91.2.247

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Customizing font in Gnome Tweak Tool doesn't change gnome panel font. Font-size is too small in gnome-panel. How do I customize this?
 

**Steps to reproduce (if you knew)**
Select any font in Gnome Tweak tool, and then look at the gnome panel

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Font-size is too small in gnome-panel. 

o_O?

Gnome-Panel in XWayland session!? You mean Gnome-Panel runs inside the Weston or other native Wayland compositors?
https://git.gnome.org/browse/gnome-panel/
In X11 session, font-family and size of Gnome-Panel should be handled via Gnome Tweaks because gnome-panel is natively built with Gtk+.

> Customizing font in Gnome Tweak Tool doesn't change gnome panel font.

Meant Gnome-Shell?
https://git.gnome.org/browse/gnome-shell/
If so, there's no user themes can handle font-families and size via Gnome Tweaks. Please check and see Googling before posting here...

Totally I can't get the point of this report.

**Comment by ceyhunnabiyev** [comment]
It doesn't matter, it is on  Wayland or on Xorg.

> Meant Gnome-Shell?

Yes.

I just ask a question. Is there any method to increase gnome-shell font size or to change font family? You see on the following picture, Gnome-Shell  Font differs from Gnome Tweaks.  
Screenshot:
![screenshot from 2017-10-29 17-15-09](https://user-images.githubusercontent.com/5506156/32144112-3c87d8ea-bccd-11e7-94c9-e425df868756.png)

**Comment by tista500** [comment]
> Is there any method to increase gnome-shell font size or to change font family? 

Hey, hey, it is NOT the theme specific issue at all, then why didn't you try to search it via Google before posting here? There's ton of articles to explain how to edit the gnome-shell theme font settings... :/

> It doesn't matter, it is on Wayland or on Xorg.

I never ask you to clarify whether you run Gnome-Shell on X11 or on Wayland. The term "Gnome-Panel" means the panel app in Gnome-Flashback X11 session. So I asked "Gnome-Panel in Westion?". If true, I need to run gnome-panel inside Weston to verify our Gtk+ theming was functional normally even if Weston XWayland mode.

Please stop taking our precious time, please.

**Comment by tista500** [comment]
Go back to 10pt and use font-scaling factor `1.1` instead.

**Comment by ceyhunnabiyev** [comment]
Nice, thank you, and sorry for wasting your time.
