### ISSUE TITLE
Weird  Toggle  View on Gnome Tweak Tool

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#542]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.92.1.29

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
I updated Adapta package version to 3.92.1.29 in Manjaro. I saw weird  toggle view on  Gnome Tweak Tool. It only occurs in Adapta, not  in another theme:
![screenshot-20171029141559-1364x215](https://user-images.githubusercontent.com/5506156/32146673-5e24f736-bcf4-11e7-8acb-9bf934ccad97.png)

**Steps to reproduce (if you knew)**
Open Gnome Tweak Tool Extensions Part. You will see Disable Extensions Toggle Button.

**Expected behaviour**
![screenshot-20171029220148-1365x222](https://user-images.githubusercontent.com/5506156/32146694-cd7796d4-bcf4-11e7-95c5-33b3d38849c1.png)

**Other Note (feature-request, question, etc...)**
This issue occurs on both Gnome Xorg and Wayland.

**Comment by tista500** [comment]
Fixed in Rev.33 already.
