### ISSUE TITLE
Radio box and check box html elements in Firefox misaligned

### ISSUE THREAD

**Issue by pmargeti34** [adapta-project/adapta-gtk-theme#543]
```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.22.25-1
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland?Wayland
 ```

**Adapta version (if you knew)**
3.92.1.39-1

**Related Application and/or Shell theming (or name of widget)**
Firefox radio box and checkbox elements

**Actual issue**
Firefox radio box and checkbox elements are misaligned with their text. Seems like there is excessive padding around them too.

**Steps to reproduce (if you knew)**
View any page with html radio/checkbox elements

**Expected behaviour**
These html elements are displayed in same line with their text and without extra padding

**Other Note (feature-request, question, etc...)**
Including screenshot
![screenshot from 2017-10-29 23-15-09](https://user-images.githubusercontent.com/13254332/32149070-ae87ee62-bcff-11e7-9cf6-6c124515015a.png)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/2c83d85d82ccf20f2f0ab9177869b9b4085788bf

But I don't know whether that commit worked or not. Anyway I'm not the Firefox user and then I'm really sick with that browser... So I will not do re-tracking this in future.

**Comment by pmargeti34** [comment]
Commit aligns bottom of html controls and text, it's better than before. So if I understand you correctly, you have no plans of supporting adapta on firefox?
