### ISSUE TITLE
Using the font, the DM specifies for applications to use

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#544]
With Roboto, there is the issue, that the glyphs are placed too tight next to each other, so that the readability is decreased (especially on small screens).

Would it therefore be possible to use the system font for programs, specified in gnome-tweak-tool?

**Comment by tista500** [comment]
Fuzzy report title, lack of DE info, how could I answer to this report?
"System font" is not the name of actual font you've set.

> especially on small screens

What that mean? I usually check the font rendering on my ThinkPad-8 8" 1080p screen and ThinkPad-10 10" 1080p screen. Then I don't think letter spacing was too tight with 10.5pt Roboto Regular. I think this is personal esthetics and/or eyesight instead. For me, other font families are wasting horizontal spacing too much.

> Would it therefore be possible to use the system font for programs, specified in gnome-tweak-tool?

o_O? Gnome-Shell?

**Comment by tista500** [comment]
>  1080p screen

Incorrect, means 1920 x 1200.

**Comment by fbruetting** [comment]
Sorry, in Gnome Shell (3.26) I can specify the font applications should use via gnome-tweak-tool – this is what I meant.

Following is an example. But maybe the decreased readabiliy is due to Roboto being scaled somewhat down, compared to Cantarell. You see this best in the middle of my attached picture. „Anwendungen“ on the far left is not thaaat easy readable without me knowing à priori what the word is, or moving my head somewhat nearer to the screen – and for older poeple this surely is even worse.

![bildschirmfoto von 2017-11-02 02-57-33](https://user-images.githubusercontent.com/10520767/32306070-a136b668-bf79-11e7-939d-697c3705cc8e.png)

**Comment by tista500** [comment]
> Gnome Shell (3.26) I can specify the font applications should use via gnome-tweak-tool – this is what I meant.

No, can't. There's no Gnome-Shell user-themes can handle the font-families and size via Gnome Tweaks. I'm really tired to answer that again and again... We can just tweak the `font-scaling-factor` only.

**Comment by fbruetting** [comment]
Not sure if I understand you correctly. But I thought you might extract that font:

![bildschirmfoto von 2017-11-02 03-23-23](https://user-images.githubusercontent.com/10520767/32306747-7f022ede-bf7d-11e7-9ab8-27ffe4420ab8.png)

**Comment by tista500** [comment]
Oh please... :/
`Gnome Tweaks -> Fonts -> Interface` handles font-families and absolute size for Gtk+ widget's interface instead of Gnome-Shell...

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/issues/541
