### ISSUE TITLE
'gnome-shell' not found when running ./autogen.sh

### ISSUE THREAD

**Issue by astralspurs** [adapta-project/adapta-gtk-theme#545]
**Reporter info**

 ```
 * Distribution - Debian 9 Stretch
 * Gtk+ 3.0 version - 3.22.24-3
 * Desktop environment - XFCE 4.12.3
 * Display server protocol - X11 or Wayland? X11 I think
 ```

**Adapta version (if you knew)**
Latest version as of Nov 1, 2017

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
When running ./autogen.sh command, gnome-shell isn't found even though I do not call --enable-gnome at any point.

> $ sudo ./autogen.sh
/+ ./configure --prefix=/usr --disable-gtk_legacy --disable-gtk_next --disable-parallel --disable-chrome --disable-plank --disable-telegram
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GDK_PIXBUF... yes
checking for GLIB... yes
checking for sassc... /usr/bin/sassc
checking for inkscape... /usr/bin/inkscape
checking for glib-compile-resources... /usr/bin/glib-compile-resources
checking for gnome-shell... no
configure: error: 'gnome-shell' not found.

**Steps to reproduce (if you knew)**
Just by running the first command from step 3 of the readme

**Expected behaviour**
I expect the autogen.sh script to complete successfully so that I have a make file i can call in the next command.

**Other Note (feature-request, question, etc...)**
I've compiled Adapta before on another computer and I do not recall having any problems. Hopefully I'm not missing anything too obvious and that I'm posting in the right spot. I appreciate your time. All the best.

**Comment by tista500** [comment]
Please read the README.md:
> To disable some DE supports, pass these specific options to autogen.sh:

DE support was enabled by default. so turn off them via by `--disable-` options.
