### ISSUE TITLE
[Lollypop] Not enough bottom padding in context menu

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#546]
**Reporter info**

 ```
 * Distribution - Fedora 27b
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Gnome 3.26.1
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.91.2-2.201711011520

**Related Application and/or Shell theming (or name of widget)**
Lollypop

**Actual issue**
The bottom padding of the context menu is too small. But it also seems, that the stars and the heart is somewhat displaced to the bottom, because the space above these icons seems too large (but this may be wrong).

![bildschirmfoto von 2017-11-03 20-03-53](https://user-images.githubusercontent.com/10520767/32391514-abeaa678-c0d2-11e7-8e03-acfbc977b023.png)

![bildschirmfoto von 2017-11-03 20-08-24](https://user-images.githubusercontent.com/10520767/32391545-c73f944c-c0d2-11e7-9591-90fcbd8c5bae.png)

**Steps to reproduce (if you knew)**
It’s just Lollypop via Flatpak and Adapta installed on both the system and via Flatpak.

**Expected behaviour**
Some padding at the bottom of the context menu, corresponding to the other borders.

**Comment by tista500** [comment]
Lollypop...

> Not enough bottom padding in context menu

This isn't the GtkMenu 'context-menu' but GtkPopover widget.

> It’s just Lollypop via Flatpak and Adapta installed on both the system and via Flatpak.

So let me know the steps to reproduce to open that GtkPopover.

**Comment by fbruetting** [comment]
I just right-clicked on an item of one of my albums…?

**Comment by tista500** [comment]
I can neither read any info from your "localized" shots nor a lollypop user.

This? : https://github.com/gnumdk/lollypop/blob/master/lollypop/pop_menu.py#L449

**Comment by fbruetting** [comment]
Oh, I thought that the problem lies within GTK popovers in general. I even can’t start it in English via `LANG=en_US.UTF8 flatpak run org.gnome.Lollypop`… O_o

But yes, this menu is a combination: In the upper part there are `QueueMenu`, `PlaylistsMenu` and `EditMenu` and below is TrackMenuPopover.

**Comment by tista500** [comment]
I don't think this does work: https://github.com/gnumdk/lollypop/blob/master/lollypop/pop_menu.py#L497

For me, totally useless...

**Comment by fbruetting** [comment]
That’s what I thought, too…

**Comment by tista500** [comment]
See the red area of this shot with Adwaita:
![32391514-abeaa678-c0d2-11e7-8e03-acfbc977b023_2](https://user-images.githubusercontent.com/6073622/32401603-941c8a42-c155-11e7-93bc-77ef98461c59.png)

Adwaita has 6px standard GtkPopover padding (hard-coded by Gtk+ itself) + extra 6px padding in the child GtkStack (I suppose you'd enabled 2.0 window-scaling-factor when taking that shot, so 24px in your case). On the other hand, Adapta subtracts 6px GtkStack padding.


My fig means Lollypop's weird 'ratings' and 'heart' seems to overhang the GtkStack region (red area). At least I don't think this issue was theme specific.

**Comment by fbruetting** [comment]
@gnumdk Is this related to your [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=774148)? But I don’t see any differences between Xorg and Wayland (at least now, after Tista’s patch).

**Comment by gnumdk** [comment]
No it may be related to this hack https://github.com/gnumdk/lollypop/blob/master/lollypop/pop_menu.py#L480

I need to port this to Gtk.PopoverMenu...

But no @tista500 "rattings" and "heart" are not overhanging with GtkStack:
|_ Gtk.Grid
   |_  Gtk.Stack
   |_  Gtk.Grid
       |_ RatingWidget
       |_ LoveWidget

And I don't know where you found this red area but Gtk Inspector does not show this.

**Comment by gnumdk** [comment]
And yes the 5 px margin is need, it should be on Gtk.Grid but it is needed because Adwaita is missing bottom margin otherwise (due to the hack used to insert widgets in menu I guess)

**Comment by tista500** [comment]
@gnumdk,

How about adding margin-bottom directly into the parent GtkGrid via CSS?
```diff
diff --git a/data/application.css b/data/application.css
index 5caa7733..a072b01c 100644
--- a/data/application.css
+++ b/data/application.css
@@ -371,3 +371,10 @@ popover.background separator {
 	border-color: alpha(@theme_fg_color, 0.1);
 	color: inherit;
 }
+
+.popover-rating-loved-grid {
+        /* (modelbutton's min-height(26px) - icon-height(16px)) / 2
+         * + popover.menu's margin(2px) & padding(4px)
+         */
+        margin-bottom: 11px;
+}
diff --git a/lollypop/pop_menu.py b/lollypop/pop_menu.py
index 7cad923f..fa84d88b 100644
--- a/lollypop/pop_menu.py
+++ b/lollypop/pop_menu.py
@@ -470,8 +470,6 @@ class TrackMenuPopover(Gtk.Popover):
             year = Gtk.Label()
             year.set_text(track_year)
             year.set_margin_end(5)
-            year.set_margin_top(5)
-            year.set_margin_bottom(5)
             year.get_style_context().add_class("dim-label")
             year.set_property("halign", Gtk.Align.END)
             year.set_property("hexpand", True)
@@ -492,17 +490,14 @@ class TrackMenuPopover(Gtk.Popover):
             grid.add(menu_widget)
 
         hgrid = Gtk.Grid()
+        hgrid.get_style_context().add_class("popover-rating-loved-grid")
         rating = RatingWidget(track)
-        rating.set_margin_top(5)
-        rating.set_margin_bottom(5)
         rating.set_property("halign", Gtk.Align.START)
         rating.set_property("hexpand", True)
         rating.show()
 
         loved = LovedWidget(track)
         loved.set_margin_end(5)
-        loved.set_margin_top(5)
-        loved.set_margin_bottom(5)
         if track_year == "":
             loved.set_property("halign", Gtk.Align.END)
         else:
```

**Comment by gnumdk** [comment]
Send me a pull request ;)
