### ISSUE TITLE
cinnamon thumbnail scripts create garbage

### ISSUE THREAD

**Issue by oberon2007** [adapta-project/adapta-gtk-theme#551]
Here's what the results in my theme folder look like:

**Adapta:**

![thumbnail](https://user-images.githubusercontent.com/11800714/32743814-d9972d84-c8ad-11e7-86c5-0db178372c84.png)

![thumbnail](https://user-images.githubusercontent.com/11800714/32743828-e573b348-c8ad-11e7-9342-621f6548edcb.png)

**Adapta-Nokto:**

![thumbnail](https://user-images.githubusercontent.com/11800714/32743969-5c6f543e-c8ae-11e7-9afe-681a41a0dd31.png)

![thumbnail](https://user-images.githubusercontent.com/11800714/32743851-fa11d7da-c8ad-11e7-8bc6-1b6632926330.png)

So, as you can see, the dark gtk one is in fact the only one usable.

**Comment by oberon2007** [comment]
For now I've created proper thumbnails for the regular adapta-themes and for our Manjaro variations. In case you would like to use them as copies, here they are: https://github.com/oberon2007/Cinnamon/commit/3a98e680f436ff8ff35f788ef19c3a5c4faf59cd

**Comment by tista500** [comment]
We don't have any icon-themes, so we should not bundle icon-theme-related things. And if you knew, let me know when they stop requiring pre-generated raster graphics as those thumbnails...

**Comment by tista500** [comment]
I mean devs should prepare for that mechanism to generate those thumbnails from user-thenes directly without any pre-generated images.

**Comment by oberon2007** [comment]
Yes, I agree.
I just see that in the assets-gtk3 file the light thumbnail indeed looks like this, why?:

![thumb_adapta](https://user-images.githubusercontent.com/11800714/32756012-4440f4c4-c8d8-11e7-9824-d8977eaa14e8.png)

**Comment by tista500** [comment]
Because light-variants bundles both light and dark variant. Then apps can handle variants via gsettings key.

**Comment by tista500** [comment]
In future I will merge those changes: https://github.com/adapta-project/adapta-gtk-theme/commit/b52f4986ed90a6aa11a13d376f0202e8fc2f9c4a

I should wait for icon-theme author's answer before marge to make the license clear...

**Comment by oberon2007** [comment]
Why do you keep saying icon-themes? I think there's a misunderstanding here! The thumbnails in question are thunbnails for the **gtk3** and **Cinnamon** desktop theme - nothing to do with any icon themes!

**Comment by oberon2007** [comment]
Have a look at Linuxmint's README about what kind of thumbnails Cinnamon needs in order to properly display them:
https://github.com/linuxmint/Cinnamon/tree/master/files/usr/share/cinnamon/thumbnails/gtk-3.0
I kind find the guidlines right now for the cinnamon deskotp themes. In any case, they need to look something like

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/thumbnails/cinnamon/unknown.png

or, the adapta-example again from my fork

https://github.com/oberon2007/Cinnamon/blob/adapta-thumbnails/files/usr/share/cinnamon/thumbnails/cinnamon/Adapta.png
