### ISSUE TITLE
Border in Lollypop Toolbar

### ISSUE THREAD

**Issue by kronstadt21** [adapta-project/adapta-gtk-theme#552]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.24-0ubuntu2
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.92.1.90-0ubuntu1~artful1

**Related Application and/or Shell theming (or name of widget)**

Lollypop

**Actual issue**

The issue relates to the border around the albumart in the CSD which on adapta is light on the sides like this
![skarmbild fran 2017-11-10 11-14-51](https://user-images.githubusercontent.com/22260777/32778760-67f7ff62-c93b-11e7-900d-e77900e798f0.png).

**Expected behaviour**

I would expect it to blend in better like in adapta-nokto. This is also an issue with other themes mixing dark or colorful and light elements like Pop and Materia.

**Comment by tista500** [comment]
Could you please stop posting multiple posts at the same time...
You should wait an answer from app developers before posting here because that will happen in other themes as well.

Closed this time, sorry.

**Comment by kronstadt21** [comment]
Well I posted here because I was simply curious about the issue. Whether it was an issue solely pertaining to lollypop or if the issue occured in other applications using the same class of widgets or attribute that renders the info.
