### ISSUE TITLE
Not ready for 300% scaling?

### ISSUE THREAD

**Issue by palob** [adapta-project/adapta-gtk-theme#553]
Arch Linux
GTK 3.22.16
GNOME Shell 3.26.2
Wayland Session
Adapta 3.91.0.150

With 300% scaling on a 14" 3840x2160 screen shadows look like this.
Persists no matter of the Shell or icon theme.
![shadow1](https://user-images.githubusercontent.com/7050624/32814317-d2c78d26-c9ae-11e7-91ca-2617b2bfffc6.png)
![shadow2](https://user-images.githubusercontent.com/7050624/32814318-d2e89296-c9ae-11e7-8375-c0f68b5fc55c.png)
![shadow3](https://user-images.githubusercontent.com/7050624/32814319-d3059800-c9ae-11e7-975d-905459e5facd.png)

What is more, window controls look ever so slightly blurry.

**Comment by tista500** [comment]
No. we don't support x3 scaling yet because x3 scaling will be usable if 5K or 8K screens become more popular, sorry

I set this 'Won't fix" currently.

**Comment by pschichtel** [comment]
I haven't tested this: Will Adapta look OK when using fractional scaling on Wayland?

**Comment by palob** [comment]
Turns out this was a GTK+ upstrem bug which got fixed by [this commit](https://gitlab.gnome.org/GNOME/gtk/commit/29f36fed085d51bad16ec0e3f7ba5085bf9f82e8) and released with 3.22.27.
