### ISSUE TITLE
firefox dropmenu style change after using adapta

### ISSUE THREAD

**Issue by ariaieboy** [adapta-project/adapta-gtk-theme#556]
hello 
I am using ubuntu 17.10 and firefox 56 
I noticed that some of the objects in Firefox have changed
for example look at this pictures
its with adapta theme
![adapta](https://user-images.githubusercontent.com/15873972/32846021-777b9da8-ca3b-11e7-9d9e-4c0e49f11e44.png)
and its adapta-nokto
![adapta-nokto](https://user-images.githubusercontent.com/15873972/32846022-77a810a4-ca3b-11e7-9ff4-345d1fb8aaa5.png)
its change drop menu style and select items and ...

**Comment by tista500** [comment]
Screenshot with Adwaita please.

**Comment by ariaieboy** [comment]
my current firefox version is 57
adwaita
![adwaita](https://user-images.githubusercontent.com/15873972/32906321-d068a182-cb11-11e7-84b7-62c6486632d6.png)
adwaita-dark
![adwaita-dark](https://user-images.githubusercontent.com/15873972/32906336-da0779ac-cb11-11e7-8da5-36026347bcc2.png)
firefox 57 in windows
![firefox57 in windows](https://user-images.githubusercontent.com/15873972/32906347-e42f2aba-cb11-11e7-898c-2950260f73bc.png)
chrome in ubuntu and windows
![chrome in ubuntu and windows](https://user-images.githubusercontent.com/15873972/32906362-ec7e60a0-cb11-11e7-8fa9-22112deaa388.png)

**Comment by tista500** [comment]
o_O?
I can't see any remarkable differences between Adapta and Adwaita. So what did you want me to do? Are there any theme specific issues in your screenshots?

**Comment by tista500** [comment]
I'm sorry I can't help you currently.
