### ISSUE TITLE
Top bar is shown with light gray background regardless of settings

### ISSUE THREAD

**Issue by bearoutthere** [adapta-project/adapta-gtk-theme#557]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)**
latest.  installed on Nov 15, 2017

**Related Application and/or Shell theming (or name of widget)**
Adapta Nokto + Global Dark Theme On

**Actual issue**
Despite the Global Dark Theme being on and the Adapta-Nokto selected for both applications and shell the top panel with the menues, clock and system controls is show in light gray background. All of the screenshots of Adapta Nokto i've seen showed it with the dark background.  How to fix this?

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O?

Run and let me see the output:
```
gsettings get org.gnome.shell.extensions.user-theme name
```

**Comment by tista500** [comment]
> Adapta Nokto + Global Dark Theme On

Then 'Global Dark Theme' switch is unrelated to Gnome-Shell theming. You don't need to enable that switch anyway.

**Comment by bearoutthere** [comment]
bear@cave:~$ gsettings get org.gnome.shell.extensions.user-theme name
'Adapta-Nokto'

**Comment by tista500** [comment]
Have you ever overridden system gresouce file in `/usr/share/gnome-shell/gnome-shell-theme.gresource`? If so, revert that file.

**Comment by bearoutthere** [comment]
it's a new install of Ubuntu, theme, and extensions.  had never changed any of the files manually.

**Comment by bearoutthere** [comment]
I installed the theme through apt install

**Comment by tista500** [comment]
Sounds quite strange. At least I could not reproduce.

**Comment by tista500** [comment]
> I installed the theme through apt install

Adapta is not included in any official Ubuntu repositories yet. Meant PPA?

**Comment by bearoutthere** [comment]
yes

**Comment by bearoutthere** [comment]
added ppa and installed

**Comment by bearoutthere** [comment]
are there possible any conflicting settings?  the problem is limited to the main top bar.  window title bars show the correct dark color

**Comment by bearoutthere** [comment]
just purged and reinstalled the theme.  same result.
screenshot attached
![screenshot from 2017-11-16 15-03-43](https://user-images.githubusercontent.com/1024870/32880232-7e9ec994-cadf-11e7-9a03-69f36342498c.png)

**Comment by tista500** [comment]
What the fuck!? Gnome-Classic is designed only for Adiwata. There's not user-themes to override that extension stylesheets, oh please... :(

https://github.com/adapta-project/adapta-gtk-theme/tree/master/shell/gnome-shell/extensions/window-list

**Comment by tista500** [comment]
We can't support Gnome/Ubuntu-Classic session officially.

**Comment by tista500** [comment]
Additional commit: https://github.com/adapta-project/adapta-gtk-theme/commit/cb568c594638a5de0feb68568261cde47e9450f0

**Comment by bearoutthere** [comment]
Thanks a lot.  When will the ppa be updated with this patch?
