### ISSUE TITLE
Nokto checkboxes are a little bit light,

### ISSUE THREAD

**Issue by cswl** [adapta-project/adapta-gtk-theme#558]
```
 * Distribution - Archlinux
 * Gtk+ 3.0 version -  3.22.26-1
 * Desktop environment - XFCE
 * Display server protocol - X11
*  Adapta version - 3.91.0.150-1
 ```

I think its a little big light.. compared to adapta.. or other themes
![adapta_screen](https://user-images.githubusercontent.com/12976647/32981918-a4ede2ea-cca3-11e7-8651-5951a9cf4b70.png)

**Comment by pschichtel** [comment]
I observed that as well. Depending on screen and light conditions it might be really hard to see the box.

**Comment by tista500** [comment]
@cswl,

Firefox Quantum? Should be fixed in git master already.
