### ISSUE TITLE
Yet one more Visual Studio Code theme

### ISSUE THREAD

**Issue by about-code** [adapta-project/adapta-gtk-theme#559]
To celebrate my favourite desktop theme I just released a new Visual Studio Code theme inspired by and integrating with Adapta GTK. If you feel that it meets the project's design philosophy don't hesitate to link to [about-code/vscode-theme-adapted](https://github.com/about-code/vscode-theme-adapted).

Thank you Adapta contributors :heart:

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/9fbe797ee18ac71ae773629e29e1d95bd08330da

Thanks.
