### ISSUE TITLE
question: white box on xfce notification

### ISSUE THREAD

**Issue by dmaglio** [adapta-project/adapta-gtk-theme#561]
In fedora 26 with xfce i have a white box around the notification, like the attachment.
it's correct or it's a bug?

![istantanea_2017-11-20_09-53-34](https://user-images.githubusercontent.com/446573/33009967-ea8acd82-cdd8-11e7-8955-62e4cf313123.png)

**Comment by tista500** [comment]
`xfce4-notifyd-config` Appearance -> Theme.

Could you please stop ignoring our ISSUE_TEMPLATE? I don't know which xfce-notifyd version was included in such distro, I don't know which Gtk+ version was used in such drstro, either. Do I have to search for web to determine those versions and known issues by myself everytime!? please...
