### ISSUE TITLE
Text unreadable in browser Textboxes

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#562]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.25
 * Desktop environment - Gnome 3.26
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
2.201711102020

**Related Application and/or Shell theming (or name of widget)**
 * Firefox 57

**Actual issue**
Like you see in the screen shot below, the text is hardly readable.
![bildschirmfoto von 2017-11-20 23-49-02](https://user-images.githubusercontent.com/10520767/33045736-31351876-ce4e-11e7-8d0c-51d8d1e0d5bc.png)

**Expected behaviour**
Text should be inverted. Is it possible to detect this? This occurrs really on a lot of pages.

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/issues/458#issuecomment-316417057
