### ISSUE TITLE
[Firefox] Resize button of text fields hardly visible

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#563]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.25
 * Desktop environment - Gnome 3.26
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
2.201711102020

**Related Application and/or Shell theming (or name of widget)**
Firefox 57

**Actual issue**
The resize icon of text fields is hardly visible:

![bildschirmfoto von 2017-11-21 01-22-37](https://user-images.githubusercontent.com/10520767/33048337-a0871fec-ce5a-11e7-9aa0-cf7e2bd5447a.png)

**Expected behaviour**
This icon should have a higher contrast, for it being able to be seen.

**Comment by tista500** [comment]
Shot with Adwaita-Dark please.

**Comment by fbruetting** [comment]
Oh, you’re right, this then looks about the same :/
Guess I should I file a bug report against Gnome/Adwaita, then?

**Comment by tista500** [comment]
o_O?

We no longer support resize-grip in Gtk+ theming. And I agree the upstream decision since I hate that widget. Useless, ugly and hard to pen/touch support. Should be replaced fixed box + scrolled-text-view. This is not the Gtk+ side issue.

**Comment by fbruetting** [comment]
Let’s hope they do a fix, which also helps the Adapta theme. ;)
