### ISSUE TITLE
[Ubuntu Dock] Overlapping running app dots

### ISSUE THREAD

**Issue by hmarthinsen** [adapta-project/adapta-gtk-theme#566]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1
 * Desktop environment - Gnome 3
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.92.2.3-0ubuntu1~artful1

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
There are two sets of overlapping dots (one red set and one blue set) in the Dash, indicating if apps are running. See attached image
![screenshot from 2017-11-23 10-40-45](https://user-images.githubusercontent.com/6989581/33166591-1337e602-d03b-11e7-8b21-c814f574f1ee.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
Only one set of dots, either red or blue.

**Other Note (feature-request, question, etc...)**
I'm not sure if it's relevant, but I'm using a 4K display with 200 % scaling set in Gnome.

**Comment by tista500** [comment]
We do not support Ubuntu session but Gnome session. Means we do not support "Ubunto Dock" extension. Use "Dash to Dock" extension instead, sorry.

I set this "Won't Fix".

**Comment by tista500** [comment]
Hmm, Try this:

1. Install 'Dash to Dock" extension.
2. Open Dash to Dock settings window.
3. Move to 'Appearance" tab and turn "Show windows counter indicators" switch on and off even if that switch was off.
4. logout and re-login into Ubuntu (or Ubuntu on Xorg) session.

If lucky, Ubuntu dock specific (hard-coded) dots would be disappeared.

**Comment by hmarthinsen** [comment]
The "Ubuntu Dock" extension was disabled, and I didn't have the "Dash to Dock" extension installed. Somehow, the red dots disappeared by simply installing the "Dash to Dock" extension and then disabling it.

**Comment by tista500** [comment]
Ah, OK. Anyway there's no user-themes to override Canonical's extension currently, so close this, sorry...

**Comment by tflori** [comment]
I'm on manjaro and have a similar issue. I already opened an issue on dash-to-dock but they are right: the dots came from adapta.

![](https://user-images.githubusercontent.com/4855611/44580492-65d41480-a79a-11e8-8320-c237b20216aa.png)

https://github.com/micheleg/dash-to-dock/issues/795

**Comment by tista500** [comment]
o_O?

Revert Settings -> Appearance -> "Customize windows counter indicators" to "Default".
