### ISSUE TITLE
Adapta Eta: the menuitem contains a checkbox is higher than others

### ISSUE THREAD

**Issue by atauzki** [adapta-project/adapta-gtk-theme#567]
**Reporter info**

 ```
 * Distribution - Debian Stretch
 * Gtk+ 3.0 version - 3.22.11
 * Desktop environment - MATE1.18
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)** 3.92,.2.11
here is a screenshot:
![scrshot](https://user-images.githubusercontent.com/19769843/33231316-0a91912a-d22e-11e7-8433-803d224a6cbf.jpg)

**Comment by ArchangeGabriel** [comment]
I think you mean taller?
