### ISSUE TITLE
Feature request: light variant

### ISSUE THREAD

**Issue by Hombremaledicto** [adapta-project/adapta-gtk-theme#568]
Is there any chance for a light (specifically headerbar & titlebar colors) variant in the future?

**Comment by tista500** [comment]
The duplicate of #494.

**Comment by tista500** [comment]
At least I don't have much time in 2017, so the next year I may or may not re-track #494, I can't promise though.

**Comment by Hombremaledicto** [comment]
No problem, i might look to work on it myself, in case you can at least review and accept the code
