### ISSUE TITLE
Customization : Highlight app svg query

### ISSUE THREAD

**Issue by meetdilip** [adapta-project/adapta-gtk-theme#569]
**Reporter info**

 ```
 * Distribution - 16.04
 * Gtk+ 3.0 version - Gtk 3.18.9-1ubuntu3.3
 * Desktop environment - Unity 7.4.0
 * Display server protocol - X11 or Wayland? Display Server: X.Org 1.18.4 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
 ```

**Adapta version (if you knew)** Updated to the latest

**Related Application and/or Shell theming (or name of widget)** assets-unity

**Actual issue**

I just want to ask which svg in the Unity folder plays role in highlighting active apps. I want to use a different pattern with it. Is it possible to use a png for the same ? 

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> which svg in the Unity folder plays role in highlighting active apps

`launcher_icon_*.svg`.

>  Is it possible to use a png for the same ?

I don't know. Should use SVGs for the quality of rendered pixbufs.
