### ISSUE TITLE
Pretty-please-beggery (mate-notification-theme-slate)

### ISSUE THREAD

**Issue by ikeydoherty** [adapta-project/adapta-gtk-theme#570]
Possible to mate the Budgie notification styling directly support [mate-notification-theme-slate](https://github.com/solus-project/mate-notification-theme-slate) ? It's a direct rip of the older Budgie notifications just with the toplevel name `slate-notification`: https://github.com/solus-project/mate-notification-theme-slate/blob/master/theme/notification.ui

This would allow MATE notifications to integrate better by being CSS rendered and not just custom hackery. Willing to donate as it would help us with Solus 4 upcoming refresh :D

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/2aadcbc69b8310200eab0f369bb08151ebfd3c71

I haven't tested well though... Maybe that commit should work as I expected. But we will drop Gtk+ 3.18.x theming in near future (April 2018), so I've added those theming for 3.2x/4.0 only.

**Comment by tista500** [comment]
Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.92.2.16

**Comment by ikeydoherty** [comment]
Thank you! Where does one send donations? :)

**Comment by tista500** [comment]
We (I) don't receive any donations in this project. So you use the money for yourself and your project-teams. Cheers. :)

Yeah all I want is new year long vacation. :p

**Comment by ikeydoherty** [comment]
Oh - very kind of you :3 Hope you really enjoy your vacation bud, god knows you deserve it :D
