### ISSUE TITLE
Weird Text Box

### ISSUE THREAD

**Issue by himanshuxd** [adapta-project/adapta-gtk-theme#571]
Ubuntu 16.04 using Unity7 : 

Constant user of Adapta theme from the past 2 months but there is a slight problem that bugs me, in certain text entry boxes the background is dark and even the text is dark so I can't see the entered text at all.

![Alt Text](https://uploads.disquscdn.com/images/ca50264902d2549d68acf2e2297ed4ca100a53000481d022dc8aa4b87e1be6d1.png)

**Comment by himanshuxd** [comment]
@tista500

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/issues/599#issuecomment-357409570
