### ISSUE TITLE
cosmetic issue with Adapta theme and the cinnamon applet dialog 

### ISSUE THREAD

**Issue by mabod** [adapta-project/adapta-gtk-theme#572]
**Reporter info**

 ```
* Cinnamon 3.6.2
 * Manjaro 17.1pre3 Hakoila
 * x86_64 Linux 4.14.2-1-MANJARO
 * GeForce GTX 750 Ti
 * adapta-breath-theme 3.92.1.108-1
 * adapta-gtk-theme 3.92.1.108-1
 * adapta-maia-theme 3.92.1.108-1

 ```
**Actual issue**

With any of the Adapta themes applied: When in the cinnamon "applet dialog" and I select one applet and then I move the mouse over this selected applet the whole entry in the dialog turns white. No text discernible anymore. See the following screenshots:

Selected Applet entry:

![bildschirmfoto vom 2017-11-26 15-29-48](https://user-images.githubusercontent.com/10911665/33253347-42c75992-d343-11e7-91f1-1178176233e8.png)

Mouse over selected entry:

![bildschirmfoto vom 2017-11-26 15-29-45](https://user-images.githubusercontent.com/10911665/33253356-4cc1e886-d343-11e7-8828-c351f2ad5edb.png)

I opened this as a cinnamon issue as well. But it was rejected as a theme issue: 
[https://github.com/linuxmint/Cinnamon/issues/7082](https://github.com/linuxmint/Cinnamon/issues/7082)

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/957c473df659c7d2ffbf6e9773828d22e725bfd2
