### ISSUE TITLE
how to change color on hover selection ? 

### ISSUE THREAD

**Issue by HaxorGaruda** [adapta-project/adapta-gtk-theme#573]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment -
 * Display server protocol - X11 or Wayland?
 ```
Gtk version : 3.22.24-3

**Adapta version (if you knew)**
clone and compile from gitub repo 

**Related Application and/or Shell theming (or name of widget)**
i use mate DE, 

**Actual issue**
how to change color on hover selection ?

**Steps to reproduce (if you knew)**
compile with ./autogen.sh and this argument not change hover selection color
--with-selection_color
--with-accent_color
--with-suggestion_color
--with-destruction_color

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

![hover](https://user-images.githubusercontent.com/5996055/33300649-18d1032c-d424-11e7-905d-51dbf5e06e34.png)

**Comment by tista500** [comment]
No, it can't. Because GtkMenuItem is not the part of selection.
https://material.io/guidelines/components/menus.html#menus-simple-menus
