### ISSUE TITLE
Cosmetic Issue: "Loading..." in file explorer

### ISSUE THREAD

**Issue by bhajneet** [adapta-project/adapta-gtk-theme#575]
```
                          Distribution - Solus 3.26.2
                      Gtk+ 3.0 version - 3.22.26-66
                   Desktop environment - Budgie 10.4-150
 Display server protocol (X11/Wayland) - X11
             Adapta version (if known) - 3.92.1.108-119
 ```

**Related Application and/or Shell theming (or name of widget)**
nautilus / Files

**Actual issue**
The loading pop-up in the bottom right corner has what looks like uneven loading animation. The stop symbol is also not "obvious" until you hover over it. A cross / x would make more sense, but even a stop sign that doesn't have a circle around it would allow a larger symbol and also clear things up a little.

**Steps to reproduce (if you knew)**
Load a large folder on the NAS via smb

**Expected behaviour**
Normal loading animation where left and right side are both same heights. A stop button that is more a cross, less a circle.

**Other Note (feature-request, question, etc...)**
![screenshot from 2017-11-28 10-42-24](https://user-images.githubusercontent.com/14130567/33329042-9eea634a-d429-11e7-859a-3b30a4969ca0.png)

**Comment by tista500** [comment]
> The stop symbol is also not "obvious" until you hover over it. 

o_O?
Isn't it the icon-theme specific? Why did you ask me?
https://github.com/GNOME/nautilus/blob/master/src/nautilus-files-view.c#L406

**Comment by bhajneet** [comment]
I'm not a theme designer, so I didn't know if it was under this theme or all themes. What about the loading animation?
