### ISSUE TITLE
green notification dot vertically misaligned

### ISSUE THREAD

**Issue by wbolster** [adapta-project/adapta-gtk-theme#576]
**Adapta version**

```
ii  adapta-gtk-theme         3.92.2.21-0ubuntu all               Adapta Gtk+ Theme
```

**Related Application and/or Shell theming (or name of widget)**

gnome-shell panel

**Actual issue**

the green notification dot seems vertically misaligned (not centered). see this screenshot:

![image](https://user-images.githubusercontent.com/748944/33330801-27adb1e2-d460-11e7-80d8-92121fdf2e86.png)

**Expected behaviour**

the dot shows up vertically centered

**Other Note (feature-request, question, etc...)**

adapta looks beautiful. thanks for making it!

**Comment by tista500** [comment]
It's intentional top-right alignment like 'needs_attention' in Gtk+ theming.
Won't change anything, Closed.

**Comment by wbolster** [comment]
hmmm in a broader context i think it's good to follow standard gtk+ theming practices.

but the thing here is that the standard practice is designed for a bigger ui, like a dialog window.

in this case there is only the gnome-shell panel, which is always a single ‘row’ of content with very limited vertical height.

i argue that for areas with a very limited vertical area such as the gnome-shell panel, using vertical ‘top’ alignment while the whole ux flow of that panel is horizontal (very wide, very small height) looks odd and out of place.

does this make sense?
