### ISSUE TITLE
Fedora 25 Eclipse Oxygen 3 GTK3 Tooltip Font color not visible properly 

### ISSUE THREAD

**Issue by prasadpatil25** [adapta-project/adapta-gtk-theme#578]
**Reporter info**

 ```
* Distribution - Fedora 25
* Gtk+ 3.0 version - gtk2-2.24.31-2.fc25.x86_64 
* Desktop environment - Gnome 3.22.16 
* Display server protocol - X11
 ```

**Adapta version (if you knew)**
Latest version build from sources

**Related Application and/or Shell theming (or name of widget)**
Fedora 25 Eclipse Oxygen 3 GTK3

**Actual issue**
Font color too light to see in debug window

**Steps to reproduce (if you knew)**
Write any Java program and run in debug mode and hover on the variable.

**Expected behaviour**
Should contain white background with black font. Or preferably nice looking tooltip.

**Other Note (feature-request, question, etc...)**

Please check picture for more details:

![eclipse debug menu](https://user-images.githubusercontent.com/12842912/33374548-a2dfbd5c-d52c-11e7-8970-7abf4107a661.jpg)

**Comment by tista500** [comment]
Eclipse tooltip, eclipse tooltip, and eclipse tooltip... What the fuck!? :/

**Comment by tista500** [comment]
Try this: https://stackoverflow.com/questions/45093561/black-background-color-tooltips-in-eclipse-oxygen

Won't fix.

**Comment by prasadpatil25** [comment]
Dear Tista,

I guess there is difference between javadoc tooltip window and debug window. I tried to change the color as per mentioned in the URL u provide. The color is changed but for javadoc windows only not for debug window.

Following is the java doc window:
![javadoc window](https://user-images.githubusercontent.com/12842912/33416924-16dd7986-d5c5-11e7-8548-898274709c2a.jpg)
