### ISSUE TITLE
[Feature Request] Matching GDM Theme Please

### ISSUE THREAD

**Issue by PJSingh5000** [adapta-project/adapta-gtk-theme#582]
**Reporter info**

 ```
* Distribution - Ubuntu 17.10
* Gtk+ 3.0 version - libgtk-3-0: 3.22.25-0ubuntu0.1
* Desktop environment - GNOME Shell 3.26.1
* Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

adapta-gtk-theme 3.92.2.32-0ubuntu

**Related Application and/or Shell theming (or name of widget)**

gdm3 3.26.1-3ubuntu3

**Other Note (feature-request, question, etc...)**

Feature Request:
Could we get a matching GDM (login screen) theme?

**Comment by tista500** [comment]
#515
