### ISSUE TITLE
Change Menu Bar Color

### ISSUE THREAD

**Issue by kashm1r** [adapta-project/adapta-gtk-theme#583]
Hello.

I want to change the color of the menu bar, but not all the applications change color.

I change values from colors.rc in gtk-2.0 folder, but it does not apply to all.

Thunar changed color to #262626, but Mousepad and other programs like Eclipse, Libreoffice, don't changed.

Adapta Version: 3.92.2 Stable Release (rev.33), I built enabling only XFCE, Chrome Support.
![adapta](https://user-images.githubusercontent.com/24923166/33574239-8a73b5ec-d91f-11e7-953e-eb109849b4c5.png)

**Comment by tista500** [comment]
Tweak Gtk+ 3 theming as well.

**Comment by tista500** [comment]
I don't answer to such questions about personal aesthetics.
