### ISSUE TITLE
Firefox title bar buttons

### ISSUE THREAD

**Issue by Joaquinrajmilevich** [adapta-project/adapta-gtk-theme#584]
* Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - Gnome 3.26.2
 * Display server protocol -  Wayland

**Related Application and/or Shell theming** - Firefox Quantum

**Actual issue**

![screenshot from 2017-12-08 14-12-05](https://user-images.githubusercontent.com/30022003/33777113-65408c7c-dc22-11e7-9978-0b01691d2f96.png)
![screenshot from 2017-12-08 14-11-30](https://user-images.githubusercontent.com/30022003/33777117-67c5064e-dc22-11e7-86f9-c468d2697db3.png)

**Steps to reproduce (if you knew)**
setting to true widget.allow-client-side-decoration in about:config

**Comment by tista500** [comment]
That feature also breaks Arc themes, so I don't think this was related to theme-side issue. And those icons are bundled with Firefox itself and un-recolourable from theme-side.

Won't fix, sorry.

**Comment by fitojb** [comment]
Why not report it to bugzilla.mozilla.org? They are interested in fixing GTK+ issues.
