### ISSUE TITLE
No Donation link on README

### ISSUE THREAD

**Issue by JoshStrobl** [adapta-project/adapta-gtk-theme#586]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.92.2.43

**Related IRL object ~Application and/or Shell theming (or name of widget)~**

My wallet.

**Actual issue**

I can't throw money at you for your constant support of Adapta, consistent updates and reliability when it comes to addressing issues.

**Steps to reproduce (if you knew)**

Go to this repo so the README shows. Try to find a link to PayPal or other donation options.

**Expected behaviour**

To be able to find such links and be able to donate.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@JoshStrobl,

I've created Patreon page: https://www.patreon.com/tista500
We are not allowed to exchange money between individuals via PayPal (it’s against the law) in my country (We can not create 'Donate' buttons anyhow). so I'm not sure whether that Patreon worked as you expected or not though, sorry...

I linked my PayPal account to payout form Patreon, but I did not test yet. :p
