### ISSUE TITLE
Media layer indicator has unusual spacing

### ISSUE THREAD

**Issue by arngo** [adapta-project/adapta-gtk-theme#588]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

Latest from github (https://aur.archlinux.org/packages/adapta-gtk-theme-git/)

**Related Application and/or Shell theming (or name of widget)**

[Media player indicator extension](https://extensions.gnome.org/extension/55/media-player-indicator/) 

**Actual issue**

Media player indicator menu has unusual spacing causing some buttons to be hidden.
![mediaplayerindicator](https://user-images.githubusercontent.com/27396817/34056313-7e30fd74-e1a0-11e7-93f5-4902a7a3ef6e.png)

**Steps to reproduce (if you knew)**
1. Install and enable Adapta from latest git with https://aur.archlinux.org/packages/adapta-gtk-theme-git/
2. Install and enable Media player indicator from https://extensions.gnome.org/extension/55/media-player-indicator/
3. Open Media player indicator menu

**Expected behaviour**
All text and buttons are centred within menu 

**Other Note (feature-request, question, etc...)**
None

**Comment by tista500** [comment]
> All text and buttons are centred within menu

We now align all of 'sub-menu' items with the parent StLabel like this: https://git.gnome.org/browse/gnome-shell-sass/commit/?id=57a2e5bfe179d9db1e05c3edaffdcb3fee307be0
