### ISSUE TITLE
Strange bot side bar at system settings

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#589]
Linux Mint
Cinnamon
x11
gtk-version: 3.18
adapta-version: 3.92
 ```
# Where
In system settings

# Behaviour
Strange bottom side bar, it hides menus names, menus icons, but i can 
click them even they are below the strange white bar

# Reproduce
Open the settings, or maybe others apps could be found this

# Expected
Showing the icons and text of the menus, but not that big bar
```
![screenshot from 2017-12-22 15-46-07](https://user-images.githubusercontent.com/25506386/34309140-499c395e-e72f-11e7-8b3a-c5b47f535ae0.png)
![screenshot from 2017-12-22 15-18-57](https://user-images.githubusercontent.com/25506386/34309010-ad9b3c30-e72e-11e7-83ce-b92a4f840d73.png)

**Comment by tista500** [comment]
We no longer maintained Gtk+ 3.18.x theming.

**Comment by gabrielfern** [comment]
oh, ok, i missed it

**Comment by tista500** [comment]
Anyway I will look into it today or tomorrow...

**Comment by gabrielfern** [comment]
Thanks, it would be great
