### ISSUE TITLE
Weird GTK2 appearance?

### ISSUE THREAD

**Issue by ugggf** [adapta-project/adapta-gtk-theme#590]
**Reporter info**

 ```
 * Distribution - Mint 18.3
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Cinnamon 3.6.7
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)**
3.92.2.54

**Related Application and/or Shell theming (or name of widget)**
GTK2 apps (ie Inkscape, Shutter)

**Actual issue**
Not adapting the theme's colors and buttons
![new document 1 - inkscape_001](https://user-images.githubusercontent.com/8597179/34318113-d5145b0e-e7c7-11e7-9634-65d5d7852d76.png)

**Steps to reproduce (if you knew)**
Open GTK2 app. Buttons don't match theme and colors are partially different from theme's colors.

**Expected behaviour**
Fully adapt theme.
![home_002](https://user-images.githubusercontent.com/8597179/34318112-d4dfc984-e7c7-11e7-855f-dff74bfaf62b.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Gtk+ 2.x is NOT the mainstream toolkit version. So we do 'fallback-mode' design for Gtk+ 2.x and some non-native Gtk+ 3.x apps. It's an intentional thing. Won't fix, sorry.

**Comment by ugggf** [comment]
Ok, thanks for the clarification!

**Comment by tista500** [comment]
o_O? Wait, the shot of Inkscape looks something strange...

Here is Gtk-2-ed Inkscape 0.92.2 on my locally installed Bionic 18.04 (Gtk+ 2.24.31, Adapta 3.92.2.54):
![screenshot from 2017-12-23 18-37-07](https://user-images.githubusercontent.com/6073622/34318622-af721f14-e810-11e7-940f-040805e5939c.png)

**Comment by ugggf** [comment]
Looking at it a bit I realized that setting adapta as the Gnome Application Style within KDE settings actually solved the problem for me. Hope this info helps.

**Comment by ugggf** [comment]
Looking at it a bit I realized that setting Adapta theme at the Gnome Application Style in KDE settings actually solved the problem for me. Hope this helps.

**Comment by tista500** [comment]
K desktop?

You reported: 
> Desktop environment - Cinnamon 3.6.7

If something was happened with K desktop settings, it's not the issue of us. Adapta is the Gtk+ theme in pure Gtk+ desktop environments...

Won't fix, sorry.

**Comment by ugggf** [comment]
No, It's Cinnamon but I have installed KDE settings (basically to be able to adjust the look of some apps like Okular or Krusader).

**Comment by ArchangeGabriel** [comment]
@ugggf Just by curiosity, what is your icon theme?

**Comment by bil-elmoussaoui** [comment]
@ArchangeGabriel It's Numix icon theme ;)

**Comment by ugggf** [comment]
Numix Circle to be precise...
