### ISSUE TITLE
How can you identify an Adapta color when it is mixed from two colors?

### ISSUE THREAD

**Issue by EastAPOLO** [adapta-project/adapta-gtk-theme#592]
Hello, 
I was looking at the colors.scss file and see all these colors being mixed, how can you tell what color will it actually be when it is mixed? Because I find that otherwise to be unreadable. For example, the color  #222D32 is clear what its gonna be. Is it possible to obtain what the color will be when two colors are mixed?

**Comment by tista500** [comment]
>  otherwise to be unreadable
Unredable o_O!?
SCSS is the source of CSS, means SCSS is the 'recipe'.
I can't get the point what you want. See the generated CSSs...
