### ISSUE TITLE
Invalid borders specified for theme pixmap in Kolourpaint when using Adapta

### ISSUE THREAD

**Issue by PJSingh5000** [adapta-project/adapta-gtk-theme#594]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1
 * Desktop environment - Gnome Shell
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.92.2.63-0ubuntu1

**Related Application and/or Shell theming (or name of widget)**

kolourpaint 17.04.3

**Actual issue**

 Invalid borders error in Kolourpaint using Adapta theme:

        Sender: kolourpaint

            Invalid borders specified for theme pixmap:
                    /usr/share/themes/Adapta/gtk-2.0/Entry/ltr-entry.png,
            borders don't fit within the image

**Steps to reproduce (if you knew)**

1. Install kolourpaint and qt5-style-plugins to make KDE apps look native in gnome.

        sudo apt install qt5-style-plugins kolourpaint

2. Set the following environment variable to make KDE apps look native in gnome.

        echo "QT_QPA_PLATFORMTHEME=gtk2" | sudo tee --append /etc/environment

3. Reboot to apply QT_QPA_PLATFORMTHEME environment variable.

4. Launch Kolourpaint.

5. Look in the logs and find the following error messages.

The following error message referencing Adapta appears:

        Sender: kolourpaint

            Invalid borders specified for theme pixmap:
                    /usr/share/themes/Adapta/gtk-2.0/Entry/ltr-entry.png,
            borders don't fit within the image

Also, the following error message is repeated for icon sizes: 16, 22, 24, 32,48,64, and 128.  I'm not sure if it is related to the Adapta theme, but I have included it here to help with debugging:

            Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"

**Expected behaviour**

The following error should not appear in the logs when launching Kolourpaint:

            Invalid borders specified for theme pixmap:
                    /usr/share/themes/Adapta/gtk-2.0/Entry/ltr-entry.png,
            borders don't fit within the image

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O?

Which "logs" are you pointing to? I could not reproduce with 4:17.08.3-0ubuntu1 on Bionic.

**Comment by PJSingh5000** [comment]
I'm getting this on two different machines, both running artful.

I see the error in...

    /var/log/syslog

...after I start Kolourpaint.
