### ISSUE TITLE
LibreOffice: Scaling down the up/down buttons

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#596]
**Reporter info**

 ```
 * Libreoffice-Flatpak
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
Current

**Related Application and/or Shell theming (or name of widget)**
LO +/− buttons.

**Actual issue**
Those buttons seem a fairly oversized in my opinion, so they either hide the size numbers partly (you don’t see "cm" anymore) or the sidebar has to be enlarged – what isn’t so good on small displays. What do you think about makeing them a bit smaller or maybe stacking them?

**Other Note (feature-request, question, etc...)**
![bildschirmfoto von 2018-01-05 00-25-54](https://user-images.githubusercontent.com/10520767/34589355-8099d7e6-f1b0-11e7-9084-594568888232.png)

**Comment by tista500** [comment]
> what isn’t so good on small displays. 

o_O?
What was the particular reason you did NOT use -eta variants for poor resolution LCDs?

**Comment by tista500** [comment]
I don't think spin up/down were quite large comapred with combobox-arrows.

> or the sidebar has to be enlarged

I'm not sure but that initial width of sidebar(?) wasn't a hard-coded?

**Comment by fbruetting** [comment]
I’m pretty much satisfied with all the other sizes. On my UHD 15" screen everything is perfect – but I have another HD 24" screen attached, and there, everything is rendered bigger… which isn’t a problem at all, but I just though about asking you reconsidering the size of this single widget. If you don’t want to change it, it’s fine! Just wanted to ask. ;)

**Comment by fbruetting** [comment]
But if you compare the spinners with the other icons, they’re really big – if you compare the button sizes in the below linked Adwaita image, everything looks more uniform. With Adapta just the drop down boxes and spinner buttons get enlarged, all the other buttons stay small… maybe you could fit that a little better? I.e. either the small buttons bigger, or the big buttons smaller.

https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fwiki.documentfoundation.org%2Fimages%2F3%2F31%2FHappy-gtk-4-5.png&f=1

**Comment by tista500** [comment]
An attached image link was rendered with Gtk+ 2.x. There's no meaning when discussing for Gtk+ 3.x theming.

LO sometimes pulls some styling form wrong selectors. For example, Those 'arrow buttons' inside the combobox node should be themed via `combobox arrow` and `combobox button.combo arrow`. But they're going to pull just `button` styling at root of our CSSs. That's why I said "won't fix". More precisely, "can't handle".

Again, won't fix at least with Gtk+-3-ed 5.4.3, sorry.

**Comment by tista500** [comment]
> dropdown boxes and spinners

"Combobox arrows and spinbuittons".

**Comment by tista500** [comment]
> Or don’t they use GTK buttons for these small buttons,

If you're talking about these tool buttons (red area of an attached image), spacing of those buttons is hard-coded (theme independent):
![34589355-8099d7e6-f1b0-11e7-9084-594568888232_2](https://user-images.githubusercontent.com/6073622/34593486-8e7e424e-f20e-11e7-856f-17c49977b455.png)

**Comment by fbruetting** [comment]
Ok, thanks for the information. I’ll report this bug there. :)
