### ISSUE TITLE
Too transparent with librsvg 2:2.41.2-1

### ISSUE THREAD

**Issue by mabod** [adapta-project/adapta-gtk-theme#597]
**Reporter info**

OS: Manjaro 17.1.0 Hakoila
Kernel: x86_64 Linux 4.14.11-3-MANJARO
DE: Cinnamon 3.6.6
WM: Muffin
WM Theme: Adapta-Nokto (Adapta)
GTK Theme: Adapta [GTK2/3]
gtk2 2.24.31-1
gtk3 3.22.26+47+g3a1a7135a2-3

**Adapta version (if you knew)**
adapta-breath-theme 3.92.2.57-1
adapta-gtk-theme 3.93.0.1-1
adapta-maia-theme 3.92.2.57-1

**Actual issue**

With librsvg 2:2.41.2-1 the Cinnamon menu is so transparent that it is almost unreadable resp. unusable. 

**Steps to reproduce (if you knew)**
Install librsvg 2:2.41.2-1.
Downgrading to librsvg 2:2.40.20-1 solves the issue.

The issue was discovered in the manjaro forum. You can find screenshots there as well:
https://forum.manjaro.org/t/testing-update-2018-01-04-kernels-xfce-settings-gimp-development-edition/37625/23

**Comment by pseudorook** [comment]
I noticed this, too (on Arch). Downgrading fixed this. 

I also noticed that the menus in the Arc theme aren't made almost transparent by the librsvg upgrade, so I overwrote the  menu.svg in the Adapta theme with the Arc one. The transparency issue disappeared. Perhaps something about the Adapta svg isn't compatible with the librsvg upgrade.
