### ISSUE TITLE
Transparent bars?

### ISSUE THREAD

**Issue by vrozsas** [adapta-project/adapta-gtk-theme#599]
![captura de tela de 2018-01-13 02-18-58](https://user-images.githubusercontent.com/30468584/34902760-df3c129c-f808-11e7-9623-afa01f976dbe.png)

Why are the Unity's superior bar and my applications bars transparent?

This happened after I upgraded Adapta (and Adapta-Nokto) to the latest version (today) and rebooted the computer.

**Comment by tista500** [comment]
Unity7 support is over.
https://github.com/adapta-project/adapta-gtk-theme#unsupported-gtk-based-desktops
https://launchpad.net/~tista/+archive/ubuntu/adapta
https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.93.0.23

And we will drop Gtk+ 3.18.x support in Apr 2018...
Won't fix, sorry.

**Comment by vrozsas** [comment]
Aw... I didn't knew. Adapta-Nokto was my favorite theme. I will have to find a similar one then.
But thank you for your time and for developing such a theme. Didn't find anything that good for Unity yet.

**Comment by tista500** [comment]
Materia might still support Unity7, maybe.

**Comment by vrozsas** [comment]
Ah, thanks. I think I've seen Materia, but didn't take a closer look yet. I'll check it out.
Thanks for the suggestion. Keep the good work!

**Comment by mbirth** [comment]
[Numix](https://github.com/numixproject/numix-gtk-theme) is also vaguely similar.

**Comment by mbirth** [comment]
@tista500 Could you maybe freeze the last version working with Unity 7 in the artful PPA (and provide the latest version as well)?
