### ISSUE TITLE
Top panel and window title bar are transparent 

### ISSUE THREAD

**Issue by sanjaypra555** [adapta-project/adapta-gtk-theme#600]
**Reporter info**
![screenshot from 2018-01-14 20-49-19](https://user-images.githubusercontent.com/18235954/34908364-5039768c-f8b4-11e7-8efc-9714b7adba13.png)

 ```
 * Distribution - Ubuntu 16.04.3 
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.3
 * Desktop environment - Unity
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)** -  3.93.0.38-0ubuntu1~xenial1 

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**  - Top panel and window title bar are transparent.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by Roald87** [comment]
Same issue here. Any ideas for a fix?

**Comment by tista500** [comment]
Nobody reads the README...
https://github.com/adapta-project/adapta-gtk-theme/issues/599#issuecomment-357409570
