### ISSUE TITLE
[Feature Request] Circular Spinner

### ISSUE THREAD

**Issue by PJSingh5000** [adapta-project/adapta-gtk-theme#603]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1 amd64
 * Desktop environment - gnome-shell 3.26.2-0ubuntu0.1
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

adapta-gtk-theme 3.93.0.43-0ubuntu1~artful1

**Related Application and/or Shell theming (or name of widget)**

GTK Spinner

**Request**

Would you consider changing the horizontal spinner to a traditional "circular" spinner?

I know a lot of thought has gone into the design of Adapta, so I know I am asking you to revisit something you have already thought through...

- The current "horizontal bar" spinner in Adapta is small and easily overlooked.

- A "circular" spinner would be more effective, especially when a gtk spinner is shown on small buttons, next to text, or in tabs.

Here is an example of the "kind" of spinner I am talking about...

https://codepen.io/mrrocks/pen/EiplA

**Comment by gabrielfern** [comment]
...personally i'd like more the horizontal spinner that was before
