### ISSUE TITLE
adapta gtk theme on lightdm

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#606]
```
linux mint
gtk 3.18
cinnamon
x11
 ```

Adapta version = 3.93.0.43

on new linux mint login window (lightdm) you can set the gtk theme to use and icons up to you preference, i have set adapta as gtk theme and the color of some elements seems to be messed up, not on the adapta-nokto wich is good, in the light adapta theme we can't see as we wich things like password letters feedback and options of desktop environments to login

here with adapta gtk theme
![photo_2018-01-15_22-45-46](https://user-images.githubusercontent.com/25506386/34968085-e7145c6a-fa45-11e7-8362-ed3732ad09fa.jpg)
here nokto flavor (which is what we expected the adapta be)
![photo_2018-01-15_22-45-58](https://user-images.githubusercontent.com/25506386/34968106-0876cdde-fa46-11e7-80b0-830ecc5d1c22.jpg)

adapta
![photo_2018-01-15_22-45-51](https://user-images.githubusercontent.com/25506386/34968110-0eca7f46-fa46-11e7-8e16-1473ecc60f5f.jpg)
adapta-nokto
![photo_2018-01-15_22-45-55](https://user-images.githubusercontent.com/25506386/34968115-15a07a00-fa46-11e7-8f37-f15cf242c031.jpg)

**Comment by tista500** [comment]
We don't support slick-greeter and unity-greeter in Gtk+ 3.18.x (development is over).

Won't fix.
