### ISSUE TITLE
Remove DEB packages >= 3.93.0.23 from Ubuntu Xenial PPA

### ISSUE THREAD

**Issue by benad** [adapta-project/adapta-gtk-theme#608]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04 LTS
 * Gtk+ 3.0 version - ?
 * Desktop environment - Unity
 * Display server protocol - Unity
 ```

**Actual issue**
Since Adapta starting with 3.93.0.23 doesn't support Unity 7 anymore, new DEB packages released in the PPA https://launchpad.net/~tista/+archive/ubuntu/adapta are causing issues in Ubuntu 16.04 LTS.

**Steps to reproduce (if you knew)**
`sudo apt upgrade` on Ubuntu 16 when the Adapta PPA was added.

**Expected behaviour**

Pin the version of the DEB for the Xenial Adapta PPA to an older version, for example 3.93.0.11.

**Comment by gabrielfern** [comment]
yum?

**Comment by benad** [comment]
Oops. Obviously `sudo apt upgrade`.

**Comment by tista500** [comment]
No we don't support Unity7 anymore in all of supported Gtk+ versions. And we will drop supporting Xenial in Apr 2018.
