### ISSUE TITLE
better support to focused window

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#609]
```
linux mint
gtk 3.18
cinnamon
x11
 ```

Adapta version = 3.93.0.56

using the "Icing Task Manager" applet instead of the original window task manager of cinnamon, which provides to us window grouping and use less panel bar space with only icons instead the title name of the window, there are no way to see what are the actual focused window with adapta desktop theme, swapping only the desktop theme to mint y for example we can notice the focused window
below images with the behaviors

in adapta desktop theme
![screenshot from 2018-01-17 17-29-20](https://user-images.githubusercontent.com/25506386/35065918-8caba224-fbad-11e7-9782-7aa215c270b3.png)
in mint y (as a example of how it could be with adapta)
![screenshot from 2018-01-17 17-28-57](https://user-images.githubusercontent.com/25506386/35065947-aa1eeaf0-fbad-11e7-9c04-d2c07caa7db3.png)

**Comment by tista500** [comment]
Damned. Broken in arc-themes as well. So I don't think that app worked with various 'standard' themes.

Anyway we can't support that app as I expected.

**Comment by gabrielfern** [comment]
even with mint y there are unexpected behaviors with the icing window manager, that is sad, because it is a must-have for cinnamon
