### ISSUE TITLE
window keeping active on task manager after closed

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#610]
```
linux mint
gtk 3.18
cinnamon
x11
 ```

Adapta version = 3.93.0.56

using the "Icing Task Manager" on cinnamon (https://github.com/jaszhix/icingtaskmanager) you can use shortcuts as "super + 1" to restore minimized windows or minimize the respective window in the position 1 of the task manager, which is similar to unity super + number shortcut, but using the adapta cinnamon desktop theme if you open a pinned app with this shortcut and minimize it with the same shortcut and after open it again and close the window the app keeps active on the task manager even after it be closed, this doesn't happen if you don't use the same shortcut to open it back, i thought this was a fault of the  Icing Task Manager, but if you swap only the desktop theme to say mint y this doesn't happen.
if you restart the cinnamon you will see the task manager updated and the closed window don't active as it should be without restarting the cinnamon, this seems to be a ui update problem. So i think this can be fixed in the adapta cinnamon desktop theme as in the mint y and others desktop themes this doesn't happen.

**Comment by tista500** [comment]
`:closed` pseudo-class!? o_O!?

Are they crazy?
https://github.com/jaszhix/icingtaskmanager/blame/7f6f2ad90c53e07437989b7acd1ec2d5cf244614/IcingTaskManager@json/3.4/stylesheet.css#L24

There's no 'standard' user-themes going to implement `:closed` pseudo-class as far as I know. :/

**Comment by gabrielfern** [comment]
this is fixed @tista500 , good job, the actives windows are being shown as it should, but now when i pointer to the focused window that window chages to only active instead colored as focused. I dont know more what to do, this icing manager is the only one for cinnamon that do what it do
