### ISSUE TITLE
Window bar transparent, no reason

### ISSUE THREAD

**Issue by ioan-cristea** [adapta-project/adapta-gtk-theme#611]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X.org
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Window bar is transparent, I don't know why. I start my laptop today and is like this...You can see screenshot in Other Note.
I tried to change with Ambience theme and there it works.
I also removed Adapta theme and reinstall it, with repository

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
![screenshot from 2018-01-18 09-29-57](https://user-images.githubusercontent.com/24575385/35085783-d418c6ca-fc32-11e7-80a6-aea49a6a4933.png)

**Comment by tista500** [comment]
Unity7 support is over.

**Comment by benad** [comment]
See ticket #608 and #612.

This theme won't work with Ubuntu 16.04 anymore, but for some reason new broken versions keep getting pushed to the PPA Apt source you installed.

I recommend removing the adapta PPA source, the current adapta package, and manually install the following last known working version: https://launchpad.net/~tista/+archive/ubuntu/adapta/+build/14213155/+files/adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb .

**Comment by benad** [comment]
BTW I keep begging the author from updating the Ububtu PPA with updates on Xenial, but no matter how I phrase the request there seem to be communication issues. If you need clearer instructions on how to remove the Adapta PPA and downgrade the theme to its last supported version, comment here and I'll reply.

**Comment by ioan-cristea** [comment]
Thanks. It works! :D

Regards,
<https://krioft.com/>

*Ioan Cristea*
*CEO & Developer*
 (+4) 0766 330 697
 ioan.cristea@krioft.com
NOTICE:
The contents of this email message and any attachments are intended solely
for the addressee(s) and may contain confidential and/or privileged
information and may be legally protected from disclosure. If you are not
the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by
reply email and then delete this message and any attachments. If you are
not the intended recipient, you are hereby notified that any use,
dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

**Comment by FalloutX** [comment]
Thanks Everyone, I was really confused why suddenly my window bar got transparent and totally unusable.
