### ISSUE TITLE
Stop Updating Ubuntu Xenial PPA

### ISSUE THREAD

**Issue by benad** [adapta-project/adapta-gtk-theme#612]
Since Adapta starting with 3.93.0.23 doesn't support Unity 7 anymore, could you stop pushing new Xenial versions of the DEB packages in the PPA https://launchpad.net/~tista/+archive/ubuntu/adapta ?

Right now Ubuntu 16.04 users accidentally get new versions of the theme which will break and are not supported anymore. This happened on January 17 when version 3.93.0.56 was released for Xenial.

To be clear, I'm not asking for the theme to be fixed on Xenial. All I'm asking for is to stop pushing new, unsupported and potentially broken versions of the theme on the Unbuntu PPA for Xenial.

**Comment by benad** [comment]
Issue #611 is an example of this situation. Many Ubuntu 16.04 users unaware that this theme is EOL on Unity 7 will open tickets here because they keep getting new versions of the theme through the PPA and automatic software updates, when obviously they shouldn't anymore.

**Comment by tista500** [comment]
o_O?

Gnome-Shell, Cinnamon, Budgie-desktop, XFce4, and other DE users should be received our updates.

**Comment by benad** [comment]
You pushed a broken update to the Ubuntu 16.04 PPA on January 17 with version 56. Please stop pushing updates to Xenial.

You do own https://launchpad.net/%7Etista/+archive/ubuntu/adapta , right? If Ubuntu 16.04 is EOL for this theme, can you please not update it anymore on Xenial?

**Comment by tista500** [comment]
Unity7 is NOT the Ubuntu 16.04 LTS.
Dropping Unity7 does not affected to other DEs.

**Comment by benad** [comment]
Ubuntu 16.04 is using Unity as far as I know. Someone in ticket #611 had this exact issue.

You made an update to the theme that breaks it on Unity. This is fine.

That update got automatically pushed as a software update on the Ubuntu PPA on Xenial (Ubuntu 16.04), which accidentally breaks it for all users that perform a software update using your PPA on Ububtu 16.04. This is the issue.

**Comment by benad** [comment]
Is there any way in the DEB packaging to prevent it from being used when Unity is used on Ubuntu 16.04? Unity is still the default DE on Ubuntu 16.04, so this would impact lots of users...

**Comment by tista500** [comment]
> Ubuntu 16.04 is using Unity as far as I know.
Using Unity7 as default does not mean all we have to support was Unity7. Unity7 was just one of DEs we supported.

we need to support Gnome-Shell, Cinnamon, XFce4, LXDE and Budgie users via PPA for Xenial until Apr 2018. Supporting Unity7 is low priority for us because that DE is not used outside the Ubuntu in most cases. So update freeze makes no sense.

>  so this would impact lots of users

I'm not sure how many users still use Unity7 though, that's not for all users in Xenial-based distros but for Unity7 users.

> Is there any way in the DEB packaging to prevent it from being used when Unity is used on Ubuntu 16.04?

I said Unity7 support was over... So if you'd like to fork our previous Unity7 styling by your own, you can do. But on my PPA, there's no plan to keep the Unity7 styling dropped from Git code bases.

**Comment by benad** [comment]
I was just trying to help. In the following days you'll see lots of tickets from users on Ubuntu 16.04 using the default DE that will get a broken theme from your PPA and opening tickets here.

I would recommend telling them to use the last well-working version for Unity as I did in #611 before closing the ticket. I suspect many users followed the steps from http://www.omgubuntu.co.uk/2016/10/install-adapta-gtk-theme-on-ubuntu and now have transparent window decorations since their latest software update.

Or you can rudely close each ticket one after the other until April.

**Comment by escalate** [comment]
I have the same problem with my Ubuntu Xenial 16.04 LTS system as mentioned above. 
I reviewed my dpkg.log and it looks like that a version of adapta-gtk-theme between 3.93.0.11 and 3.93.0.56 is broken.

```
GOOD - dpkg.log.1:1622:2017-12-07 09:23:14 status installed adapta-gtk-theme:all 3.92.2.33-0ubuntu1~xenial1
GOOD - dpkg.log:700:2018-01-09 15:37:08 status installed adapta-gtk-theme:all 3.93.0.11-0ubuntu1~xenial1
BROKEN - dpkg.log:1716:2018-01-18 09:30:13 status installed adapta-gtk-theme:all 3.93.0.56-0ubuntu1~xenial1
```

Is there a quick fix to solve this UI issues?

**Comment by benad** [comment]
Here's what I did:
```
sudo apt remote adapta-gtk-theme
sudo rm /etc/apt/sources.list.d/tista-ubuntu-adapta-xenial.list*
wget https://launchpad.net/~tista/+archive/ubuntu/adapta/+build/14213155/+files/adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb
sudo dpkg -i adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb
rm adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb
```

Then I used Unity Tweak Tool to reload the Adapta theme by selecting another theme and selecting back Adapta.

Future updates in `ppa:tista/adapta` won't support the Unity desktop, so it's safer to just remove the PPA from the APT sources and manually install the last known working version.

**Comment by escalate** [comment]
@benad Thanks for your help.

I tried something different. I installed Gnome-Shell because it is a supported environment.

`
apt-get install gnome-shell gnome-session gnome-tweak-tool
`

It is very similar to Unity when you install and configure some Gnome extensions from https://extensions.gnome.org.

I use the extensions "Dash to dock" and "Extend panel menu" at the moment.

**Comment by EugenIvanou** [comment]
How to restore supporting for ubuntu 16.04? I can't image my ubuntu without this theme. Author, please!

**Comment by marcogutama** [comment]
@benad Thanks
With your help I easily restored the theme with unity support. I think there are still  a lot o people using ubuntu 16.04 with unity.

**Comment by nsneck** [comment]
Yeah, I was bitten by this as well. Kind of annoying.

**Comment by Scrumplex** [comment]
You guys could also download the old version from the ppa and *hold* the packages. [How to hold a package (Prevent upgrade)](https://askubuntu.com/a/18656)

**Comment by about-code** [comment]
@tista500 Thank you for having a heart for users of Xubuntu 16.04 :heart:  ;-)

**Comment by Lenbok** [comment]
Where can we get the old Xenial packages now? They look to have gone from the PPA altogether :-( (I don't use Unity BTW)

**Comment by benad** [comment]
@Lenbok Check my earlier comment https://github.com/adapta-project/adapta-gtk-theme/issues/612#issuecomment-358663661 . You can find a full list of the archived files here: https://launchpad.net/~tista/+archive/ubuntu/adapta/+builds?build_state=built . The last working version for Ubuntu 16.04 LTS (xenial) is 3.93.0.11.

**Comment by Lenbok** [comment]
@benad Awesome, thanks!!

**Comment by Lenbok** [comment]
@benad Perhaps a side topic, but why does that list of all builds appear incomplete? For example, on one of my xenial machines I am happily running 3.93.0.280, which seems to have a page at: https://launchpad.net/~tista/+archive/ubuntu/build/+build/14791515 but I can't find that build on the list page you linked.

**Comment by macagoraga** [comment]
@benad how to make a new installation for ubuntu 16.04 as you mention how to remove.
Can you please explain steps for make an installation and also last supported version.
thanks

**Comment by outhud** [comment]
@macagoraga Latest working 16.04 xenial deb is: https://launchpad.net/~tista/+archive/ubuntu/adapta/+build/14213155/+files/adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb
