### ISSUE TITLE
Add Additional Warning for Unity users in Adapta's Readme

### ISSUE THREAD

**Issue by chuutatsu** [adapta-project/adapta-gtk-theme#613]
I knew that Adapta does not support Unity. But....

Some people are still using Ubuntu 16.04 with Unity and they didn't know that updating Adapta to the latest version will broke their desktop's appearance. From the post [here](https://github.com/adapta-project/adapta-gtk-theme/issues/612), you said that removing Adapta from Xenial repository is difficult because Adapta still supports other DEs. I understand that.

So... how about putting the old Adapta link https://launchpad.net/~tista/+archive/ubuntu/adapta/+build/14213155/+files/adapta-gtk-theme_3.93.0.11-0ubuntu1~xenial1_all.deb somewhere in readme? 

And perhaps add something like, "_We does not support Unity anymore and will not accept Unity-related issues + complaints. If you are an Unity user and insist to use this theme; download this old, unmaintained theme at your own risk OR switch to other DEs/themes which still support Unity._ " after that link. 

This is just a suggestion, though. I did this because Adapta was one of my favorites and I currently used it in in Mate.

**Comment by tista500** [comment]
I've already mentioned in Nov 16 2017:

8236f3f48623f549efe3f40bb639f7b1f79813cb
> README.md: Add some TODOs and update wording
> 
> * Add EOL of Unity7 & Gtk+ 3.18 support.
> * Fix typo.
> * Flat-Plat has been renamed to Materia.

Will they read our README this time?

**Comment by chuutatsu** [comment]
The whole point of my suggestion is **to put** the old unsupported Adapta deb link in the Readme.... in case if those Unity users insist to use Adapta. And add additional words to emphasize that _Adapta support for Unity has been completely dropped and left out_.

So when they came to complain, you have a stronger reason to bring forward (e.g. _I have explained everything in the better polished Readme_), refuse their requests and instead redirect them to reread the Readme. If they insist to take the risk by installing old Adapta, then let them be.

This is just a suggestion, so accepting this is up to you. 
I'll close this now so that anyone may read this in the future.
