### ISSUE TITLE
Maximize button on non header bar windows has wrong icon when maximized

### ISSUE THREAD

**Issue by arngo** [adapta-project/adapta-gtk-theme#614]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.93.0.12

**Actual issue**

Maximize button icon on non CSD/header bar windows not changing to restore icon when maximized.
Non header bar window (Firefox):
![image](https://user-images.githubusercontent.com/27396817/35115676-05427b82-fc57-11e7-9606-751ff7f2019a.png)
Window with header bar (GNOME Files):
![image](https://user-images.githubusercontent.com/27396817/35115787-5720d034-fc57-11e7-8eec-ef94a7dfba48.png)

**Expected behaviour**

Maximize button icon should change to restore icon.

**Comment by tista500** [comment]
o_O?
I've dropped our specific titlebutton featrues in this commit:
f63ffbe8a12ca4fa12223f2d3e935f23fbdd95ee

So I don't have any ideas why still those titlebuttons are rendered in Firefox.
Anyway Firefox does not supoort `.maximized` pseudo-class in its root GtkWindow, so this happens on all Gtk+ themes (Chromium as well). That "restore" icons are handled by `window.background.maximized headerbar button.titlebutton.maximize` selectors in Gtk+ >= 3.2x.

Needs upstream changes, won't fix currently, sorry.

**Comment by tista500** [comment]
report for stem of the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1408335
