### ISSUE TITLE
google chrome title bar buttons

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#615]
```
linux mint
gtk 3.18
cinnamon
x11
 ```

Adapta version = 3.93.0.66

- Related Application
Google Chrome

- Actual issue
When not using system title bar on google chrome (for more space purposes, and is beauty too) the buttons used with adapta-theme is not the common of the theme, using the system titlebar the common are used, which is the expected, but with others themes without system titlebar the common buttons of the theme are used but not with adapta

the google chrome with adapta (not using the normal buttons)
![screenshot from 2018-01-19 15-46-47](https://user-images.githubusercontent.com/25506386/35166393-871594f8-fd30-11e7-99d5-c90db1d12baa.png)
the adapta normal titlebar buttons
![screenshot from 2018-01-19 15-50-02](https://user-images.githubusercontent.com/25506386/35166396-893e24ac-fd30-11e7-854d-0d034f31c96e.png)

- Expected behaviour
normal titlebar buttons of the theme used in chrome
![screenshot from 2018-01-19 15-47-39](https://user-images.githubusercontent.com/25506386/35166431-a95cb1b8-fd30-11e7-81b7-6e8af3deaf36.png)
the same buttons in other window as well
![screenshot from 2018-01-19 15-47-59](https://user-images.githubusercontent.com/25506386/35166450-bbde0b84-fd30-11e7-9d46-f5bd3e42a155.png)

**Comment by tista500** [comment]
No. Gtk+ 3.18 theming development is OVER.
