### ISSUE TITLE
sound applet media progress bar

### ISSUE THREAD

**Issue by gabrielfern** [adapta-project/adapta-gtk-theme#617]
*another issue with cinnamon desktop theme sound applet
when you are playing some media with compatible players you have through the applet control to the player, with adapta cinnamon desktop theme the progress of the media is weird
here we are
adapta-nokto: the point in time the audio is playing is unnoticeable
![screenshot from 2018-01-19 21-41-44](https://user-images.githubusercontent.com/25506386/35177886-8277caec-fd62-11e7-98e9-b765813ef213.png)
adapta: more acceptable, but could be more noticeable
![screenshot from 2018-01-19 21-42-04](https://user-images.githubusercontent.com/25506386/35177887-85627432-fd62-11e7-8188-274f48994ccf.png)
mint y dark: as a example
![screenshot from 2018-01-19 21-41-33](https://user-images.githubusercontent.com/25506386/35177891-879bda18-fd62-11e7-98f4-680732245251.png)

**Comment by tista500** [comment]
Listen to me. I'm NOT the LinuxMint user. Cinnamon is NOT my session. Ton of your issues are bothering in a couple of days.

I'm not a robot.

**Comment by tista500** [comment]
And stop ignoring our issue_template.

**Comment by gabrielfern** [comment]
Come on, i'm just trying to help these days. And you don't need to be a linuxmint user to use cinnamon, you can try manjaro cinnamon for example, or set up cinnamon in your distro on your own.
