### ISSUE TITLE
Brightness and Volume sliders shifting on mouse hover in GNOME status menu

### ISSUE THREAD

**Issue by viggy96** [adapta-project/adapta-gtk-theme#618]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version -  3.22.25-0ubuntu0.1 
 * Desktop environment - GNOME 
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.93.0.66-0ubuntu1~artful1 

**Related Application and/or Shell theming (or name of widget)**
GNOME Shell

**Actual issue**
Brightness and volume slider change size and shift upon mouse hover

**Steps to reproduce (if you knew)**
Open GNOME status menu, and hover over brightness or volume sliders

**Expected behaviour**
Sliders should stay the same size and not shift

**Other Note (feature-request, question, etc...)**
Its very hard to depict this in an image.

**Comment by tista500** [comment]
Shift?
The centre of the sliders does not shift anywhere... o_O?

**Comment by arngo** [comment]
@tista500 I think you misunderstood, here's a gif demonstrating the issue:
![adapta_bug](https://user-images.githubusercontent.com/27396817/35495335-75f7cd48-048e-11e8-9a7b-71851504841f.gif)
This is on stable release 3.93.0 rev.72.

**Comment by tista500** [comment]
o_O?

Could not reproduce anyway:
![ezgif com-crop](https://user-images.githubusercontent.com/6073622/35500157-de2ab544-0518-11e8-91dd-dcd021c2206a.gif)

**Comment by arngo** [comment]
Problem solved, I had an outdated .gresosurce file for the GDM theme. Sorry for the confusion!
