### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by pwhitehouse** [adapta-project/adapta-gtk-theme#620]
Managed to get up to the make step, I'm now getting this:

/usr/bin/sassc: symbol lookup error: /usr/bin/sassc: undefined symbol: libsass_language_version

I've no idea what's causing it. This is my last resort posting here, I've been searching for a while and can't find a fix.

**Comment by tista500** [comment]
I don't think this was as "Make error" but the issue of locally installed `sassc` and `libsass`. Anyway there is few info we should see, distribution info, sassc/libsass versions, the method how you had  installed sassc and more...

**Comment by tista500** [comment]
I suspect that the issue was related to some linking issues between sassc and libsass. So I can't help you, sorry.
