### ISSUE TITLE
Nautilus menus are unreadable with light theme

### ISSUE THREAD

**Issue by viggy96** [adapta-project/adapta-gtk-theme#622]
**Reporter info**

```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version -  3.22.25-0ubuntu0.1 
 * Desktop environment - GNOME 
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.93.0.72-0ubuntu1~artful1 

**Related Application and/or Shell theming (or name of widget)**
Nautilus file manager

**Actual issue**
The menus in nautilus are unreadable. 
https://imgur.com/a/mamHl

**Other Note (feature-request, question, etc...)**
I have tried logging out and logging back in.

**Comment by tista500** [comment]
o_O?

**Comment by tista500** [comment]
#548.

**Comment by tista500** [comment]
I can't help because I could not reproduce now and then.
