### ISSUE TITLE
Firefox Quantum 58.0, LibreOffice and the Login Screen

### ISSUE THREAD

**Issue by nrfaikar** [adapta-project/adapta-gtk-theme#623]
* Distribution - Solus
* Gtk+ 3.0 version - 3.22.26
* Desktop environment - GNOME
* Display server protocol - X11

**Adapta (Nokto Eta) version 3.93

** This is what it looks like
![screenshot from 2018-01-25 16-46-14](https://user-images.githubusercontent.com/26834955/35382268-38adafec-01f1-11e8-9961-a7ca102336a3.png)
![screenshot from 2018-01-25 16-48-43](https://user-images.githubusercontent.com/26834955/35382277-4a3cfe02-01f1-11e8-83ee-87448b59a6c4.png)
![img_20180125_170211](https://user-images.githubusercontent.com/26834955/35382587-4e996ed0-01f2-11e8-8334-d8b0b474321f.jpg)

1, 2) It should be white color with dark background.
3) It shouldn't be to tight

**Comment by tista500** [comment]
Adwaita-dark please.

**Comment by nrfaikar** [comment]
The result is the same. :(

**Comment by tista500** [comment]
Fig.1 and 2: Those are not user-theme specific. That happened other dark variant themes as well.

So won't fix, sorry.
