### ISSUE TITLE
Suggestion to the theme

### ISSUE THREAD

**Issue by jatin-zlatanist** [adapta-project/adapta-gtk-theme#624]
Please add a theme which will make things transparent except the top bar that can remain black as it is or a just bit of transparency in top bar. I am using adapta as both gtk and shell i tried arc theme but i dont like its folder and few things please consider thank you 😉

**Comment by tista500** [comment]
Adapta is not the fork of Arc themes, and I dislike those semi-transparent Gtk+ widgets except for OSD-widgets. Won't accept, sorry.
