### ISSUE TITLE
Theme problem with "PSPP"

### ISSUE THREAD

**Issue by Sa-ghosts** [adapta-project/adapta-gtk-theme#625]
```
 * Distribution: Solus
 * Gtk+ 3.0 version: 3.22.26-68
 * Desktop environment: gnome 3.26.2
 * Display server protocol: X11
 ```
*Adapta version : 3.93.0.49-135
*Related Application: PSPP (statistics program)

**Actual issue**
The active cell (in use) seems to overlay a duplicate cell on top of it so that when I edit a cell I can't see my edit unless I move to another cell then the change appear in the original cell.

Pictures to show the problem
https://imgur.com/a/JIaQC

**Expected behavior**
The active cell does not duplicate it self and I can see my edit right away.

Pictures to show the expected behavior:
https://imgur.com/a/y540e

**Comment by tista500** [comment]
WTF...

This is not the theme issue but upstream issue, I think.
In current Gtk+ 3.x, we support those spreadsheet via `treeview` node styling with combobox, editable entries and some other widgets. But that app does not convert their sheets to GtkTreeView yet, at least on my locally installed 1.0.1. So PSPP's cells, columns, rows are contained in unknown `widget` node what we unexpected. It means PSPP ignores our GtkTreeView design completely.

**Comment by JoshStrobl** [comment]
Hey @tista500, I know you were referring to upstream as PSPP, but just wanted to chime in and let you know that `3.93.0.90` is [now in Solus unstable repo](https://dev.solus-project.com/R338:22b73cdb9ef6a68e5eb1a41fdf39add5b10f562a) and will be available to stable users tomorrow (including @Sa-ghosts). Thanks as always for the quick response times to these issues :+1:
