### ISSUE TITLE
Full transparency?

### ISSUE THREAD

**Issue by aevernum** [adapta-project/adapta-gtk-theme#626]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version -3.22.26
 * Desktop environment - mate/pantheon
 * Display server protocol - X11
 ```

**Adapta version (if you knew)** 
3.93 from repo

**Other Note (feature-request, question, etc...)**

How can i make _all_ theme transparent like logout window?

![2018-01-30_10 29_](https://user-images.githubusercontent.com/9028087/35555659-91813b42-05a8-11e8-8269-998a4ee4e024.png)

**Comment by tista500** [comment]
I don't support modifications based on your personal aesthetics, sorry.
