### ISSUE TITLE
If a window snaps to the edge of the screen you can't resize it from there

### ISSUE THREAD

**Issue by Riamse** [adapta-project/adapta-gtk-theme#627]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - Cinnamon
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.93.0.72-1

**Related Application and/or Shell theming (or name of widget)**
N/A, I think

**Actual issue**
Non-maximised windows that take up the whole screen can't be resized

**Steps to reproduce (if you knew)**

1. Open a new window
2. Drag it to the edge of the screen so that the right edge of the window snaps to the right edge of the screen
3. Try to resize the window from the right
4. Realise it doesn't work because your cursor can't actually reach the edge for the resize cursor to activate

**Expected behaviour**
5. You should be able to resize windows if they're not maximised

**Other Note (feature-request, question, etc...)**
For comparison, instead of dragging the edge of the screen, try resizing the window by clicking and dragging the right edge as far right as possible. You'll see there's some space where you simply cannot drag further. The window border needs to have padding as a "handle" for you to resize the window back.

Windows XP did things right.

**Comment by tista500** [comment]
o_O? Is this user-theme specific issue?

Are you one of devs of Muffin?
I haven't read the codes of Muffin, but at least Mutter-related OpenGL compositors/Window Managers with current Gtk+ >= 3.22.26 handle 'un-tiling' via grabbing its window titles or pressing keyboard shortcuts. It does not matter whether Gtk+ theming has solid visible `border` properties or not. Because resizable grips are rendered outside of its GtkWindow as 'invisible' in the `margin` region of GtkWindow.

> Windows XP did things right.

So what?

**Comment by Riamse** [comment]
I'm afraid I don't have the expertise to explain further. I'm just a guy trying to resize windows that snap to the edge of the screen. Just reporting what I saw. :(

**Comment by Riamse** [comment]
>> Windows XP did things right.

> So what?

I switched window borders to the Windows XP Cinnamon theme and resizing windows after snapping to edge works fine.

**Comment by tista500** [comment]
This? : https://github.com/petrucci4prez/CinnXP

Oh what a beautiful theme it is... No thank you. 

Won't fix, sorry. you do it with your theme if you have...

**Comment by tista500** [comment]
Hmm, I could not find remarkable differences compared with Arc, Mint-Y and Adwaita on the behaviours of ServerSideDecorations.

**Comment by Riamse** [comment]
> Won't fix, sorry.

Why?

> Hmm, I could not find remarkable differences compared with Arc, Mint-Y and Adwaita on the behaviours of ServerSideDecorations.

I'm not entirely sure what you mean by that. Do those have the same issue I have? If not, how is it that Adapta has the issue but they don't?

**Comment by Riamse** [comment]
@tista500
