### ISSUE TITLE
Problem with control styling in Firefox 58

### ISSUE THREAD

**Issue by kreuzman** [adapta-project/adapta-gtk-theme#629]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20.4
 * Desktop environment - Gnome Shell
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.0.97-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
Firefox 58

**Actual issue**
Firefox display system control too big or css make it overlaps with marging/padding. Problem start with update to Firefox 58.

**Steps to reproduce (if you knew)**
Open any site with checkbox or radiobutton fe. https://passwordsgenerator.net/
Actual state - https://pasteboard.co/H5tEMup.png

**Expected behaviour**
Controls layout should be ok.
Expected state - https://pasteboard.co/H5tGkxt.png

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
This damned issue should be fixed in Gtk+ 3.22 theming already...
