### ISSUE TITLE
LIbreoffice 5.4.4 ui notebook dark background

### ISSUE THREAD

**Issue by a11g0rhythm** [adapta-project/adapta-gtk-theme#631]
**Reporter info**
dark background in notebook -> Groupedbar mode
https://imgur.com/a/iOA1d

 ```
 * Distribution - Ubuntu mate 17.10
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - mate 18.2
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

**adapta-gtk-theme/artful,artful 3.93.0.110-0ubuntu1~artful1** 

**Related Application and/or Shell theming (or name of widget)**

**libreoffice  1:5.4.4~rc2-0ubuntu0.17.10.1~lo1**

**Actual issue**
dark background in notebook -> Groupedbar mode
https://imgur.com/a/iOA1d

**Steps to reproduce (if you knew)**

Tools > Options >   Select ‘LibreOffice’ > ‘Advanced’ >  Check ‘Enable Experimental Features’
View > Toolbar Layout > Notebookbar > Groupedbar mode

**Expected behaviour**
Something like this
https://imgur.com/a/ozJyc

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Numix and Arc-Darker please.

**Comment by a11g0rhythm** [comment]
Hmm Ok, 
For people who like effect of Your Hard Work here is a dirty hack  
Open
/usr/share/themes/Adapta/gtk-2.0/colors.rc
change line 
gtk-color-scheme = "inverted_dark_color:#222D32\ninverted_fg_color:#CFD8DC"
to
gtk-color-scheme = "inverted_dark_color:#FAFBFC\ninverted_fg_color:#CFD8DC"
efect 
https://imgur.com/a/tDBUX
I did check  it with gtk-2 apps like zim and inkscape and look ok

**Comment by tista500** [comment]
Let me see how Numix and Arc-Darker thems looked before posting such useless things.

**Comment by tista500** [comment]
Dstro: Ubuntu Bionic
Gtk+-3: 3.22.26
LibreOffice-gtk3: 5.4.3

Numix:
![screenshot from 2018-02-05 01-07-08](https://user-images.githubusercontent.com/6073622/35779479-057851ae-0a11-11e8-960b-eb4500b9661f.png)

Arc-Darker:
![screenshot from 2018-02-05 01-06-35](https://user-images.githubusercontent.com/6073622/35779482-11eb31c2-0a11-11e8-95e3-80901cf295e0.png)

**Comment by tista500** [comment]
And Materia:
![screenshot from 2018-02-05 01-19-59](https://user-images.githubusercontent.com/6073622/35779582-d1bbda3c-0a12-11e8-93b4-a869a34ea026.png)
