### ISSUE TITLE
Inconsistent maximize/unmaximize icons in Cinnamon

### ISSUE THREAD

**Issue by pseudorook** [adapta-project/adapta-gtk-theme#633]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22.26+161+g60750b3ffd-1
 * Desktop environment - Cinnamon
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
b6f1a8d457df09d5db43f0d82768a80a9da5de82

**Related Application and/or Shell theming (or name of widget)**

Window titlebars

**Actual issue**

The new icons for maximize/unmaximize are only applied to applications that don't use the gtk header bar style (not sure what it's called) where the 3 title bar icons are shared with other controls. 

![screenshot from 2018-02-05 12-25-38](https://user-images.githubusercontent.com/6200846/35819471-c1c81de2-0a9a-11e8-9908-53accfd4aabe.png)

**Comment by tista500** [comment]
o_O?

`make clean && make`

**Comment by pseudorook** [comment]
Yeah, that was the problem.
