### ISSUE TITLE
Updates every day

### ISSUE THREAD

**Issue by pierrocknroll** [adapta-project/adapta-gtk-theme#638]
Hello,

Is it normal to have an update almost every day ? I'm in linux Mint 18.3 64 bits with this ppa : 
deb http://ppa.launchpad.net/tista/adapta/ubuntu xenial main

Thanks

**Comment by tista500** [comment]
Yes. So what's the problem? If you won't, stop using my PPA, please.

**Comment by tista500** [comment]
Or download the built package and install it manually when you need.

**Comment by pierrocknroll** [comment]
Relax.
I'm just wondering if it's a good development process to release something every day.

**Comment by ceyhunnabiyev** [comment]
Hi @pierrocknroll , Is there any packager for Linux Mint in order to package Stable Releases?
For example, Arch Linux and Manjaro package Adapta Stable Releases.
