### ISSUE TITLE
Title text in tabs and in menu is not visible on Firefox Quantum 58 (Ubuntu 16.04 Gnome)

### ISSUE THREAD

**Issue by xbound** [adapta-project/adapta-gtk-theme#640]
**Reporter info**

 ```
  Distribution - Ubuntu 16.04 Gnome
  Gtk+ 3.0 version - 3.20.8
  Desktop environment - Gnome 3.20.4
  Display server protocol - X11
 ```

**Adapta version:** 3.93.0.119-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**: Firefox Quantum 58.0.2 with adapta-gtk-theme

**Actual issue**
Text of title tabs and menu is not visible in Firefox Quantum when using adapta-gtk-theme. Adapta, Adapta-Eta, Adapta-Nokto, Adapta-Nokto-Eta neither of these themes show correct text color of tabs' text in Firefox. 
![screenshot from 2018-02-14 07-57-43](https://user-images.githubusercontent.com/25953958/36191818-4243712c-115f-11e8-948c-7f621217c3d1.png)

**Steps to reproduce (if you knew)**
* Ubuntu 16.04 Gnome wth Gnome Shell 3.20.4
* Adapta theme applied to gtk windows
* Firefox Quantum 58.0.2 installed 

**Expected behaviour**
Text in tabs and menu should be visible and should not overlay with background color.

**Other Note (feature-request, question, etc...)**
Other gtk-themes (Materia,Numix, Adwaita) show tabs' title text and menu text just fine. 
![screenshot from 2018-02-14 08-20-47](https://user-images.githubusercontent.com/25953958/36191993-0226ab4e-1160-11e8-983a-243d082f3dc5.png)

**Comment by tista500** [comment]
Dup of #639.
