### ISSUE TITLE
So hardly seen Google Chrome New Tab button on Dark variant

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#641]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.26+161+g60750b3ffd-1
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? Wayland
 ```

**Adapta version (if you knew)**
3.93.0.72

**Related Application and/or Shell theming (or name of widget)**
Google Chrome/Chromium

**Actual issue**
Google Chrome New Tab button is Hardly seen on Dark variant:
![screenshot from 2018-02-15 12-20-49](https://user-images.githubusercontent.com/5506156/36246956-8479ad08-124b-11e8-9803-92688e08c90c.png)

**Steps to reproduce (if you knew)**
1. Just open the Google chrome. 
2. Look at New tab button.

**Expected behaviour**
Screenshot from Adwaita Dark:
![screenshot from 2018-02-15 12-21-15](https://user-images.githubusercontent.com/5506156/36247031-d2616b32-124b-11e8-93b4-169948bc9f64.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Already fixed in Refresh-mode.
