### ISSUE TITLE
theming vala panel

### ISSUE THREAD

**Issue by denikris** [adapta-project/adapta-gtk-theme#643]
**Reporter info**

 ```
 * Distribution - lubuntu 17.10
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - 0.99.2
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

latest from ppa ubuntu

**Related Application and/or Shell theming (or name of widget)**

vala panel from https://github.com/rilian-la-te/vala-panel

**Actual issue**

there is icon task list plugin from budgie-desktop implemented in this panel and this plugins not readable which one is running and which one is not, and the color of panel is white (which is text and component also white) so it's also not readable, and when using eta variant, the color of panel follow window color

**Steps to reproduce (if you knew)**

**Expected behaviour**

if it possible please make icon task lists look like budgie-desktop has and make menu fonts (application, places, system) bold

**Other Note (feature-request, question, etc...)**

![2018-02-15-201624_1024x600_scrot](https://user-images.githubusercontent.com/16707606/36259607-4a7c20fe-1291-11e8-8b7b-05f18f90e14c.png)
![2018-02-15-201629_1024x600_scrot](https://user-images.githubusercontent.com/16707606/36259614-4ff49ea8-1291-11e8-85b3-51f7f7754bce.png)

**Comment by tista500** [comment]
We do not support that panel yet.

**Comment by denikris** [comment]
hope you support that panel later or sooner, this theme is good :-)

**Comment by tista500** [comment]
I don't think that panel was major.
