### ISSUE TITLE
Adapta-Nokto theme as Firefox addon theme?

### ISSUE THREAD

**Issue by ceiphr** [adapta-project/adapta-gtk-theme#644]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - 3.22.28
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? Wayland
 ```

**Related Application and/or Shell theming (or name of widget)**
Firefox

**Other Note (feature-request, question, etc...)**
Can there be an Adapta-Nokto theme on the Firefox addons marketplace so I can have this beautiful theme synced between all my computers? I've found [this one](https://addons.mozilla.org/en-US/firefox/addon/adapta-nokto/), but it isn't as good as the current theme when default is selected. Thanks for taking my input, love the theme!

**Comment by tista500** [comment]
Unfortunately there's no plan to provide such extra theming for that app. But you might be able to do. That app should work without any extra theming addons, though the default theme is still damned terrible.

Won't fix, sorry. If you could make anything, let me know please...

**Comment by tista500** [comment]
Currently I don't have much time to do extra design works...

**Comment by ArchangeGabriel** [comment]
@ceiphr Firefox now uses GTK theming directly on Linux, so that should suits you.
