### ISSUE TITLE
Feature request: 1.5x scaled version for WQHD screen

### ISSUE THREAD

**Issue by fr3dm4n** [adapta-project/adapta-gtk-theme#647]
**Reporter info**

 ```
 * Distribution: Solus and Antergos
 * Gtk+ 3.0 version: 3.22.28
 * Desktop environment: Gnome 3.26.2
 * Display server protocol: X11
 ```

**Adapta version (if you knew)**
in Solus: latest from Solus supported
in Antergos: build from Repository today

**Feature**
At first: Thx for your marvelous work! Your theme is one off those which are using the available space for window controls and just beautiful done. Thank you so much!

Is it possible to create a bigger version of Adapta as well? I think about a 1.5x version. I am in hope it can be done quickly as you already scaled down Adapta for the Eta variant.

**Use case**
It looks like Wayland will need another year to successfully bring (monitor wise) fractional scaling. I am working at a 15" screen with 2560x1440 resolution. UI scaling of 100% ist small and 200% ist way to big. Also I use bigger font sizes (1.5 font scaling) the window controls are relatively small.

What do you think?

**Comment by tista500** [comment]
I can't get the point of this report... You mean the larger `padding` values were needed in your case without scaled vector graphics contents like fonts and/or SVG assets?

Fonts and vector image assets should follow the value of Gtk+ (and Gdk) scaling-factor. Mutter's fractional scaling looks to be based on rasterized interpolation method like xrandr. So I don't have any ideas why we should provide the x1.5 spacing values without any help from Gtk+ itself because fonts and icon images are not correctly rendered with such x1.5 spacing outside the Wayland sessions. If you would like to discuss for supporting fractional scaling in Gtk+, should talk with Gtk+ devs instead... Once Gtk+ implemented x1.5 scaling, we will add more assets for x1.5 mode.

Personally I don't need to use x2 scaling on WQHD/15" LCDs (actually I use ThinkPad T460s WQHD with native resolution). UHD/12-13" should be x2 scaled in various cases though. For me, WQHD/15" is not the Hi-DPI case.

> I am in hope it can be done quickly as you already scaled down Adapta for the Eta variant.

Hey, do you have any ideas how many days I've spent my time for implementing Eta variants? Oh please...

**Comment by fr3dm4n** [comment]
> I can't get the point of this report... You mean the larger padding values were needed in your case without scaled vector graphics contents like fonts and/or SVG assets?

I am at Antergos at the moment, running Lightdm with Gnome. Because I have problems with some external monitors at the university, I am not able to use Wayland and therefore Mutter with fractional scaling.

Everything is quite fine, except the tiny window control bars and the bit large font size of the date/time. Here are some Screenshots. I apologize they are in German.
![bildschirmfoto von 2018-02-28 09-20-24](https://user-images.githubusercontent.com/6654064/36778831-3bda1150-1c6e-11e8-9921-3bd8fcd2472a.png)
Font scaling solves most problems for me.

![full-screenshot](https://user-images.githubusercontent.com/6654064/36779304-d7c78006-1c6f-11e8-87da-0e866c186f19.png)
As you can see: In some windows like Chrome the window control bar is really small. I use the Dash-to-Panel plugin which has an option to scale the status icons (battery, wifi, audio icons). But I haven't figured out how to scale the date/time font. Which is actually just a aesthetic problem to be honest. The window control bar size is the biggest pain point to me.

>> I am in hope it can be done quickly as you already scaled down Adapta for the Eta variant.
>
>Hey, do you have any ideas how many days I've spent my time for implementing Eta variants? Oh please...

You might thing I am an arrogant asshole. Actually I am full of respect for your performance (especially your issue status ratio) and the passion you show for your project. My argument was based on [this file](https://github.com/adapta-project/adapta-gtk-theme/blob/master/gtk/sass/3.22/gtk-eta.scss):

```sass
$variant: 'light';
$ref_weight: 0.7;
```
`$ref_weight` looked to me like a scaling factor. So I was wondering if a "anti-eta" variant would bring a quick solution for this. But I understand you think I lack of respect. Therefore I also started a small Patreon subscription. At the moment I am just a student. Maybe I can increase the payments later.

I dont want to waste your time, so better close this issue. Please allow me a last question: Do you think its possible to scale the window control bar with moderate effort?

**Comment by tista500** [comment]
Basically gsettings key `get org.gnome.desktop.interface text-scaling-factor` is not used for scaling symbolic icon assets pulled from your selected icon-theme and our gtk-theme/gnome-shell-theme specific assets either. On the other hand, Mutter's fractional scaling feature directly upscales the GPU (EGL) buffered surfaces (slices) in Wayland mode, maybe.

> Do you think its possible to scale the window control bar with moderate effort?

All you need is `gsettings get org.gnome.desktop.interface scaling-factor` can accept for *non-integer* (like 1.5) value instead. This should be implemented in Gtk+, Gnome-Shell, and all icon-themes to support/provide `@1.5` (1.5x) sized icon assets. So I don't think larger spaced Gtk+ theme variants make sense with non-upscaled icon assets in various cases.

> In some windows like Chrome the window control bar is really small.

Mutter's titlebuttons are not just the case but also all other assets should be concerned.

Anyway I won't do anything with this request currently until upstream may or may not add such features, sorry...

Regards.

**Comment by fr3dm4n** [comment]
I understand its not common problem, its just my problem. So I try to find a solution myself.
Sry wasting your time and being impolite. It was not an intention.
