### ISSUE TITLE
Text readability issue/suggestion

### ISSUE THREAD

**Issue by meganukebmp** [adapta-project/adapta-gtk-theme#648]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.28
 * Desktop environment - XFCE 4.12
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

3.93.0, upsteam compile

**Actual issue**

Text color does not adapt to accent color leading to unreadable text in certain locations such as buttons.

**Expected behaviour**

Text which is on top of colored accent elements should follow Success Creation contrast rules as defined here https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html and https://material.io/guidelines/style/color.html#color-usability.

**Comment by tista500** [comment]
So what was the actual issue?

**Comment by meganukebmp** [comment]
I mean text contrast ratio. When an element has white text on it and it has a bright color the text should become another darker color (usually black). Similarly for black text and dark background colors. Theme build script should check color contrast of user selected colors and then dynamically set the text colors accordingly. Go [here](https://material.io/color/) and set the primary color to something that would make white text hard to see on top of, such as light greys and yellow. Notice how the suggested text color changes to black. That's contrast ratio.

**Comment by tista500** [comment]
> Theme build script should check color contrast of user selected colors and then dynamically set the text colors accordingly. 

No I won't, sorry.
