### ISSUE TITLE
./configure: line 2867: syntax error near unexpected token `PKG_CHECK_MODULES'

### ISSUE THREAD

**Issue by hAtul89** [adapta-project/adapta-gtk-theme#649]
```
 * Distribution - Ubuntu 17.10 
 * Gtk+ 3.0 version - 2.24.31-2ubuntu1
 * Desktop environment - ubuntu 
 * GNOME Shell - 3.26.2
 * Display server protocol - X11 or Wayland? default 
 ```
**Adapta version (if you knew)**
current one

I get this error when typing ./autogen.sh 

/tmp/themes/adapta-gtk-theme$ ./autogen.sh
+ ./configure --prefix=/usr --disable-gtk_legacy --disable-gtk_next --disable-parallel --disable-chrome-legacy --disable-plank --disable-telegram
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
**./configure: line 2867: syntax error near unexpected token `PKG_CHECK_MODULES'
./configure: line 2867: `PKG_CHECK_MODULES(GDK_PIXBUF, gdk-pixbuf-2.0 >= 2.32.2)'**

**Expected behaviour**
Proceed installation when running `./autogen.sh`

**Comment by tista500** [comment]
o_O? Where is the `pkg-config`?
