### ISSUE TITLE
Display issue in Gno-Menu extension

### ISSUE THREAD

**Issue by gregorydk** [adapta-project/adapta-gtk-theme#653]
**Reporter info**

 ```
 * Distribution - NA
 * Gtk+ 3.0 version - NA
 * Desktop environment - GNOME 3.x
 * Display server protocol - X11 and Wayland
 ```

**Actual issue**

I don't know if it's a bug in the Gno-Menu extension or in the Adapta GNOME Shell theme but the buttons don't display properly.

Standard GNOME Shell theme
![gno-menu_standard](https://user-images.githubusercontent.com/7804464/37039134-fdc13d42-2156-11e8-8295-bbfcee43003f.png)

Adapta GNOME Shell theme
![gno-menu_adapta](https://user-images.githubusercontent.com/7804464/37039148-0396afb8-2157-11e8-8897-907ede052d42.png)

**Comment by tista500** [comment]
We don't support that extension now and then,

**Comment by tista500** [comment]
The dup of #291.
