### ISSUE TITLE
Where is gone  Adapta-Nocto-Eta?

### ISSUE THREAD

**Issue by Maik93** [adapta-project/adapta-gtk-theme#654]
Hi, really cool theme, I'm using it almost for one year, but now that I've reinstalled Ubuntu (16.04) I can't find anymore Adapta-Nocto-Eta...

I've installed (from ppa):
adapta-gtk-theme/xenial,xenial,now 3.93.0.159-0ubuntu1~xenial1

Where it's gone? There's another package where I can find it?
Thanks for help!

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme#variant-matrix
> Eta is a tiny Gtk+ 2.x/3.2x Gtk+ widget variant for saving space.

Eta variants are NOT supported in Gtk+ 3.18.x distros, please read the README.md first, please...
And we will drop Xenial support in Apr 2018.
