### ISSUE TITLE
[Gtk+ 3.22.28] Blurry window control icons

### ISSUE THREAD

**Issue by palob** [adapta-project/adapta-gtk-theme#656]
```
 * Arch Linux
 * GTK 3.22.28
 * GNOME
 * Wayland session
 * Adapta 3.93.0.106
 ```

Looks like this with 200% UI scaling. No matter whether CSD or SSD window.

![blurry](https://user-images.githubusercontent.com/7050624/37244205-bdd83c9e-2485-11e8-9b64-086d7b6594b3.png)

Icons provided by the icon theme look crisp.

**Comment by tista500** [comment]
This? : https://gitlab.gnome.org/GNOME/gtk/issues/63

Check Arc themes whether this happened or not as well.

**Comment by tista500** [comment]
I think this is the regression of Gtk+ >= 3.22.27. : https://github.com/NicoHood/arc-theme/issues/52

**Comment by palob** [comment]
It is present with Arc as well but IIRC it was present before the uptdate to 3.22.27 but then again i think Arch shipped GTK3 with some 3.22.27 commits towards before it was released.

**Comment by tista500** [comment]
Anyway we should wait for the bump of Gtk+ 3.22.2x which that commit has been merged. Currently I don't think I have to do something for this issue, sorry.

If this still happened after newer Gtk+ was landed, I will re-open it.

**Comment by tista500** [comment]
Hey, read that commit again please.
We're talking about the image px sizes provided from Gtk+ themes, instead of icon themes. Those Gtk+ themes do not provide any titlebutton SVG/PNG images... :(
