### ISSUE TITLE
How to resolve the top bar color issue? 

### ISSUE THREAD

**Issue by hAtul89** [adapta-project/adapta-gtk-theme#658]
```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.26.2
 * Desktop environment - Gnome shell 3.26.2
 * Display server protocol - X11
 ```

**Related Application and/or Shell theming (or name of widget)**
I have installed this theme a month+ ago. 

**Actual issue**
Top bar is displayed (always) white with a darker fade color. [See Image](https://i.stack.imgur.com/xebYD.png). 

and chrome theme doesn't load properly (white theme too)

**Expected behaviour**
Top bar / chrome should be using the default color

**Comment by tista500** [comment]
The dup of #365.

**Comment by zzeroo** [comment]
@hAtul89 Just drag n drop images here. See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
