### ISSUE TITLE
deeper shadows?

### ISSUE THREAD

**Issue by mock** [adapta-project/adapta-gtk-theme#659]
**Reporter info**

 ```
 * Distribution - Fedora 27 Workstation
 * Gtk+ 3.0 version - gtk3 3.22.26-2
 * Desktop environment - Gnome 3.26.2
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**

latest pull as of this post (git hash: 3afbcf1c)

**Related Application and/or Shell theming (or name of widget)**

none

**Actual issue**

question/request: is there a way to increase the depth of the shadow at compile time to be a deeper shadow (for a more raised effect)? and if not, could it be possible to add as a feature?

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by ovichiro** [comment]
I'm interested in a little bit larger shadows also. Using the default install in Solus.

**Comment by tista500** [comment]
Partially committed: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.93.0.220

**Comment by tista500** [comment]
But currently there's no plan to edit shadow parameters via autoconf, sorry.
