### ISSUE TITLE
Better contrast/separation of objects

### ISSUE THREAD

**Issue by ovichiro** [adapta-project/adapta-gtk-theme#660]
**Reporter info**

 ```
 * Distribution - Solus 3
 * Gtk+ 3.0 version - Gnome 3.28 (latest in Solus)
 * Desktop environment - Solus Budgie
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.93.0.193 (the one in the Solus repo)

**Related Application and/or Shell theming (or name of widget)**

Gnome Settings, Geany, Disks app (SMART data & self-tests dialog)

**Actual issue**

Some elements lack contrast / separation which makes them harder to tell apart. The result is I need to focus harder to understand simple UI widgets.
Screenshots are attached below.

**Steps to reproduce (if you knew)**

**Expected behaviour**

UI elements are well separated and easy to read.

**Other Note (feature-request, question, etc...)**

![adapta-gnome-settings](https://user-images.githubusercontent.com/14822344/38092835-04a71596-3372-11e8-92a6-6bf90ce05f14.png)
![adapta-geany1](https://user-images.githubusercontent.com/14822344/38092862-10d86dce-3372-11e8-9199-4c28838daf38.png)
![adapta-geany2](https://user-images.githubusercontent.com/14822344/38092872-138c37ee-3372-11e8-9518-af1c1750501b.png)

**Comment by mmirg** [comment]
I'm not sure if I'm seeing the same issue, but since updating from 3.93.0.90 to 3.93.0.200 I've noticed that elements have lost contrast in Thunderbird.
![screenshot from 2018-03-30 15-28-08](https://user-images.githubusercontent.com/4317194/38127054-59856212-342f-11e8-8691-c72628e10c6d.png)

**Comment by tista500** [comment]
Budgie-wm does not have modal-dialog effects, so no, won't fix.

**Comment by tista500** [comment]
In future I may or may not update the colour scheme though, currently I won't fix, sorry.

**Comment by ovichiro** [comment]
I did not intend to make the issue all about modal dialogs. I found a setting to not attach modal dialogs to their parent window which gives them a shadow. So that's not a problem any more.

The report was meant to point out some inconsistencies and lack of spatial separation with UI elements (mainly buttons).
So, while I like the general feel of Adapta, there are things that bug me.
Some elements don't look like the screenshot the project has in the Readme.md, which seems great (Except maybe for the "Run" button on the "Zelda" window. I'd like it like a regular dark "togglebutton", but that's a personal preference).
I've attached some more screenshots with examples for future reference.
All in all nice work!

Gnome Tweaks
![gnome-tweaks-light](https://user-images.githubusercontent.com/14822344/38150455-9f077d92-3467-11e8-8dd5-ddd1ce495694.png)
![gnome-tweaks-dark](https://user-images.githubusercontent.com/14822344/38150458-a1b5866a-3467-11e8-8e1d-86ad75213a6a.png)

Geany
![geany-prefs](https://user-images.githubusercontent.com/14822344/38150461-a436c41c-3467-11e8-89f7-67dc9275dfb3.png)

Rhythmbox
![rhythmbox](https://user-images.githubusercontent.com/14822344/38150465-a76f8eac-3467-11e8-89a6-708c4855dfce.png)

HexChat
![hexchat](https://user-images.githubusercontent.com/14822344/38150469-a9b059b2-3467-11e8-895a-e3f1a79f732b.png)
