### ISSUE TITLE
Adapta-Eta and Adapta-Nokto-Eta title bars show up as Adwaita on Ubuntu 18.04

### ISSUE THREAD

**Issue by rinrincodes** [adapta-project/adapta-gtk-theme#661]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04 Bionic Beaver (Development Branch)
 * Gtk+ 3.0 version - 3.22.29-2ubuntu1
 * Desktop environment - GNOME 3.28.0
 * Display server protocol - Wayland and X11
 ```

**Adapta version (if you knew)**
Any builds dating up to and below the latest stable build from the bionic PPA.

**Related Application and/or Shell theming (or name of widget)**
Pretty much every application both snap or regular. Nautilus 3.26.3 that Ubuntu is using in 18.04 does theme the title bar correctly.
  
**Actual issue**
Adwatia overrides the title bars on both Adapta-Nokto-Eta and Adapta-Nokto. I'm not sure if there is a styling error or GNOME 3.28 introducing some new style changes.

**Steps to reproduce**
-Select Adapta-Eta or Adapta-Nokto-Eta from Gnome Tweaks
-Open any application such as Chrome of Firefox except for Nautilus that themes it correctly

**Expected behaviour**
Please see the regular Adapta and Adapta-Nokto themes as they apply the theming to the title bars correctly.

**Other Note (feature-request, question, etc...)**
None at the moment. This theme still looks awesome but maybe some more color variants and Adapta-Notko fixes for Firefox will be nice.

**Comment by rinrincodes** [comment]
After a reboot it fixed itself. Nothing to worry about! Ubuntu is just a bit buggy as it is! :P

**Comment by rinrincodes** [comment]
Oops. I didn't mean to close this but oddly Gnome Characters that was introduced in GNOME 3.28 is currently unthemed as it still uses the Adwaita theme (effective on all Adapta themes).

**Comment by tista500** [comment]
I can't help you at all, sorry. Unable to reproduce.

**Comment by bilelmoussaoui** [comment]
Maybe you have installed the flatpak/snap package of GNOME Characters. If it's a flatpak package, you can install the adapta flatpak theme. If it's a snap package, well you can't do anything about it...
