### ISSUE TITLE
Text color in textbox is almost same as background color

### ISSUE THREAD

**Issue by bjarkt** [adapta-project/adapta-gtk-theme#662]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubu
 * Desktop environment - Xfce4
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.0.225-0

**Related Application and/or Shell theming (or name of widget)**
Evince

**Actual issue**
In the textbox that holds the zoom amount, the text is almost the same color as the background color
![Image of issue](https://0x0.st/su1H.png)

**Steps to reproduce (if you knew)**
Open a PDF in Evince

**Expected behaviour**
The text color should be lighter, same color as the current page color.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
I don't have any ideas why CSD was disabled on Evince 3.26.
