### ISSUE TITLE
Ubiquity installation slide text is unreadable/dark 18.04

### ISSUE THREAD

**Issue by linuxlite** [adapta-project/adapta-gtk-theme#663]
**Reporter info**

 ```
 * Distribution - 18.04
 * Gtk+ 3.0 version - libgtk-3-0:amd64  3.22.29-3ubuntu1  amd64
 * Desktop environment - XFCE 4.12.3
 * Display server protocol - X11
 ```

**Adapta version** 3.93.0.241-0ubuntu1~bionic1

**Related Application and/or Shell theming (or name of widget)**
ubiquity:
  Installed: 18.04.4
  Candidate: 18.04.4
  Version table:
 *** 18.04.4 500

**Actual issue** - The Adapta theme displays the Ubiquity installation slide text as unreadable/dark:

![ubu1](https://user-images.githubusercontent.com/5382578/38533554-ec3ec3c2-3ccd-11e8-8398-0fbc5c93b13c.png)

Using Adapta-Nokto displays text visibly:

![ubu2](https://user-images.githubusercontent.com/5382578/38533572-0a04c294-3cce-11e8-9c6b-3bbf2f075387.png)

**Expected behaviour**

Display the Ubiquity slideshow text if using the Adapta theme.

**Other Note (feature-request, question, etc...)**

Hoping for a fix soon as our release date nears.

Thank you,

Jerry
Linux Lite Creator.

**Comment by tista500** [comment]
I don't know Linux Lite and I'm not the member of Linux Lite developers. So I have not any clue why I should be in *your* release timing... :(

**Comment by linuxlite** [comment]
Thank you @tista500 confirmed fixed.

![ubiq](https://user-images.githubusercontent.com/5382578/38538921-029b115e-3cea-11e8-97bc-39eddcdb412a.png)

Donation coming your way :)
