### ISSUE TITLE
Text on certain websites is a light grey Adapta Nokto

### ISSUE THREAD

**Issue by coreybruce** [adapta-project/adapta-gtk-theme#664]
Xubuntu 16.04 LTS

On certain websites like Google+ the text is a light Grey color on white on text boxes when typing for example.

How it's suppose to look and does looks on other themes:
![image](https://user-images.githubusercontent.com/8393780/38553278-18ba4bcc-3d02-11e8-93f9-c162d4c655ef.png)

How it looks when using Adapta Nokto:
![image](https://i.imgur.com/n1nY81k.png)

**Comment by tista500** [comment]
Xenial and Gtk+ 3.18.x support will be dropped this month, so I won't do anything, sorry.
