### ISSUE TITLE
won't that'd be better to use red color for delete buttons

### ISSUE THREAD

**Issue by boredbmora** [adapta-project/adapta-gtk-theme#665]
**Reporter info**

 ```
 * Distribution -Arch
 * Gtk+ 3.0 version -
 * Desktop environment -Gnome 3.26
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
wouldn't that be better to use red color as _TWEAK-TOOL>Font scaling factor **-**(minus)_ button for delete buttons (i.e in permanently delete pop up) instead of teal green

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Ask to apps devs to use destructive action button instead of suggested action button.
