### ISSUE TITLE
gnome shell top bar transparent

### ISSUE THREAD

**Issue by whdgmawkd** [adapta-project/adapta-gtk-theme#667]
**Reporter info**

 ```
 * Distribution - Debain buster/sid
 * Gtk+ 3.0 version - 3.22.29
 * Desktop environment - gnome-shell 3.28.0
 * Display server protocol - X11 or Wayland? wayland
 ```

**Adapta version (if you knew)**

 3.93.0.247

**Related Application and/or Shell theming (or name of widget)**

gnome-shell top bar

**Actual issue**

when window is not maximized, top bar background goes transparent.
but font color still remains grey. so i can't see top bar text without hovering them.

![screenshot from 2018-04-13 00-44-36](https://user-images.githubusercontent.com/6850405/38688386-e5f6ee8a-3eb3-11e8-941a-e1742e067886.png)
![screenshot from 2018-04-13 00-44-45](https://user-images.githubusercontent.com/6850405/38688387-e64be084-3eb3-11e8-963e-b7239cef2417.png)

**Steps to reproduce (if you knew)**

unmaximize windows, minimize all windows or close all windows

**Expected behaviour**

gnome-shell's top bar still show black background, show half transparent background or top bar's text color set to white.

**Other Note (feature-request, question, etc...)**

add half transparent background

**Comment by tista500** [comment]
The dup of #516.

**Comment by tista500** [comment]
Use extension(s) instead.

**Comment by tista500** [comment]
Commit: https://github.com/adapta-project/adapta-gtk-theme/commit/16a4b6235b6bddbe16e56b32718555d3cb849d46
