### ISSUE TITLE
Mega.nz desktop client

### ISSUE THREAD

**Issue by ivandotv** [adapta-project/adapta-gtk-theme#669]
**Reporter info**

 ```
 * Distribution - Ubuntu Gnome 16.04
 * Gtk+ 3.0 version -don't know
 * Desktop environment - Gnome 3.18.2
 * Display server protocol - X11
 ```

**Adapta version**
3.93.0.244-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
Mega.nz desktop client

**Actual issue**
Adapta Nokto - design is broken
![selection_047](https://user-images.githubusercontent.com/390700/38752194-ac6cf98c-3f5a-11e8-94e0-1d46717953ae.jpg)

**Comment by ivandotv** [comment]
I'm not using qt5ct.

**Comment by tista500** [comment]
Configure Qt/Gtk backend properly. Not our issue anyway,
