### ISSUE TITLE
Top bar in GNOME Shell no longer transparent with latest update to Adapta-Notko-Eta

### ISSUE THREAD

**Issue by vaskark** [adapta-project/adapta-gtk-theme#671]
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1
 * Desktop environment - GNOME Shell
 * Display server protocol - X11
 ```
 

**Adapta version (if you knew)**

3.93.0.258-0ubuntu~artful1

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Top bar in Gnome Shell lost transparency in latest theme update (Adapta-Notko-Eta variant)

**Steps to reproduce (if you knew)**

**Expected behaviour**

Would like to know how to get transparency back.

**Other Note (feature-request, question, etc...)**

Edit: Of course, I meant full transparency. I'm sure it's in the gnome-shell.css file but I can't seem to find it.

**Comment by tista500** [comment]
Use extension(s) like 'dynamic-panel-transparency' or similar tools to override our backgrounds instead, please.
