### ISSUE TITLE
WPS spreadsheet cell uses brown color

### ISSUE THREAD

**Issue by boredbmora** [adapta-project/adapta-gtk-theme#672]
**Reporter info**

 ```
 * Distribution - Solus3
 * Gtk+ 3.0 version - No idea
 * Desktop environment - Budgie
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)**

3.93.0.244-153

**Related Application and/or Shell theming (or name of widget)**

WPS office spreadsheet

**Actual issue**

Adapta Nokto(dark variant) uses a brown color(#443d2f) as cell color in WPS office spreadsheet

**Steps to reproduce (if you knew)**

- 

**Expected behaviour**

-

**Other Note (feature-request, question, etc...)**

Usually that's white & also LibreOffice calc uses white with that theme.
most importantly, it's hard to work with that color.

**Comment by tista500** [comment]
WTF... https://github.com/horst3180/arc-theme/issues/748

I don't think this is unrelated to Gtk+ themes specific...
