### ISSUE TITLE
some elements are blurry

### ISSUE THREAD

**Issue by boredbmora** [adapta-project/adapta-gtk-theme#673]
**Reporter info**

 ```
 * Distribution - Solus3
 * Gtk+ 3.0 version -
 * Desktop environment - Budgie
 * Display server protocol - X11 or Wayland?X11
 ``` 

**Adapta version (if you knew)**
3.93.0.244-153

**Related Application and/or Shell theming (or name of widget)**

1.pop up box arrow
2.animated loading(both big & small)
3.What section button in the search menu box of nautilus
4.few Image viewer full screen action buttons are blurred 

**Actual issue**

1 & 2 are little blurred everywhere(noticable), not sharp edges
ONLY the search menu box button in nautilus under what, doesn't look properly as others which comes under that same button type.

some image viewer full screen action buttons are blurred such as zoom in/zoom out, etc.

**Steps to reproduce (if you knew)**
-

**Expected behaviour**

-
**Other Note (feature-request, question, etc...)**

no idea whether an upstream issue, krita app menu bar buttons are unclear(not even easily readable) on hover cause it uses light blue background with kind of a white gray text.(on-click, it's fine)
![screenshot from 2018-04-16 22 16 44](https://user-images.githubusercontent.com/38057676/38824328-843b2204-41c6-11e8-9450-b822d3deb964.png)

[**Suggestion**]wondering! wouldn't it be better to remove the pop up arrow(pop ups without a arrow pointing towards the menu which woke them)
[**Suggestion**]what about using a separator between paths in pathbar, something like,
![screenshot from 2018-04-16 22 57 31](https://user-images.githubusercontent.com/38057676/38825429-28f315c4-41ca-11e8-9940-4ebf394c4a08.png)

**Comment by tista500** [comment]
Stop posting multiple topics in a single report.

**Comment by tista500** [comment]
Won't read, and won't fix, sorry.
