### ISSUE TITLE
[Geary] Attachment widgets show superfluous padding

### ISSUE THREAD

**Issue by fbruetting** [adapta-project/adapta-gtk-theme#674]
**Reporter info**

 ```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - Gnome 3.26
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.93.0.225-1

**Related Application and/or Shell theming (or name of widget)**
Geary 12.1 (flatpak)

**Actual issue**
Attachment widgets show superfluous padding when an E-Mail is opened. When I click onto some of those attachments, that padding disappears somehow (and also empty space below the mail content disappears). See my screencasts – the first one is of January, the second one of today. This doesn’t happen with Adwaita, and just happens if there are more than one attachment. If there is just one attachment, no superfluous padding gets introduced.

I first filed a bug against Geary, you find it here: https://bugzilla.gnome.org/show_bug.cgi?id=792420

**Steps to reproduce (if you knew)**
Just open a mail with more than one attachment.

[Screen casts.zip](https://github.com/adapta-project/adapta-gtk-theme/files/1921906/Screen.casts.zip)

**Comment by tista500** [comment]
o_O?

That happned with Adwaita-Dark as well in case I've run locally installed Geary 12.1 via CSS inspector epsiecially when GearyMainWindow was on backdrop state while drawing message body contents and GtkFlowBox.

So I don't think that related to Gtk+ theme specific.

**Comment by tista500** [comment]
Happend with Arc 3 variants as well.

**Comment by fbruetting** [comment]
Thanks for investigation, I reopened the Geary bug then.
