### ISSUE TITLE
Stop updating Artful PPA on release of Ubuntu 18.04

### ISSUE THREAD

**Issue by rinrincodes** [adapta-project/adapta-gtk-theme#676]
This is a suggestion but most people will be updating to 18.04 anyways so it will be best to deprecate the PPA for Artful a bit early on April 26th instead of Artful's EOF date in July with the Xenial PPA.

**Comment by tista500** [comment]
Hmm. Artful still has our supported Gtk+ version and build dependencies so I currently keep providing artful packages although many users will move to Bionic when officially released.

Anyway I may or may not change my mind in future though...

Regards.
