### ISSUE TITLE
[Question]  Text position is not correct in firefox quantum 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#678]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22.29
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
3.93.0.244

**Related Application and/or Shell theming (or name of widget)**
Firefox Quantum

**Actual issue**
Text position is a little upper.
Screenshot:
![screenshot from 2018-04-20 14-55-40](https://user-images.githubusercontent.com/5506156/39047433-e9dc1d02-44aa-11e8-835e-2dd8c42cf9a4.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
Screenshot from Chrome:
![screenshot from 2018-04-20 14-57-05](https://user-images.githubusercontent.com/5506156/39047524-46059888-44ab-11e8-8aa2-f24677eb6400.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Adwaita:
![screenshot from 2018-04-21 02-37-35](https://user-images.githubusercontent.com/6073622/39065526-0675cc58-450d-11e8-90a1-17f8c4150db6.png)

**Comment by tista500** [comment]
> Let me see how Adwaita looks with this Mozilla code sample on damned Firefox:

No need to upload anything. I don't see any differences between Adapta and Adwaita in sizes of check/radio widgets.

**Comment by ceyhunnabiyev** [comment]
Really damned Firefox. Thank you for info..
