### ISSUE TITLE
Inconsistencies in Gnome Adapta-Nokto-Eta-Maia

### ISSUE THREAD

**Issue by izznogooood** [adapta-project/adapta-gtk-theme#679]
**Reporter info**

 ```
 * Manjaro Gnome
 * Gtk+ 3.0 version = 3.22.29+86+gd92df4ff2c-1 
 * Desktop environment - Gnome
 * Display server protocol - X11
 ```
The window control bar and buttons have different sizes.

I switched to the Eta theme as this seems to have a more compact build, but some Window-Control-Buttons remain "large". In fact very large to my taste ;).

![scr_small_hover](https://user-images.githubusercontent.com/23040578/38636582-eb899370-3dc8-11e8-89fa-30effdeb0f9f.png)
![scr_big_hover](https://user-images.githubusercontent.com/23040578/38636586-f1075f1c-3dc8-11e8-8ebf-18a35ec6d9f0.png)

The large ones you see are Nautilus and  Tweaks, while Evolution (GTK?) and Telegram (qt) are small (Normal)
It seems to affect "random" as Evolution and Nautilus are both GTK ?
Unless Evolution is now qt, then it would make more sense.

Related:

https://github.com/manjaro/desktop-settings/issues/119

**Comment by tista500** [comment]
SSDs and CDs have different button sizing. Won't change, sorry.
