### ISSUE TITLE
[Question] App-grid icon in the Dock ?

### ISSUE THREAD

**Issue by PJSingh5000** [adapta-project/adapta-gtk-theme#682]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version - libgtk-3-0:amd64 version 3.22.25-0ubuntu0.1
 * Desktop environment - Ubuntu 17.10
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

adapta-gtk-theme version 3.93.1.1-0ubuntu1~artful1

**Related Application and/or Shell theming (or name of widget)**

gnome-shell-extension-ubuntu-dock version  0.7.1

**Actual issue**

Previously, dash-to-dock used app-grid icons bundled inside Adapta's gnome-shell-theme.gresource file.
The Adapta icons used were...
    - ```assets/show-apps.svg```
    - ```assets/show-apps-hover.svg```
    - ```assets/show-apps-checked.svg```

These were all bundeled inside ```/usr/share/themes/Adapta-Nokto/gnome-shell/gnome-shell-theme.gresource```.

Recently, I noticed that user's selected icon theme's app-grid icon is being used instead.
Since I use the Papirus icon theme, the app-grid icon I see in the dock is...
    ```/usr/share/icons/Papirus/symbolic/actions/view-app-grid-symbolic.svg```

QUESTIONS:
1. Was this the result to a change made to the Adapta theme?
2. If so, what was the motivation?
3. If not, do you know if this behavior is the result of changes made to gnome-shell or to the dock extension?

**Steps to reproduce (if you knew)**

1. Ensure Ubuntu 17.10 is updated
2. Install the latest version of Adapta.
3. Copy ```/usr/share/themes/Adapta-Nokto/gnome-shell/gnome-shell-theme.gresource``` to ```/usr/share/gnome-shell/```
4. Reboot
5. Notice that the app-grid icon is ```view-app-grid-symbolic.svg``` from your currently selected icon theme.

**Expected behaviour**

I expected the app-grid icon from  ```/usr/share/themes/Adapta-Nokto/gnome-shell/gnome-shell-theme.gresource``` to be used instead.

**Other Note (feature-request, question, etc...)**

I liked the hover and click effect of the previous way of doing it, but it certainly is easier to change the icon if it is located directly in the user's icon folder, instead of a resources file. Either approach is fine. I'm just curious where the change was made, and if it was an Adapta theme change, or an Ubuntu or a Gnone Shell change?

**Comment by PJSingh5000** [comment]
Just a note, when the icons were located in the resources bundle, I was able to create a really nice hover and click effect by re-bundling these three modified logo icons...

![app-grid icons](https://user-images.githubusercontent.com/19394936/39283613-0efedb0c-48dd-11e8-8f9e-cc652f03b9d3.png)

**Comment by tista500** [comment]
We no longer include those assets.

> a really nice hover and click effect by re-bundling these three modified logo icons...

Disagreed.
Logo images are unmatched to its button functions (open/close AppsGrid).
Won't change, sorry.

**Comment by PJSingh5000** [comment]
Thanks for the explanation.
