### ISSUE TITLE
Optional flags for window background colors?

### ISSUE THREAD

**Issue by Koopzington** [adapta-project/adapta-gtk-theme#685]
I like this theme a lot and was wondering what you'd think about adding more flags for setting the background color of the windows itself.
I'm pretty new to GTK theming and currently diving into this codebase to see how Adapta-Nokto would look like with Grey instead of Blue Grey...
Would it even be worth it to make those colors changeable at build time or should one rather create an entirely new flavour (Mallumo) out of this (or possibly 2 with a brown version (Krepusko))?

**Comment by tista500** [comment]
No I won't. Use Materia please.
