### ISSUE TITLE
The dark gedit theme is under the light theme folder

### ISSUE THREAD

**Issue by PJSingh5000** [adapta-project/adapta-gtk-theme#689]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - libgtk-3-0:amd64 version 3.22.30-1ubuntu1
 * Desktop environment - gnome-shell
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
```
adapta-gtk-theme version 3.93.1.7-0ubuntu1~bionic1
```
**Related Application and/or Shell theming (or name of widget)**

```
gedit version 3.28.1-1ubuntu1
```

**Actual issue**

The gedit-material-theme theme for gedit is in the wrong folder in Adapta, because it is a dark theme, not a light theme.

**Steps to reproduce (if you knew)**

Select the Adapta Gedit theme in Gedit. Even though you navigate the the Atapta "light" theme folder (```/usr/share/themes/Adapta/```), a dark gedit-material-theme is selected.

**Expected behaviour**

The gedit-material-theme theme is under the ```/usr/share/themes/Adapta/``` folder, but it should be moved under ```/usr/share/themes/Adapta-Nokto/``` because it is a dark theme.

The name of the theme should be changed from **Adapta Gedit** to **Adapta-Nokto Gedit** to reflect that it is a dark theme. This can be done easily by replacing ```name="Adapta Gedit"``` in ```adapta.xml``` with ```name="Adapta-Nokto Gedit"```

The current link link to ```../Adapta/gedit``` under ```/usr/share/themes/Adapta-Nokto/``` should be removed.

When a "light" variant of gedit-material-theme is created, it should be placed ```/usr/share/themes/Adapta/```. If no "light" variant is available, it would be misleading to create a link to ```/usr/share/themes/Adapta-Nokto/gedit```.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme#gtksourceviewgedit-color-scheme-support

> Currently only dark-variant is supported.

Adapta is not the complete light-variant but mixed-variant.

**Comment by tista500** [comment]
Won't change until author provides the PR.
