### ISSUE TITLE
Bug of panel, using Adapta, Vala Panel and Lubuntu 18.04

### ISSUE THREAD

**Issue by gusbemacbe** [adapta-project/adapta-gtk-theme#694]
**Reporter info**

Observe that it is not me who has this bug, but the user @denikris has. I will provide his computer details.

I am not sure if it is panel bug or Adapta theme bug. 

He uses Lubuntu 18.04, whose environment desktop is LXDE, uses [Vala Panel](https://github.com/rilian-la-te/vala-panel) and the last version of Adapta. 

I am a collaborator of Suru++ and owner of Suru++ Lubuntu and Suru++ Dark Lubuntu.

I and designer created a icons theme for Lubuntu users and I reprogrammed and readjusted the `index.theme` that icons can become colourful in the panel, but do not for the user @denikris. 

Please, team, review the panel bugs, referencing to:
https://github.com/Magog64/SURU-PLUS/issues/4#issuecomment-388342212
https://github.com/gusbemacbe/suru-plus-dark-lubuntu/issues/1
https://github.com/rilian-la-te/vala-panel/issues/96

Please test with our repositories Suru++ Dark Lubuntu, with Adapta Nokto and Vala Panel. Analyse and find the bugs which keep the icons of being colourful.

**Comment by tista500** [comment]
I don't think this was related to Gtk+ themes but app codes at least on IconTasklistApplet of Vala-panel.
