### ISSUE TITLE
[QUESTION]: XFCE4 Panel

### ISSUE THREAD

**Issue by archqob** [adapta-project/adapta-gtk-theme#696]
First of all, thanks for that great theme.
i don't know if that intensionally or not so you can treat it as a question.

**Reporter info**

 ```
 * Distribution - Fedora 28
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - XFCE
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.16

**Related Application and/or Shell theming (or name of widget)**
Xfce4-panel

**Actual issue**
xfce panel has a darker color than the title bar

**Expected behaviour**
xfce has the same color as the title bar

![untitled](https://user-images.githubusercontent.com/21042432/40525587-3aacc3f2-5fe1-11e8-9435-22f1aa6b7636.png)

**Comment by tista500** [comment]
o_O?

In MD, "Status Bar" should be darker than "App Bars".
