### ISSUE TITLE
Missh desktop trash can icon

### ISSUE THREAD

**Issue by jason-gu** [adapta-project/adapta-gtk-theme#697]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04 LTS
 * Gtk+ 3.0 version - 3.28
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.93.1 Stable Release (rev.18)

**Related Application and/or Shell theming (or name of widget)**

Ubuntu version of Dash-to-Dock gnome extension

**Actual issue**

When the using the adapta theme, the desktop trash icon is missing.

**Steps to reproduce (if you knew)**

**Expected behaviour**

Desktop icon should be displayed if enabled

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
I don't have any ideas why that gnome-shell extension was related to Nautilus's feature...

**Comment by tista500** [comment]
I can't help this report because I could not reproduce that appearance anyhow, sorry.
