### ISSUE TITLE
Button Group Margin

### ISSUE THREAD

**Issue by nrfaikar** [adapta-project/adapta-gtk-theme#700]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - Gnome
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.16

**Related Application and/or Shell theming (or name of widget)**
Inkscape

**Actual issue**
The button group (I guess) doesn't have right margins. 
![screenshot from 2018-06-17 19-24-22](https://user-images.githubusercontent.com/26834955/41507819-8533f982-7264-11e8-8685-d31290da8de5.png)

**Steps to reproduce (if you knew)**
Just open Inkscape with Adapta-Eta desktop theme enabled.

**Expected behaviour**
Here's the sample of using Adwaita desktop theme.
![screenshot from 2018-06-17 19-23-48](https://user-images.githubusercontent.com/26834955/41507818-81dbf5d2-7264-11e8-9d6a-a8e0e377b2f5.png)

**Comment by nrfaikar** [comment]
And doesn't it has a margin against the split line?
![screenshot from 2018-06-17 19-32-02](https://user-images.githubusercontent.com/26834955/41507860-253abc40-7265-11e8-8f37-8b16e9943518.png)

**Comment by tista500** [comment]
Win't fix, sorry.
