### ISSUE TITLE
Tab's Margin Bottom

### ISSUE THREAD

**Issue by nrfaikar** [adapta-project/adapta-gtk-theme#701]
**Reporter info**

 ```
* Distribution - Solus 3.9999
* Gtk+ 3.0 version - 3.22.30
* Desktop environment - Gnome 3.28.2
* Display server protocol - X11
 ```

Adapta version (if you knew)
3.93.1.16

**Related Application and/or Shell theming (or name of widget)**
Inkscape, GIMP and some applications

**Actual issue**
Here's the screenshot of the issue.
![adapta theme bug on tabs](https://user-images.githubusercontent.com/26834955/41520654-f81128e6-72f8-11e8-9f42-4d0e9d593abd.png)

**Steps to reproduce (if you knew)**
The default appearance.

**Expected behaviour**
I guess, the non-active tabs should have margin-bottom too...

**Comment by tista500** [comment]
o_O?

I won't tweak Gtk+2 theming.

**Comment by tista500** [comment]
Here's the Gtk+2-ed Inkscape with Adwaita:

![screenshot from 2018-06-18 16-42-36](https://user-images.githubusercontent.com/6073622/41524001-e9b025ea-7316-11e8-9863-34032ab5cf83.png)
