### ISSUE TITLE
Border at the Left of the Choosed User on the Gnome Login Screen

### ISSUE THREAD

**Issue by nrfaikar** [adapta-project/adapta-gtk-theme#702]
**Reporter info**

 ```
 * Distribution - Solus 3.9999
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - Gnome 3.28.2
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.16

**Related Application and/or Shell theming (or name of widget)**
Gnome Login Screen

**Actual issue**
Border at the left?
![img_20180619_074917](https://user-images.githubusercontent.com/26834955/41569757-6aa518b6-7396-11e8-83ac-66c39c313255.jpg)

**Steps to reproduce (if you knew)**
...

**Expected behaviour**
(I just asking)

**Other Note (feature-request, question, etc...)**
I guess, it has no border at the left before...

**Comment by tista500** [comment]
o_O?

That's our design for multi user switching mode since before.
