### ISSUE TITLE
Firefox Maximase Button

### ISSUE THREAD

**Issue by nrfaikar** [adapta-project/adapta-gtk-theme#703]
**Reporter info**

 ```
 * Distribution - Solus 3.9999
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - GNOME 3.28.2
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.22

**Related Application and/or Shell theming (or name of widget)**
Mozilla Firefox

**Actual issue**
![screenshot from 2018-06-24 07-59-37](https://user-images.githubusercontent.com/26834955/41814898-208eeb74-7785-11e8-86b6-cb2931f64ace.png)

**Steps to reproduce (if you knew)**
Default appearance

**Expected behaviour**
![screenshot from 2018-06-24 08-04-12](https://user-images.githubusercontent.com/26834955/41814902-34479a6c-7785-11e8-9a4c-86b27fac126a.png)

**Other Note (feature-request, question, etc...)**
I don't know it should be like what.... Because on mine, there's no differences between minimased and maximased button while using Adwaita Desktop Theme...

**Comment by SolarLiner** [comment]
This is an issue with Firefox CSD and not Adapta. Firefox CSD's implementation does not include options like window buttons position, and reacts badly to changes. Supposedly future versions will make it better, but CSD support in Firefox isn't that great, and there is nothing GTK themes can do about it.

**Comment by nrfaikar** [comment]
Oh, sorry. I don't know...

 Thanks for your info...
