### ISSUE TITLE
No sample colours in xfce4-appearance-settings

### ISSUE THREAD

**Issue by malysps** [adapta-project/adapta-gtk-theme#704]
**Reporter info**

 ```
 * Distribution - Xubuntu 17.10
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Xfce 4.12
 * Display server protocol - X11
 ```

**Adapta version**
3.93.1.22 (from the PPA)

**Related Application**
xfce4-appearance-settings (Xfce's Appearance, Style tab, themes list)

**Actual issue**
Hello Tista. This a minor issue of low importance. There are no sample theme colours ("palette") visible near the Adapta theme entries in Xfce's Appearance settings (xfce4-appearance-settings). See screenshot below:

![adapta-xfce-colors](https://user-images.githubusercontent.com/16068365/41831019-e34436aa-7844-11e8-9526-be91e83df379.png)

Fortunately this is very easy to fix. I've tested it on the "Adapta-test" theme (visible above) and it works. You would have to move this section...
 ```
#
# Colour scheme
#
gtk-color-scheme = "base_color:#FFFFFF\nbg_color:#FAFBFC"
gtk-color-scheme = "text_color:#263238\nfg_color:#263238"
gtk-color-scheme = "selected_bg_color:#00BCD4\nselected_fg_color:#FFFFFF"
gtk-color-scheme = "tooltip_bg_color:#222D32\ntooltip_fg_color:#CFD8DC"
gtk-color-scheme = "link_color:#03A9F4\nvisited_link_color:#9C27B0"
gtk-color-scheme = "inverted_dark_color:#222D32\ninverted_fg_color:#CFD8DC"
gtk-color-scheme = "scroll_slider_color:#BEC2C3\nscroll_slider_prelight_color:#979D9F"
gtk-color-scheme = "panel_bg_color:#13191C"
gtk-color-scheme = "secondary_dark_color:#F7F9F9"
gtk-color-scheme = "solid_white:#FFFFFF"
gtk-color-scheme = "accent_color:#4DB6AC"
gtk-color-scheme = "light_color:#FFFFFF"
 ```
...from the `/gtk-2.0/colors(-dark).rc` file(s) to the `/gtk-2.0/gtkrc` file(s), for all four variants. "xfce4-appearance-settings" just expects that section (well, just three particular colours from it, from the first three lines) to be directly in the `gtkrc` file, not the imports / includes.

I said it before and I'll say it again - your theme is awesome. Thanks for supporting Xfce.

**Comment by tista500** [comment]
No, won't. Because XFce4 devs have already started Gtk+ 3 porting. And there's no guidelines that `gtk-color-scheme` property must be put into `gtkrc` directly. That's the very specific circumstances of Gtk+-2-ed XFce4 what I don't have to follow at least. See the Gtk+-3-ed XFce4.

Won't fix, sorry.

**Comment by malysps** [comment]
True, good point. At this stage it's probably better to wait and see how it will look after the GTK3 port. Maybe I should let the Xfce devs know about this, so that colours could be taken from the imports / includes also.

**Comment by tista500** [comment]
>  so that colours could be taken from the imports / includes also

o_O?
That's the different mechanism to look-up Gtk+ theme colours between 2 and 3. in Gtk+ 3, apps can find and pull theme's colour scheme from CSSs (or gresource) via `@define-color theme_xxxx_color` lines at the end of those files. Alternatively, apps can also fork colours via `widget.get_style_context()` and `get_rgba()`, or some other methods.

**Comment by malysps** [comment]
Sorry if I made a fool of myself, I'm not a developer or a themer, so I didn't know how it exactly works. I guess when they finally port whole core Xfce to GTK3 there would be no reason to pull those colours from the GTK2 gtkrc file anymore. Anyway, I don't want to waste your time on this issue, thanks for your quick reply. If this will be occurring after the GTK3 port in the future, I'll let the Xfce devs know. Cheers.
