### ISSUE TITLE
Adapta in Ubuntu-Budgie 18.04, pixel-saver applet.

### ISSUE THREAD

**Issue by Coeur-Noir** [adapta-project/adapta-gtk-theme#705]
```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version -
 * Desktop environment - Budgie
 * Display server protocol - X11
 ```
Hello,

while using adapta theme in Ubuntu-Budgie 18.04, pixel-saver applet in panel is not themed accordingly.

For reference : https://discourse.ubuntubudgie.org/t/adapta-and-pixel-saver-applet/661

Fossfreedom's suggestion is about modifying some css regarding pixel saver : 

```
  & .horizontal.titlebar { //budgie-pixel-saver applet
          background-color: transparent;
          border: none;
          min-height: 0px;
          color: $inverse_fg_color;
          box-shadow: none;

          & .image-button.titlebutton.close {
            background-color: transparent;
          }
}
```

**Comment by tista500** [comment]
o_O?

At least that is not our issue. WTF...

**Comment by tista500** [comment]
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/c979061dc5c02819c089eb3dd2a108de4efad288
