### ISSUE TITLE
Start menu font appears too large by default unless overall scaling is reduced

### ISSUE THREAD

**Issue by movisman** [adapta-project/adapta-gtk-theme#707]
**Reporter info**

 ```
 * Distribution - Linux Mint 19 'Tara'
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - Cinnamon
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.94.0.1-0ubuntu1~bionic1

**Related Application and/or Shell theming (or name of widget)**
n/a

**Actual issue**
Font size appears to be larger than intended in the start menu, when 'desktop' under 'themes' is changed over to Adapta. Using Mint-Y, with default 9pt/10pt fonts and 1.0 scaling, the font appears as 9pt. With Adapta it looks like it's appearing as 10pt.

**Steps to reproduce (if you knew)**
When font sizes are set as OS default, when 'desktop' under 'themes' is changed to Adapta the items in the start menu have a 10pt font, when it should be 9pt.

_Note_ - if I change any of the font sizes in Mint's font preferences, the start menu font size does not change at all under Adapta. The only way I can make it work is to increase the default font from 9pt to 10pt, and then set the scaling to 0.9 (to make it 9pt again). This then changes the font in the start menu to be the correct size. This serves as a workaround which is fine.

**Expected behaviour**
Font size should be 9pt as per Mint-Y. I can change the default font size in Mint-Y to whatever I want and the start menu adjusts accordingly, I do not need to mess around with overall scaling.

**Other Note (feature-request, question, etc...)**
Fresh install of Linux Mint 19.

In addition, three screenshots as examples.

adapta-9pt_1.0.png - This is how the start menu looks with default Mint fonts and scaling under Adapta. You can see the font is 10pt, when it should be 9pt
mint-y-9pt_1.0.png - This is how the start menu looks with default Mint fonts and scaling under Mint-Y. Note how the font shows as 9pt.
adapta_10pt_0.9.png - This is how it all looks with Mint default fonts 'increased' to 10pt, but the overall scaling set to 0.9. This looks good and is showing at 9pt. Please note, changing any of the font sizes in this window doesn't affect the start menu font size under Adapta. Only changing the overall scaling appears to work.

Hope this all makes sense.

Thanks!

![adapta-9pt_1 0](https://user-images.githubusercontent.com/18538104/42415169-dc4f9698-823d-11e8-90e4-53f525e7a05f.png)
![mint-y-9pt_1 0](https://user-images.githubusercontent.com/18538104/42415170-df3ed760-823d-11e8-9d3e-52d379a51455.png)
![adapta_10pt_0 9](https://user-images.githubusercontent.com/18538104/42415168-d9979130-823d-11e8-840f-8fa9026d6db9.png)

**Comment by tista500** [comment]
o_O?

**Comment by movisman** [comment]
Apologies for the confusion, my explanation of the issue is probably not very good! No idea why it happens though, i'd have thought changing the font size would affect the start menu font size in Adapta like it does with the built in Mint themes.

**Comment by tista500** [comment]
> i'd have thought changing the font size would affect the start menu font size in Adapta like it does with the built in Mint themes.

Sounds quite strange for me.Because Gtk+ themes and Cinnamon shell themes are completely independent from each other. So I don't have any ideas why Mint-Y(?) could apply `org.cinnamon.desktop.interface.font-name` key into shell themes. They defines their shell font styling like this: 
https://github.com/linuxmint/mint-y-theme/blob/master/src/cinnamon/cinnamon.css#L1

That `stage` node can't be overridden by setting "Default font" in theory. All users can scale the font-size is `org.gnome(cinnamon).desktop.interface.text-scaling-factor` gsettings key.

That was really a theme specific issue?

**Comment by tista500** [comment]
> Font size should be 9pt as per Mint-Y

No I won't. :/
Set "Default font" as 10pt then scale down to 0.9 via text-scaling-factor.

**Comment by movisman** [comment]
No problem at all, thanks for the help.

**Comment by movisman** [comment]
Hi,

I just had one other question which I meant to ask before. I have read the readme etc, and was just wondering, is there any reason not to use Roboto in Cinnamon? I see the table says Noto Sans for Primary in Cinnamon - however as I am using en_GB, am I ok to use either font? The reason is, I prefer Roboto and so far not seeing any side effects, but was wondering if there was a particular reason to avoid apart from the locale thing.

Also on this note I understand Linux Mint uses Muffin as it's window manager. In the compatibility table there is no tick for Muffin on the ETA variant, but so far it displays ok for me. Is there a particular reason to avoid using this variant?

Thanks very much!
