### ISSUE TITLE
Update styling of Solus Mate Panel to remove separators

### ISSUE THREAD

**Issue by Jacalz** [adapta-project/adapta-gtk-theme#710]
**Reporter info**
The Solus Mate panel has some separators that should be removed to give a more pleasing visual appearance:
[![F4432138-_F9_FA-4918-_A442-9_A01_BDD2026_C.jpg](https://s15.postimg.cc/a31k2k3xn/F4432138-_F9_FA-4918-_A442-9_A01_BDD2026_C.jpg)](https://postimg.cc/image/4rmnhuhuv/)
 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Mate
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.93.1.28 

**Related Application and/or Shell theming (or name of widget)**
Solus Mate Panel?

**Actual issue**
The separators should be removed as it looks better without them as seen in:
https://dev.solus-project.com/T5010
Arc actually doesn’t use these separators and it looks better in my opinion but Adapta looks bette rain general ;)

**Steps to reproduce (if you knew)**
Spin up an iSO of Solus Mate and switch to Adapta to see the separators in the panel compared to Arc!

**Expected behaviour**
No separators

**Other Note (feature-request, question, etc...)**
Thanks for making a great looking and functional theme!

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/pull/438

**Comment by tista500** [comment]
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/Menta/gtk-3.0/mate-applications.css#L363

**Comment by tista500** [comment]
Won't change, sorry. Those 'handles' are needed when grabbing and moving wnck tasklist applet and NaTray applet.

**Comment by Jacalz** [comment]
But Arc gtk theme doesn’t have those, how is that?

**Comment by Jacalz** [comment]
If removing them is no go then maybe they can be reworked or something to make them fit in better?
