### ISSUE TITLE
Allow application to change button color

### ISSUE THREAD

**Issue by KSXGitHub** [adapta-project/adapta-gtk-theme#714]
**Reporter info**

 ```
 * Distribution - Antergos
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - GNOME3
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**

3.94.0.7-1 _(from community/adapta-gtk-theme)_

**Related Application and/or Shell theming (or name of widget)**

* [pamac](https://gitlab.manjaro.org/applications/pamac/)
* Adwaita (GNOME default theme)

**Actual issue**

* Button color cannot change under Adapta theme.

**Steps to reproduce (if you knew)**

[YouTube video](https://youtu.be/BQfV8VEpYKA).

**Expected behaviour**

* Button color should change in Adapta theme.

**Notes**

* Unlike most buttons, pressing these buttons does not trigger an actual action, instead, it adds/removes associated action to a queue. (Similar to a checkbox)
  - Default-colored button means that associated action is not in the queue.
  - Colored button means that associated action is in the queue.

**Comment by tista500** [comment]
o_O?

Looked strange with Adwaita themes. Why those GtkButtons have switched to suggested/destructive action styling only when pressed (`:active` pseudo-class)?

**Comment by KSXGitHub** [comment]
@tista500 I know nothing of GTK+ development, let alone theming, if that question is for me, I cannot answer.

**Comment by KSXGitHub** [comment]
I've just added some notes btw

**Comment by KSXGitHub** [comment]
> Let me see the selector of those GtkButton (GtkToggleButton?) via CSS inspector.

The application is [pamac](https://gitlab.manjaro.org/applications/pamac/)

[It appears to be a GtkToggleButton](https://user-images.githubusercontent.com/11488886/42931164-26d57bfe-8b69-11e8-85cf-c4e861d2ff5e.png).

**Comment by tista500** [comment]
Not property but 'CSS nodes' please (I said 'the selector').

**Comment by KSXGitHub** [comment]
This is for the active 'Remove' button

![image](https://user-images.githubusercontent.com/11488886/42931668-84de58aa-8b6a-11e8-9298-5c0a73c23835.png)

When not active

![image](https://user-images.githubusercontent.com/11488886/42931726-a1bb2ef8-8b6a-11e8-88bd-75dac9009fc9.png)

**Comment by KSXGitHub** [comment]
Also, this is for the active 'Reinstall' button

![image](https://user-images.githubusercontent.com/11488886/42931867-0139b4bc-8b6b-11e8-8ec4-6c8b666aee68.png)

**Comment by KSXGitHub** [comment]
It turns out that it adds `destructive-action` to 'Remove' button and `suggested-action` to 'Reinstall' button and 'Install' button.

**Comment by tista500** [comment]
> It turns out that it adds destructive-action to 'Remove' button and suggested-action to 'Reinstall' button and 'Install' button.

No need extra info. Fig shows everything.
