### ISSUE TITLE
Inactive tab title hardly visible in Google Chrome with new Material Design interface

### ISSUE THREAD

**Issue by tkiraga** [adapta-project/adapta-gtk-theme#717]
**Reporter info**

 ```
 * Distribution - Fedora 28
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - Gnome
 * Display server protocol - Wayland
 ```

**Adapta version (if you knew)**
3.94.0.65

**Related Application and/or Shell theming (or name of widget)**
Google Chrome (dev channel)

**Actual issue**
Inactive tab title hardly visible in google-chrome-unstable (using new "Material Design" interface)
Example:
![screenshot from 2018-08-01 14-24-56](https://user-images.githubusercontent.com/1019163/43524260-baf4b69c-9596-11e8-996d-0401a429895f.png)

**Steps to reproduce (if you knew)**
* Open Chrome (google-chrome-unstable)
* Switch to Material Design interface (should be by default in "unstable. If not go to "chrome://flags/#top-chrome-md and switch to "Refresh")
* Add new tab

**Expected behaviour**
The color of the inactive tab title should be slightly lighter, similarly to how it is in Firefox:
![screenshot from 2018-08-01 14-33-10](https://user-images.githubusercontent.com/1019163/43524837-2bffcc7c-9598-11e8-9ef4-0f048b40c219.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
o_O?

Let me see how Arc-Darker works.

**Comment by tkiraga** [comment]
It's little bit more visible, but still not as good as in Firefox.
![screenshot from 2018-08-01 16-17-23](https://user-images.githubusercontent.com/1019163/43530855-75baa7de-95a6-11e8-8264-384bf30add61.png)
