### ISSUE TITLE
adapta firefox

### ISSUE THREAD

**Issue by trancef0rmer** [adapta-project/adapta-gtk-theme#718]
* Distribution - Manjaro Linux
 * Gtk+ 3.0 version - 3.22.30-1
 * Desktop environment - KDE Plasma 5.13.3
 * Display server protocol - X11 
I have set adapta-nokto-eta for GNOME Application Style in KDE.
This is how webmin looks in firefox with another gtk theme
http://i.prntscr.com/UFDpsHjKRBS5SJ14hqcBoA.png
And this is hot webmin looks with adapta gtk theme
http://i.prntscr.com/yErcO-OZRNKNO3pp7mGxRA.png

I have noticed that adapta is changing "style" on some sites.
I reealy like adapta and I would like to find a workaround for that.
Thank you!

**Comment by tista500** [comment]
WTF... :/

**Comment by tista500** [comment]
I could not reproduce at all:

Webmin 1.890, Firefox 63.0a1 (2018-08-03), Gnome-Flashback 3.28.0
![screenshot from 2018-08-04 00-37-04](https://user-images.githubusercontent.com/6073622/43652043-03713fb4-977f-11e8-8e41-0ae83a799511.png)

**Comment by trancef0rmer** [comment]
Thank you @tista500 
I'm using Firefox Quantum 61.0.1 (64-bit) and  Authentic Theme 19.19 for webmin

**Comment by tista500** [comment]
I have nothing to do with this report because I could not see any remarkable differences between Arc and Adapta, sorry.
