### ISSUE TITLE
Weird application dock window indicators in Ubuntu 18.04

### ISSUE THREAD

**Issue by ntsim** [adapta-project/adapta-gtk-theme#719]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - 3.22.30-1ubuntu1
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.94.0.76

**Related Application and/or Shell theming (or name of widget)**

Application Dock in combination with any Adapta theming

**Actual issue**

This issue occurs when using the combination of Adapta and the User Themes Gnome extension in Ubuntu 18.04. When opening up two (or more) windows of the same application, there appears to be some weird styling which looks like the following:

![image](https://user-images.githubusercontent.com/9917868/43675873-33b72552-97df-11e8-93db-0b87067998a2.png)

![image](https://user-images.githubusercontent.com/9917868/43675964-bd026dca-97e0-11e8-9840-11103284c831.png)

It seems like Ubuntu's window indicators are being rendered on top of Adapta's?

This has been a recent regression for me (maybe in the last week or two). Previously there wasn't any issue with Adapta's shell theming.

**Steps to reproduce (if you knew)**

1. Install Adapta on Ubuntu 18.04.
2. Install User Themes Gnome extension and enable it in Gnome Tweak Tool.
2. In Gnome Tweak Tool, under Appearance, change Shell theme to any of the Adapta variants.  

**Expected behaviour**

There should only be one set of window indicators that is consistent with the Adapta theme.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
We never support Ubuntu session, use Gnome session instead. Canoncal's fuckin' Ubuntu  dock extension issue.

**Comment by tista500** [comment]
The duplicate of #566.
