### ISSUE TITLE
System Monitor in Ubuntu 18.04 is not styled

### ISSUE THREAD

**Issue by VladimirDev93** [adapta-project/adapta-gtk-theme#721]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version - 3.22.30
 * Desktop environment - GNOME
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
- Latest from Ubuntu PPA, I believe it's `3.94.0 Stable Release (rev.84)`

**Related Application and/or Shell theming (or name of widget)**
- System Monitor

**Actual issue**
- The "System Monitor" in Ubuntu 18.04 is not styled

**Steps to reproduce (if you knew)**
- Open System Monitor

**Expected behaviour**
- It should be styled with Adapta GTK theme

**Other Note (feature-request, question, etc...)**
- Is this a known issue? Are there any additional steps to do after installing the Adapta GTK theme so that "System Monitor" can be styled?

**Comment by tista500** [comment]
The dup of #695.

**Comment by VladimirDev93** [comment]
@tista500 Thanks, that worked.
