### ISSUE TITLE
Inconsistent color in slider

### ISSUE THREAD

**Issue by superlativo77** [adapta-project/adapta-gtk-theme#723]
My LMDE looks awesome with adapta nokto theme. Thanks for your great work!

**Reporter info**

 * Distribution - LMDE2
 * Gtk+ 3.0 version -
 * Desktop environment - Cinammon
 * Display server protocol - X11

**Adapta version (if you knew)**
Last

**Related Application and/or Shell theming (or name of widget)**
All sliders

**Expected behaviour**
Same turquoise color in everywhere because slider and dot are green. This elements isn't the same turquoise color from the rest of elements. And dot size is so big. I think.

Screenshot: 
https://i.imgur.com/foJUXe9.png

Adapta theme is awesome yes, but I saw that minimal details.

Thanks in advance.

**Comment by tista500** [comment]
> Same turquoise color in everywhere because slider and dot are green. This elements isn't the same turquoise color from the rest of elements. And dot size is so big. I think.

o_O?
I don't have any ideas why the different purposes should share the exact same colour?
"Selection" and "Dynamic progress"/"Signal Gain" are their own specific colours in Adapta. Won't change, sorry.

**Comment by tista500** [comment]
Slider height in:

Mint-Y-Dark:
![screenshot from 2018-08-20 02-51-36](https://user-images.githubusercontent.com/6073622/44311554-9297cd00-a424-11e8-99bd-07aa0f9db401.png)

Adapta-Nokto:
![screenshot from 2018-08-20 02-51-03](https://user-images.githubusercontent.com/6073622/44311567-b9ee9a00-a424-11e8-9df1-9c10ed403d0c.png)

I don't think our sliders are 'too' large than others.
