### ISSUE TITLE
Duplicated window count indicators in dash to dock

### ISSUE THREAD

**Issue by tflori** [adapta-project/adapta-gtk-theme#724]
**Reporter info**

 ```
 * Distribution - Manjaro
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - Gnome-Shell 3.28.2
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**
adapta-maia-theme 3.94.0

**Related Application and/or Shell theming (or name of widget)**
dash to dock extension with customized windows counter indicators.

**Actual issue**
The window counter indicators are duplicated.

This is a duplicate of #566. I know you have already a solution for it and I would prefer to have the answer in this topic but unfortunately you have locked the conversation there.

You suggested to change the "Customize windows counter indicators" setting to "default" and it is absolutely unclear to me what is "Revert Settings". It looks like a name (because of capitals) instead of an instruction "revert your settings". But I can't find anywhere a tool or application called "Revert Settings".

Next stepp is "Appearance" - I checked multiple settings with a tab "Appearance" none of them have a setting "Customize windows counter indicators". 

Please write more details in which program to find these settings, thanks in advance.

**Comment by tflori** [comment]
If you mean to revert the settings in dash to dock: I want the custom style, how to disable the dots from adapta?

**Comment by tista500** [comment]
![screenshot from 2018-08-27 17-46-28](https://user-images.githubusercontent.com/6073622/44650481-bb6e2280-aa21-11e8-8fe3-1dd1decec68a.png)

> how to disable the dots from adapta?

No, can't. Use other shell themes.

**Comment by tista500** [comment]
Commit https://github.com/adapta-project/adapta-gtk-theme/commit/5ec618e07d1d05374299df9c8429f641958c1259 drops our own indicator assets, means we no longer concern those indicators anymore. You make your own indicators instead.
