### ISSUE TITLE
Regression Bug in DashToDock styling

### ISSUE THREAD

**Issue by pratikborsadiya** [adapta-project/adapta-gtk-theme#725]
**Reporter info**

 ```
 * Distribution - Ubuntu 18.04
 * Desktop environment - GNOME Shell 3.28.3
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.94.0.132

**Related Application and/or Shell theming (or name of widget)**
DashToDock gnome shell extension

**Actual issue**
Dash to dock extenuation is not highlighting running applications and is not showing dots for multiple window instances.

**Expected behaviour**
Dash to dock should highlight the applications which are currently running and should show indicator open window instance number.

**Other Note (feature-request, question, etc...)**
This is a regression bug it was working fine in release 3.94.0.129

**Before - Release 3.94.0.129**
![screenshot from 2018-08-28 11-25-19](https://user-images.githubusercontent.com/7806891/44703424-35032080-aab5-11e8-9d02-a21aa07f0b1c.png)

**After - Release 3.94.0.132**
![screenshot from 2018-08-28 11-20-41](https://user-images.githubusercontent.com/7806891/44703269-9e366400-aab4-11e8-9a25-ddd1cc61175a.png)

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.94.0.132

What was the "BUG"? o_O?

Dash to Dock ver.63 can now handle various types of "window counter indicators" by its own function via customization. We no longer bundle our assets anymore. Tweak extension settings by yourself.

**Comment by pratikborsadiya** [comment]
The bug is that even after explicitly changing the indicator style from dash to dock settings it's not showing with Adapta theme while it's working fine with default (adwaita) theme. See attached screencast.
[Screencast from Tuesday 28 August 2018 03_05_27  IST.zip](https://github.com/adapta-project/adapta-gtk-theme/files/2327468/Screencast.from.Tuesday.28.August.2018.03_05_27.IST.zip)

**Comment by pratikborsadiya** [comment]
Release 3.94.0.143 fixed the issue. Thanks for the awesome GTK theme ever.
