### ISSUE TITLE
xfece-notifyd icon is too big

### ISSUE THREAD

**Issue by asegarra** [adapta-project/adapta-gtk-theme#726]
**Reporter info**

 ```
 * Distribution - Xubuntu 18.04.1
 * Gtk+ 3.0 version - 3.22
 * Desktop environment - XFCE
 * Display server protocol - X11 or Wayland? X
 ```

**Adapta version (if you knew)**
Latest - 3.94.0.132

**Related Application and/or Shell theming (or name of widget)**
xfce4-notifyd

**Actual issue**
The xfce4-notifyd icon is bigger then the rest, does not happen in greybird theme.

![adapta-notifyd](https://user-images.githubusercontent.com/12531275/44724114-d2535a00-aa9f-11e8-91c3-cb1d8919fce2.png)

**Steps to reproduce (if you knew)**
Switch to Adapta theme, logout and login.

**Comment by tista500** [comment]
Unable to reproduce with:

greybird-gtk-theme: 3.22.8-1
xfce4-panel: 4.13.3-1ubuntu1
xfce4-notifyd: 0.4.2-0ubuntu3

Left: Greybird, Right: Adapta
[40px height]
![40px](https://user-images.githubusercontent.com/6073622/44730031-ff911e00-ab1a-11e8-9c4c-478002e0fcf7.png)
[32px height]
![32px](https://user-images.githubusercontent.com/6073622/44730061-0e77d080-ab1b-11e8-8195-e961c17fdc33.png)
[24px height]
![24px](https://user-images.githubusercontent.com/6073622/44730075-1899cf00-ab1b-11e8-9cce-ae22ba7ecf84.png)

o_O?

**Comment by tista500** [comment]
Xfce4-panel 4.12.2 specific... Confirmed.

**Comment by asegarra** [comment]
bummer, what I'm seeing even in lower panel height e.g. 22 - 24 there's no padding around the notifyd icon. Have to logout/Login or restart the panel to see it though, did you do that?
