### ISSUE TITLE
Dash to dock icon not showing open application count in Adapta shell theme only

### ISSUE THREAD

**Issue by tesla500** [adapta-project/adapta-gtk-theme#727]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Display server protocol - X11

Adapta from ppa dev channel.

When opening multiple applications the icons in the dock doesn't show the count or "dots" representing the number of open applications. This is an issue of the Adapta shell theme only, for other shell themes it works and is the same in all variants of Adapta shell themes like Adapta, Adapta-Eta, Nokto, etc.

Steps:
Install Adapta, install dash to dock and user-theme extensions. Select any of the shell themes from the above-mentioned list. Open multiple applications.

**Comment by tista500** [comment]
#725.
