### ISSUE TITLE
Adapta creates a lag when opening menus in PulseEffects

### ISSUE THREAD

**Issue by flipwise** [adapta-project/adapta-gtk-theme#728]
**Reporter info**

 ```
 * Distribution - Manjaro Linux (stable)
 * Gtk+ 3.0 version - 3.22.30-1
 * Desktop environment - KDE Plasma 5.13.4
 * Display server protocol - X11 or Wayland? X11, but tested with Wayland as well
 ```

**Adapta version**
3.94.0.92-1

**Related Application and/or Shell theming (or name of widget)**
The problem occurs in PulseEffects, which uses GTK3. 

**Actual issue**
Whenever a menu is opened, the whole UI lags. The problem is worse when clicking the menu multiple times. PulseEffects demostrates this nicely because it has a spectrum that freezes up. The situation is a bit better in Wayland, but not by much.

Video proof: https://www.youtube.com/watch?v=WOvChdc5F7M&feature=youtu.be

**Steps to reproduce (if you knew)**
Open any menu in PulseEffects. 

**Expected behaviour**
No lag, as with e.g Adwaita or Breeze-GTK.

**Other Note (feature-request, question, etc...)**
PE bug [ #321](https://github.com/wwmm/pulseeffects/issues/321)

**Comment by tista500** [comment]
Won't fix, sorry.
Because that did not happen in many types  of Gnome apps, and that app eats CPUs resources even with Adwaita, so no, won't do anything for that app currently.
In future I may or may not concern those things.
