### ISSUE TITLE
How can I modify Adapta's theming in the menu bar?

### ISSUE THREAD

**Issue by m-roberts** [adapta-project/adapta-gtk-theme#730]
**Reporter info**

 ```
 * Distribution - Raspbian (Raspberry Pi Debian)
 * Gtk+ 3.0 version - 3.22.30-2+rpi1
 * Desktop environment - LXDE
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
3.94.0.143-0ubuntu1~bionic1

**Related Application and/or Shell theming (or name of widget)**
LXPanel

**Actual issue**
I would like to adjust the Adapta theme, if possible. Here is a screenshot of the part of the theme that I would like to adjust, but I do not understand enough of how the theme is constructed to be able to modify it. Essentially, I would like to be able to make the bar "thicker".
![](https://i.imgur.com/OzeTuXR.jpg)
![](https://i.imgur.com/T9MKM0C.jpg)

**Steps to reproduce (if you knew)**
I downloaded Raspbian from [here](https://www.raspberrypi.org/downloads/raspbian/), and then ran the following:
```
# adapta-gtk-theme requires libgtk-3-common (>= 3.22.24) but 3.22.11-1+rpi3 is latest

wget http://archive.raspbian.org/raspbian/pool/main/g/gtk%2b3.0/libgtk-3-common_3.22.30-2%2brpi1_all.deb
dpkg -i libgtk-3-common_3.22.30-2+rpi1_all.deb


# Add adapta-gtk-theme repo from Ubuntu

apt-get install -y dirmngr
sh -c "echo 'deb http://ppa.launchpad.net/tista/adapta/ubuntu bionic main' > /etc/apt/sources.list.d/adapta-ppa.list"
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com B76E53652D87398A


# Install Adapta

apt-get update
apt-get install -y adapta-gtk-theme adapta-backgrounds


# Update theme

sed -i "s|sNet/ThemeName=PiX|sNet/ThemeName=Adapta|1" /home/pi/.config/lxsession/LXDE-pi/desktop.conf
```

**Expected behaviour**
Whilst I understand that this is not Ubuntu, it is a Debian-based operating system, which is why everything appears to be working correctly.

**Comment by tista500** [comment]
Edit `gtk/asset/assets-gtk2.svg.in` "Others_panel-xxx" objects and `gtk/gtk-2.0/3rd-party-xxx.rc', then rebuild.
