### ISSUE TITLE
Option to customize background color

### ISSUE THREAD

**Issue by OlegKrikun** [adapta-project/adapta-gtk-theme#731]
It would be nice to add option to override background color (like `--with-primary_color` and `--with-primary_light_color` for light variant)

**Comment by bayang** [comment]
I agree, with last update to 3.95.0 a few hours ago, nearly all the apps I use got a pitch black background, which wasn't the case before. 
I would prefer a dark greyish like it was beafore.
Just pure black is hard to use.

**Comment by tista500** [comment]
No won't, sorry.
