### ISSUE TITLE
Ver 3.95: Some programs do not display windows borders correctly 

### ISSUE THREAD

**Issue by spsf64** [adapta-project/adapta-gtk-theme#733]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.24.1
 * Desktop environment - Cinnamon
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)**
3.95

**Related Application and/or Shell theming (or name of widget)**
Mostly related to gnome programs (ver 3.94 used to work fine)
In the attached image the problem occurs with gnome calculator, gnome archive manager and pamac.
Also happens with google chrome.
QT programs are working ok!

**Actual issue**
Windows borders/decorations not following theme

See attached image:
![adapta395](https://user-images.githubusercontent.com/1877391/46286236-cc481180-c554-11e8-841e-0663e9daaf2b.png)

**Comment by tista500** [comment]
Huh?

We no longer provide any CSD titlebutton images. It depends on your icon-theme.
