### ISSUE TITLE
Workspaces to Dock Extension double border

### ISSUE THREAD

**Issue by ravsimar-sodhi** [adapta-project/adapta-gtk-theme#734]
```
 * Distribution - Ubuntu 18.04
 * Gtk+ 3.0 version -
 * Desktop environment - Gnome Shell 3.28.3
 * Display server protocol - X11
 ```

**Adapta version 3.95**

**Workspaces To Dock**
Getting a double border in Workspaces To Dock extension after today's update.  Is this intentional?
![screenshot from 2018-10-01 19-02-54](https://user-images.githubusercontent.com/25057577/46291657-af3f2d00-c5ac-11e8-8b30-0efbe616327d.png)

**Comment by tista500** [comment]
I've already mentioned: https://github.com/adapta-project/adapta-gtk-theme#unsupported-gtk-based-desktops

Use gnome-session instead of ubuntu-session. That's not our issue.
