### ISSUE TITLE
Could you consider to add back the old Adapta-Nokto-Eta color theme??

### ISSUE THREAD

**Issue by danleepw** [adapta-project/adapta-gtk-theme#735]
Adapta-Nokto-Eta 3.95 is great. And could you consider to add back the old Adapta-Nokto-Eta with another name? I quite miss the old color theme.

Thanks for your consideration.

**Comment by dagleykd** [comment]
I agree, I like the new color, but I do miss the nice teal color of the previous theme!

**Comment by teranex** [comment]
These new dark colors look awful :(

**Comment by jonnyso** [comment]
This version doesn't look as polished as the previous one, the new combobox is also buggy in certain cases. I don't like touching on matters that are more about taste than something objective but in this case it looks way worse and I don't know why they changed it like that.

**Comment by teranex** [comment]
It really feels like this should have been a new, separate theme, or at least a new set of variants.
For now I compiled 3.94.0.149 myself and disabled the PPA

**Comment by prestig3** [comment]
I dont really like this new update either, previous one was definitely better in my opinion

**Comment by Jacalz** [comment]
Same thing for me, sorry but I really liked the old colors way better :sweat:

**Comment by amxmln** [comment]
I think the new accent is nice, but as an Adapta-Nokto user, I have to say that the new dark background colours are far too dark. They hurt my eyes, especially in contrast with lighter things such as websites.

I feel the redesign works well for the Gnome-Shell theme, but the window Gtk theme needs some improvements. The anti-aliasing of the 1px rounded corners is really unsightly and it’s become extremely hard to distinguish different parts of the UI.

I appreciate all the hard work that you’re putting into this theme and I’ve been using it for a very long time. Hopefully there can be some updates to make this redesign on par both visually and from an UX point of view with the prior version, which was nearly perfect in my opinion.

**Comment by lionawurscht** [comment]
I also came here after a recent system update. First I thought something got messed up until I realized I was facing a change in design.
Previously I was very happy with the look of Adapta-Nokto which I had settled on after trying out several other flattish/material themes before. Having previously tried to create just a GTK-theme myself (was way too much work for a side project) I realize how much work has to go into this project and I'm  very grateful you spend your time on it.
That being said, unfortunately I have to agree with the people before me. I was quite happy with the color scheme of Adapta-Nokto, specifically because it wasn't pitch black. It is totally understandable that, as this themes creator you sometimes wish to change things around and surely many will appreciate this change, for those of us who preferred the previous design I would still very much like to have the option to revert to it or an altered version with a slightly lighter background color..

Thanks in advance, I still love the light version of your theme and if it weren't for my habit of staying up well into the night I wouldn't mind at all and just switch to that one.

**Comment by fbruetting** [comment]
Exactly the same for me, I just was about to file a bug against gedit for loading some wrong theme.

The ew version is really ugly! Please create a new variant with a new name for this – this is not Adapta anymore. And certainly not the reason why Adapta had become famous.

Otherwise, I beg someone to fork and maintain the *real* variant.

**Comment by Jacalz** [comment]
I have forked the old code just with the goal of preserving the code. I am no programmer when it comes to GTK+ themes, but pull requests are of course welcome if anyone decides to contribute in the future...
https://github.com/Jacalz/adapta-gtk-theme-legacy

**Comment by Palanthis** [comment]
Love the new colors, but couldn't the be Adapta Nokto New or something? This change breaks my QT/GTK match.

**Comment by PHLAK** [comment]
I like the new theme components but would an option to have the old colors with the new theme layout/components.

**Comment by luis-banuelos-chacon** [comment]
Just raising another hand here. I really dislike the latest update. Not just the color scheme, but a myriad of other rendering issues that showed up with this change (Some examples below).

I think the color scheme could work eventually, but as a separate theme. This change is big enough that it doesn't match the rest of my system, both in colors and in style. It feels like a completely different theme

Some examples:
![screenshot from 2018-10-01 10-32-31](https://user-images.githubusercontent.com/26231454/46305148-6e6ff580-c565-11e8-8b3b-510331b04242.png)
![screenshot from 2018-10-01 10-32-55](https://user-images.githubusercontent.com/26231454/46305149-6e6ff580-c565-11e8-9e23-453258d1f48c.png)

**Comment by orangecoloured** [comment]
For me the first thing is the color scheme. I'm kind of OK with that acid blue, but the dark colour is way too dark. On a dimmed screen it's close to pitch black. Circled buttons also don't look as good as in the light variant.
And the second thing - tabs. It's painful to watch these round corners with narrowing borders. It's like I'm 10 years back and looking at some "jQuery & CSS rounded corners" tutorial.

**Comment by serebit** [comment]
I actually prefer the new color scheme, personally.

**Comment by varlesh** [comment]
We lost Adapta style :( Our project now freezed

**Comment by ghuwe** [comment]
I completely agree that I want the old Adapta back. Plus, the devs of the Qt port said they won't be porting this new version, so as a KDE user with lots of both GTK and Qt applications, I can't have an uniform theme anymore.

**Comment by varlesh** [comment]
earlier we had this:
![image](https://user-images.githubusercontent.com/8083855/46309743-4d8fba80-c5ce-11e8-917c-d77d897fffaf.png)
now we have this:
![image](https://user-images.githubusercontent.com/8083855/46309761-65673e80-c5ce-11e8-8af6-081ebc298684.png)
All elements changed. We lost shadows from toolbar, colors , tone, contrast and etc... New Adapta it's new theme

**Comment by jupitteer** [comment]
The new adapta version honestly reminds me more of something like [ant-dracula](https://github.com/EliverLara/Ant-Dracula) than adapta as it has been.

**Comment by thegreatyellow67** [comment]
There's and interesting set of Adapta gtk theme colorpack compiled from version 3.94.0 rev.149 here:
https://github.com/ivan-krasilnikov/adapta-gtk-theme-colorpack

**Comment by ghuwe** [comment]
I created an AUR package for adapta-gtk-theme-legacy: https://aur.archlinux.org/packages/adapta-gtk-theme-legacy-git/

Hopefully this will make it easier for people to find and install the old version.

**Comment by NorcuxOS** [comment]
@Jacalz Could you please make a new tag/release and setup issues for your fork?

**Comment by natemonster321** [comment]
+1 for putting it in as a different style rather than just replacing the old one. The new styles are drastically different, and while they do look very nice, should not completely displace the old ones

**Comment by ferlanero** [comment]
I don't really like the new color schema, specially the new dark color looks really awful. I think the 3.95 version should be a new theme rather than replace the great 3.94 version which looks almost perfect. I really hope @tista500 consider his decision over the new dierction of the great Adapta GTK Theme.

**Comment by fbruetting** [comment]
Downgrading the Adapta Flatpak:
```
flatpak update org.gtk.Gtk3theme.Adapta-Nokto --commit 792ab1ec4aa8
```
But I don’t know how to pin this…

**Comment by tista500** [comment]
Reverted: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.95.0.7

**Comment by jupitteer** [comment]
With the reversion, is this still going to be maintained? Is the newer version going to be maintained in a different form? What's going on?

**Comment by ghuwe** [comment]
@jupitteer I hope so. I interpret tista's wording as they're saying they're abandoning 3.94 and calling 3.95 something else, but obviously I could be wrong.

I know it's a lot of work maintaining even one theme at a time, but I really like both versions (3.95 with a bit more polish and a Qt port would look really nice) and I hope we will see more of both themes.

**Comment by JoshStrobl** [comment]
Via their Patreon, which I've happily supported (even with the latest styling changes):

```
I've decided to move to somewhere else from Adapta-project. Mainly I want to make MY OWN themes for myself. So please stop donating me for Adapta developments. Maybe someone else will hand over that project in future (I hope so)... :)

Finally thank you all patrons again!! You helped me.

Best Regards.
Tista500
```

My interpretation is @tista500 has decided to revert to the 3.94 series and leave it to a new maintainer to come forward and begin work, they'll be working on theming privately for themselves.

While I don't necessarily agree with the decision by @tista500 to effectively step down from Adapta Project, it's something I respect and wish them the best in the future. Personally, I would have chosen to do the following around the two biggest points of contention:

1. Continued to ship new dark theming, however implement variables (both in the SASS as well as via configure.ac) to enable packagers and/or downstreams to ship a Adapta Nokto / Adapta Nokto Eta that has coloring, contrast, etc. that is more in line with their expectations. This is something that was already done for accent colors (_such as what we do for Solus_) and while it would've been slightly more cumbersome to do, [SASS color functions](http://sass-lang.com/documentation/Sass/Script/Functions.html) for desaturation / lightening could've been used to reduce the workload for both parties.
2. Reverted curved tab design to that of the 3.94 series. That seemed to be the second largest point of contention.

**Comment by dyshan** [comment]
> @jupitteer I hope so. I interpret tista's wording as they're saying they're abandoning 3.94 and calling 3.95 something else, but obviously I could be wrong.
> 
> I know it's a lot of work maintaining even one theme at a time, but I really like both versions (3.95 with a bit more polish and a Qt port would look really nice) and I hope we will see more of both themes.

Agreed – I hope that @tista500 considers continuing to maintain both... personally, I preferred the new design to the legacy one, and personally hope that two separate branches (support for the "legacy" teal version as well as the newer indigo) could be maintained.

**Comment by TiZ-EX1** [comment]
I think the big problem with all of this was changing the look so drastically and still calling it Adapta, when so many other themes called Adapta existed depending on that look in order to synergize it. The new theme is a perfectly good theme; it's just not Adapta. @tista500, what are you gonna call the new theme?

**Comment by serebit** [comment]
I agree with Trent. I really like the new theme, but it's certainly a departure from what most people consider to be Adapta.
