### ISSUE TITLE
Window buttons different size

### ISSUE THREAD

**Issue by duhok1** [adapta-project/adapta-gtk-theme#737]
**Reporter info**

 ```
 * Arch Linux
 * Gtk 3.24
 * Gnome 3.30.1
 * Xorg
 ```

**Adapta version**
 3.95

**Actual issue**
4K monitor - 192 DPI

When using 2x (200% scaling) and font scaling 1.00 (default) the window buttons are very large on Gnome window and apps title-bar, for example compared to Firefox (GTK based too) which seems a normal size button. See both images below:
![1](https://user-images.githubusercontent.com/40549014/46313759-ad6a6f00-c596-11e8-8490-c6bfba9304e1.png) Button size on Gnome and Gnome apps
![2](https://user-images.githubusercontent.com/40549014/46313764-b0fdf600-c596-11e8-8f6e-4454e3585268.png) Button size on GTK apps (looks normal)

**Note:** this is zoomed, but it gives an idea of size different

**Comment by tista500** [comment]
Intentional. GtkHeaderBar and other default-decoration classes are different container sizing. I don't think titlebuttons are 'very' large compared to other GtkButtons contained in GtkHeaderBars.
