### ISSUE TITLE
Version still says 3.94 in configure.ac

### ISSUE THREAD

**Issue by NorcuxOS** [adapta-project/adapta-gtk-theme#738]
**Adapta version (if you knew)**
3.95.0.7

**Actual issue**
Because the sources were reverted to 3.94, the version in the configure.ac file is still at 3.94, although it should be 3.95 now.

**Comment by tista500** [comment]
https://github.com/adapta-project/adapta-gtk-theme/commit/cdfdc9df5307e1abca769999098e762d4c605499
