### ISSUE TITLE
Where can we find the new theme?

### ISSUE THREAD

**Issue by PHLAK** [adapta-project/adapta-gtk-theme#742]
With all the [controversy over the new theme](https://github.com/adapta-project/adapta-gtk-theme/issues/735) it's been reverted back to the 3.94 colors and styles. However, I (and many others I'm sure) liked the new theme to varying degrees. How can those of us that want it get the new theme now?

**Comment by ListeningGarden** [comment]
I imagine there may still be some time before Tista will launch their next project. Hopefully freeing themselves from Adapta will allow them to create the theme exactly as they want, especially as Google themselves moves forward with Material Design 2 as a spec.

Still, eager to see what comes next!

**Comment by tista500** [comment]
Currently I can't promise WHEN and WHERE I open a thing, so close, sorry.
